### ISSUE TITLE
TypeError in ProductController / ProductCombinationFinder

### ISSUE THREAD

**Issue by pottink** [shopware/platform#1631]
**Description**  
I see this popping up in the error logging of my application:

```
Uncaught PHP Exception TypeError: "Argument 3 passed to 
Shopware\Storefront\Page\Product\Configurator\ProductCombinationFinder::find()
 must be of the type array, null given, called in 
/data/web/releases/20210127.0806/vendor/shopware/storefront/Controller/ProductController.php
 on line 105
``` 

**Possible Solution**  
The corresponding code that triggers this is:

`$newOptions = json_decode($request->query->get('options'), true);`

A json_decode of NULL outputs NULL which causes this TypeError to occur. Best would be to update this to:

`$newOptions = json_decode($request->query->get('options'), true) ?? [];`

**Additional context**  
Shopware 6.3.4.1

**Comment by mitelg** [comment]
hey @pottink 
thanks for bringing this up 👍 sounds like a good first issue for a PR 🙂 maybe you, or someone else would like to contribute 💪

**Comment by pottink** [comment]
I don't know how this gets triggered exactly but I assume by search robots. Pops up frequently.
