### ISSUE TITLE
Item price !== Unit Price

### ISSUE THREAD

**Issue by tinect** [shopware/platform#1653]
**Description**  
the English texts for "Unit price" is mixed. "Item Price" or "Price per Unit" and (more often) "Unit price" is used.

**Possible Solution**  
Change all to "Unit price"

**Additional context**

**Comment by GitEvil** [comment]
Hi @tinect! I think this will be tackeled with the "from prices" epic. Changes have been made here and "Item prices" are gone for sure. Can you hint me towards where "Price per Unit" is in use?

**Comment by tinect** [comment]
Hey @GitEvil,
"I think" is not a reliable content 🤔 
[find "Price per Unit"](https://github.com/shopware/platform/search?q=%22Price+per+Unit%22) :-)

**Comment by GitEvil** [comment]
@tinect you are so right ... I took this up on me and will do my best to make it a part of "from prices". :) will keep you updated!

**Comment by GitEvil** [comment]
Hi @tinect, Storefront snippets have been altered to use "unit price" as a translation for the German "Stückpreis". The changes will be released with 6.4.0.0. :+1:
