### ISSUE TITLE
bin/console sitemap:generate fails

### ISSUE THREAD

**Issue by vardumper** [shopware/platform#1654]
**Description**  
ERROR     [console] Error thrown while running command "sitemap:generate --salesChannelId 00c8e87f5c0a4772a323fcadd70cac86". Message: "Warning: gzopen(/tmp/00c8e87f5c0a4772a323fcadd70cac86-sitemap-1.xml.gz): failed to open stream: Permission denied" ["exception" => ErrorException { …},"command" => "sitemap:generate --salesChannelId 00c8e87f5c0a4772a323fcadd70cac86","message" => "Warning: gzopen(/tmp/00c8e87f5c0a4772a323fcadd70cac86-sitemap-1.xml.gz): failed to open stream: Permission denied"]

SitemapHandle.php Line 47

**Possible Solution**  
No idea why the exception is thrown in the first place.

**Additional context**  
this is ran as root user via sudo. nginx/php run as www-data. 
the file does exist and its not empty (-rw-rw-rw- www-data www-data 1211042 /tmp/00c8e87f5c0a4772a323fcadd70cac86-sitemap-1.xml.gz)
other sales channels' sitemaps get created successfully just milliseconds before.

**Comment by shyim** [comment]
We have entirely refactored Sitemap generation on Shopware 6.4. This should be fixed with that
