### ISSUE TITLE
[BUG] Dynamic Product Groups not working with custom fields

### ISSUE THREAD

**Issue by dev-flti** [shopware/platform#1657]
**Description**

- Dynamic Product Groups are not working with custom fields, although custom field is set and content filled!

**Possible Solution**  

Reference to [1558](https://github.com/shopware/platform/issues/1558)

![conditions](https://user-images.githubusercontent.com/64775806/108336240-1d173e00-71d4-11eb-96fd-ee02b4246215.png)
![nodata](https://user-images.githubusercontent.com/64775806/108336243-1dafd480-71d4-11eb-8588-5c3b84849464.png)

**Comment by shyim** [comment]
Has been fixed in newest release
