### ISSUE TITLE
Sync api error handling

### ISSUE THREAD

**Issue by ascheider** [shopware/platform#1666]
Currently if you use shopware sync api and send multiple items per request you don't know on which entities error appeared.
For example if you send array with content, where first and third products are not valid
![image](https://user-images.githubusercontent.com/6016485/109180333-0bf99e80-778b-11eb-8152-9343a69d7871.png)
the response looks like this:
![image](https://user-images.githubusercontent.com/6016485/109181619-6b0be300-778c-11eb-92cf-c620399da6c3.png)
![image](https://user-images.githubusercontent.com/6016485/109181644-719a5a80-778c-11eb-9665-aafa7dd8a317.png)
![image](https://user-images.githubusercontent.com/6016485/109181662-76f7a500-778c-11eb-8517-65dcc85d7fc9.png)

So there is no information or id of the entity on which error occurred.
Maybe it is possible to add the id of the entity to the response, not only the error code to detected on which products error happened.

**Comment by shyim** [comment]
You have in the error the pointer. It says the third row productNumber is empty. does that not help?

**Comment by ascheider** [comment]
@shyim Hey, yes you are right at that point. I will try to provide better example, i think there is issue if you send not only the product as entity, but also product-translation and if there is also error in the same request than the error message is ambiguous. If i can reproduce it, i will upload example here. thanks

**Comment by shyim** [comment]
Can you upload it directly to https://issues.shopware.com/ it's better prioritized than GitHub :)
