### ISSUE TITLE
Move/add sorting of salutations to SalutationRoute

### ISSUE THREAD

**Issue by PheysX** [shopware/platform#1676]
**Description**  

Shopware is adding a custom sorting function in multiple files:

- [CheckoutRegisterPageLoader](https://github.com/shopware/platform/blob/trunk/src/Storefront/Page/Checkout/Register/CheckoutRegisterPageLoader.php#L122)
- [AccountLoginPageLoader](https://github.com/shopware/platform/blob/trunk/src/Storefront/Page/Account/Login/AccountLoginPageLoader.php#L87)
- [AddressDetailPageLoader](https://github.com/shopware/platform/blob/trunk/src/Storefront/Page/Address/Detail/AddressDetailPageLoader.php#L101)
- [AddressListingPageLoader](https://github.com/shopware/platform/blob/trunk/src/Storefront/Page/Address/Listing/AddressListingPageLoader.php#L113)
- [AccountProfilePageLoader](https://github.com/shopware/platform/blob/trunk/src/Storefront/Page/Account/Profile/AccountProfilePageLoader.php#L84)

But not in the store-api route **SalutationRoute**.

All of this files are calling the **SalutationRoute** to get the salutation collection and sort it by themselves:

```
$salutations->sort(function (SalutationEntity $a, SalutationEntity $b) {
    return $b->getSalutationKey() <=> $a->getSalutationKey();
});
```

Move the sorting function into the **SalutationRoute** to make it available via store-api, plugins no longer have to sort it themselves to get the same sorting and reduce duplicate code in one small step. 😊

**Comment by shyim** [comment]
Thats intended as the route is like an repository for us. It can be called through PHP or API. The API users can sort by own criterias. Thats the reason why its outside
