### ISSUE TITLE
Images and diagrams are not displayed in the documentation

### ISSUE THREAD

**Issue by seriewe** [shopware/platform#1682]
**Description**  

Examples
https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/core

https://github.com/shopware/platform/blob/2f0f1379273f6869d20e5e5032f720aae746d80c/src/Docs/Resources/current/60-references-internals/10-core/__categoryInfo.md

https://github.com/shopware/platform/blob/2f0f1379273f6869d20e5e5032f720aae746d80c/src/Docs/Resources/current/60-references-internals/10-core/__categoryInfo.md

**Possible Solution**  

rebuild documentation?
The "dist" folder does not seem to be there.

**Additional context**

**Comment by elkmod** [comment]
Hi @seriewe - thank you for noting the issue! The documentation is not maintained anymore. Please refer to developer.shopware.com or github.com/shopware/docs instead.
