### ISSUE TITLE
bin/setup database port failes

### ISSUE THREAD

**Issue by axzx** [shopware/platform#1684]
**Description**  

https://docs.shopware.com/en/shopware-platform-dev-en/system-guide/installation?category=shopware-platform-dev-en/system-guide
```
> bin/setup
```

```
Database host [localhost]:
```
`localhost`

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Style\SymfonyStyle::ask() must be of the type string or null, int given, called in development/bin/setup on line 94 and defined in development/bin/vendor/symfony/console/Style/SymfonyStyle.php:267
```

**Possible Solution**  
edit `bin/setup`
line 94

```
$configuration['DB_PORT'] = $io->ask('Database port', '3306', $emptyValidation);
```

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/development/commit/b372df485a37c0f3090d32276a64b686f87c32af
