### ISSUE TITLE
State machine state - name is expected to be a string but it should be nullable

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1690]
**Description**  
As the name of the state machine state is translatable, the name field should actually be nullable, however, according to https://github.com/shopware/platform/blob/v6.3.5.2/src/Core/System/StateMachine/StateMachineEntity.php#L76
it currently is required to be a string.

This is especially an issue in combination with https://issues.shopware.com/issues/NEXT-13730

**Possible Solution**  
Adjust type hint and also fix https://issues.shopware.com/issues/NEXT-13730

**Additional context**  
Currently, state transitions to various order/payment/delivery state changes fails completely (server error), if it is not translated to the current language, as name is `null` and the template tries to access name (which is wrong too).

**Comment by ghost** [comment]
@AndreasA currently I have this issue. I'm not sure if I understand your solution, do you mean that the name (subject) of a email template isn't translated correctly or the statename? I cannot find anywhere that I can change the statename?
Can you help me out?

**Comment by AndreasA** [comment]
@studiovlist 
Various e-mail templates (not sure if that is still the case) use `*.stateMachineState.name` like `order.stateMachineState.name`. The issue is that e.g. `order.stateMachineState.name` does not take translation fallbacks into account.

It would have to be replaced with `order.stateMachineState.translated.name` that way it should work fine. This has to be done in all relevant e-mail templates. You need to check all templates you use in all languages and subjects and contents (html and plain).

From what I saw a similar issue exists with the sales channel name, like `salesChannel.name` which should be `salesChannel.translated.name` in the e-mail template (check subject and contents).

State names currently can only be changed in the databse directly. Probably something that should be changed as well.

Though I am not sure it will still fail the to send the e-mail as this https://github.com/shopware/platform/pull/2136 was merged but it might still not produce any state names.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
