### ISSUE TITLE
Addition of static content/CMS blocks

### ISSUE THREAD

**Issue by niklaswolf** [shopware/platform#1695]
**Description**  
It would be a great addition to the already great shopping experiences if there was the possibility to add/edit static cms blocks. A static block in my understanding is a cms block, that has some static content and is reusable in different places. Like this, there is the possibility to manage content in a single place that gets reused throughout different layouts, pages, etc...
I propose also to make these blocks individually queryable through the store api by a custom name so that it also can be used in headless scenarios, e.g. static pages in shopware-pwa which have a small block of reused content.

**Example**  
Imagine for example a "social-media"-block with all the icons/links to the corresponding social media channels of the merchant. This block should then be shown in different places, e.g. the footer, in a sidebar on categories, on product pages, etc... This is a quite simple example, but right now it requires the merchant to add different blocks with the same content which is quite redundant.

EDIT: also created this feature-request in the shopware issue tracker: https://issues.shopware.com/issues/NEXT-14206

**Comment by gRoberts84** [comment]
I'll be needing something like this shortly for a project I'm working on, however I assume you simply register your own blocks using plugins and then you can use them anywhere you like. 

https://docs.shopware.com/en/shopware-platform-dev-en/how-to/custom-cms-block

**Comment by niklaswolf** [comment]
@gRoberts84 yes that's indeed a workaround, but like this you have to hardcode the content in the plugin code. Like this the merchant is not able to change the content through the admin interface. Furthermore, these blocks can not be queried through the store-api, just as a part of a whole layout.

**Comment by LouisEiermann** [comment]
Configureable "static" blocks would really go a long way. Sometimes i come back to a project and find myself wanting to change things in several different blocks, which you can only really do by changing them individually where they stand in different layouts/pages right now. A central place to manage the contents of a block is much needed i think.

**Comment by CrystalG23** [comment]
+1

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
