### ISSUE TITLE
Inconsistent cart error alert placeholder

### ISSUE THREAD

**Issue by leohilbert** [shopware/platform#1717]
**Description**  
Hi, when creating cart errors in Shopware, which need values displayed in the Storefront, Shopware supports to define these values as properties, so that they can be referenced in the translation-snippets.
Here is an example from Shopware's own `\Shopware\Core\Content\Product\Cart\ProductOutOfStockError`
```    
Code:
public function getParameters(): array
{
    return ['name' => $this->name];
}

Translation-Snippet:
"product-out-of-stock": "%name% is not available at the moment.",
```

Unfortunately Shopware interprets these properties differently based on where in the Storefront it gets displayed.

When showing the error in the `offcanvas-cart` view, it reads the properties from the parameter like expected (`src/vendor/shopware/storefront/Resources/views/storefront/component/checkout/offcanvas-cart.html.twig:39`).

When showing the error in the `/checkout/cart`-view, it includes `@Storefront/storefront/component/checkout/cart-alerts.html.twig` to display these errors, which only replaces the "name"-parameter using the PHP-Property of the error and completely ignores the "getParameters()"-array defined in the class.

So for example if I define a parameter "value" in the "getParameters()"-array of the PHP-Error and then use "%value%" in my snippet, it will be displayed correctly when viewing it in the offcanvas-view, but remains "%value%", when viewing it in the "normal" cart-view.

So to get a consistent translation for all views, you must only use the "name"-parameter, since otherwise it will not be replaced correctly for the cart-view.

Here is a screenshot to showcase this:
<img width="927" alt="Bildschirmfoto 2021-03-18 um 12 11 00" src="https://user-images.githubusercontent.com/2004063/111617690-b93c6100-87e3-11eb-9b89-3564d54f7936.png">

For now I will simply use the "name"-placeholder, but it took me some time to figure that out an it will probably confused more developers working on this. Also this prohibits using more than one value in your translations, since you only have "name" to work with.

**Possible Solution**  
I don't know why it was implemented that way, but I'm sure it wasn't without its reasons.
IMO the cleanest approach would be to use the same Altert-Include for the Cart-View that it used for the off-canvis cart view:
```
{% for type, messages in app.flashes %}
    {% sw_include '@Storefront/storefront/utilities/alert.html.twig' with {
        type: type,
        list: messages
    } %}
{% endfor %}
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
