### ISSUE TITLE
Customer email not sent when additional recipients are set for Order placed business event

### ISSUE THREAD

**Issue by giacmir** [shopware/platform#1720]
**Description**  

I added some additional recipients to the "Order placed" business events and now the confirmation email is sent only to those recipients and not to the customer.

It can be reproduced with there steps:
1. in admin go to settings -> business events and search for "order placed"
2. change the business event configuration adding at least one recipient (note that it says "Customer emails will be sent regardless."
3. place an order
4. check mailhog
an email has been sent but only to the additional recipient. If you delete it from config and place another order then the email is sent to customer.

**Comment by foxgreek** [comment]
ping @giacmir - did you found a workaround for this issue? The problem still exists in 6.3.5.4

**Comment by giacmir** [comment]
@foxgreek issue seems fixed in trunk, for 6.3.x I solved with this patch (installed with [cweagans/composer-patches](https://github.com/cweagans/composer-patches)):


```Index: vendor/shopware/platform/src/Core/Content/MailTemplate/Subscriber/MailSendSubscriber.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- a/vendor/shopware/platform/src/Core/Content/MailTemplate/Subscriber/MailSendSubscriber.php	(date 1616688354642)
+++ b/vendor/shopware/platform/src/Core/Content/MailTemplate/Subscriber/MailSendSubscriber.php	(date 1616688354642)
@@ -121,9 +121,9 @@

         $data = new DataBag();

-        $recipients = $mailEvent->getMailStruct()->getRecipients();
+        $recipients = $mailEvent->getMailStruct()->getRecipients() ?? [];
         if (isset($config['recipients'])) {
-            $recipients = $config['recipients'];
+            $recipients = array_merge($recipients, $config['recipients']);
         }

         $data->set('recipients', $recipients);
```

**Comment by foxgreek** [comment]
@giacmir thanks a lot!

**Comment by mitelg** [comment]
so the issue could be closed, as it is fixed with 6.4.0.0 ?

**Comment by giacmir** [comment]
@mitelg I have not tried with 6.4, but looking at source code and history I think that e66cd0b18702b7ff32eb0a3c78162bc75f7c1545 may have solved the issue. Maybe @hungmac-sw has some more information?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
