### ISSUE TITLE
Bug: Sales channel base URL ignored during theme compilation - e.g. command line

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1725]
**Description**  
The command line `theme:compile`  always falls back to the `APP_URL`  variable for the `sw-aasset-theme-url` etc.

However, that variable might not be the one used for the current sales channel. Sure, it will still work but it points to the wrong domain which is weird that e.g. if the other domain is not reachable anymore those assets cannot be loaded anymore and the network tab will show requests to a different domain. With language switchers it is even more complicated.

But why do you need the URL anyway? shouldn't those files be reachable by using `/...`?  is this for the hot reloading server?

**Possible Solution**  
- Do not use the URL at all. using `/` only should be fine as Symfony does with `path` twig helper. Might be an issue for watch tasks but I think for those the default APP_URL could be injected, if necessary.

or:
- Improve the variable to inject the domain from the sales channel.
- This will also require you to compile the theme per domain instead of per sales channel. This actually would make more sense as the variables should not be different per sales channel as the theme config is uniquely defined.

**Comment by AndreasA** [comment]
This is actually more of an issue then I though because e.g. web fonts will fail to load without adjustments to the CORS headers as those are limited by CORS too.

**Comment by yunits** [comment]
This issue still exists in 6.4.14.0. In my case I have 2 sales channel. 
My first sales channel has the same URL as my APP_URL.
My second sales channel has another URL but "all.css" gets loaded from my APP_URL.
That means myseconddomain.com loads myfirstdomain.com/all.css and this all.css tries to load my webfonts => CORS
Is there any workaround?

**Comment by hlohaus** [comment]
I had created a pull request, but i didn't had time to finishing it:

https://github.com/shopware/platform/pull/321

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
