### ISSUE TITLE
sw-asset-theme-url scss variable: Does not point to the theme but only the default public URL

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1726]
**Description**  
`$sw-asset-theme-url`  only points to the default public URL which is kind of wrong. I would have expected it to point to the current heme, so like e.g. `https://example.com/theme/<id>`

that would also ensure the asset path defined here: https://github.com/shopware/platform/blob/trunk/src/Storefront/Resources/app/storefront/src/scss/abstract/variables/_custom.scss#L30

would not be theme specific but could be: `'#{$sw-asset-theme-url}/assets` or similar.
Which would allow one to just use
`'#{$sw-asset-theme-url}/bundles/font/myfont.otf` in a theme instead of something like:
`'#{$sw-asset-theme-url}/bundles/mytheme/assets/font/myfont.otf` or even weirder and it actually points to outside the theme.

**Possible Solution**  
- Pass on the theme ID the variable injector.
- Create a ThemeBasedPackageInerface that has a setThemeId method which you call before getUrl, so the URL generator can access the theme id.
- Maybe unset theme ID after determining URL.
- Or set the the package ID through dependency injection somehow, e.g. by a themeidprovider service or similar.

Not sure that is the best solution though.

**Comment by shyim** [comment]
I would see there an specific variable for that. sw-asset are dynamic variables based on registered Symfony assets

**Comment by AndreasA** [comment]
There is already a sw-asset-public-url for that. Those are also assets and it is called sw-asset-*theme*-url. So it should point to the theme not to the root directory but a separate variable is fine too.

And as mentioned here https://github.com/shopware/platform/issues/1725 it uses always the same host, so that is wrong too as the URL atually depends on the domain assigned to the sales channel. Though I am not sure one actually needs the full URL. I think a path starting with `/`  as Symfony's `path` twig helper do, should be enough. Not sure regarding watch tasks though but in that case the APP_URL could be injected instead.

**Comment by shyim** [comment]
We built it in the meanwhile relative to the CSS file. This should fix it
