### ISSUE TITLE
DAL: More complicated queries, e.g. SQL functions like COALESCE etc. in filter and sorting, also filter by grouped by values and use functions there

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1731]
**Description**  
DAL currently only allows very basic queries, e.g. I am not able to do something simple like 
```sql
ORDER BY COALESCE (`updatedAt`, `createdAt`) DESC
```
which would be really helpful to find out the last edit record which can only be determined this way. There are a lot of order things like this that simple are not possible but are really easy using SQL directly. 
However, it sounds like a bad idea to bypass DAL and retrieve data using DBAL directly in case of future updates. Also I would only retrieve rows and would then still have to convert those to entities, e.g. retrieve a lost of IDs and then retrieve those records but in combination with pagination this is way more complicated.
Another example would be to group records and only return those where the grouped count is greater than eg. 1

**Possible Solutions**  
- Probably not feasible for SW6: Switch back to Doctrine ORM. Seriously, the DAL part of Shopware 6 has way to many missing features (proxies etc). Probably not possible for SW6 but you should seriously consider this for SW7. Even the configuration is way more complicated (missing annotations etc.).
- Allow at least some more complicated queries for DAL entities. Might not be possible to support the full Doctrine ORM featureset but at least a bit mroe complex queries would be nice, e.g. using functions in field sorting.
- Maybe support building the query using DBAL and use it to retrieve data using DBAL as doctrine ORM has something similar?

**Comment by ireznik** [comment]
The current implementation of the filters does not allow to implement custom filters to search e.g. xpath expressions in json data.

**Comment by shyim** [comment]
DAL tries to solve with an very difference approach how to handle data. It's not really compareable with the Doctrine ORM. The criteria has to be valid in Elasticsearch and SQL. So the usage of of SQL functions will never work. 
The solution would be to have own filters in DAL which will be translated to the wanted SQL and to the Elasticsearch implementation of it.

Your example is possible to do by adding two sortings updatedAt desc, createdAt desc

**Comment by AndreasA** [comment]
No that is not the same updatedAt has `NULL` values which will be at the end of the query. 
This means that `NULL` values with `DESC` in updatedAt are at the end of the query, even if their createdAt might be newer. This is a huge difference.

And how would I create such a filter to manually do this and use it in field sorting etc.? Is there an example documentation? Because yes I can create a filter but: How would I use that in a field sorting? And how would I convert it to SQL syntax?

And I know that DAL tries to do stuff differently from doctrine ORM and that results in way more issues then it resolves in my opinion.

**Comment by AndreasA** [comment]
Btw. elastic search and database queries are quite different. Not only from the syntax but also from how, e.g. in the elastic search one usually places the fields in the index multiple times, e.g. copy the name into a field that has different tokenization etc. Which can then be queried. This is not the case for databases. 
Sure I could create a calculated field but that is not the same and for existing entities I cannot just add such fields anyway in DAL.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
