### ISSUE TITLE
Entity Extension - Support scalar (non relation) fields

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1733]
**Description**  
Why can I not add scalar fields using entity extensions. That seems like an unnecessary restriction. Sure I could use custom fields but those are always translatable and they are JSON fields so not that nice for filter/search purposes.

Such fields could even be calculated fields. This could also help a bit with https://github.com/shopware/platform/issues/1731 though it isn't a perfect solution. Not to mention it makes it easier to extend the entity for filterable fields that do not require relations (otherwise a 1:1 relation is needed).

**Comment by shyim** [comment]
Hey,

this restriction is intended as an ALTER TABLE call for example an order table can take very long when there are multiple million rows. Is there any problem using the 1:1 association to create new fields?

**Comment by AndreasA** [comment]
@shyim 

It can be quite tedious,

- Extending the admin interface is way more complicated. For instance the product admin, and new products, it was quite tricky to support a field in the one to one relation there in 6.3.5.4 as the corresponding extension might not be there yet which resulted in problems with entering data and/or saving data.
- The data is not always there. Everywhere one needs it, it might need to be joined manually. Sure I can set autoload but not sure , if it is really a good solution and not 100% sure if it works in all scenarios as the product could already be an association of an association. Though I think it does work.
- For n:1 relations I still need to modify the original table like e.g. adding a custom order state. This still triggers the ALTER TABLE. Furthermore, your own core migrations also sometimes alter tables, which is the same issue.

It just seems like an arbitrary limitation that actually makes things unnecessary difficult, especially when dealing with a new project where there are not yet a lot of rows and even then at least Shopware core updates might still trigger such updates.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
