### ISSUE TITLE
Cart error shown twice, if newly added e.g. quantity change

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1735]
**Description**  
Cart errors are shown twice in the storefront if it is newly added. The reason is that once it is shown in the flash bag and once from the cart itself. This is kind of confusing. This happens e.g. on cart quantity change, if a cart processor adds the error for certain quantities.

**Possible Solution**  
- Clear the flashbag of all cart errors on checkout pages that show the cart errors too? Or just skip outputting those in the template. Should only happen on pages that show the cart errors.

**Comment by AndreasA** [comment]
This is also the case for the offcanvas cart, if e.g. a product is added.

**Comment by AndreasA** [comment]
This is actually even more tricky as the success message for the quantity change also is not shown. It is related to the cart processor adding the error. I have now as workaround excluded those routes from the cart processor as it will show the error afterwards anyway.

Maybe some flag could be added to let the cart processor know if it is one such route to fix this?

**Comment by AndreasA** [comment]
On production cart errors also added to the flashbag upon adding an item to cart, this does not happen in dev which results in the cart either not having the flash message (dev with disabling adding messages during cart add) or multiple times (prod with enabled adding messages during cart add).

```
        if ($request->cookies->get('sf_redirect') === null) {
            $cart = $page->getCart();
            $this->addCartErrors($cart);
            $cart->getErrors()->clear();
        }
```

in `\Shopware\Storefront\Controller\CheckoutController::offcanvas`

If I remember this correctly, the sf_redirect cookie is only set if the web profiler is enabled as it contains debug information for the profiler, which should not be the case in production enviornments.

**Comment by AndreasA** [comment]
The same solution I mentioned in https://github.com/shopware/platform/issues/1865 should also work here.

> Remove this check and do it differently, e.g. by using peek and only adding the cart flash message, if a message with the exact same content does not yet exist as the message would be the same anyway. Especially, as newly determined cart errors still have to be added. Might not the best solution but it is easy to implement and product a consitent result. Furthermore, it avoids accidentally duplicate flash messages,

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
