### ISSUE TITLE
Better way regarding calling external services during cart processors e.g. tax calculation or shipping charges

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1740]
**Description**  
The current cart processor can be called multiple times due rule / prices etc. changes. This is quite a problem, if external services are called like e.g. shipping charges / tax calculation etc. 

An improvement was to ensure these are only called for the second iteration and upwards as the cart processor is called at least twice (all rules active and current rules active). However, it would probably be even better to only call them after the internal processing is done - if it is possible for these services which should not be an issue for the ones I mentioned (external delivery and tax calculation).  
Furthermore, a memory cache ensures that the service is only called, if the request data to it change during that processing but as for multiple iterations that is quite likely the case, this is still an issue.

Furthermore, the cart route and various others actually retrieve the cart twice and calculated their values, which means for those routes without any workarounds the external services are at least called four times.

To avoid multiple calls during the cart processing:
- Maybe add a post cart processing that is only called after the main iterations are done and uses separate services.
- Ensure that those are only called once per request, e.g. on cart loading route, the initial loading should not execute them. 
- Not directly related to the performance issue but it would be helpful: Also add an option to let the user know the cart processing/recalculation is done just prior to order conversion as e.g. the tax calculation should also create a transaction then using the external service. Which cannot be done after the order has been placed as otherwise the taxes could be changed between transaction creation and calculation.

**Comment by AndreasA** [comment]
Maybe an easier and better solution could be to add three event listeneres:
- AdjustCartAfterProcessing
- AdjustCartAfterCartLoadedProcessing
- AdjustCartAfterProcessingDuringOrdering

probably not the best names but if you add these events, provide the calculated cart, the request and sales channel context, one could determine that e.g. it is the cart route (request attribute) and only call the external services in the AdjustCartAfterCartLoadedProcessing event.

You would, of course need to recalculate the cart sums after calling those events.

And one limitation would be the the active rules will not take these changes  into account but I think if it is documented correspondingly that should be fine.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
