### ISSUE TITLE
ElasticSearch 'Failed to create query: [nested] nested object under path [x] is not of nested type' with Entity Extensions

### ISSUE THREAD

**Issue by runelaenen** [shopware/platform#1744]
**Description**  
When using entity extensions, filtering on fields in these extensions will not work. The extensions are correctly pushed to elasticsearch, but their fields are not propertly initialized as a nested type so ES gives an error when you try to filter on such a field.

**Possible Solution**  
The \Shopware\Elasticsearch\Framework\Indexing\EntityMapper class needs to be updated to work with entity extensions.

**Comment by shyim** [comment]
The entire indexing will be changed in next major. You will need to extend the elasticsearch mapping by yourself when you need it in the index
https://github.com/shopware/platform/blob/trunk/changelog/release-6-4-0-0/2021-02-16-elasticsearch-refactoring.md

**Comment by runelaenen** [comment]
Okay, thanks! That's how we fixed it in the meantime 👍
