### ISSUE TITLE
Elasticsearch creates unused indices - Language not used in a sales channel or admin interface (language pack plugin)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1753]
**Description**  
If a language is not used in the admin interface or a sales channel an index for it still is created. This results in 60 indices and 180 shards (default config) being created once the new language pack plugin is installed.

After creating the aliases those shards increase by a factor of 4 again which most are unassigned in single node environments (local development or not too many products to require multiple nodes), see https://github.com/shopware/platform/issues/1752

**Possible Solution**  
Add an option to ignore languages in the elastic search and ensure those are correctly set in the language pack, if the language is disabled in storefront.

**Comment by shyim** [comment]
that is fixed in the plugin
