### ISSUE TITLE
Elasticsearch Config as bundle config instead of one array parameter

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1754]
**Description**  
Using an array parameter has huge disadvantages:
- Parameters in Symfony are one-dimensional, so it is impossible to e.g. just adjust the number of replicas without copying the whole parameter.
- The parameter array is not validate whereas with a bundle configuration it would be which would result in an error quite early, e.g during cache clear with warmup command.
- This means also that defining the parameter manually allows one to basically set an empty array as parameter which means all configuration is gone.

Using bundle configuration like you do for the framework etc. would make more sense and solve all these issues.

**Comment by shyim** [comment]
its since a month as symfony config
