### ISSUE TITLE
Elasticsearch for no products results in a server / client error exception instead of showing now products

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1757]
**Description**  
If there are no products at all and elasticsearch is used, then a storefront category that shows products results in an exception that no documents are indexed which technically is true but it should just show there are no products available. Or install language pack and execute `dal:refresh:index` multiple times without calling the cleanup command.

I haven't done too much testing when exactly this happens but it definitely happens, if there are no products at all in the database. If there is at least one that can be disabled, it doesn't seem to be an issue. 
However, I didn't check what happens, if that product is not assigned to the current sales channel.

**Comment by AndreasA** [comment]
Same issue exists for categories etc. if those entities are also in the elasticsearch

**Comment by AndreasA** [comment]
This seem to only happen if there is no entity (doesn't matter if it is enabled or not) indexed at all. However, that is still a valid response. it is possible that I have no products yet (especially in the admin interface). 

I haven't tested this with 6.4 RC1 yet but the method `\Shopware\Elasticsearch\Framework\ElasticsearchHelper::hasIndexDocuments` is now gone, so I guess this might actually be fixed there already.

**Comment by shyim** [comment]
Thats fixed. It does not check anymore the count
