### ISSUE TITLE
NEXT-14628 | Honeypots can be ignored by bots since its labeled

### ISSUE THREAD

**Issue by juripetersen** [shopware/platform#1760]
**Description**  

Honeypots in the registration form are wrapped like this:
```
<div class="captcha--honeypot">
        {% block component_captcha_honeypot_input %}
            <input type="text"
                   name="{{ constant('Shopware\\Storefront\\Framework\\Captcha\\HoneypotCaptcha::CAPTCHA_REQUEST_PARAMETER') }}"
                   class="d-none"
                   value=""
                   tabindex="-1"
                   autocapitalize="off"
                   spellcheck="false"
                   autocorrect="off"
                   autocomplete="off"
            >
        {% endblock %}
    </div>
```

This introduces the possibility for bots to query for something like "honeypot" and ignore all inputs that are children of the element. 
Multiple customers have been "attacked" by bots even though they use the Honeypot. 

**Possible Solution**  

The solution is fairly simple, since the ```class="captcha--honeypot"``` does not introduce new styles in the standard template, a change of naming could prevent bots or scraping programs to identify the honeypot.

**Additional context**

**Comment by shyim** [comment]
PR is merged
