### ISSUE TITLE
Context object missing useState method like the scope, enableInheritence etc. methods?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1771]
**Description**  
Shouldn't the context object have an option to use a state and immediately remove it again afterwards using a method similar to the current scope method? e.g. I want to only enable elasticsearch for the current search and then disable it afterwards.

**Comment by shyim** [comment]
With 6.4 the context can have states.
Elasticsearch is implemented as you suggest it :)
https://github.com/shopware/platform/blob/52af79fac965193041a1282a4eee9e1bd675ba15/src/Core/Content/Product/SalesChannel/Search/ProductSearchRoute.php#L77

**Comment by AndreasA** [comment]
@shyim 
Hi, yes but I did not mean `add` and `remove` methods.

I meant an option to do something like:

```
$context->useState(Context::STATE_ELASTICSEARCH_AWARE, function ($context) {
    // Execute search here.
});
```

where only that one search inside is called with the adjusted context to ensure I do not need to manually remove it again.

Not that big an issue but it should be quite straightforward to implement.

However, I think this https://github.com/shopware/platform/issues/1757 has been fixed with 6.4 now but I am not 100% sure as I did not test it.

**Comment by shyim** [comment]
Ahh. Looks like an easy task. Maybe want to provide an PR? 😊

**Comment by AndreasA** [comment]
I am not sure if I should put it into the context object or in the state aware trait. I think it should be possible to implement in both but not sure if it would be better to put it in the trait or not

**Comment by shyim** [comment]
Trait would be better as addState is there

**Comment by AndreasA** [comment]
OK. I am not yet sure when I will find the time but I will create a PR once I have the time if no one else hasn't created one yet.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
