### ISSUE TITLE
Order list breaks on customization

### ISSUE THREAD

**Issue by powli** [shopware/platform#1774]
**Description**  
Customizing (through a `Shopware.Component.override`) the order list (`sw-order-list` component) in administration results in no orders being shown anymore.

**Affected versions**
* 6.4.0.0-RC1
* dev-trunk (949b6ca9ef)

**Additional context**  
Our investigation showed that the resulting `sw-order-list`-component will have the stub methods and data defaults from the [`listing`-mixin](https://github.com/shopware/platform/blob/4f0a618/src/Administration/Resources/app/administration/src/app/mixin/listing.mixin.js). So somewhere in the process, the mixin is applied in a wrong way, overriding the local implementation/properties of the order-list component.

Following **empty** customization is enough to provoke the behaviour:
```js
Shopware.Component.override('sw-order-list', {

});
```

We assume the problem got introduced with [this change](https://github.com/shopware/platform/commit/6feca3e465143198a29b469790e678f2fadc410a).

The following illustrates the issue: the`sortBy` property is `null`, as defined in the [listing mixin](https://github.com/shopware/platform/blob/4f0a618/src/Administration/Resources/app/administration/src/app/mixin/listing.mixin.js#L11). The `getList` methods logs the default implementation from the [listing mixin](https://github.com/shopware/platform/blob/4f0a618/src/Administration/Resources/app/administration/src/app/mixin/listing.mixin.js#L246-L251) instead of running the implemented version of the [sw-order-list component](https://github.com/shopware/platform/blob/4f0a618e2cdab1a4b53f9411ccd9d80bf3d54d2e/src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-list/index.js#L255-L272)
![Order list with console output](https://user-images.githubusercontent.com/4511053/114880614-7e3d4580-9e02-11eb-8c96-6a97302516c8.png)

**Comment by shyim** [comment]
https://github.com/shopware/platform/commit/a05c17cc5995769d524359bddd144a357c117394 has been fixed

**Comment by powli** [comment]
We can confirm that the change solved the problem alright.
