### ISSUE TITLE
Rule for generic "order amount" / one can circumvent payment methods selected by CartAmountRule

### ISSUE THREAD

**Issue by apfelbox** [shopware/platform#1790]
**Description**  
I have the issue, that in our shop we need to allow checkouts with "empty" carts, so where the cart amount is 0,00€.

However, for carts with amount 0,00€ we only want to have a single payment method called "Free" (we just relabeled "cash on delivery" for that). 

We enable + disable these payment methods based on rules, using the `CartAmountRule`.

But: 

* I now want to checkout with my cart with value 100€.
* The rule works, it presents the regular payment methods and I choose "Paypal".
* I hit "order now"
* I am redirected to Paypal
* I abort the payment with Paypal and get redirected back to the shop.
* Now my cart was transformed to an order, so I don't get redirected back to `/checkout/...` but rather to `/account/order/edit/...`. Also my cart was transformed to an order.
* My cart is now empty, so the rule only enables the "free" payment option.
* I can checkout for free.

I understand that technically the rule is correct, however is there a rule that handles the "order amount" value? And "order amount" is intelligently either the cart amount (for `/checkout/...` or the order amount (for `/account/order/edit..`)?

Is there any other way to solve this?

**Possible Solution**  
Unfortunately I have no idea on how to solve that.

**Additional context**  
I have no idea if this is a bug report, a feature request or just a question.

For me, intuitively "cart amount" would have covered both cases, even if technically in the second case it is not a "cart" anymore. So, no idea.

**Comment by JOverhaus** [comment]
Hello,
I was able to solve the issue by using a different condition in the rule builder.
The rule line item total price is equal to 0,00€ was working fine in the payment change process.

If this is not working for your case of course feel free to let us know.

**Comment by apfelbox** [comment]
@JOShopware thanks for your response.

So I tried to set the rules to `Line item total price < 0.01` and `Line item total price >= 0.01` accordingly (just using `0` doesn't work for me, as the value is not stored / removed. Probably an invalid PHP `empty()` check..).

It works on the cart page, however on the account order edit page, I now have no possible payment methods.
So unfortunately, this doesn't seem to work either.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
