### ISSUE TITLE
Mail service pre and post render events

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1793]
**Description**  
There are no pre and post render events in the mail service. Would be nice to have them.

**Comment by mitelg** [comment]
does this help?
https://github.com/shopware/platform/commit/81b90998c4ffcd0fac8803ff4f48b2f063d363a0

**Comment by AndreasA** [comment]
@mitelg I think it will as I have the template info available and can modify the data before the render is called. post render would still be nice.

**Comment by shyim** [comment]
You can use https://github.com/shopware/platform/blob/724b35bd985bbe790d9e670b54284e78d9de80c5/src/Core/Content/Mail/Service/MailService.php#L118-L120 to manipulate the variables of the mail
