### ISSUE TITLE
ACL for Storefront users - like Symfony security bundle with voters, roles etc.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1812]
**Description**  
It would be nice if the storefront users could have advanced permissions which is easily possible using the symfony security bundle but seems way more complicated with your setup for Storefront users - even roles are missing.

Most cases not necessary but for advanced custom features this would be a nice feature to have.

**Comment by mitelg** [comment]
there is an enterprise extension for different roles of customer accounts: https://enterprise.shopware.com/en/b2b-commerce/

so this will not be part of the core, but is part of the enterprise version

**Comment by AndreasA** [comment]
@mitelg That is only the case for B2B customers. what about private customers?

**Comment by mitelg** [comment]
as you already stated by yourself, this is a very custom scenario. so in my opinion nothing that has to be available in a standard software solution. 
If the enterprise version does not match for a project, this needs be implemented with a custom functionality/plugin.

**Comment by mitelg** [comment]
I don't know the enterprise extension in detail, but I guess I could use this role management for all customers

**Comment by AndreasA** [comment]
@mitelg Roles are only available for B2B customers and even then only for the contacts the create. it has no impact on private customers at all as the B2B has a completely different interface.

futhermore, the b2b plugin does not support headless at all, so it cannot be used here either.

**Comment by mitelg** [comment]
okay, that could be :blush: as I said before, I don't know the enterprise extensions in detail. I thought this would be possible. 

But nevertheless this will not change the decision that your feature request will not be part of the core, as this is a too specific feature for only few merchants. 

to be honest this is the first time I face someone requesting roles for "normal" private customers :blush: 
maybe different customer groups could already do the trick?

**Comment by AndreasA** [comment]
It might not be needed very often but if you have a system in place in the core, it would be usable for B2B etc. and Symfony security would provide everything you need and it could also be used for api validation in the admin etc. but it would probably require a lot of rework.

**Comment by mitelg** [comment]
that's right :+1: 

if I remember correctly we even evaluated to use the security component for customers in the beginning. But unfortunately I can't remember why we decided not to use it :slightly_frowning_face:
