### ISSUE TITLE
APP_DEBUG=0 can result in frozen parameter bag errors

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1821]
**Description**  
Using the console command debug:config with APP_DEBUG=0 can result in `Impossible to call set() on a frozen ParameterBag.` as you set parameters in the bundle class of the framework directly. However this should actually happen in the extension.

**Possible Solution**  
Set the corresponding parameters in the FrameworkExtension.

or adjust the set to:
```
if (!$container->getParameterBag() instanceof FrozenParameterBag) {

    $container->setParameter('locale', 'en-GB');
}
```
However, that then results in another error.

Though using the extension would be a cleaner solution.

The same is the case for loading various configuration files. this should be done using `PrependExtensionInterface` for the extension. This is actually probably the second issue.

The issue might not happen all the time but it definitely occurs.

**Comment by shyim** [comment]
Works in trunk

Tested:
```
APP_DEBUG=0 APP_ENV=dev bin/console debug:config
APP_DEBUG=0 APP_ENV=prod bin/console debug:config
```

**Comment by AndreasA** [comment]
@shyim Great. The ticket is older after all.

**Comment by AndreasA** [comment]
@shyim you also need to specify a config name to read for. With 6.4.2.1 it definitely doesn't work. Also it might be possible that the issue can be mitigated if there is no cache folder yet in that environment.

Can you try the following:

```shell
APP_DEBUG=0 APP_ENV=prod bin/console cache:clear
APP_DEBUG=0 APP_ENV=prod bin/console debug:config shopware
```

**Comment by mitelg** [comment]
with the example given by @AndreasA, I can also reproduce this issue

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
