### ISSUE TITLE
sw_thumbnails: Use highest thumbnail as highest resolution image instead of original image

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1825]
**Description**  
In case the user uploads an image with 8192px width, and their monitor is above the maximum bootstrap container width and the image is inside the container, it really does not make sense to display the original image as the bootstrap container limits the image width. Currently the sizes then use `100vw` which is actually the viewport width which makes sense for fluid containers but not for others.

Therefore, it would make more sense to use the highest resolution thumbnail instead` of the original. Especially as the original will not be optimized either.

Or is there already an option for this that I just don't see?

**Comment by ChristopherDosin** [comment]
You can define the thumbnail sizes per viewport - maybe you're overlooking this? check out the following article:
https://developer.shopware.com/docs/guides/plugins/plugins/storefront/use-media-thumbnails#dealing-with-thumbnail-sizes

**Comment by AndreasA** [comment]
@ChristopherDosin Yes but that produces the following max size media query:
```
(max-width: 1920px) and (min-width: 1200px) 284px,
...,, 100vw
```
and 
srcset:
```
http://shopware.local/media/06/f0/5c/1614258798/example-image.jpg 1921w,
....
````


which means that the if the viewport is above 1920px, it falls back to 100vw and therefore the original image. and viewports above 1920 are not that unusal anymore. However, if the image is shown inside a bootstrap container it is still unnecessary to load the original image or to be more precise as the original usually is not compressed, it will be unnecessary nearly all the times.

So I don't want it to fallback to `100vw` at all. Would I need to create additional viewports? But even then it would result in a max value before it falls back to 100vw.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
