### ISSUE TITLE
Add test for mailer configuration

### ISSUE THREAD

**Issue by AltayAkkus** [shopware/platform#1828]
**Description**  

Adding a button + a text field with an email address, when clicking the button Shopware6 will try to send a mail to that address via the mailer configuration

Setting up the mailer config without having this feature is kind of hard, a manual test so see if the connection even works would be even better.
(For passing users: I just registered a new User, and then used the forgot password form in order to check the mailer)

**Comment by xLarry** [comment]
There is a (well hidden) feature which comes close to what you are looking for I guess:

If you are looking at a specific mail template there's a `paperplane` icon  on the top right which reveals a form to send a test mail to a specific address:

![image](https://user-images.githubusercontent.com/16979039/118259461-77f9c200-b4b1-11eb-97f3-e210f191d32e.png)

**Comment by shyim** [comment]
With 6.5 we have also

```
./bin/console mailer:test <your-mail>
```
