### ISSUE TITLE
inheritace of variants products

### ISSUE THREAD

**Issue by Skpe829** [shopware/platform#1830]
There's a issue/bug in Products.

When you create a product and theirs variants in **Prices**, in tax rate inherited from parent appears wrong. You check several options  and Tax rate is not set correctly

![image](https://user-images.githubusercontent.com/15944889/116107190-6ecac180-a678-11eb-9999-fa8b743bf775.png)

https://drops.digital-loop.com/3Oi0y6

**Comment by JoshuaBehrens** [comment]
Hi @Skpe829 I did not get the scenario yet. So you have multiple product variants with the same rate as the parent by inheritance. And a single variant has a different rate. How do you get into that situation and why is that bad?

**Comment by Skpe829** [comment]
Hi @JoshuaBehrens! When you check many variants you have some variants set with "Standard rate" (normal) and anothers ones with Reduced rate 2  or Reduced Rate.

Here is a video: https://drops.digital-loop.com/3Oi0y6

Parent: 
![image](https://user-images.githubusercontent.com/15944889/116250637-81560100-a733-11eb-866d-d4dd8de0138d.png)

Variant 1: 
![image](https://user-images.githubusercontent.com/15944889/116250662-89ae3c00-a733-11eb-8ac9-7fd541c5f314.png)

Variant 2:
![image](https://user-images.githubusercontent.com/15944889/116250702-929f0d80-a733-11eb-9973-6945487af357.png)

**Comment by JoshuaBehrens** [comment]
So you did not set these manually but they popped up out of nowhere? That is indeed crazy

**Comment by Skpe829** [comment]
Hi @JoshuaBehrens  Yes, its crazy... I made a video when I create a new product with new variants.

**https://drops.digital-loop.com/d3mpm4**

There you'll can watch in 2nd variant its selected a different option.

**Comment by JoshuaBehrens** [comment]
Which shopware version?

**Comment by Skpe829** [comment]
6.3.4.1 and 6.3.5.4, I made tests in these versions

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
