### ISSUE TITLE
Performance: high memory usage, long execution time

### ISSUE THREAD

**Issue by DirkPersky** [shopware/platform#1831]
**Description**
Some times the memory usage is very high, if i add 1 Product ty the card the Memory usage is increased by 10-40MB per product.

The Screens below are a cart of 25 products: `/checkout/cart`
![image](https://user-images.githubusercontent.com/1736266/116377880-e8e27e00-a811-11eb-8a16-c542da18ba16.png)
![image](https://user-images.githubusercontent.com/1736266/116377851-e4b66080-a811-11eb-946a-3ef2176ba029.png)

If i ordered the products than the memory usage drop down to 25 MB.

**Comment by mitelg** [comment]
hey @DirkPersky 
on which version did you have this issue? we highly improved the performance in 6.4.0.0 which is currently in RC phase

**Comment by AltayAkkus** [comment]
hey,
if this took place in a newer version, would you mind posting the steps to reproduce?
thank you in advance

**Comment by DirkPersky** [comment]
![image](https://user-images.githubusercontent.com/1736266/116519571-ec3d3e80-a8d1-11eb-9212-5ed96c6b562e.png)


6.3.5.2 @mitelg

**Comment by mitelg** [comment]
do you have the possibility to check the 6.4.0.0RC release? would be nice to know, if this version will fix your problem :blush:
