### ISSUE TITLE
product_category.repository - Fitler by category.<property> - Fails as it generates a join referencing version_id instead of category_version_id

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1833]
**Description**  
Using the product category repository to find all IDs for a specific product ID and a certain related product property over the category join (it is enough to use `category.id` but in my case I actually want to access data in a category extension, fails as DAL tries to reference `version_id` instead of `category_version_id`. 

The reason is that in ´\Shopware\Core\Framework\DataAbstractionLayer\Dbal\FieldResolver\ManyToOneAssociationFieldResolver::buildWhere` the `version_id` is hardcoded.

**Possible Solution**  
Use the reference version storage name instead of the hardcoded field name. Probably not the only such instance.

**Comment by AndreasA** [comment]
I have now retrieved that data by using terms aggregation in combination with filter aggregation from the product repository as I only need the combinations for one product ID, it wasn't even that complicated, but there is no reason to not being able to execute the search directly from the product category repository to find its ids..

**Comment by JoshuaBehrens** [comment]
Is it related to https://github.com/shopware/platform/pull/1101 ?

**Comment by AndreasA** [comment]
@JoshuaBehrens Probably. However, that ticket was closed as fixed but I don't think it was fully fixed. I think in this case the issue is that the table has two prefixed version columns. The product_version_id is prefixed correctly from what I can tell. I did a bit of debugging and I don't know anymore where it was exactly but in one class there is an array that is filtered/limited to the first elmenet regarding vesion columns. maybe related to that but not 100% sure.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
