### ISSUE TITLE
@6.x Storefront Controller redirectToRoute()/createActionResponse() pathing from plugins are broken since start.

### ISSUE THREAD

**Issue by moorl** [shopware/platform#1841]
**Description**  
Since Start of Shopware 6 the Routing from Plugins never work.
1. I cant use path() in my TWIG templates, i will always get the path of the default SalesChannel and not the active from the Storefront -> The Controller don't know the right SalesChannelContext and respond with wrong languages etc.
2. If I call my Plugins Storefront Controller and the Shop is in a Subdirectory, the redirectToRoute() path is always broken. Problem is known from the start too but never fixed:

Controller Path: `mydomain.com/my-plugin-test/public/moorl-accessory-finder/set-filter`
Redirect Path with redirectToRoute(): `mydomain.com/seo-url`
What I expect to get with redirectToRoute(): `mydomain.com/my-plugin-test/public/seo-url`

This problem is really discusting since my plugins do not pass the Shopware Quality Guidelines to release them in the store.

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/3df3fe758e992525db188caa565c071589a57868
