### ISSUE TITLE
Change Timezone in Backend

### ISSUE THREAD

**Issue by moorl** [shopware/platform#1842]
**Description**  
We have no option to configure the shop owners timezone. If I work with ordertimes or desired delivery/self collect times I need the correct timezone. Actually we just have the UTC timezone - local times are clientside - not serverside. This is not hard to implement in Shopware core. I would like to have this option, so I don't need to add this configuration to my plugins. ;)

**Comment by shyim** [comment]
Same as https://github.com/shopware/platform/issues/2038
