### ISSUE TITLE
MailSender failed recipients always empty

### ISSUE THREAD

**Issue by bpeschlaudert** [shopware/platform#1851]
**Description**  
Failed recipients are always empty.

**Possible Solution**  
Get failed recipients from exception or envelope

**Additional context**  
https://github.com/shopware/platform/blob/trunk/src/Core/Content/Mail/Service/MailSender.php#L40

**Comment by mynameisbogdan** [comment]
Since it uses `symfony/mailer` under the hood, it's no longer possible to check for status of the email due to `Symfony\Component\Mailer::send()` returning `void`. It also supports using an async messenger transport so wouldn't be possible anyways.
