### ISSUE TITLE
BeforeLineItemAddedEvent/AfterLineItemAddedEvent - not dispatched when expected (before executed after add e.g.)?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1852]
**Description**  
The events AfterLineItemAddedEvent and BeforeLineItemAddedEvent are executed at positions that I would not expect from the event name. First both are singular but the after is used after all items are saved and not for just one. And the other says before but is executed after `add`, so it is not before. Sure it is before the cart is saved but it is still after it was added to the cart.

Current code is:

```php
  foreach ($items as $item) {
            $alreadyExists = $cart->has($item->getId());
            $cart->add($item);

            $this->eventDispatcher->dispatch(new BeforeLineItemAddedEvent($item, $cart, $context, $alreadyExists));
        }

        $cart->markModified();

        $cart = $this->cartCalculator->calculate($cart, $context);
        $this->cartPersister->save($cart, $context);

        $this->eventDispatcher->dispatch(new AfterLineItemAddedEvent($items, $cart, $context));
        $this->eventDispatcher->dispatch(new CartChangedEvent($cart, $context));

        return new CartResponse($cart);
```

I would expect it to be more like this:

```php
  foreach ($items as $item) {
            $alreadyExists = $cart->has($item->getId());
            $this->eventDispatcher->dispatch(new BeforeLineItemAddedEvent($item, $cart, $context, $alreadyExists));

            $cart->add($item);

            $this->eventDispatcher->dispatch(new AfterLineItemAddedEvent($item, $cart, $context, $alreadyExists));
        }

        // New event
        $this->eventDispatcher->dispatch(new AfterLineItemsAddedEvent($items, $cart, $context));

        $cart->markModified();

        $cart = $this->cartCalculator->calculate($cart, $context);
        $this->cartPersister->save($cart, $context);

        // new event
        $this->eventDispatcher->dispatch(new AfterLineItemsAddedAndSavedEvent($items, $cart, $context));
        $this->eventDispatcher->dispatch(new CartChangedEvent($cart, $context));

        return new CartResponse($cart);
```

In this case I would also add some more events to catch everything but that is not strictly necessary. As it is a breaking change it would either require a feature flag or new events.

**Possible Solution**  
See code sample above.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
