### ISSUE TITLE
Use-case Shopware 6 PSP plugins

### ISSUE THREAD

**Issue by CrystalG23** [shopware/platform#1856]
I want to use these Shopware 6 plugins in my project:

    PayPal https://docs.shopware.com/en/shopware-6-en/extensions/paypal
    Sofort Überweisung ( Klarna ) https://docs.shopware.com/de/shopware-6-de/erweiterungen/klarna
    amazon pay https://docs.shopware.com/de/shopware-6-de/erweiterungen/amazon-pay

I was searching in the documentation for an explanation: How to use the PSP Plugins from Shopware 6 in Shopware PWA.
https://shopware-pwa-docs.vuestorefront.io/landing/concepts/payment.html#process

I would like an Answer, if the compatibility is okay.

**Comment by elkmod** [comment]
Hi @CrystalG23, please reopen if this is still relevant? For future requests about compatibilities / extensions, please head to our Slack Channel shopwarecommunity.slack.com.
