### ISSUE TITLE
[v6.4.0.0] Mails are not being sent anymore

### ISSUE THREAD

**Issue by xLarry** [shopware/platform#1860]
I just updated Shopware to 6.4.0.0 which worked without any issues. The only thing is, that emails (e.g. order confirmations or delivery notes) are not being sent anymore.

The only details I could find so far was the following within `var/log/dev.log`:

`
[2021-05-13T01:31:17.412631+00:00] app.ERROR: Could not send mail: Failed sending mail to following recipients: {{ recipients }} Error Code:0 Template data:  {"recipients":{"...@gmail.com":"..."},"senderName":"...","salesChannelId":"98432def39fc4624b33213a56b8c944d","templateId":"d94e1656434a4cdf85101286f8989d19","customFields":null,"contentHtml":"...","subject":"Bestellbest\u00e4tigung","mediaIds":[]}
`

It might have something to do with the migration to [Symfony Mailer](https://github.com/shopware/platform/blob/v6.4.0.0/UPGRADE-6.4.md#swift_mailer-exchanged-with-symfonymailer) but that's just a shot in the dark.

Any ideas who to further narrow down what's causing the problem?

**Comment by shyim** [comment]
Which method of configuration do you use for Symfony mailer?

**Comment by xLarry** [comment]
I configured an external SMTP server which worked well before upgrading to v.6.4.0.0

As it just turned out the issue was caused by several reasons:

1. I had a **custom document template** for the invoice layout which broke because the [base template](https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Resources/views/documents/base.html.twig) changed. While attaching them to the mail, the rendering threw an error (which could only be seen when downloading the invoices manually) and the sending failed. Unfortunately the rendering error occured only in a few situations which made it hard to reproduce the error.
2. Once the above issue was resolved the event log reported a successful `mail.sent` event (without throwing the above given error message) but the actual sending still didn't happen. After a while I realized that I haven't had a **message consumer** job running (as described [here](https://developer.shopware.com/docs/guides/hosting/infrastructure/message-queue)), which seems to be required for the new Symfony mailer.
3. [_UPDATED_] last but not least I had to **remove all emojis from my mail template**, which seems to cause that error as well

After all the issue was caused by erroneous document customization and incomplete system configuration. However, it would be great if

1. errors thrown by rendering the attachments could be caught and logged separately, to make it easier to track them
2. the requirement of a message consumer job could be added to the [upgrade notes](https://github.com/shopware/platform/blob/trunk/UPGRADE-6.4.md#swift_mailer-exchanged-with-symfonymailer)

**Comment by miko007** [comment]
we got a similar problem but on `v6.3.4.3` already, where variable names in the respective templates had changed. if the variable names are wrong, no emails get sent.

**Comment by xLarry** [comment]
@miko007 afaik in `v.6.3.x.x` an error message related to the rendering of the template has been logged to `var/log/dev.log`, hasn't it? This doesn't seem to be the case in `v6.4.0.0`.

@shyim I just realized that this error also occurs when I'm using an emoji in the email template. Can you confirm this?

**Comment by xLarry** [comment]
For the records: scanning through the [changelog of v6.4.1.0](https://github.com/shopware/platform/blob/trunk/CHANGELOG.md#6410) it seems like (2) described in my comment above (_mails not being sent if a message consumer job has not been configured_) has most likely been resolved by executing the job synchronously (see [NEXT-15368](https://issues.shopware.com/issues/NEXT-15368))

**Comment by shyim** [comment]
This should be working again with 6.4.1.0
