### ISSUE TITLE
Performance of SystemConfigService::get

### ISSUE THREAD

**Issue by beberlei** [shopware/platform#1862]
We are seeing calls to `SystemConfigService::get` in the areas of 10-50ms in a few of our customers shops with file caches using Tideways Profiler. This is due to the fact that the `TagAwareCache` adds quite a lot of overhead and many tags, even though the system_config table is really small and loading it into memory using a single SQL statement or storing it into a single cache file as one big array would also work.

![Screenshot_2021-05-14 demos-tideways Shopware6 – Tideways](https://user-images.githubusercontent.com/26936/118309407-84037500-b4ed-11eb-84a4-3f0d2c91f2ce.png)

Is there a reason tags are necessary for the system cache? Otherwise I would think we could create a specialized cache adapter just for the system config cache, as this could reduce performance for both uncached responses and cached responses (that currently always fetch at least the `core.seo.redirectToCanonicalUrl` key).

**Comment by shyim** [comment]
Hey,

Did you tested it also against the 6.4.0.0 release? We refactored the entire caching in the Storefront

**Comment by beberlei** [comment]
@shyim I have not, i was trying to get a baseline for 6.3 before upgrading to 6.4 and comparing. That is great news! Do you know from the top of your head which ticket that was? I didn't find this in the changelog here: https://www.shopware.com/en/changelog/

**Comment by OliverSkroblin** [comment]
Hi Benjamin, the whole cache and performance optimization has been done under [this ticket](https://issues.shopware.com/issues/NEXT-6580).

The optimizations that affect this area are the following:

* https://github.com/shopware/platform/blob/trunk/src/Core/System/SystemConfig/CachedSystemConfigLoader.php#L31
* https://github.com/shopware/platform/blob/trunk/src/Core/System/SystemConfig/SystemConfigService.php#L95
* https://github.com/shopware/platform/blob/trunk/src/Core/System/SystemConfig/SystemConfigService.php#L356

**Comment by shyim** [comment]
Closing this as its old and was 6.3
