### ISSUE TITLE
Create customer account - Should be optional instead of default and no privacy policy checkbox (guest and customer account) - on checkout regarding law?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1868]
**Description**  
During checkout the create custom account is the default option. However, as fas as I know European law demands that it is the other way around that creating a customer account should be the optional version (no disable but enable).

Furthermore, I should need to accept the privacy policy / T&Cs before the acocunt is created.

**Comment by AndreasA** [comment]
Also the privacy policy also needs to be accepted for guest accounts as data of the user is still stored.

**Comment by AndreasA** [comment]
I think one can now be enabled in the admin interface?

**Comment by nikkoch** [comment]
This issue is still in Shopware 6.14.8.1
Not depending on backend settings (Create customer account by default) this option is present unchecked in the cart: 'Kein Kundenkonto anlegen.'

Does someone know a fix?

**Comment by AndreasA** [comment]
@nikkoch You can enable the FEATURE_NEXT_16236 flag. That should enable the corresponding necessary change:

In your `.env` or `.env.local`etc. file:

```dotenv
FEATURE_NEXT_16236=true
```

That should enable the configuration option `Create customer account by default` which should be disabled (if it isn't already) to get the intended behavior.

**Comment by AndreasA** [comment]
@shyim I think with 6.5 this is actually the default behavior and before it can be enabled with a corresponding feature flag, so I guess I can close this issue or should I keep it open until 6.5 release?

**Comment by shyim** [comment]
Let's close it directly when it's fixed there :)

**Comment by amenk** [comment]
The confusing part is, that the config checkbox seems to be there in 6.4 versions, even the feature is not really working. So setting the feature flag should fix it.

Means, the "feature flag" is IMHO more a "bug fix flag" in this case - but I guess this method was chosen to not change such a crucial behavior before 6.5.

Fine with me, just wanted to clear this out :-)
