### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by nothingismagick** [shopware/platform#187]
In the README you refer to a non-existent license file.

https://github.com/shopware/platform/blob/master/LICENSE

Remediation: 
- put a license header in every file (preferred by FSF)
- place the LICENSE file in the repository with proper copyright notification (easier)

**Comment by nothingismagick** [comment]
Just saw that the license is available, albeit at a different link:
https://github.com/shopware/platform/blob/master/license.txt

**Comment by mitelg** [comment]
hey @nothingismagick 
I was just preparing a PR for that, when you open a PR by yourself. I will take care of it :+1:
