### ISSUE TITLE
[db install] error on clear installation

### ISSUE THREAD

**Issue by TOWUK** [shopware/platform#1871]
**Description**  
on clear maria db installation shopware error

```
Error
Received an error message.
URL: importDatabase
Message:

Please try to fix this error and restart the update.
Response
{"valid":false,"errorMsg":"An exception occurred while executing 'ALTER TABLE `order` MODIFY COLUMN `language_id` BINARY(16) NOT NULL':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column '`admin_sw`.`o`.`price`' in 'CHECK'"}
```

**Possible Solution**  
idk

**Additional context**  
youtube: https://youtu.be/TfEuH607gZw

**Comment by mactetz** [comment]
I got the same error yesterday.
Last week the installation was fine on my testsystem.
same system debian 10, mariadb 10.5, nginx, and php8.0.

I am going to check the correct versions of the software to compare.

**Comment by mitelg** [comment]
do you use a bugged version of MariaDB?

see https://jira.mariadb.org/browse/MDEV-25672

**Comment by mactetz** [comment]
It seems to be exactly the issue, I use mariadb 10.5.10.

I am new to shopware,
do you know where I can add the  FLUSH TABLES to avoid the issue?

**Comment by mitelg** [comment]
you can find our workarounds here: https://github.com/shopware/platform/search?q=NEXT-15275&type=commits

**Comment by shyim** [comment]
Upgrade mariadb to latest version
