### ISSUE TITLE
@6.4 search api endpoint not found

### ISSUE THREAD

**Issue by kugelbit** [shopware/platform#1875]
**Description**  
I cant use the search endpoint in the Version 6.4.0.0.
if i try to use the search endpoint i get 404.
Im trying to use the order search with an filter. To do so i send an POST-Request to the "/api/search/order" endpoint. In the response a get an 404 an the message: 

`{"errors":[{"code":"0","status":"404","title":"Not Found","detail":"No route found for \u0022POST \/api\/v3\/search\/order\u0022"}]}`

The Request works perfectly fine with the Version: 6.3.5.2.

So what do i missing?

**Additional context**  
Here is an curl example of my request:

`curl -k --silent -H "Content-Type: application/json" -H "Authorization: Bearer 1234345" --request POST --data '{"limit":500,"filter":[{"type": "equals","field": "order.stateMachineState.technicalName", "value": "open" }]}' https://myShop.de/api/v3/search/order `

**Comment by mitelg** [comment]
https://github.com/shopware/platform/blob/trunk/UPGRADE-6.4.md#api-versioning-change

**Comment by kugelbit** [comment]
Thanks for your help.
