### ISSUE TITLE
Image-Zoom-Plugin will break when starting to drag the zoomed-in area

### ISSUE THREAD

**Issue by mruettgers** [shopware/platform#1881]
**Description**  
While trying to move the zoomed-in area by dragging I get the following error:
` Uncaught TypeError: this._storedTransform.set is not a function` 

![shopware_image_zoom_plugin_issue](https://user-images.githubusercontent.com/1706429/119239863-4b4a4800-bb4c-11eb-8ee2-ad286ca56ea5.png)

The issue seems to be caused by a missing `set` method in the class Vector3:https://github.com/shopware/platform/blob/4947407f8c27f5175d306b537f48eb284e1d87e7/src/Storefront/Resources/app/storefront/src/helper/vector.helper.js#L231-L253

The method is being called here: https://github.com/shopware/platform/blob/4947407f8c27f5175d306b537f48eb284e1d87e7/src/Storefront/Resources/app/storefront/src/plugin/image-zoom/image-zoom.plugin.js#L427

**Possible Solutions**  
* a) Implement `set` method in ` Vector3`:
``` 
class Vector3 extends Vector {
 
    set(vector) {
        return new this.constructor(vector);
    }

}
``` 

* b) Get rid of `.set()`-Call in ` image-zoom-plugin.js`

**Comment by alessandroaussems** [comment]
Seems to be fixed by: https://github.com/shopware/platform/commit/004b1908ff8038f731a12988664937b584210059
SW issue: https://issues.shopware.com/issues/NEXT-15730
