### ISSUE TITLE
@6.4 HttpCacheGenerateKeyEvent hash became suddenly useless

### ISSUE THREAD

**Issue by moorl** [shopware/platform#1882]
**Description**  
Between 6.4 EA and 6.4.0 Something has changed in the CacheStore.php. Since then I am not able anymore to get cached http files by the hash from the HttpCacheGenerateKeyEvent

https://github.com/shopware/platform/commit/c4294bbd12a4ce08d7a83e7a8fcf0bbe0e3423b1#diff-6caed8bb0ab711d9d54e78907bf0506d46aaaffdb9cb0d0a508b2bc629713d7a

**Additional context**  
SHOPWARE_HTTP_CACHE_ENABLED=1/0 Has absolutly NO EFFECT
APP_ENV=prod/dev (prod = CACHE ENABLED, dev =CACHE NOT ENABLED)

**Comment by moorl** [comment]
INFO: This behavior does not apply to the templates. 

BUT FOR CMS ELEMENT RESOLVER

public function collect() - NOT EXECUTED
public function enrich() - NOT EXECUTED

Just executed one time until cache cleared.

HttpCacheGenerateKeyEvent has NOT EFFECT
CHANGING URL (+ ?someVar=someValue) HAS EFFECT - collect() and enrich() EXECUTED AGAIN

Hope this helps ;)

**Comment by moorl** [comment]
For now I have found the solution by using the CategoryRouteCacheKeyEvent. I think it works for me ;)

**Comment by moorl** [comment]
One think is annoying: I need to subscribe HttpCacheGenerateKeyEvent for the templates and CategoryRouteCacheKeyEvent for the data. At least it would be helpful when the session is started before HttpCacheGenerateKeyEvent, so I don't need to initialize it on myself.

```php
    public function onHttpCacheGenerateKey(HttpCacheGenerateKeyEvent $event): void
    {
        if (strpos($event->getRequest()->getPathInfo(), 'navigation') === false) {
            return;
        }

        if (!$this->systemConfigService->get('MoorlAccessoryFinder.config.cacheFix')) {
            return;
        }

        if (!$this->session->isStarted()) {
            $this->session->setName('session-');
            $this->session->start();
            $this->session->set('sessionId', $this->session->getId());
        }

        if (!$this->session->get('moorl-accessory-finder_selected')) {
            return;
        }

        $hash = $event->getHash();
        $hash = hash('sha256', $hash . '-' . serialize($this->session->get('moorl-accessory-finder_selected')));
        $event->setHash($hash);
    }
```

Additional i need this if I use CMS Elements:

```php
    public function onCategoryRouteCacheKeyEvent(CategoryRouteCacheKeyEvent $event): void
    {
        $data = $this->session->get('moorl-accessory-finder_selected');

        if (!$data || !is_array($data)) {
            return;
        }

        foreach ($data as $key) {
            $event->addPart($key);
        }
    }
```

**Comment by shyim** [comment]
It's pretty bad behaviour initializing session when not actually needed. It makes the Request slower and blocks other requests. We will never do that :)

**Comment by DevertNet** [comment]
The new cache behavior also stole a few hours from me :D
My problem was 2 of the new cached* classes and the normal HTTP cache.
I understand the background of the new caches, but it was no fun to figure it out.

**Comment by moorl** [comment]
@shyim okay i thought a session will be initialized anyway. Especially on storefront controller requests. It was just a nice2have to remove this from my snippet

```php
        if (!$this->session->isStarted()) {
            $this->session->setName('session-');
            $this->session->start();
            $this->session->set('sessionId', $this->session->getId());
        }
```
