### ISSUE TITLE
Product configuration loader breaks when product has no options

### ISSUE THREAD

**Issue by janmartenjongerius** [shopware/platform#1883]
**Description**  

When a product has no options configured, but is activated, its corresponding product detail page breaks.

**Possible Solution**  

When short circuiting the result of `$product->getOptionIds()` using null coalescence, `$product->getOptionIds() ?? []`, the product detail page loads once more.

**Additional context**  

![image](https://user-images.githubusercontent.com/642417/119475045-0ccfab80-bd4d-11eb-8efe-9727767b9f11.png)

![image](https://user-images.githubusercontent.com/642417/119475366-620bbd00-bd4d-11eb-99ca-ffadcbd19bb3.png)

See: https://issues.shopware.com/issues/NEXT-15468

**Comment by shyim** [comment]
See PR as answer
