### ISSUE TITLE
Bug : Blank Product Title at LineItems section in Orders 

### ISSUE THREAD

**Issue by ali-ghalambaz** [shopware/platform#1889]
**Description**  
shopware/core": "6.3.5.*"
I'm trying to create an order with orderRepository, everything is fine with creation but 'LineItems' in order section in admin panel  has no title when type is equal to `LineItem::PRODUCT_LINE_ITEM_TYPE`
```php 
$orderArray = [
            'id' => $orderId,
            'orderDateTime' => $currentDate,
            'stateId' => $openStateId,
            'orderNumber' => 'XYZ-123',
            'languageId' => $languageId,
            'price' => $price,
            'shippingCosts' => $shippingCost,
            'orderCustomer' => [
                ...
            ],
            'paymentMethodId' => $paymentMethodId,
            'currencyId' => $currencyId,
            'currencyFactor' => 1.0,
            'salesChannelId' => $salesChannelId,
            'billingAddressId' => $billingAddressId,
            'addresses' => [
                [
                   ...
                ],
            ],
            'transactions' => [
                ...
            ],
            'lineItems' => [
                [
                    'id' => $lineItemId,
                    'orderId' => $orderId,
                    'identifier' => $productId,
                    'referencedId' => $productId,
                    'productId' => $productId,
                    'quantity' => 10,
                    'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                    'label' => $product->getTranslation(self::KEY_SHOPWARE_TITLE),
                    'price' => $lineItemPrice,
                    'removable' => true,
                ],
            ],
            'deliveries' => [
                ...
            ],
            'tags' => [
               ...
            ],
            'context' => '{}',
            'payload' => '{}',
            'customFields' => [
                ...
            ],
        ];
```

**Possible Solution**  

**Additional context**  
if changing `LineItem::PRODUCT_LINE_ITEM_TYPE` to `LineItem::CUSTOM_LINE_ITEM_TYPE`, the product title is showing but the link to the product will disappear (it's so important to have a link between line items and products)

**Comment by ali-ghalambaz** [comment]
screenshot of created order [
![Screenshot 2021-06-02 at 08 34 07](https://user-images.githubusercontent.com/84901707/120434939-5cc9f600-c37d-11eb-9c7d-7027657a04cf.png)
](url)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
