### ISSUE TITLE
Boolean custom field value converted to float on indexing

### ISSUE THREAD

**Issue by rjwebdev** [shopware/platform#1890]
**Description**  

In our Shopware setup, we have a custom field configured with type `bool`. This custom field will be used in products.

When a product is being indexed that contains a custom field of type bool, this bool value will be converted to a float because of this piece of code:
```php
private function formatCustomFields(array $customFields): array
{
    foreach ($customFields as $name => $customField) {
        if (\is_int($customField)) {
            $customFields[$name] = (float) $customField;
        }
    }
    
    return $customFields;
}
```
in `\Shopware\Elasticsearch\Product\ElasticsearchProductDefinition`

**Possible Solution**  

When looping true the custom field values, check the type of the custom field for each value to make sure a correct conversion is done for the value.

**Additional context**  

Value of custom fields on a product:
```json
{
    "fsc": 1,
    "media_packshot_6": null,
    "media_packshot_7": null,
    "media_packshot_8": null
}
```

When this product is being indexed, following error occurs:
`[app] failed to parse field [customFields.fsc] of type [boolean] in document with id '57a1f0ec0373491b9178ced49bdb5c41'. Preview of field's value: '1.0'`

**Comment by rjwebdev** [comment]
Noticed that this also happens when pushing products to Shopware using the sync api.

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/069dda4ba3447734ca6cb5f98338805bf1a5dffa
