### ISSUE TITLE
Product export scheduler is not working 

### ISSUE THREAD

**Issue by joberthel** [shopware/platform#1900]
**Description**  

The product export scheduler is not working if no product export is found for the first sales channel in the scheduled task handler. It just stops.

**Possible Solution**  

This line has to be changed from "return" to "continue":

https://github.com/shopware/core/blob/791f38c693db4b11d9d2ce46e86cb7dc5dc1c35f/Content/ProductExport/ScheduledTask/ProductExportGenerateTaskHandler.php#L94

**Comment by mitelg** [comment]
there was already an unfinished PR for that https://github.com/shopware/platform/pull/1530

maybe you would like to take another try? :blush:

**Comment by shyim** [comment]
Is fixed meanwhile
