### ISSUE TITLE
Creation of Custom Fields and Custom Field Sets fails

### ISSUE THREAD

**Issue by vardumper** [shopware/platform#1901]
**Description**  
When creating a new custom field set on 6.4 stable I see the following behaviour:
1) Add new custom field set. Name it. Set type to products. Save. OK
2) When trying to add a new custom field now, the new field is not added to the list of files. 
3) Re-creating the field results in an error: "Der technische Name existiert bereits."

**Possible Solution**  
This might be JSON and Escaping related.

**Additional context**  
SW6.4, PHP8, MySQL8, Nginx, Redis

The console shows a 500 error:

```
{
    "errors": [
        {
            "code": "0",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "An exception occurred while executing 'SELECT `custom_field`.`id` as `custom_field.id`, `custom_field`.`name` as `custom_field.name`, `custom_field`.`type` as `custom_field.type`, `custom_field`.`config` as `custom_field.config`, `custom_field`.`active` as `custom_field.active`, `custom_field`.`set_id` as `custom_field.customFieldSetId`, `custom_field`.`created_at` as `custom_field.createdAt`, `custom_field`.`updated_at` as `custom_field.updatedAt` FROM `custom_field` WHERE (`custom_field`.`set_id` IN (?)) ORDER BY LENGTH(IF(JSON_TYPE(JSON_EXTRACT(`custom_field`.`config`, '$.customFieldPosition')) != \"NULL\", CONVERT(JSON_UNQUOTE(JSON_EXTRACT(`custom_field`.`config`, '$.customFieldPosition')) USING \"utf8mb4\") COLLATE utf8mb4_unicode_ci, NULL)) ASC, IF(JSON_TYPE(JSON_EXTRACT(`custom_field`.`config`, '$.customFieldPosition')) != \"NULL\", CONVERT(JSON_UNQUOTE(JSON_EXTRACT(`custom_field`.`config`, '$.customFieldPosition')) USING \"utf8mb4\") COLLATE utf8mb4_unicode_ci, NULL) ASC' with params [\"\\x46\\xed\\xec\\x89\\x18\\x3e\\x45\\x54\\x8c\\x8d\\x96\\xf8\\x06\\xfb\\xf4\\x95\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'NULL' in 'order clause'"
        }
    ]
}
```

If I replace the two occurrences of `!= \"NULL\"` with `!= NULL` I get an empty result set.

**Comment by shyim** [comment]
Still relevant that issue?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
