### ISSUE TITLE
Bug in swag/swag-extension-store & middleware.helper.js

### ISSUE THREAD

**Issue by plivinskiy** [shopware/platform#1905]
**Description**  

In your Extension **SwagExtensionStore** in the JS File: **_custom/plugins/SwagExtensionStore/src/Resources/app/administration/src/module/sw-extension-store/index.js_** in function **routeMiddleware**(Line 102-103) is  the call of **next(currentRoute)** missing. 
It's kills the call chain and other plugins, that use the function [routeMiddleware](https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/core/helper/middleware.helper.js) to add routes, can't add it.

**Possible Solution**  

Just add **next(currentRoute)** to end of the function **routeMiddleware** in file custom/plugins/SwagExtensionStore/src/Resources/app/administration/src/module/sw-extension-store/index.js  in the Extension **SwagExtensionStore**

**Comment by mitelg** [comment]
hey,
this was already fixed with https://issues.shopware.com/issues/NEXT-15508
An update will be provided soon
