### ISSUE TITLE
Decorating the ProductPriceCalculator leads to error

### ISSUE THREAD

**Issue by darinda** [shopware/platform#1907]
**Description**  
In Shopware 6.4.1, when decorating the [`ProductPriceCalculator`](https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/SalesChannel/Price/ProductPriceCalculator.php) as described [in the official documentation](https://developer.shopware.com/docs/guides/plugins/plugins/checkout/cart/customize-price-calculation#decorating-the-calculator) a fatal error is thrown.

This is caused by `ProductCartProcessor` [__construct method](https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/Cart/ProductCartProcessor.php#L62) expecting a service that is of type `ProductPriceCalculator` 

**Possible Solution**  
Change the type of the `$priceCalculator` argument of the [`ProductCartProcessor`](https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/Cart/ProductCartProcessor.php) to be [`AbstractProductPriceCalculator`](https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/SalesChannel/Price/AbstractProductPriceCalculator.php) instead of [`ProductPriceCalculator`](https://github.com/shopware/platform/blob/trunk/src/Core/Content/Product/SalesChannel/Price/ProductPriceCalculator.php).

**Additional context**  
Currently this can bug can be worked around by letting the decorating PriceCalculator extend the original one, but this is clearly not intended as it is shown otherwise in the official docs

**Comment by mitelg** [comment]
sounds like an easy pick for a PR :blush:
