### ISSUE TITLE
Hot reload watch task and app-css-relative-asset-path - howto ensure it works correctly for fonts in my theme and storefront fonts?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1910]
**Description**  
In  https://github.com/shopware/platform/commit/563d32597f23cca0869f157566d29675dcfcf405#diff-ca7a404fa7e9c58756c9ec8bdfea69ca6cd32a3126be716ef4a3c10b40962f7eL360 this variable was overridden with a storefront specific value.
This is fine for the storefront fonts but if I add a custom font to my theme this will fail, also not sure how to override this path for my fonts/assets and keep the storefront assets/fonts working. 

Do I need to create a separate variable that extends tthe original app-css-relative-asset-path  for my theme or is there a better solution?

issue tracker issue: https://issues.shopware.com/issues/NEXT-15846

**Comment by AndreasA** [comment]
I have found a solution for this but it is kind of an unnecessary workaround and unnecssarily complicated to use.

I added the following files to my theme:

- `src/Resources/app/storefront/env/hot/scss/_variables.scss`:

```scss
$my-theme-asset-path: '/bundles/mytheme/assets';
```

- `src/Resources/app/storefront/env/default/scss/_variables.scss`:

```scss
$my-theme-asset-path: $app-css-relative-asset-path;
```

- `src/Resources/app/storefront/build/webpack.config.js`:

```js

const { join, resolve } = require('path');

const isHotMode = process.env.MODE === 'hot';

module.exports = () => {
    return {
        resolve: {
            alias: {
                'my-theme-env': resolve(
                    join(__dirname, '..', 'env', isHotMode ? 'hot' : 'default')
                ),
            },
        },
    };
};
```

Then adjusted the files:
- `src/Resources/theme.json`: 
    - replaced `app/storefront/src/scss/base.scss` with
    ```json
       "app/storefront/src/scss/base.scss": {
        "resolve": {
          "my-theme-env": "app/storefront/env/default"
        }
      }
    ```
- `src/Resources/app/storefront/src/scss/base.scss`:
    - Add at the following at the beginning of the file:
    ````scss
    @import '~my-theme-env/scss/variables';
    ````


This way the variable `$my-theme-asset-path` can be used to get to the correct asset path for the hotproxy and production builds.

However, it is unnecessary complicated. Futhermore, it is necessary to create an additional (unnecessary) variable `$my-theme-asset-path` to be able to have a different path for this variable than the one provided by `$app-css-relative-asset-path`.

An easy fix would be to allow custom variable overrides in hot proxy mode but even that way a custom variable is necessary. 

The best solution would be to ensure the theme asset path stays the same between production and proxy mode but that is probably more complicated to implement.

It works because during `theme:compile` (config from `theme.json`) the module alias `my-theme-env` points to a different path than with hotproxy active in the `webpack.config.js`. file.

**Comment by jhit** [comment]
@AndreasA I have issues repeating your workaround in a current setup. 
I get the  error:
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                        1:35:32 PM

 error  in /app/var/theme-entry.scss

Module build failed (from ../node_modules/sass-loader/lib/loader.js):

@import '~my-theme-env/scss/variables';
       ^
      Can't find stylesheet to import.
  ╷
1 │ @import '~my-theme-env/scss/variables';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /app/custom/plugins/MyTheme/src/Resources/app/storefront/src/scss/base.scss 1:9  @import
  stdin 14:9                                                                               root stylesheet
      in /app/custom/plugins/MyTheme/src/Resources/app/storefront/src/scss/base.scss (line 1, column 9)

 @ /app/var/theme-entry.scss 2:14-356 21:1-42:3 22:19-361
```
Any Idea why the resolving of ~my-theme-env does not work?

**Comment by AndreasA** [comment]
@jhit You added `src/Resources/app/storefront/build/webpack.config.js` and `src/Resources/theme.json` to your theme, didn't you?

You already ran `bin/console cache:clear`, `bin/console plugin:update ...`, `bin/console theme:refresh` , `bin/console theme:dump` and `./bin/build-storefront.js` once after adding the above changes, just to be safe? Because it might be necessary to correctly compile everything once.

If possible maybe post a repository with the corresponding theme as source code? However, I haven't tested this for a while so it might not work with the latest version, though I don't think the theme compilation behavior changed regarding this.

**Comment by AndreasA** [comment]
@jhit In which file do you try to reference the variables because for theme:compile the alias has to be defined per referenced file in the `theme.json`. See https://github.com/shopware/platform/blob/v6.4.14.0/src/Storefront/Resources/theme.json#L11

I am basically combining: https://developer.shopware.com/docs/guides/plugins/plugins/plugin-fundamentals/using-npm-dependencies#registering-a-package-in-the-build-system and https://github.com/shopware/platform/blob/v6.4.14.0/src/Storefront/Resources/theme.json#L11

**Comment by jhit** [comment]
@AndreasA Thanks for your help. After fiddling around half a day I wiped everything off the table and started from scratch. I think my missing piece was just not running the `bin/build-storefront.sh` script. That was really unlucky because it cost me so much time 
I have your workaround now running without issues.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
