### ISSUE TITLE
Sitemap generation fails with tmp/<name> failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Schrank** [shopware/platform#1915]
**Description**  
In `\Shopware\Core\Content\Sitemap\Service\SitemapHandle::finish` we iterate over the tmpFiles which are named by the domain name of the sales channel and delete them right after writing them to the final file.

The problem is, that if we have two domains for a sales channel like:

- http://example.com
- httpS://example.com

we delete on the first run the tmp file of the second domain.

**Possible Solution**  
Split deletion of files from writing them to final file. But it might be a problem that the content of the file is then doubled.

**Additional context**

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/997fe54f7a471632965914af02500b5d9d3fbd86
