### ISSUE TITLE
Bug : Blank Product Title at LineItems section in Orders 

### ISSUE THREAD

**Issue by ali-ghalambaz** [shopware/platform#1920]
**Description**  
I'm working on a new plugin that creates orders from some imported data. when trying to add new order with line items, order's line items will show in with blank titles 
more information: https://github.com/shopware/platform/issues/1889

**Possible Solution**  

**Additional context**  
![Screenshot 2021-06-02 at 08 34 07](https://user-images.githubusercontent.com/84901707/122020637-39fc0080-cdc5-11eb-9e53-762e1ba39017.png)

**Comment by shyim** [comment]
Closing as duplicate to #1889
