### ISSUE TITLE
{% parent %} in nested twig blocks

### ISSUE THREAD

**Issue by TimWuyts** [shopware/platform#1927]
**Description**  
Whenever you use the {% parent %} tag in administration related component overrides (Vue.js & Twig.js), it is causing duplicated content in nested twig blocks. In this way it's not possible to override certain/parent blocks containing other child blocks (from which the content should be inherited, not overridden).

**Possible Solution**  
The {% parent %} tag should always return the inherited contents of the wrapping {% block %} in rendered templates.

**Additional context**  
Eg: When overriding the "sw-product-list" component in "src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/sw-product-list.twig" in order to add additional properties to the "sw-entity-listing" component.

The "sw-entity-listing" tag from the "sw_product_lis_grid" block is repeated in the "sw_product_list_grid_columns" block.

```twig
{% block sw_product_list_grid %}
    <sw-entity-listing
        ref="swProductGrid"
        class="sw-product-list-grid"
        :items="products"
        :columns="productColumns"
        :repository="productRepository"
        detail-route="sw.product.detail"
        :show-selection="true"
        :is-loading="isLoading"
        identifier="sw-product-list"
        :allow-edit="acl.can('product.editor')"
        :allow-delete="acl.can('product.deleter')"
        :allow-inline-edit="acl.can('product.editor')"
        :sort-by="sortBy"
        :sort-direction="sortDirection"
        :natural-sorting="naturalSorting"
        :criteria-limit="limit"
        :disable-data-fetching="true"
        :allow-bulk-export="acl.can('product.viewer')"
        @column-sort="onColumnSort"
        @page-change="onPageChange"
        @inline-edit-save="onInlineEditSave"
        @selection-change="updateSelection"
        @update-records="updateTotal"
        @bulk-export="onBulkExport"
    >
        {% block sw_product_list_grid_columns %}
            {% parent %}
        {% endblock %}
    </sw-entity-listing>
{% endblock %}
```

**Comment by mynameisbogdan** [comment]
Isn't the correct syntax [`{{ parent() }}`](https://twig.symfony.com/doc/3.x/functions/parent.html)? 
I'm not familiar with twig.js but I assume it should be the same.

**Comment by TimWuyts** [comment]
No, this syntax is introduced as an additional statement tag that can be used in order to prevent conflicts with the Vue.js template bindings.

https://github.com/shopware/platform/blob/01d2da25be8d437bae0e6617c6e11b102c9ece6d/src/Administration/Resources/app/administration/src/core/factory/template.factory.js#L53

**Comment by mynameisbogdan** [comment]
Ah, it's a custom tag. TIL.

Thank you.

**Comment by chb567** [comment]
I noticed that nested components may also **disappear**. 

I tried custumizing the `sw-order-detail-base` view, to alter to the `sw-order-user-card` component's props, however the sw_order_detail_base_overview_status_change block will not show using `{% parent %}`.

```twig
{% block sw_order_detail_base__user_card %}
<sw-order-user-card
    :key="isEditing"
    :current-order="order"
    :version-context="versionContext"
    :is-loading="isLoading"
    :is-editing="isEditing"
    @order-change="saveAndReload"
    @order-reset="recalculateAndReload"
    @error="$emit('error',$event)"
>

  {% block  sw_order_detail_base_overview_status_change %}
      {% parent %}
  {% endblock %}

</sw-order-user-card>
{% endblock %}
```
src/Administration/Resources/app/administration/src/module/sw-order/view/sw-order-detail-base

**Comment by shyim** [comment]
Thats not possible in twig https://twigfiddle.com/j0hiow

**Comment by creinelt** [comment]
> Thats not possible in twig https://twigfiddle.com/j0hiow

And there isn't a way to make it possible ?
We have a lot of cases like that, and it makes template extension unnecessarily hard and annoying, it was better with smarty in Shopware 5. The Administration is changing a lot in the template factory, why not change that as well?

**Comment by dithom** [comment]
@creinelt We get stuck at this a lot as well. If the existing blocks are not structured enough, there seems to be no other way, than copying a lot of code, which is very bad practice in case of code updates from Shopware. However, as a best practice we now wrap our adjustments inside an if case. This way the adjusted and copied code is at least only used, when the "plugin case" is true and the default code can stay as is.

For example if you need to extend an if case like this:
```
{% block a_existing_block %}
  <template v-if="some.shopware.boolean">
    ...
  </template>

  Need another case here!

  <template v-else>
    ...
  </template>

  {% block another_existing_block %}
    ...
```

You can at least try:
```
{% block a_existing_block %}
  <template v-if="some.plugin.case">
    <template v-if="some.shopware.boolean">
      Copied code
      ...
    </template>

    Your plugin code...

    <template v-else>
      Copied code
      ...
    </template>

    {% block another_existing_block %}
      Copied code
      ...
  </template>

  <template v-else>
    {% parent %}
  </template>
```

Always open for and interested in better solutions. Hope it helps! :)
