### ISSUE TITLE
Services (maybe other things) should be loaded in the `Extension` not the plugin/bundle - Service build does not fail but should and setArgument / replaceArgument methods cannot be used correctly

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1930]
**Description**  
Services should NOT be loaded in the Plugin/Bundle but the extension.

It is important in order to support using setArgument and replaceArgument correctly in the extension, e.g. if one uses setArgument it will be triggered too late and it cannot be done in the plugin as extension config might be needed.

Furthermore, failed service config e.g. unused bindings do not trigger errors.

Services might not be the only things that should be loaded in the extension.

**Possible Solution**  
- Add a default extension
- override `getContainerExtensionClass` to provide the default extension, if NO custom extension is provided by the plugin/bundle.
- Add trait to load services
- Load services in default extension
- Adjust documentation regarding extending services needing the trait if used in a custom extension. Not extending from custom extension as Symfony has at least two possible extensions to inherit from.

Created also issue tracker issue: https://issues.shopware.com/issues/NEXT-15845

**Comment by shyim** [comment]
Never had any issues with $container->addCompilerPass

**Comment by AndreasA** [comment]
This is not a compiler pass ? It is this https://symfony.com/doc/current/bundles/configuration.html

but yes, replaceArgument might work. It is still wrong to register services in the bundle directly as you can see from the linked symfony doumentation.

And as mentioned errors are not triggered, e.g. an unused binding in the services definition.

Also addCompilerPass is correct to be used in the Plugin/Bundle file.

**Comment by shyim** [comment]
Hey,

As I understand the main reason for the extension is that you offer custom configuration. The basic plugin does not have that. 
You still have as a plugin the chance to do that and offer extension.  So I don't see any point to change there :thinking:

**Comment by AndreasA** [comment]
It is still not correct service wise. See Symfony documentation where it is always done in the extension class. It is probably also the reason why e.g. sometimes when debugging config results in a frozen parameter bag issue: https://github.com/shopware/platform/issues/1821

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
