### ISSUE TITLE
Storefront: Store API Proxy route does not forward language ID (uses wrong translations)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1931]
**Description**  
If the Store API proxy route is used in Storefront and e.g. the navigation route is requested and one uses a domain that is NOT the default language, then the content is still translated in the sales channel default language. 

Except if the language header is manually provided.

**Possible Solution**  

- Set the header `\Shopware\Core\PlatformRequest::HEADER_LANGUAGE_ID` in the subrequest to the current language ID, in case none is provided by the Store API. However, that that header attribute works is actually undocumented.
- Or: Set the language ID in the current sales channel context. As this language ID should only be used in the store API, it should work without issues. And this is documented to work.

Personally I think the header is the better solution and the Store API documentation should be adjusted that the header can be used to override the language from the current context.

see also issue tracker issue: https://issues.shopware.com/issues/NEXT-15839

**Comment by AndreasA** [comment]
Futhermore, WHY is the request stack cleared. using a subrequest is fine but why does the master request need to be changed.

**Comment by JoshuaBehrens** [comment]
AFAIK lots of context infos are taken from the master request at several different places within Shopware. I assume that is why it is reset.

**Comment by AndreasA** [comment]
@JoshuaBehrens Probably true but then the question is, if that is actually correct because most likely it isn't as it now requires a really hacky workaround.

**Comment by JoshuaBehrens** [comment]
Let's see what it needs.

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/platform/commit/9f9b0b102cac62c7c434fa09e9192ca230df5957#diff-9e0f6f17cff28d329d70cb2c3647f970db7cbb1f168da348a16d72f7b656e69d
