### ISSUE TITLE
Storefront: Store API proxy - Error responses contain wrong content or are returned as HTML

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1932]
**Description**  
The store API proxy does the following:

```php
       $subRequest->attributes->set(SalesChannelRequest::ATTRIBUTE_IS_SALES_CHANNEL_REQUEST, true);

        if ($request->hasSession()) {
            $subRequest->setSession($request->getSession());
        }
```

which results in Store API exception listener not being used by default but the Storefront one. Mostly it is the attribute `ATTRIBUTE_IS_SALES_CHANNEL_REQUEST`.

if one uses `Accept: application/json` then a JSON response is given but not the Store API response with `errors` array but the symfony default one which contains completely different data.

However, that attribute should not be necessary, the same for the session as the corresponding context token header is set which contains all necessary data for the store API, see these lines:

```php
        $subRequest->headers->set(PlatformRequest::HEADER_ACCESS_KEY, $context->getSalesChannel()->getAccessKey());
        $subRequest->headers->set(PlatformRequest::HEADER_CONTEXT_TOKEN, $context->getToken());
```

**Possible Solution**  
- Remove the code mentioned above.
- Optionally, ensure that store API proxy results in corresponding JSON responses for exceptions.

Personally, I think the best oslution is the first one to just remove the code as that way the Store API proxy responses/request behave exactly like normal store API responses / requests and not something that is a mixture of store api and storefront.

issue tracker issue: https://issues.shopware.com/issues/NEXT-15842

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/platform/commit/41fa97d39e2b1b45d0d39cf3af57b6a9906bdcf6#diff-9e0f6f17cff28d329d70cb2c3647f970db7cbb1f168da348a16d72f7b656e69d
