### ISSUE TITLE
Remove package strict limits or upgrade all packages to latest minor versions at least monthly

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1934]
**Description**  
A lot of your packages are still out of date. Even regarding their latest minor version. For most packages limiting them to specifc package versions should not be necessary as they follow semantic versioning.

However, I understand that you want to ensure to use working packages BUT if you do so, you need to at least provide an upgrade to the currnt minor versions for all active Shopware 6 versions to include possible security fixes, bugfixes etc.

e.g. 6.3.5.4 (not the latest 6.4) uses `lcobucci/jwt` in `3.3.1` which has a bug that makes it impossible to use with other libraries (e.g. apple sign in as it requires an update to 3.3.3 or 3.3.4 but it cannot be done).

Another example is `scssphp` which is way out of date, even in 6.4 you still force the use of `scssphp/scssphp` (**this version was released in December 2019!**) which even in the same minor version would allow an update to `1.0.9` but as it mostly follows semantic versioning you could probably even update to the latest `1.5.2` . 

**Possible Solution**  
- Do not use strict version requirements for most of your package.s
- Update your package versions regularly for all active Shopware versions - at least bi-monthly but probably monthly would be better.

added issue tracker issue: https://issues.shopware.com/issues/NEXT-15843

**Comment by shyim** [comment]
I will look internally at how we can integrate https://github.com/renovatebot/renovate

**Comment by AndreasA** [comment]
@shyim Great. Sounds like a good solution.

**Comment by mynameisbogdan** [comment]
@AndreasA regarding `scssphp/scssphp` is due for an update in #1906.

@shyim also I would recommend adding `npm upgrade --dry-run` into CI since currently the dependency-tree is broken.

![Screenshot 2021-06-23 at 14 33 14](https://user-images.githubusercontent.com/707714/123089722-fb52ef80-d42f-11eb-998e-e60b88bb6f25.jpg)

**Comment by AndreasA** [comment]
@mynameisbogdan regarding scssphp great but it isn't the only one. Just one that is extremely out of date and I know about but not all others are up-to-date so easily as well. Though not that extrem.

**Comment by mitelg** [comment]
closing, because there is already a ticket :blush:
