### ISSUE TITLE
Update to bootstrap 5 and remove jquery or make jquery optional

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1935]
**Description**  
Bootstrap 5 has been released and it does not require jquery anymore which is great as it is unnecessary nowadays, especially as one can use vue.js etc. instead.

Would be nice if Shopware 6 would upgrade to Bootstrap5 and make jquery optional to be included, e.g. by add `@jquery` to a theme's javascript files or just remove it altogether as one can add custom javascript modules anyway.

I know **IE11** is **NOT** supported anymore by bootstrap 5 but as Microsoft stops supporting the browser on their websites this year and removes it from Windows 10 next year this should be fine - maybe wait until the end of the year. 

However, this should therefore be done in a 6.5 or 6.6 or 6.7 upgrade only, dpeneding on when it is done.

issue tracker issue: https://issues.shopware.com/issues/NEXT-15841

**Comment by JoshuaBehrens** [comment]
There is lots of other things than updating bootstrap takes with it that you don't see upfront: https://getbootstrap.com/docs/5.0/migration/#sass e.g. they are taking print styles. That is something you don't see right away and this might break things. I think a new storefront that uses bootstrap 5 is the better way to go for.

**Comment by AndreasA** [comment]
@JoshuaBehrens might indeed be a better solution but not sure how much effort it would be to maintain both. or just wait a year or so and then adapt to it.

**Comment by JoshuaBehrens** [comment]
I think you need a migration period and have both at the same time will end up in two themes :/ Not want to stop anyone upgrading to the new bootstrap version. 👍

**Comment by mitelg** [comment]
We have already a ticket for that https://issues.shopware.com/issues/NEXT-15229
Unfortunately it was not public until now. I closed your ticket as duplicate and will also close this issue as the work will be done on the ticket :slightly_smiling_face: 

Thanks for bringing this topic up
