### ISSUE TITLE
bin/console system:install --drop-database --create-database fails on MariaDB 10.3.29

### ISSUE THREAD

**Issue by Schrank** [shopware/platform#1941]
**Description**  
I'm trying to drop and reinstall the database on my server running MariaDB 10.3.29

I know, that this version is marked as "with technical problems". If you don't want to change this, tell me, then I don't report MariaDB problem :-)

**Possible Solution**  

**Additional context**  
Prepare installation

Drop database `shopware`
Created database `shopware `
Importing base schema.sql

Get collection for identifier: "core"
migrate Migrations
 104/346 [========░░░░░░░░░░░░░░░░░░░░]  30%13:51:30 ERROR     [app] Migration: "Shopware\Core\Migration\Migration1563805586AddLanguageToOrder" failed: "An exception occurred while executing 'ALTER TABLE `order` MODIFY COLUMN `language_id` BINARY(16) NOT NULL':

SQLSTATE[42S22]: Column not found: 1054 Unknown column '`shopware `.`o`.`order_date_time`' in 'GENERATED ALWAYS'"

**Comment by shyim** [comment]
We can't do anything. It's fixed in the next patch version of mariadb: https://jira.mariadb.org/browse/MDEV-25672
Until then you have to use an older version

**Comment by Schrank** [comment]
@shyim Thanks! And sorry for wasting your time. Being more explicit, that it is a core bug in MariaDB and not a shopware problem would help here:

> MariaDB 10.3.29, 10.4.19, 10.5.10 are not compatible at the moment
https://developer.shopware.com/docs/guides/installation/overview#system-requirements

<3
