### ISSUE TITLE
Consistency for version checks

### ISSUE THREAD

**Issue by toonvd** [shopware/platform#1948]
### Please describe the feature you would like to see implemented.

In SW5, the command `bin/console --version`, provides the Shopware version.
In SW6 this command provides the Symfony version. This inconsistency makes it harder for a hosting provider to detect the version.

Is there any other consistent way or can this command be adapted?

**Comment by maximilianruesch** [comment]
I propose the `bin/console version` or the `bin/console version:check` command, as they will be fairly easy to implement from what i currently know of symfony.

If you approve of this solution, could you assign me to this issue? Thanks :)

**Comment by toonvd** [comment]
Adding an extra command would not fix the inconsistency unless it is backported to SW 5.

**Comment by osrecio** [comment]
This ticket should be closed due to this commit: https://github.com/shopware/platform/commit/9862251d8e4b61aad9574f1be190b15249a1bfb5

**Comment by keulinho** [comment]
@osrecio thanks for your heads up. I just checked again with the current trunk and `bin/console --version` now returns the correct shopware version.

**Comment by toonvd** [comment]
Agreed. Thanks for the heads-up!

**Comment by toonvd** [comment]
Thanks for the follow-up. Time to edit some Ansible :3.

**Comment by keulinho** [comment]
@toonvd 
@osrecio made me aware that my previous statement holds only true when you set up the platform directly. Not if you use the preferred setup with the `production` template. I will change it in the production template too, but there it will only work starting with the next release.

**Comment by osrecio** [comment]
@keulinho I tested too in the `development` repo and I think the commit/changes aren’t there: 
https://github.com/shopware/development/blob/trunk/bin/console#L49

Maybe I’m wrong I don’t know exactly how is the process to replicate the changes between repos/templates

**Comment by keulinho** [comment]
Let me take care of that.
That's one of the reasons we want to deprecate the development template for the 6.5 major version.

**Comment by keulinho** [comment]
It's now also fixed for [production](https://github.com/shopware/production/commit/d92eeb39a76af4f8a60761f76148af03b71719c8) and [development](https://github.com/shopware/development/commit/a5ffdd8ee6b1b6816ba90cbd22663c87776f69e9).
