### ISSUE TITLE
BCC Emails don't send

### ISSUE THREAD

**Issue by bpeschlaudert** [shopware/platform#1949]
### PHP Version

7.4

### Shopware Version

6.4

### Expected behaviour

BCC emails are being sent out

### Actual behaviour

BCC emails are not being sent out

### How to reproduce

Add a BCC recipient to the email object before it gets sent.

**Comment by shyim** [comment]
We just use the Symfony Mailer library. Please create a issue there https://github.com/symfony/symfony
