### ISSUE TITLE
Plugin Config not available any more in Twig

### ISSUE THREAD

**Issue by akuehnis** [shopware/platform#1950]
### PHP Version

7.4

### Shopware Version

6.4.1.2

### Expected behaviour

Plugin config values should be available in Twig as described here:

https://developer.shopware.com/docs/guides/plugins/apps/configuration

```
{{ shopware.config.DemoApp.config.field1 }}
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/7479604/123844225-0cf63480-d913-11eb-9d88-44127b1fc44b.png)

There are no config values any more in 'shopware'. The array only shows 'dateFormat', 'csrfEnabled' and 'csrfMode'.

### How to reproduce

Add Config to a plugin and show {{dump()}} in Twig.

It still worked in 6.4.0, I do not know when this very important data were removed.

**Comment by mitelg** [comment]
please have a look here: https://github.com/shopware/platform/blob/trunk/UPGRADE-6.4.md#twig-system-config-theme-access

I will make the sure the docs get fixed 🙂👍

**Comment by mitelg** [comment]
my colleague was already on it today 😁👍
https://github.com/shopware/docs/pull/323
