### ISSUE TITLE
Update 6.4.1.2 failed

### ISSUE THREAD

**Issue by gummipunkt** [shopware/platform#1952]
### PHP Version

7.4.18

### Shopware Version

6.4.1.2

### Expected behaviour

Completed update with success

### Actual behaviour

php bin/console system:update:finish
Run Post Update

Get collection for identifier: "core"
migrate Migrations
  0/16 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% ---------- ----------------------
  Action     Number of migrations
 ---------- ----------------------
  Migrated   0 out of 16
 ---------- ----------------------

In MigrationCommand.php line 162:

  Migration error: An exception occurred while executing '
          ALTER TABLE `mail_template_type`
          ADD `template_data` LONGTEXT COLLATE utf8mb4_unicode_ci NULL':

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '`sw_gehring`.`mail_template.mailTemplateType`.`available_entities`' in 'CHECK'
  Trace:
  #0 /var/www/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
  #1 /var/www/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException()
  #2 /var/www/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2121): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
  #3 /var/www/shopware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1463): Doctrine\DBAL\Connection->handleExceptionDuringQuery()
  #4 /var/www/shopware/vendor/shopware/core/Migration/V6_4/Migration1617000878AddTemplateDataToMailTemplateType.php(18): Doctrine\DBAL\Connection->executeStatement()
  #5 /var/www/shopware/vendor/shopware/core/Framework/Migration/MigrationRuntime.php(48): Shopware\Core\Migration\V6_4\Migration1617000878AddTemplateDataToMailTemplateType->update()
  #6 /var/www/shopware/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(53): Shopware\Core\Framework\Migration\MigrationRuntime->migrate()
  #7 /var/www/shopware/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(155): Shopware\Core\Framework\Migration\Command\MigrationCommand->getMigrationGenerator()
  #8 /var/www/shopware/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(97): Shopware\Core\Framework\Migration\Command\MigrationCommand->runMigrationForIdentifier()
  #9 /var/www/shopware/vendor/symfony/console/Command/Command.php(256): Shopware\Core\Framework\Migration\Command\MigrationCommand->execute()
  #10 /var/www/shopware/src/Command/SystemUpdateFinishCommand.php(100): Symfony\Component\Console\Command\Command->run()
  #11 /var/www/shopware/src/Command/SystemUpdateFinishCommand.php(74): Shopware\Production\Command\SystemUpdateFinishCommand->runMigrations()
  #12 /var/www/shopware/vendor/symfony/console/Command/Command.php(256): Shopware\Production\Command\SystemUpdateFinishCommand->execute()
  #13 /var/www/shopware/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run()
  #14 /var/www/shopware/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
  #15 /var/www/shopware/vendor/symfony/console/Application.php(290): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
  #16 /var/www/shopware/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
  #17 /var/www/shopware/vendor/symfony/console/Application.php(166): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
  #18 /var/www/shopware/bin/console(70): Symfony\Component\Console\Application->run()
  #19 {main}

In AbstractMySQLDriver.php line 79:

  An exception occurred while executing '
          ALTER TABLE `mail_template_type`
          ADD `template_data` LONGTEXT COLLATE utf8mb4_unicode_ci NULL':

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '`sw_gehring`.`mail_template.mailTemplateType`.`available_entities`' in 'CHECK'

In Exception.php line 18:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '`sw_gehring`.`mail_template.mailTemplateType`.`available_entities`' in 'CHECK'

In PDOConnection.php line 52:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column '`sw_gehring`.`mail_template.mailTemplateType`.`available_entities`' in 'CHECK'

system:update:finish

### How to reproduce

php bin/console system:update:finish

**Comment by shyim** [comment]
Update your mariadb to the latest patch version
