### ISSUE TITLE
customFields are not been populated to  all menu , offcavas item-link

### ISSUE THREAD

**Issue by akshaynikhare** [shopware/platform#1953]
### PHP Version

7.4

### Shopware Version

6.3.4.1

### Expected behaviour

sub menu field in offcanwas , menu should get data from Custom fields 

as this 
![image](https://user-images.githubusercontent.com/9725336/124120429-697f5e00-da91-11eb-9997-0e6429b89559.png)

not populating in sub-menu
![image](https://user-images.githubusercontent.com/9725336/124120779-c67b1400-da91-11eb-909d-7d17b8680c30.png)

### Actual behaviour

offcanwas , sub menu is not getting data from Custom fields 

### How to reproduce

1. create Settings  > System > Custom fields > Add new Set 
2. name it "custom_category_field"  and Assign it to "Categories" 
![image](https://user-images.githubusercontent.com/9725336/124119362-0ccf7380-da90-11eb-8e2c-5cddd74001b3.png)

3. in it add New custom field > add field type as text, and name it  "custom_category_field_name2" ( anything else )
![image](https://user-images.githubusercontent.com/9725336/124119396-18bb3580-da90-11eb-9394-9a571a58c3b1.png)

4. now navigate to Category> any sub category > Custom fields , add new name to the item and save it .
![image](https://user-images.githubusercontent.com/9725336/124119518-40aa9900-da90-11eb-96b7-b97a86aadf3b.png)
![image](https://user-images.githubusercontent.com/9725336/124119575-528c3c00-da90-11eb-8183-2e1aa833a5e0.png)

5.  now try to read that property in theme in the offcanvas panel , slide in menu from left . for this we need to override a twig template so ,Custom template content for "/layout/navigation/offcanvas/item-link.html.twig"
`
{% sw_extends '@Storefront/storefront/layout/navigation/offcanvas/item-link.html.twig' %}
{% block layout_navigation_offcanvas_navigation_categories_list_category_item_link_text %}
    <span itemprop="name">{{ item.category.customFields.custom_category_field_name2 }}
    {{ dump(item.category.customFields) }}</span>
    {% if hasChildren %}
        {% block layout_navigation_offcanvas_navigation_categories_list_category_item_link_icon %}
            <span
                class="navigation-offcanvas-link-icon js-navigation-offcanvas-loading-icon">
                {% sw_icon 'arrow-medium-right' style { 'pack':'solid', 'size': 'sm' } %}
            </span>
        {% endblock %}
    {% endif %}
{% endblock %}
`

6. see on the on storefront in reduced resolution screen , as in an mobile phone 
now the parent menu is correct 
![image](https://user-images.githubusercontent.com/9725336/124120183-14dbe300-da91-11eb-95af-b1675189fa91.png)
but the sub menu ( short shoes )
![image](https://user-images.githubusercontent.com/9725336/124120295-3dfc7380-da91-11eb-9da6-757fe4ae24ca.png)
7. we don't have any data of customFields , so now we can also dump data here 
![image](https://user-images.githubusercontent.com/9725336/124120429-697f5e00-da91-11eb-9997-0e6429b89559.png)
![image](https://user-images.githubusercontent.com/9725336/124120779-c67b1400-da91-11eb-909d-7d17b8680c30.png)

**Comment by Tschucki** [comment]
I encountered the same bug in version 6.4.2.1.

The snippets have the translation or the technical name as their value (See: Settings -> Shop -> Text modules).

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
