### ISSUE TITLE
Adding a repeater field to customFields

### ISSUE THREAD

**Issue by heydavee** [shopware/platform#1954]
### Please describe the feature you would like to see implemented.

Adding a repeater field as a customField would be a huge quality of life improvement.

For example: I want to add some additional blocks. Each block contains a title, text and a link. 

Product A has 2 of these blocks
Product B has 5 of these blocks
Product C has 1 of these blocks

Currently my only knowing solution for this is to create as many customFields as it _could_ be.

So i have to create

```
title1, text1, link1
title2, text2, link2
title3, text3, link3
title4, text4, link4
title5, text5, link5
```

etc.

That is really inefficient. Fields are empty in the backend. Writing that template is just inconvient and could me much more easier with an for each loop.

Overall i think this will give every side (developer & backend user) a much better experience.

**Comment by OliverSkroblin** [comment]
Hey, have you tried a JsonField? Or a ListField? CustomFields are free for developers in the data structure.

**Comment by heydavee** [comment]
> Hey, have you tried a JsonField? Or a ListField? CustomFields are free for developers in the data structure.

Hey sorry i can't follow here. In the backend i cannot find any of those options.

![P0rVfru](https://user-images.githubusercontent.com/5037624/126038742-5eee4d25-0d70-4351-ab30-4ccffe607dfb.png)

Can you elaborate further what you mean with a JsonField and a ListField? Appreciate the help.

**Comment by Alphaegen** [comment]
I was wondering whether any more information is available about the issue above? How would I start creating a custom repeater field type with code?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
