### ISSUE TITLE
Turnover number formatting should be limited to 2 decimal places.

### ISSUE THREAD

**Issue by rlincke** [shopware/platform#1957]
### PHP Version

7.4.13

### Shopware Version

6.4.1.2

### Expected behaviour

On the dashboard (admin login), the Turnover should show, e.g., €277.06

### Actual behaviour

On the dashboard (admin login), the Turnover should show, e.g., €277.05999999999995

### How to reproduce

Login to administration and go to Dashboard.
In the Today's statistics, if you have orders, the Turnover will not be rounded to 2 decimal places.

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/platform/commit/9cdafc429a996c1b23cfecb24dd5d0fae0026654#diff-b917d5beba3db7bb99711f9ac63ab977d9771b4b3fdabe1e74fe204b5898f40b
