### ISSUE TITLE
Core Kernel.php overwrites existing timezone settings from php

### ISSUE THREAD

**Issue by reldorkamori** [shopware/platform#1958]
### PHP Version

7.4

### Shopware Version

6

### Expected behaviour

The existing timezone settings from the local php.ini should be considered and not overwritten.

### Actual behaviour

In the file "core/Kernel.php" line 89 the default timezone is overwritten generally...
It is my understanding, that if not defined in the current php.ini, the timezone will generally fallback to UTC, which is the normal behaviour.
With overwriting it generally this brings the issue, that e.g. payment services which rely on a signature with a timestamp will have issues and the paymentplugins will have to set the timezone manually instead of using the systems settings.
Which causes besides other problems, that the product image cache is invalidated if a plugin sets the timezone and everything will be broken...

Either you should have a setting for the timezone in the .env file or simply use the global php settings.

### How to reproduce

Create a controller with the response of the following method:
`
     /**
     * @Route("/dev/timezone", name="storefront.dev.timezone", options={"seo"="false"}, methods={"GET"})
     */
    public function timezone(Request $request) {
        return new Response(date_default_timezone_get());
    }
`

you will see, that no matter what is set in the php.ini the timezone will be overwritten generally...

**Comment by shyim** [comment]
Hey,

That's expected behavior. Shopware works only with UTC internally. Can you bring an actual problem?  Plugins should not generally override the timezone.

**Comment by reldorkamori** [comment]
Hey :)
Sure, we have a payment provider in Germany which expects the actual time and date of the transaction, which will then be used for verification and signature.
Which can of course be solved by also submitting the Timezone value UTC, but imho that is not the right behaviour for localized servers.

I just checked it, that works.
But if this is expected behaviour then I'll close the issue!

Maybe that could be a feature request for some time, but as I understand it the entire core is built to use UTC which might be a big feature request ;)

Thank you for the quick answer tho <3
