### ISSUE TITLE
Composer install - illegal byte sequence

### ISSUE THREAD

**Issue by zolthan** [shopware/platform#1967]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

Installing shopware/platform without warning.

### Actual behaviour

```
 194/195 [===========================>]  99%    Failed to extract shopware/platform: (50) '/usr/bin/unzip' -qq '/.../www/vendor/composer/tmp-f39a5c9f1b9ae415a14c1d53647b5507' -d '/.../www/vendor/composer/f8588bb5'

error:  cannot create /.../www/vendor/composer/f8588bb5/shopware-platform-3a64905/changelog/release-6-4-2-0/2021-06-17-fix-that-the-checkboxes-in-the-category-tree-don-?t-get-hidden-after-closing.md
        Illegal byte sequence

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```
There seems to be a naming issue in a changelog filename.

### How to reproduce

- Delete vendor directory
- composer install (or composer update)

**Comment by shyim** [comment]
Hey,

maybe try composer cc and deleting the vendor folder. If it's not helping try to get support from the composer project directly https://github.com/composer/composer/issues

**Comment by zolthan** [comment]
I think it would be better to use only normal filename characters in filenames, and no `´` like in
https://github.com/shopware/platform/blob/trunk/changelog/release-6-4-2-0/2021-06-17-fix-that-the-checkboxes-in-the-category-tree-don´t-get-hidden-after-closing.md

Don't understand why you are closing the issue?

**Comment by shyim** [comment]
What is your OS?

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/platform/commit/bd8c04d3a51c5e6b55eb8e27aa6ddda287061311

**Comment by zolthan** [comment]
MacOS, but I think it just should be removed, just like you did. Thx
