### ISSUE TITLE
MailSendSubscriber causes rollback in case of non-standard language

### ISSUE THREAD

**Issue by pascaljosephy** [shopware/platform#1972]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

Outer transactions should not be cancelled.

### Actual behaviour

The method MailSendSubscriber::sendMail throws an exception if a mail is sent in a non-standard language here: 
https://github.com/shopware/platform/blob/1395010cb7762a7d0ea3813ef675ec1d20734518/src/Core/Content/MailTemplate/Subscriber/MailSendSubscriber.php#L151

The line therefore has been wrapped in a try / catch block in the following commit:

https://github.com/shopware/platform/commit/7b6404d6fa30b0ec59feaa3f86c9a0321d9875cf

This solves the problem of an exception being thrown, however, if a transaction is being started in the calling code (for example code that causes a state change), the whole transaction is cancelled (rollbackOnly is set to true).

### How to reproduce

- Add a domain in a non-standard language
- Activate for example the mail order.state.cancelled
- Perform an order in the non-standard language domain
- Write code that starts a transaction, performs the state change, does some other db operation and then commits everything

--> the other changes are not written to the database

**Comment by pascaljosephy** [comment]
Note: According to the code this bug will be fixed after the shopware internal ticket (NEXT-15475) is closed.

**Comment by shyim** [comment]
We added a option to disable this https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks#prevent-mail-data-updates
