### ISSUE TITLE
HTMLPurifier does not respect umask

### ISSUE THREAD

**Issue by ingowalther** [shopware/platform#1975]
### PHP Version

8.0

### Shopware Version

v6.4.2.1 Stable Version 

### Expected behaviour

The permissions of the cache files created by HTMLPurifier should respect the umask.

### Actual behaviour

The permission for the files (not directories) will be set to "0644".

### How to reproduce

1. Request a page in the store front.
2. Check the permissions in the cache/HTML and cache/URL folders.

**Comment by ingowalther** [comment]
If can be fixed with adding 

`$config->set('Cache.SerializerPermissions', 0777 & ~umask());`

to the `HTMLPurifier_Config`

**Comment by shyim** [comment]
Can you create a pull request?

**Comment by shyim** [comment]
fixed with https://github.com/shopware/platform/commit/8a8fa01ee1185652b97c441a4679e56a579996ba
