### ISSUE TITLE
Scheduled task uses wrong DateTime format for next execution date time check

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#1978]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

Retrieve the next scheduled tasks corectly, independent of MySQL / system timezone.

To retrieve the next scheduled task, currently ATOM timezone is used instead of the `\Shopware\Core\Defaults::STORAGE_DATE_TIME_FORMAT`

this results in MySQL 8 with the server being set to Germany timezone (currently with daylight savings being active) that the server always retriggers jobs that are executed once per hour as the next date time is stored in UTC but ATOM provides a timezone  which with MySQL 8 is not ignored.

### Actual behaviour

see above

### How to reproduce

see above

### Issue on issue tracker
https://issues.shopware.com/issues/NEXT-16402

**Comment by shyim** [comment]
I have closed your ticket as duplicate cause of https://issues.shopware.com/issues/NEXT-15289 fyi

**Comment by AndreasA** [comment]
strictly speaking I think they are related which is why I created a separate one. as the linked one is a general timezone mismatch issue. this is a query DateTime format used issue. 
It probably has the same same issue regarding the end result so in a way they might be duplicates but the why is a bit different. But as long as they other one fixes this too I am fine with it.

**Comment by shyim** [comment]
The fix from our side would be to set the time zone to UTC of the MySQL connection. This should solve your too

**Comment by AndreasA** [comment]
@shyim The currently included fix uses 'UTC'  when setting the timezone which seems to fail for me. 

What works instead is `SET @@session.time_zone = '+00:00';`

Using MySQL 8

Is this just me or would `+00:00` be the generic solution? 

Also: Shouldn't the timezone be set by default and as mentioned the correct STORAGE_DATE_TIME_FORMAT should still be used.

**Comment by ts-mothership** [comment]
I can confirm this issue still exists in 6.4.5.1. NEXT-15289 was not fixed properly. Our MySQL time_zone is set to "CET" and the Shopware API always returns invalid results when using the date range filter.

We could ask our hoster to change DB timezone, but this should be fixed by Shopware.

Either what @AndreasA suggested:
```
SET @@session.time_zone = '+00:00';
```

or via PDO INIT Command in Shopware's Kernel:
```
$parameters['driverOptions'][\PDO::MYSQL_ATTR_INIT_COMMAND] = 'SET NAMES utf8mb4, time_zone="+0:00"';
```
https://github.com/shopware/platform/blob/trunk/src/Core/HttpKernel.php#L136
https://github.com/shopware/platform/blob/trunk/src/Core/Kernel.php#L234

**Comment by AndreasA** [comment]
Also, from what I can set the session time zone is not set by default. The setting has to be enabled which is also weird, it should be necessary to disable it instead: https://github.com/shopware/platform/blob/v6.4.7.0/src/Core/Kernel.php#L392

Furthermore, I think using `STORAGE_DATE_TIME_FORMAT` would also fix it and in addition to using the correct value for session.time_zone, would be the best solution.

Maybe the session timezone could be set using a ENV variable, then using +00:00 or UTC or whatever would work too.

**Comment by shyim** [comment]
You need to set `SHOPWARE_DBAL_TIMEZONE_SUPPORT_ENABLED=1` in the `.env`.

Setting MySQL Time Zones does not always work as the timezone information needs to be populated

**Comment by AndreasA** [comment]
As I said +00:00 works but e.g. UTC does not for me. And it isn't really a bugfix as it is optional currently and might fail (no UTC timezone).

**Comment by AndreasA** [comment]
I have now also tried `SET @@session.time_zone = 'UTC';` and `SET @@session.time_zone = '+00:00';` on multiple systems (debian, ubuntu, mac, red hat and mysql version 5.7 and 8.0) and `SET @@session.time_zone = '+00:00';` works on all of those system. However, `UTC` only worked on Debian one. 

Most of them are not managed by me but that is exactly why the current fix is not optimal because one is not always able to influence database config.
