### ISSUE TITLE
deprecated code

### ISSUE THREAD

**Issue by lxregistry** [shopware/platform#1984]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

please fix all deprecated code, make it working with symfony 5.3.5 without any deprecated warnings

### Actual behaviour

User Deprecated: Since symfony/framework-bundle 5.2: Accessing the "serializer" service directly from the container is deprecated, use dependency injection instead. {"e
xception":"[object] (ErrorException(code: 0): User Deprecated: Since symfony/framework-bundle 5.2: Accessing the \"serializer\" service directly from the container is d
eprecated, use dependency injection instead. at.....

User Deprecated: Since symfony/twig-bundle 5.2: Accessing the "twig" service directly from the container is deprecated, use dependency injection instead. {"exception":"
[object] (ErrorException(code: 0): User Deprecated: Since symfony/twig-bundle 5.2: Accessing the \"twig\" service directly from the container is deprecated, use depende
ncy injection instead. at .......

### How to reproduce

just open site

**Comment by shyim** [comment]
The mentioned deprecations are already fixed in trunk
