### ISSUE TITLE
Cannot edit address in checkout.

### ISSUE THREAD

**Issue by giacmir** [shopware/platform#1985]
### PHP Version

7.4

### Shopware Version

6.4..2.1

### Expected behaviour

editing address in checkout should work.

### Actual behaviour

If "ShowVatIdField" is true then the address edit modal displays the following error
```
An exception has been thrown during the rendering of a template ("Property vatId do not exist in class Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity").
```

That's because the `vatId` property was removed from `Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity` but it's still used in twig ` Storefront/Resources/views/storefront/component/address/address-form.html.twig` (line 110)

### How to reproduce

- Install Shopware 6.3
- enable vat Id display
- upgrade to 6.4
- go to checkout
- click "change address" button

**Comment by shyim** [comment]
That is fixed in meanwhile
