### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by lxregistry** [shopware/platform#1987]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

receive list of extensions

### Actual behaviour

"POST /api/search/sales-channel HTTP/1.1" 200 21075 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.4) Gecko/20100101 Firefox/60.4"
PHP Fatal error:  Uncaught Error: Class 'Symfony\\Component\\ErrorHandler\\ThrowableUtils' not found in /vendor/symfony/error-handler/ErrorHandler.php:563\nStack trace:\n#0 [internal function]: Symfony\\Component\\ErrorHandler\\ErrorHandler->handleException()\n#1 {main}\n  thrown in /vendor/symfony/error-handler/ErrorHandler.php on line 563
PHP Fatal error:  Uncaught Error: Class 'Symfony\\Component\\ErrorHandler\\Error\\FatalError' not found in /vendor/symfony/error-handler/ErrorHandler.php:686\nStack trace:\n#0 [internal function]: Symfony\\Component\\ErrorHandler\\ErrorHandler::handleFatalError()\n#1 {main}\n  thrown in /vendor/symfony/error-handler/ErrorHandler.php on line 686

### How to reproduce

in admin area open extensions/my extensions

**Comment by shyim** [comment]
Hey,

replace your vendor folder with the install zip. There are some files missing
