### ISSUE TITLE
When duplicating a Mail Template, the created_at field gets duplicated too

### ISSUE THREAD

**Issue by peterjaap** [shopware/platform#1988]
### PHP Version

7.4

### Shopware Version

6.3.5.2

### Expected behaviour

The `created_at` field in the `mail_template` table should contain the timestamp of when the mail template was duplicated, not the value of the original mail template.

### Actual behaviour

The `created_at` field contains the date of when the ORIGINAL mail template was created.

### How to reproduce

Duplicate a mail template, check the `created_at` field in the `mail_template` table.

**Comment by shyim** [comment]
fixed with https://github.com/shopware/platform/commit/0731d626222043d922838a7eac7003229434e530
