### ISSUE TITLE
DAL Search: Indexing of customFields fails

### ISSUE THREAD

**Issue by Donderda** [shopware/platform#1989]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

The indexer shouldn't throw a 500 error code when trying to index customFields, the customFields should be indexed correctly.

### Actual behaviour

Throws error:
<img width="1864" alt="Bildschirmfoto 2021-07-30 um 08 46 12" src="https://user-images.githubusercontent.com/3691838/127620018-8e89a892-ceba-43ee-a7b3-44a51cde4ca3.png">

This seems to be caused by a `null` field in  line https://github.com/shopware/platform/blob/724b35bd985bbe790d9e670b54284e78d9de80c5/src/Core/Content/Product/DataAbstractionLayer/SearchKeywordUpdater.php#L244 . 

Working `$fields` example:
<img width="869" alt="Bildschirmfoto 2021-07-30 um 09 58 19" src="https://user-images.githubusercontent.com/3691838/127621045-e1a803b9-e6b1-483d-afc1-73279621037e.png">

Here's an example of a "faulty" `$fields` value:

<img width="704" alt="Bildschirmfoto 2021-07-30 um 09 53 55" src="https://user-images.githubusercontent.com/3691838/127620519-747b3875-4b79-4a96-aa4a-2103a334f6be.png">

For now, I just added a check if the `$field` is null before passing it to the mentioned line, but I'm pretty sure that there is a much more elegant way :-)

### How to reproduce

* added a CustomField (type: text) to the products
* set a value for one product for the defined customField
* add customField to the searchable content
* reindex search

**Comment by OliverSkroblin** [comment]
Hi @Donderda,

can you please check if you have the following commit? And if not, please test it with the commit - it should be fixed

https://github.com/shopware/platform/commit/23db1f33c7eb73de90815a77422b747ccae0b68a

`src/Core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php` is the relevant part

**Comment by Donderda** [comment]
yep, it works. thank you.
