### ISSUE TITLE
Run plugin commands / actions from the admin's plugin page

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#1990]
### Please describe the feature you would like to see implemented.

We have a Shopware 6 plugin with provides several commands (Symfony commands) which can be run with `bin/console <command>`. To access it, we have to connect to our customer's server which is always different and can take some time to establish a connection.

If the Shopware admin panel would provide an option to run Symfony commands, this would save a lot of time for us.

**Comment by keulinho** [comment]
I don't think that this should be a general feature for the plugin system, i see some potential problems here.

First CLI commands are meant to run in CI context or by running directly in the shell, but in both cases the "user" of those commands is a developer or operator, that is not necessarily the same "userbase", as the users of the administration. So the users of the administration may not be able to judge the effects of running the commands. Also security concern come into mind, not every administration user should be able to call those commands, but what privileges does the user need?

Additionally  there may be arguments that need to be passed to the command, how should they be captured and validated dynamically in the administration?

Lastly there may be a huge difference for CLI and WEB context in terms of the php runtime. It is common that the max_execution_time and max_memory settings for the web/fpm context are considerably slower then for the CLI context, so a command that runs fine when calling over cli may result in timeouts when calling over web. Not even to mention that in some wild cases even the php version may differ between cli and fpm contexts.

IMHO the way better solution would be to handle it individually inside your plugin. In your case your console commands should use some service that implements the functionality, the command should only parse input arguments and provide some console outputs, but the business logic should be encapsulated in it's own service. That it should be rather easy to create a custom controller that makes that functionality available over the API, by reusing the common service. You can then extend the administration to show buttons or stuff like that to run your "commands" by using the API.

This is exactly the way we handle situation like that for the shopware platform itself, for example the plugin lifecycle commands (plugin:install, plugin:activate, etc.) and the cache clear commands are both available as a CLI command and from inside the administration. In both cases the general functionality is encapsulated in a service that can be called by an CLI command or by a controller.

I hope this answer helps you going forward ;)
Kind regards
Jonas

**Comment by Zerotask** [comment]
> First CLI commands are meant to run in CI context or by running directly in the shell, but in both cases the "user" of those commands is a developer or operator, that is not necessarily the same "userbase", as the users of the administration. So the users of the administration may not be able to judge the effects of running the commands.

If a backend user is able to access system settings like plugins, he should also have access to plugin commands. Additionally there could be new permissions to give a backend user such rights.
Just because they are **currently** not meant for such cases, this could be considered and this is the reason for this feature request.

> Also security concern come into mind, not every administration user should be able to call those commands, but what privileges does the user need?

I don't see any security issues by running predefined commands. I don't say one should be able to run system commands.

> Additionally there may be arguments that need to be passed to the command, how should they be captured and validated dynamically in the administration?

I don't see a problem here. Arguments could be passed within forms and validated within PHP. This feature just have to consider that.

> Lastly there may be a huge difference for CLI and WEB context in terms of the php runtime. It is common that the max_execution_time and max_memory settings for the web/fpm context are considerably slower then for the CLI context, so a command that runs fine when calling over cli may result in timeouts when calling over web. Not even to mention that in some wild cases even the php version may differ between cli and fpm contexts.

If this happens, **then** one can switch to a shell and run it there. But you forget all those cases where this doesn't happen.
I don't say the plugin option should replace the current way, it's just an addition.

**Comment by JoshuaBehrens** [comment]
I am with @keulinho regarding security. In shopware you always get a context at hand that will ensure right usage and right access. On CLI you "only" have the default context. In the past you were forced to use that one or generate yourself a different context that matches more closely your case. Like a SalesChannelContext. So by default everyone right now uses the most elevated context: the default context. This is a real security breach.

You had to exclude some commands as well. system:setup --drop-database is not sth anyone should execute from a webcontext.

Due to work on HEPTAconnect we already had our thoughts on providing single actions in a web and in a CLI context. This is not as easy as it sometimes sound. You can already see that there are event different application/kernels used on CLI and on Web actions. Only by the intention that a command would be cool to use on web doesn't mean it belong there. Output and input is difficult to abstract to make it work in the web.

How would you make it interactive?

Comparing it to laravel actions: they can be run from CLI and web but you have to specify the support. So eventually the plugin/command developer still has to support it on their own. Now you still rely on the good-will of the dev to add support.

**Comment by Zerotask** [comment]
> I am with @keulinho regarding security.

There aren't any security concerns if your implement it properly.

> How would you make it interactive?

As I already wrote above, there could be a form (text input) to define flags and arguments, but it could also be a modal where you can see all available flags and you can check them (checkboxes), so there are predefined fields which can then be validated within PHP. There are not really technical issues to implement it that way. There is just a concept needed how to do that - like with every new feature.

> Comparing it to laravel actions: they can be run from CLI and web but you have to specify the support. So eventually the plugin/command developer still has to support it on their own.

That would be fine for us. A developer could opt-in to some commands which should be accessible by the web.
We don't need default commands to be run via web, just our own (from static-plugins).

**Comment by JoshuaBehrens** [comment]
>  We don't need default plugins to be run via web, just our own (from static-plugins).
That make things a bit easier and less concerning.

Regarding interactivity. It is not about flags and arguments. On CLI you have a TTY. You can wait for user input. That won't work that easy out of a single web request.

> There aren't any security concerns if your implement it properly.

There hasn't been a way to do it go the proper way NOW within a CLI command to rely on a provided context. As the context heavily impacts the security features you will open up unwanted execution right elevations.

Having tooling around it just ends up in writing a route/controller. When you properly separated code into a service that just relies on input parameter destruction into parameters for a method you will probably have the same amount of work to do to have it on CLI and Web.

**Comment by Zerotask** [comment]
> On CLI you have a TTY. You can wait for user input. That won't work that easy out of a single web request.

It's technically doable and that's the point.

> As the context heavily impacts the security features you will open up unwanted execution right elevations.

As I already wrote, if you implement this feature properly, there aren't any security concerns. But it seems that you don't want to invest your time into this feature. Then just close my request, but don't say it's due to security concerns or stuff.

> Having tooling around it just ends up in writing a route/controller. When you properly separated code into a service that just relies on input parameter destruction into parameters for a method you will probably have the same amount of work to do to have it on CLI and Web.

If you implement it properly, then this will be just a little opt-in addition for developers.
The main point, as stated above is probably that you don't want to invest time in such a feature or you don't have such use cases.
So to avoid playing the ball around, just decline my feature request and close it.

**Comment by JoshuaBehrens** [comment]
> But it seems that you don't want to invest your time into this feature. 

I am not shopware! So don't take my reaction as one from an owner. I just work a lot with shopware and seen implementations that tried to do SSH over HTTP in a shopware plugin and yes, it worked but no it is not as cool as one might think first.

> you don't have such use cases

I have lot's of cases where I want commands to be accessable from the web, but I know the work I have to do and just don't do it in the first place. Maybe I got your feature request wrong but there is already everything you need to do it. What would the feature simplify? What use case is yours? What would your command do?
