### ISSUE TITLE
Cannot translate custom fields in product edit

### ISSUE THREAD

**Issue by grubolsch** [shopware/platform#2001]
### PHP Version

PHP 8.0

### Shopware Version

6.4.3

### Expected behaviour

Being able to translate custom fields on a product.

### Actual behaviour

I fill in the first translation (english). Everything works fine.
We switch to the german language. First minor bug here, the english text is already filled in.
When I save the components do not reload (no spinning gif).
When I now reload the interface is completely broken and the custom fields do not load/show anymore.

If you completly leave the product page and come back later the feature this work, but not for "bugged" products.

### How to reproduce

Preparation: Create in the admin a custom field text field for the product entity.

I fill in the first translation (english). Everything works fine.
We switch to the german language. First minor bug here, the english text is already filled in.
When I save the components do not reload (no spinning gif).
When I now reload the interface is completely broken and the custom fields do not load/show anymore.

We saw following errors in the console

TypeError: entity.customFields is null
    fn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    kt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    fn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    kt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    fn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    i http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    St http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    anonymous http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    _render http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    i http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    get http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    run http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    vn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    rt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Qe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
vendors-node.js:2:653842
    Ue http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Ge http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Ve http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    _render http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    i http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    get http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    run http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    vn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    rt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Qe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
TypeError: entity.customFields is null
    fn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    kt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    fn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    kt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    fn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    i http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    St http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    anonymous http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    _render http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    i http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    get http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    run http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    vn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    rt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Qe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
vendors-node.js:2:653842
vendors-node.js:2:653842
TypeError:
    Ee http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    callback http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070 line 2 > Function:3
    Xe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    n http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Xe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    $emit http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    updateValue http://shopware-demo.local/bundles/administration/static/js/app.js?16279781165413442:1
    set http://shopware-demo.local/bundles/administration/static/js/app.js?16279781165413442:1
    updateCurrentValue http://shopware-demo.local/bundles/administration/static/js/app.js?16279781165413442:1
    Xe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    n http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Xe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    $emit http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    currentValue http://shopware-demo.local/bundles/administration/static/js/app.js?16279781165413442:1
    run http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    vn http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    rt http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
    Qe http://shopware-demo.local/bundles/administration/static/js/vendors-node.js?16279781161521070:2
right-hand side of 'in' should be an object, got null

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
