### ISSUE TITLE
Dev server install error because of demo data / image generator

### ISSUE THREAD

**Issue by stiegi** [shopware/platform#2003]
### PHP Version

8.0.5

### Shopware Version

6.4

### Expected behaviour

Pull development repo, run `cd development && ./ psh.phar docker:start &&  ./psh.phar docker:ssh`, then `./psh.phar install` will install demo shop with demo data.

### Actual behaviour

Install process crahes:
![image](https://user-images.githubusercontent.com/29003519/128211026-7808a3c7-a9ff-40c9-a2b7-a6425f90b898.png)

Current workarounds for those who need this NOW: before install, comment out `INCLUDE .demo_data.sh` in `/dev-ops/common/actions/install.sh`.
Then run installer. Then search for `bheller` in all files, replace with `Maltyxx`, then run (from within docker app container) `bash /app/dev-ops/common/actions/demo-data.sh`.

### How to reproduce

Pull development repo, run `cd development && ./ psh.phar docker:start &&  ./psh.phar docker:ssh`, then `./psh.phar install`

**Comment by shyim** [comment]
Checkout a tag in the development template

**Comment by stiegi** [comment]
In v6.4.3.1 this error occurs

**Comment by shyim** [comment]
```
git checkout v6.4.3.1
rm -rf vendor composer.lock
Run install
```

Should do it. The trunk branch is intended to contribute

**Comment by stiegi** [comment]
I deleted vendor and composer.lock but the error still exists in v6.4.3.1. For us this is part of automatic testing, running on a Jenkins, so basically it is installed on a completely fresh and empty environment, there are no artifacts of old versions.

**Comment by xUJYx** [comment]
@stiegi  
See solution inside [this comment](https://github.com/shopware/platform/issues/2037#issuecomment-912585994)

**Comment by stiegi** [comment]
@xUJYx Thanks for letting me know. I will wait for the fix for now.
