### ISSUE TITLE
Amazon integration private key not working

### ISSUE THREAD

**Issue by jonyking** [shopware/platform#2014]
### PHP Version

8.0.0

### Shopware Version

6.4.3.0

### Expected behaviour

Accept the json file content for private key

### Actual behaviour

The content of the given json file is not excepted. "Format is invalid"

### How to reproduce

Just try to integrate Public.Key, Store.ID and Private.Key from your amazon pay account.

**Comment by shyim** [comment]
Hey,

this is only for the Shopware 6 platform itself. Please use the issue tracker to create a specific issue to the Amazon Pay plugin https://issues.shopware.com/createissue
