### ISSUE TITLE
OneToOne EntityExtension broken in 6.4.3.0 (Internal Server Error)

### ISSUE THREAD

**Issue by sawden** [shopware/platform#2015]
### PHP Version

7.4.22

### Shopware Version

6.4.3.0

### Expected behaviour

It should be possible to expand the product with a "OneToOneAssociationField" as described in the [documentation](https://developer.shopware.com/docs/guides/plugins/plugins/framework/data-handling/add-complex-data-to-existing-entities#adding-a-field-with-database).

**_This error is very critical because none of the plugins that extend the product entity can currently be used._** 

### Actual behaviour

Currently, all plugins that extend the product entity with a "OneToOneAssociationField" lead to a 500 error when saving or editing products in the administration.

An error message appears in the upper corner.
![sw6_err](https://user-images.githubusercontent.com/36924392/128963822-7151448e-4aaf-42b9-a64e-181f81e1cb1d.png)

In the developer tools you can see that there is an Internal Server Error.
![sw6_err2](https://user-images.githubusercontent.com/36924392/128963981-3ab40ec4-4a76-47b3-9659-96e994636166.png)
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'OTO' in 'field list'`

### How to reproduce

Create a Plugin that extends the "Product" with a "OneToOneAssociationField" or download/clone my example plugin that reproduce this error.

[Github repository here](https://github.com/sawden/OneToOneProductExtensionTest)

- Install the plugin.
- Open the administration and edit an existing product (add a space in to the name) or try to create a new product.
- Press "Save"

...**Internal Server Error**...

**Comment by shyim** [comment]
Your field is Inherited, you need to use the inheritance updater to add a new column in product table named like your association

**Comment by sawden** [comment]
Thanks, everything works as expected.

Thanks for your work 🙂

**Comment by sawden** [comment]
@shyim It seems as if the inheritance for product extensions does not work with a one-to-one relation. 🤔

I've updated the code in my [reproduction repository](https://github.com/sawden/OneToOneProductExtensionTest) but the extension is not inherited on to the variant products.

I've already tried everything and I'm running out of ideas... 😕
