### ISSUE TITLE
dal:create:schema does not work correctly with kernel.project_dir

### ISSUE THREAD

**Issue by dsnnnnnnnnn** [shopware/platform#2018]
### PHP Version

7.4.19

### Shopware Version

v6.4.2.1 Stable Version

### Expected behaviour

During command execution `bin/console dal:create:schema` I'm in the Class `Shopware\Core\Framework\DataAbstractionLayer\Command\CreateSchemaCommand::59` here:

```
if (!file_exists($this->dir)) {
    mkdir($this->dir);
}
```

must get path `/var/www/html/public/../schema/` because my root in public and execution work from public/index.php

After that, a folder with project rights called `schema` is created in my project working directory

### Actual behaviour

I am getting the wrong path: `/var/www/html/../schema/`

![image](https://user-images.githubusercontent.com/23435785/126987091-50e6686c-7cbf-4b64-8675-3f3700ecaa26.png)

and the application tries to create a folder outside the working directory:
/var/www/schema

### How to reproduce

1) run the command `bin/console dal:create:schema`
2) get error

![Selection_857](https://user-images.githubusercontent.com/23435785/126987230-43dc25ca-52c2-4b98-b294-f971d85af23d.png)

**Comment by shyim** [comment]
Fixed with https://github.com/shopware/platform/commit/b686c665c9b32d90ca2787907a4129c3e3afd77e
