### ISSUE TITLE
Criteria cache keys do not include associations 

### ISSUE THREAD

**Issue by Josniii** [shopware/platform#2020]
### PHP Version

7.4

### Shopware Version

6.4.2.1

### Expected behaviour

When requesting entites through a cached route (eg. using ShippingMethodRoute to load available shipping methods), the result should only be cached if we have an exact match on the Criteria, including any associated entities.

### Actual behaviour

When requesting two different associations, the same result is reused despite differences in associations. For example, requesting associated media on one request, and prices on another (but with the same query, filters, etc.) - the results will be that the second request simply finds a cache hit, which is wrong.

### How to reproduce

Basic example with the ShippingMethodRoute:

```
$request = new Request();
$request->query->set('onlyAvailable', true);
$resultA = $this->shippingMethodRoute
    ->load($request, $salesChannelContext, (new Criteria())->addAssociation('media'))
    ->getShippingMethods();

$request = new Request();
$request->query->set('onlyAvailable', true);
$resultB = $this->shippingMethodRoute
    ->load($request, $salesChannelContext, (new Criteria())->addAssociation('prices'))
    ->getShippingMethods();
```

`$resultB` will be a cache hit from resultA, and no prices will therefore be loaded, making it seem like the shipping methods just don't have any prices.

The issue is pretty severe and can cause bugs that are a pain to debug. That said, the fix should simply be to add associations to the cache key being generated in `\Shopware\Core\Framework\DataAbstractionLayer\Cache\EntityCacheKeyGenerator`

**Comment by shyim** [comment]
This is fixed already
