### ISSUE TITLE
Product listing limit causes invalid results

### ISSUE THREAD

**Issue by kardi31** [shopware/platform#2022]
### PHP Version

7.4

### Shopware Version

6.4.2

### Expected behaviour

When sending GET request to `/api/product` endpoint with filters including result limit=1 applied to url, I expect a valid product to be returned. 

### Actual behaviour

Random product is being returned. 

### How to reproduce

Filters used : 
```
'query' => [
        'type' => 'equals',
    'field' => 'productNumber',
    'value' => '15028c',
],
'limit' => 1
```

Example url: '/api/product?query%5B0%5D%5Bquery%5D%5Btype%5D=equals&query%5B0%5D%5Bquery%5D%5Bfield%5D=productNumber&query%5B0%5D%5Bquery%5D%5Bvalue%5D=15028c&limit=1'

Same query without passing `limit=1` in url returns a correct result. 

I tracked the issue being caused by https://github.com/shopware/platform/commit/7492840e2724a0e5b90e2fd594d87cbe36e4cad4#diff-5baaaba385312522430d48fe76762868af0be5171929a25e23c7ae0b9223b20dR105
As a result when filter is added, the SQL statement does not have a `group by` clause, which basically returns invalid result. 

SQL query with limit = 1
```
SELECT `product`.`id`, SUM(IF(`product`.`product_number` = :param_0bf09c73a4de4699891ee37575bd05dc , '1', 0)) as _score FROM `product` WHERE `product`.`version_id` = :version HAVING _score >= :_minScore ORDER BY _score DESC LIMIT 1
```

SQL query without limit=1
```
SELECT `product`.`id`, SUM(IF(`product`.`product_number` = :param_a23a3af80298447dae96c42e4cda5be0 , '1', 0)) as _score FROM `product` WHERE `product`.`version_id` = :version GROUP BY `product`.`id` HAVING _score >= :_minScore ORDER BY _score DESC
```

**Comment by OliverSkroblin** [comment]
Hi @kardi31,

i tried to recreate the query you describe above... but if i see the right thing, the payload should look like this:
```
{
    "query": [
        { 
            "query": {
                "type": "equals", 
                "field": "productNumber",
                "value": "15028c"
            },
            "ranking": 100
        }
    ],
    "limit": 1
}
```

You are using here the `query` parameter which is used for search rankings / boostings. To search for a product exactly by its product number, you should use the 'filter' parameter 


```
{
    "filter": [
        {
            "type": "equals", 
            "field": "productNumber",
            "value": "15028c"
        }
    ],
    "limit": 1
}
```

**Comment by kardi31** [comment]
Thank you @OliverSkroblin  . Indeed the request with filter parameters is returning correct results. I will leave this issue up to you to decide what to do. IMO if a functionality should not be used in certain way, there should be some precautions against it. With the way it currently is, we receive a successful response with incorrect data.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
