### ISSUE TITLE
Cheapest unit Price not visible anymore after 6.4.3.1 Update

### ISSUE THREAD

**Issue by heydavee** [shopware/platform#2024]
### PHP Version

7.4

### Shopware Version

6.4.3.1

### Expected behaviour

Cheapest Unit price should be visible in the product listing.

### Actual behaviour

The div is empty and you cannot see the cheapest unit price

### How to reproduce

Updating shopware to 6.4.3.1. Standard Theme , no active plugins

**Comment by DaveWoody** [comment]
![Example](https://user-images.githubusercontent.com/5037624/129922991-48b7f02d-7bb8-4508-b4b2-5dec6ffdb3cd.png)

**Comment by heydavee** [comment]
![Example](https://user-images.githubusercontent.com/5037624/129923164-bb31fd1e-7921-48b9-a345-f34105c6a115.png)

**Comment by shyim** [comment]
Still valid?

**Comment by heydavee** [comment]
I think it is fine for now, we see the lowest variant price after the latest updates. 
<img width="1353" alt="Bildschirmfoto 2022-11-16 um 08 01 37" src="https://user-images.githubusercontent.com/5037624/202108479-e5f574cc-30cc-4ab6-ad13-402b403e5a51.png">

Would close this for now. Thanks!
