### ISSUE TITLE
order_count and last_order_date not set in customer table

### ISSUE THREAD

**Issue by ivan-logeecom** [shopware/platform#2026]
### PHP Version

7.4.3

### Shopware Version

Shopware 6.4.3.1

### Expected behaviour

order_count and last_order_date field should be set for customers with orders

### Actual behaviour

order_count is set on 0, and last_order_date is null.

### How to reproduce

Register customers, and create some orders.
Check the database columns last_order_date, and order_count of the customer table for the same customer

**Comment by wrongspot** [comment]
can not confirm that. Shopware 6.4.4.1
![Bildschirmfoto 2021-09-29 um 20 26 12](https://user-images.githubusercontent.com/907458/135327299-98b0b1f9-1cdb-45ab-a6ca-7e6a9ac675b4.png)

**Comment by shyim** [comment]
Cannot be reproduced
