### ISSUE TITLE
Creating a database entry should return an instance of the entity

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2032]
Scenario:
You want to return an entity and if it doesn't exist, it should be created.

This means you have to look it up (search()). If it's null, you call create(). The return of the create()-Call is an instance of `EntityWrittenContainerEvent` and I didn't find a way to get an actual entity of this newly created entry.
This means, after I created it, I have to look it up (search()) again.
This results in 3 database actions.

Another way would be calling upsert() at the beginning and after it, I look it up (search()). But this would mean, that I have always 2 database actions.

Therefore the return of a create() should offer me the actual entity of the freshly created entry.

To avoid breaking changes, this could be done with an additional property for `EntityWrittenContainerEvent`, which can be accessed with `getEntity()`.

**Comment by uehler** [comment]
I don't think, this will be implemented because right now, you have 1 db request for your creation and one for the search of the new entity. If the event returns an entity this is a hidden request for every creation regardless if the result is used or not.

**Comment by JoshuaBehrens** [comment]
Why do you need it, when it does not exist? I assume you want to refer to it in a relation. When you want to refer you can use the primary key. You can make up your own primary key with `Uuid::randomHex()` and use it in the relation directly without the need of loading the entry again.

Do you have a different use-case? I can think of so many different expectations on that behaviour right now :)

**Comment by Zerotask** [comment]
> Why do you need it, when it does not exist?

After I created it, it does exist.

From other ORMs it's usual practice that creating an entity will return the created entity.

> If the event returns an entity this is a hidden request for every creation regardless if the result is used or not.

If this is a technical limitation, then my feature request can be closed.

**Comment by mitelg** [comment]
please be aware that our data abstraction layer (DAL) should not be considered as full featured ORM. 
In ORMs it is easy to return the entity while creating it, because usually you use the entity object for this. 

Our DAL only creates objects while reading from the database. there is no way from the entity to database direction.

**Comment by Zerotask** [comment]
Alright. Then I will close this.

**Comment by JoshuaBehrens** [comment]
> Why do you need it, when it does not exist?

Was meant as an introduction to my assumption: why you need that entity. Probably for linking it to sth else

Just to clarify some confusion 😓
