### ISSUE TITLE
Shopware doesn't seem to work with AWS Elasticsearch Service (or Opendistro)

### ISSUE THREAD

**Issue by katzefudder** [shopware/platform#2034]
### PHP Version

7.4.22

### Shopware Version

6.4.3.1

### Expected behaviour

I've got Shopware6 to work with Elasticsearch running in Docker (https://hub.docker.com/_/elasticsearch)

### Actual behaviour

When it comes to be using AWS Elasticsearch Service **or** OpenDistro, I always end up with the following:
`./bin/console es:status

In StaticNoPingConnectionPool.php line 64:
                                        
  No alive nodes found in your cluster  
                                        

es:status
`

I can confirm Elasticsearch is running and accepting requests from the instance where Shopware is running. Config is also correct as far as I can tell.

`curl https://elastic:whatever@your-aws-es-host.eu-central-1.es.amazonaws.com
{
  "name" : "221258ba665d4c66a54ad535a94dfe7d",
  "cluster_name" : "xyz...",
  "cluster_uuid" : "uAHMm6Q_SXCu0M1VIB7p3Q",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-05-21T20:25:46.519671Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}`

Config .env for Shopware as follows:
`
...
SHOPWARE_ES_HOSTS='https://elastic:whatever@your-aws-es-host.eu-central-1.es.amazonaws.com'
SHOPWARE_ES_ENABLED="1"
SHOPWARE_ES_INDEXING_ENABLED="1"
...
`

### How to reproduce

Use opendistro and/or AWS Elasticsearch Service instead of plain/pure Elasticsearch.

**Comment by shyim** [comment]
Tested open distro and OpenSearch. No problem so far

```
dev@653ee4884d4b /var/www/html/sw6 $ ./bin/console es:status
+-----------------+-----------+
| Name            | Status    |
+-----------------+-----------+
| Cluster Status  | yellow    |
| Available Nodes | 1         |
| Indexing        | completed |
+-----------------+-----------+
```

{
  "name": "a7a349e0b372",
  "cluster_name": "docker-cluster",
  "cluster_uuid": "DPjmxTQpQCGkQH52WydRmw",
  "version": {
    "distribution": "opensearch",
    "number": "1.0.0",
    "build_type": "tar",
    "build_hash": "34550c5b17124ddc59458ef774f6b43a086522e3",
    "build_date": "2021-07-02T23:22:21.383695Z",
    "build_snapshot": false,
    "lucene_version": "8.8.2",
    "minimum_wire_compatibility_version": "6.8.0",
    "minimum_index_compatibility_version": "6.0.0-beta1"
  },
  "tagline": "The OpenSearch Project: https://opensearch.org/"
}

**Comment by katzefudder** [comment]
Interesting... what's the config for your container?
Have you ever gotten Shopware to work with AWS Elasticsearch Service?
The interesting part is: ES is responding via HTTP(S), so I guess no issues with that. I suppose the issue lies in my configuration. I wonder what needs to be set to make Shopware accepting Elasticsearch with authentication, but in different flavours (opendistro, opensearch) in my case.

**Comment by shyim** [comment]
Your URL example should work by default in the PHP client. https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/host-config.html . 

I would suggest you debug by own with an empty PHP project by just installing https://github.com/elastic/elasticsearch-php

**Comment by katzefudder** [comment]
It has been confirmed Shopware was not tested before with OpenSearch or the Elasticsearch Service on AWS.
Hence, an issue has been created just recently, following up a discussion on Slack:
https://issues.shopware.com/issues/NEXT-16942

**Comment by shyim** [comment]
Hey,

We currently don't test it on Gitlab automatically. Have you a local configuration set (best with Docker) for your Setup? I am pretty sure it is an configuration error and not an actual problem

**Comment by shyim** [comment]
Should be solved with https://github.com/shopware/platform/commit/d7db506d8b44264996efc169ddb3b0f3d0244c25#diff-7a31977ec68728f37d290e489c2fb803eac1fabd064f1c33a4fc0351beaac0e1

**Comment by katzefudder** [comment]
You added the option for not verifying the SSL cert, which is nice to have.
Still, Shopware doesn't work with the Elasticsearch Service on AWS, which was the reason to raise this ticket. Please have a look into the matters. In case you need more information, please get back to me any time.

**Comment by katzefudder** [comment]
In addition to that, the ticket on your end has recently been closed for being a duplicate -> https://issues.shopware.com/issues/NEXT-16942

**Comment by shyim** [comment]
We have another ticket NEXT-16636 which adds Opensearch to the CI currently located at the DevOps team.  From code it works

**Comment by katzefudder** [comment]
@shyim any progress to support OpenSearch and/or the AWS OpenSearch service?

**Comment by shyim** [comment]
Both work already

**Comment by thesec** [comment]
The root issue is still present. 6.4.18.1 and 19.0 do not connect to AWS, neither to an instance running Elasticsearch, nor to one running OpenSearch.

Would love to get into details to find a solution.

**Comment by shyim** [comment]
Both are working we are using AWS Opensearch in our Cloud product. Maybe check your network stuff

**Comment by thesec** [comment]
I very much doubt they are. Definitely not when set up as documented, definitely not for self-hosted.

Maybe lend a helping hand ... ?

But that'll not drive money to your "Cloud product".
