### ISSUE TITLE
Replace Hardcoded 'UTC' Timezones with Environment Variable (If possible)

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2038]
### Please describe the feature you would like to see implemented.

For example I want to calculate if a store is open to given opening hours serverside, there are always problems with the timezone.

I would have simple solution for it:
- Add a Environment Variable: SHOPWARE_TIMEZONE=Europe/Berlin
- Replace `'UTC'` with `getenv('SHOPWARE_TIMEZONE')`

I have seen, there are many hardcoded `'UTC'` in the Core, so it would be hard to build in a `system_config`?

Anyway, if the suggested solution works, it would be fine.

**Comment by shyim** [comment]
What does solve that for you? The system timezone is Berlin then and? 😄 It makes no difference to have Berlin / what ever timezone. The timezone needs on each time calculated / printed to the customer timezone / where it will be shown.

For the admin user, it will be controlled by https://github.com/shopware/platform/blob/trunk/src/Core/System/User/UserDefinition.php#L90

The storefront will be controlled by 
https://github.com/shopware/platform/blob/d6c853ca3b6b167d61d70e6329f4fcface5c5245/src/Storefront/Resources/app/storefront/src/utility/timezone/timezone.util.js#L15-L19

**Comment by dennishei** [comment]
It makes a difference if you want to analyze log files for example....
Example: prod-2021-09-06.log

**Comment by shyim** [comment]
@dennishei That should be a custom option of monolog https://github.com/symfony/monolog-bundle/issues/419

I am closing this as its inactive
