### ISSUE TITLE
Images in the product detail page gallery slider are not sorted

### ISSUE THREAD

**Issue by dagy304** [shopware/platform#2042]
### PHP Version

7.4.23

### Shopware Version

v6.4.3.1

### Expected behaviour

Images in the product detail page gallery slider should be sorted by the postion that is defined by the product in the administration.

### Actual behaviour

Images in the product detail page gallery slider are not sorted.

### How to reproduce

Add two Images to a Product in the administration and than check the order this images are show on the product detail page.
Then go back to the administration and change the order of the images with drag and drop, then save.
The Images are still in the old order.

I found the bug in this commit https://github.com/shopware/storefront/commit/d5abc1b5bb8d102046e148bd7d61fd1553320608. 
Since the sorting is no longer done with the criteria, the images are not sorted when the slides are added, only after.

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/004a49ee51cc4a9b2b1582b9054bb051cc7e60ce
