### ISSUE TITLE
Shopware is returning 404 for all the operation on frontend ui

### ISSUE THREAD

**Issue by rajat-garg** [shopware/platform#2044]
### PHP Version

7.4.23

### Shopware Version

5.7.2

### Expected behaviour

User should be able to create the test accounts/register and sign up, dummy products and place order/checkout on the machine.

### Actual behaviour

I have installed Shopware 57.2 on Ubuntu 18.04 machine. I am able to access the backend at http://10.1.10.104/shopware5/shopware.php/backend but when I visit the frontend at http://10.1.10.104/shopware5/shopware.php , I can see the DemoShop UI Page but when I click on any button/url like Sign Up or register it shows 404.
The Apache rewrite module is also enabled. 
Here is my .conf file:

```
<VirtualHost *:80>
    <Directory "/var/www/html/shopware5/">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/shopware5
    ServerName examples.com

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

The project is placed under /var/www/html/shopware5.
I am suspecting some issue on the redirection side. Can someone please take a look at this. 

### How to reproduce

I am facing the issue by following the normal installation method mentioned here: 
https://docs.shopware.com/en/shopware-5-en/first-steps/installing-shopware#shopware-one-file-installer

After following everything, I am facing this issue.

**Comment by mitelg** [comment]
at first, this is the place for Shopware 6 issues 😉

second, make sure that you configured the right host and path in your shop config. this should match the path to your Shopware installation
