### ISSUE TITLE
Autowiring and autoconfiguration

### ISSUE THREAD

**Issue by fpesch** [shopware/platform#2050]
### Please describe the feature you would like to see implemented.

Please make use of Symfony's [autowiring](https://symfony.com/doc/current/service_container.html#the-autowire-option) and [autoconfiguration](https://symfony.com/doc/current/service_container.html#the-autoconfigure-option).

It would make platform and bundle development [way easier](https://symfony.com/doc/current/service_container/autowiring.html) and custom tags are [also supported](https://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags).

**Comment by shyim** [comment]
You can do that alreadyhttps://github.com/FriendsOfShopware/FroshDevelopmentHelper/blob/0.3/src/Resources/config/services.xml#L13

**Comment by fpesch** [comment]
You can autowire most of your own services but there are issues when it comes to repository injections & automatic tagging. For example when trying to auto-tag an entity definition.

**Comment by shyim** [comment]
Repositories work already https://github.com/shopware/platform/commit/7bbf8da091bbc053e666ad10b109cc2ff31c0635

Feel free to create a pull request to add more auto-tagging.

**Comment by fpesch** [comment]
didn't know but looks great! thanks!
