### ISSUE TITLE
Error in generating demo data while running command "framework:demodata" in development installation

### ISSUE THREAD

**Issue by govindamandal** [shopware/platform#2052]
### PHP Version

7.4.23

### Shopware Version

6.4.3.1

### Expected behaviour

While installing Shopware 6.4.3.1 when it comes to generate demo data and images, it uses `bheller\ImagesGenerator\ImagesGeneratorProvider` in classes `Shopware\Core\Framework\Demodata\DemodataService` and `Shopware\Core\Framework\Demodata\Generator\MediaGenerator` which is not available in [`shopware/platform`](https://github.com/shopware/platform). 

### Actual behaviour

[`shopware/platform`](https://github.com/shopware/platform) should use class `Maltyxx\ImagesGenerator\ImagesGeneratorProvider` to generate demo data and images which is available.

Screenshot -

![image](https://user-images.githubusercontent.com/16445109/132129322-14d8da48-615d-4154-bbbd-5a792f7cc091.png)

![image](https://user-images.githubusercontent.com/16445109/132129339-8d0b1d36-0c3c-46c3-bf42-a14c8e96e9b6.png)

### How to reproduce

`Maltyxx\ImagesGenerator\ImagesGeneratorProvider` is available but not used and `bheller\ImagesGenerator\ImagesGeneratorProvider` used but not available. When try to install by command `composer require bheller/images-generator`, it shows conflict between these both package.

**Comment by thecaliskan** [comment]
Same problem on docker install.

**Comment by shyim** [comment]
Is fixed with 6.4.4.0
