### ISSUE TITLE
Theme config inheritance

### ISSUE THREAD

**Issue by PheysX** [shopware/platform#2055]
### PHP Version

7.4

### Shopware Version

6.4.4.0

### Expected behaviour

The saved `config_values` in database from my theme will be merged with the storefront fields.

### Actual behaviour

My theme without `base_config` fields shows all storefront theme `base_config` fields in administration. I can save it and it will be written in the `config_values` column in theme table. But if I reload the page, the ThemeService doesnt merge it, so i will see the storefront values forever.

When i copy the whole base_config in my theme, its working for me. I think here is the issue:
https://github.com/shopware/platform/blob/trunk/src/Storefront/Theme/ThemeService.php#L267

### How to reproduce

Add custom theme
Save config in administration
Reload

**Comment by shyim** [comment]
is fixed with https://github.com/shopware/platform/commit/7d9ce504e1b220d769de64c00b27e5188cbac02a
