### ISSUE TITLE
PriceFieldSerializer.php: $row['percentage'] - Undefined Index

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2056]
### PHP Version

7.4.21

### Shopware Version

6.4.4.0

### Expected behaviour

Immediately after the Update to 6.4.4.0 all Pages with Price Information have the same error message (dev-mode).
(Landingpages without prices still work)
I expect them top be visible as before the update. And guess the percentage-Display is something new.

### Actual behaviour

![grafik](https://user-images.githubusercontent.com/90198009/132223956-ec1549af-782e-471c-8529-94446dfe8274.png)

Wild guess:
Database-Migration for Shopware-Data from SW 6.4.3.0 to 6.4.4.0 missed out that one.

### How to reproduce

I Updated from 6.4.3.0 to 6.4.4.0 and tried to open a page with a price to display.
Listing or Detail-Page... does not matter as long as there are prices to display.

**Comment by shyim** [comment]
Did you run the migrations?

**Comment by jonas-sfx** [comment]
I did!

**Comment by shyim** [comment]
Thanks I could reproduce it.

Run ./bin/console dal:refresh:index to avoid this error.

We have already an ticket at our issue tracker, so I close this in favor of that https://issues.shopware.com/issues/NEXT-17072

**Comment by jonas-sfx** [comment]
Running  ./bin/console dal:refresh:index does not fix it.
Avoiding dev-mode by switching to prod mode is a workaround.
But i do not want to dispense with dev-mode altogether.
