### ISSUE TITLE
URL field in theme.json causes parse error

### ISSUE THREAD

**Issue by Vandaahl** [shopware/platform#2059]
### PHP Version

7.4

### Shopware Version

6.4.4.0

### Expected behaviour

When I have a URL field in my theme.json file, my theme should compile successfully.

### Actual behaviour

Once a URL is entered in the URL field of my theme settings, the theme can't be compiled anymore due to a parse error at /app/vendor/shopware/storefront/Theme/ThemeCompiler.php:201

### How to reproduce

Add a URL field to your theme.json file, like so:

`"terms-url": {
        "label": {
          "en-GB": "Link to external terms/conditions page"
        },
        "type": "url",
        "value": "",
        "editable": true,
        "block": "urls",
        "fullWidth": true
      }`

Then enter a URL in your theme settings and hit save. A parse error occurs.

**Comment by shyim** [comment]
Add `"scss": false` to the element.

https://github.com/shopware/platform/blob/4c8f81606252c8f6aedc30b9bdb1631c88c02334/src/Storefront/Theme/ThemeCompiler.php#L272
