### ISSUE TITLE
Add Demo Mode

### ISSUE THREAD

**Issue by amenk** [shopware/platform#2067]
We propose to add a demo mode, to indicated that a copy or a Shopware 6 shop is not a "real shop", but for testing / demo purposes.

This demo mode could be activated in the `.env` file by adding

    DEMO=1

When this is set, there would be a clear indicator in the store front / admin panel, to indicate it is s demo

Text proposal

"Dies ist eine Demo/Test Installation. Bestellungen in diesem Shop werden nicht ausgeführt."

"This is a Demo/Test installation. Orders in this shop are not fullfilled."

Design propsal:

![image](https://user-images.githubusercontent.com/1087128/132940816-4fe18734-b303-4ca7-89e1-eec697dbf171.png)

## Clean indication in testing

Users / testers of the test installation can easily see that they are on a demo site and not confuse it with the production installation or vice versa.

## Fix of license check problems

As written on https://docs.shopware.com/en/shopware-6-en/tutorials-and-faq/tipsforusingtheadmin/create-test-environment?category=shopware-6-en/tutorials-and-faq, problems with license checks can appear, when creating test environments.

![ksnip_tmp_sZVSfZ](https://user-images.githubusercontent.com/1087128/132940694-273f15d4-c884-4912-8276-70eede85879b.png)

In a professional and semi-professional development of a Shopware shop it is very important to use one or more test environments. This should work smoothly despite the legit need for checking licenses of paid extensions.

If we add the demo mode, the license warning / domain verification could be simply disabled for such demo installations while still being active for the production installation.

So those messages do not have to appear again and again on demo installations:

![image](https://user-images.githubusercontent.com/1087128/132941077-7078a833-dda7-469d-87bf-091b1b422f60.png)

# Next steps

We would be happy to make a pull requests for this, that we post it on GitHub. But as it touches license politics we will wait for the feedback from the Shopware team.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by amenk** [comment]
* the "Licensing issue" became much better, and appears only when apps are used
* the DEMO Banner is already implemented in the new staging mode

![image](https://github.com/user-attachments/assets/da0c2e13-4e60-4e9d-87ca-ba5958051f16)

https://developer.shopware.com/docs/guides/hosting/configurations/shopware/staging.html

so no need for excuses - it's all fine already
