### ISSUE TITLE
Sections can't be moved in Shopping Experience since 6.4.4.0

### ISSUE THREAD

**Issue by Watschman** [shopware/platform#2069]
### PHP Version

7.4.23

### Shopware Version

6.4.4.1

### Expected behaviour

When moving a section via the Navigator in a shopping experience. The section gets moved to the new position and stays there after save.

### Actual behaviour

When Moving a section via the Navigator an "auto save" gets initiated. The new positions are not getting saved and are reset to there previous state. This makes changing things rather tiresome.

### How to reproduce

1. Install a fresh Shopware 6.4.4.0 or later instance
2. go into the shopping experience
3. click on any shopping experience which is editable
4. try to move existing sections via the navigator or add a new one and try to move it afterwards.
5. observe problem

I have debugged the issue a bit and was able to pinpoint the problem in the https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/module/sw-cms/page/sw-cms-detail/index.js file.

The issue is that onSave gets called without recalculating the new section positions. I found that adding `this.onPageUpdate()` at the beginning of the onSave function fixes the issue.

**Comment by marcelbrode** [comment]
Will be done via https://issues.shopware.com/issues/NEXT-16457
