### ISSUE TITLE
Very slow href-lang feature

### ISSUE THREAD

**Issue by Isengo1989** [shopware/platform#2071]
### PHP Version

7.4.23

### Shopware Version

6.4.4.1

### Expected behaviour

A seo url should load in milliseconds, since it is requested quite often.

### Actual behaviour

The query should not take 600-1000ms when only 1-2 languages are used and 250-300k seo urls entries are in the seo_url table. This is slowing down the product detail page by a lot (link to APM [screenshot](https://ibb.co/vB97spx))

`
SELECT `seo_url`.`id` as `seo_url.id`, `seo_url`.`sales_channel_id` as `seo_url.salesChannelId`, `seo_url`.`language_id` as `seo_url.languageId`, `seo_url`.`foreign_key` as `seo_url.foreignKey`, `seo_url`.`route_name` as `seo_url.routeName`, `seo_url`.`path_info` as `seo_url.pathInfo`, `seo_url`.`seo_path_info` as `seo_url.seoPathInfo`, `seo_url`.`is_canonical` as `seo_url.isCanonical`, `seo_url`.`is_modified` as `seo_url.isModified`, `seo_url`.`is_deleted` as `seo_url.isDeleted`, `seo_url`.`custom_fields` as `seo_url.customFields`, `seo_url`.`created_at` as `seo_url.createdAt`, `seo_url`.`updated_at` as `seo_url.updatedAt`, `seo_url.language`.`id` as `seo_url.language.id`, `seo_url.language`.`parent_id` as `seo_url.language.parentId`, `seo_url.language`.`locale_id` as `seo_url.language.localeId`, `seo_url.language`.`translation_code_id` as `seo_url.language.translationCodeId`, `seo_url.language`.`name` as `seo_url.language.name`, `seo_url.language`.`custom_fields` as `seo_url.language.customFields`, `seo_url.language`.`created_at` as `seo_url.language.createdAt`, `seo_url.language`.`updated_at` as `seo_url.language.updatedAt`, `seo_url.language.locale`.`id` as `seo_url.language.locale.id`, `seo_url.language.locale`.`code` as `seo_url.language.locale.code`, `seo_url.language.locale`.`created_at` as `seo_url.language.locale.createdAt`, `seo_url.language.locale`.`updated_at` as `seo_url.language.locale.updatedAt`, `seo_url.language.locale.translation.name`, COALESCE(`seo_url.language.locale.translation.name`,`seo_url.language.locale.translation.name`) as `seo_url.language.locale.name`, `seo_url.language.locale.translation.territory`, COALESCE(`seo_url.language.locale.translation.territory`,`seo_url.language.locale.translation.territory`) as `seo_url.language.locale.territory`, `seo_url.language.locale.translation.customFields`, COALESCE(`seo_url.language.locale.translation.customFields`,`seo_url.language.locale.translation.customFields`) as `seo_url.language.locale.customFields`, `seo_url.language.locale.translation.createdAt`, `seo_url.language.locale.translation.updatedAt`, `seo_url.language.locale.translation.localeId`, `seo_url.language.locale.translation.languageId` FROM `seo_url` LEFT JOIN `language` `seo_url.language` ON `seo_url`.`language_id` = `seo_url.language`.`id` LEFT JOIN `locale` `seo_url.language.locale` ON `seo_url.language`.`locale_id` = `seo_url.language.locale`.`id` LEFT JOIN (SELECT `seo_url.language.locale.translation`.locale_id, `seo_url.language.locale.translation`.name as `seo_url.language.locale.translation.name`, `seo_url.language.locale.translation`.territory as `seo_url.language.locale.translation.territory`, `seo_url.language.locale.translation`.custom_fields as `seo_url.language.locale.translation.customFields`, `seo_url.language.locale.translation`.created_at as `seo_url.language.locale.translation.createdAt`, `seo_url.language.locale.translation`.updated_at as `seo_url.language.locale.translation.updatedAt`, `seo_url.language.locale.translation`.locale_id as `seo_url.language.locale.translation.localeId`, `seo_url.language.locale.translation`.language_id as `seo_url.language.locale.translation.languageId` FROM `locale_translation` `seo_url.language.locale.translation` WHERE `seo_url.language.locale.translation`.language_id = ?) `seo_url.language.locale.locale_translation` ON `seo_url.language.locale.locale_translation`.`locale_id` = `seo_url.language.locale`.`id` WHERE (`seo_url`.`is_canonical` = ? AND `seo_url`.`path_info` = ? AND `seo_url`.`sales_channel_id` = ?)
`

### How to reproduce

Add +100k seo Urls in the table and see how the timing on the PDP increases by every entry. 

The problem is probably in vendor/shopware/core/Content/Seo/HreflangLoader.php

---

Table | Hint
-- | --
**seo_url** | The table was retrieved with this index: fk.seo_url.sales_channel_idYou can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.Approximately 192319 rows of this table were scanned.

**seo_url.language** | This table was retrieved with a full table scan, which is often quite bad for performance, unless you only retrieve a few rows.The table was retrieved with this index: No index was used in this part of the query.You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.Approximately 3 rows of this table were scanned.

**seo_url.language.locale** | The table was retrieved with this index: PRIMARYYou can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.Approximately 1 row of this table was scanned.

**seo_url.language.locale.translation** | The table was retrieved with this index: PRIMARYYou can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.Approximately 1 row of this table was scanned.

**Comment by shyim** [comment]
We addressed that already in core
