### ISSUE TITLE
override sw-extension-card-base template not working

### ISSUE THREAD

**Issue by rklak** [shopware/platform#2077]
### PHP Version

7.4

### Shopware Version

6.4.3.0

### Expected behaviour

Block is overriten by custom template

### Actual behaviour

Block is not rendered in browser properly

## Test files
Create simple plugin that extends **sw-extension-card-base** with simple template. Main files:

**sw-extension-card-base/index.js**
```
import template from './template.html.twig';

Shopware.Component.override('sw-extension-card-base', {
    template
});
```

**sw-extension-card-base/template.html.twig**
```
{% block sw_extension_card_base %}
    <b>Override</b>
{% endblock %}
```

**main.js**
```
import './extension/sw-extension-card-base';
```

## Debugging
When debug the new plugin in:

**vendor/shopware/administration/Resources/app/administration/src/core/factory/component.factory.js:309**
```
    /**
     * Get the final template result including all overrides or extensions.
     */
    config.template = getComponentTemplate(componentName);

    if (componentName === 'sw-extension-card-base') {
        console.log('final template', config.template);
    }
```

effect of console.log in developer tools is:
```
final template     <b>Override</b>
```
**but in browser html is not ovverriden.**

so something is not refreshed internally? Please verify this behaviour. 

## Guess
I see that component **sw-extension-card-base** is marked private - maybe thats the case?
```
/**
 * @private
 */
Component.register('sw-extension-card-base', {
    template,

    inheritAttrs: false,
```

**Comment by nielsVoogt** [comment]
I also ran into this today doing a clean install, `{% sw_extends '...' %}` inside a theme are overruled by the templates from the platform. Checked out release 6.4.4.0 and it doesn't have this issue.

**Comment by rklak** [comment]
6.4.4.1 - problem still exists

**Comment by shyim** [comment]
We explicitly want that nobody extends the extension manager / extension store. That's the reason why it's set to private
