### ISSUE TITLE
CustomField Sorting criteria dropdown only shows 25 customField options

### ISSUE THREAD

**Issue by Gugiman** [shopware/platform#2092]
### PHP Version

php 8

### Shopware Version

6.4.3.1

### Expected behaviour

When select customField on "Sorting criteria" i suspect that i can choose from all article customFields.

### Actual behaviour

There are only 25 shown with no possibility to load more.
Get Ajax Request is always set with a limit of 25

### How to reproduce

Create several (like 30) customFields with relation to products
Go to Settings -> Products -> Scroll down and add a new Sorting criteria.
Choose Custom Field
Look at the list.

**Comment by shyim** [comment]
Set the Criteria to 500 limit, until https://github.com/shopware/platform/pull/2076 is fixed

**Comment by maximilianruesch** [comment]
I just tested this and it seems like this issue is no longer existing in v6.4.5.1. A request to load more custom fields is sent each time you reach the bottom of the scroll, each with a set limit of 25 but a (working) pagination.
