### ISSUE TITLE
Product Detail Page - Images will not sorted as in backend

### ISSUE THREAD

**Issue by Fantic666** [shopware/platform#2106]
### PHP Version

7.4.23

### Shopware Version

6.4.5.0

### Expected behaviour

Product Image should be sorted as in backend 

### Actual behaviour

Images wont be sorted as in the Database product_media.position
Not sure - but Images seems to be sorted with product_media.id

### How to reproduce

Add more pictures to one product, change picture sorting in backend, watch frontend product

**Comment by BlackScorp** [comment]
Cannot reproduce the error with default theme, maybe your theme is broken?

**Comment by shyim** [comment]
is fixed with https://github.com/shopware/platform/commit/004a49ee51cc4a9b2b1582b9054bb051cc7e60ce
