### ISSUE TITLE
Order-ID ist not present in generated invoice pdf when using the API

### ISSUE THREAD

**Issue by azngeek** [shopware/platform#2113]
### PHP Version

 7.4.15

### Shopware Version

6.4.4.1

### Expected behaviour

If using the API to create an invoice, then the generated invoice pdf must have the given document number in the pdf.

`
{{endpoint}}/api/_action/order/<uuid>/document/invoice?fileType=pdf
{
    "config": {
        "documentNumber": "1000"
    }
}
`

The relevant part of the PDF should be like this:

![image](https://user-images.githubusercontent.com/213429/136565861-19c53203-9b95-457f-814b-82ad6cf5cabd.png)

### Actual behaviour

The orderId ist not present in the pdf. 

![image](https://user-images.githubusercontent.com/213429/136565982-68274c1e-6da6-4d86-a33a-a0503591ed64.png)

### How to reproduce

1. create an order
2. For this order create an invoice using the API-Endpoint {{endpoint}}/api/_action/order/<uuid>/document/invoice?fileType=pdf
3. Open the PDF and the orderid will not be present

**Comment by shyim** [comment]
As it's working in the Administration look into the API call of the Admin
