### ISSUE TITLE
system:setup add flag to pass mailer URL

### ISSUE THREAD

**Issue by Zerotask** [shopware/platform#2115]
### Please describe the feature you would like to see implemented.

Similar to the flag `--database-url`, it would be great to have a flag `--mailer-url`.

**Comment by shyim** [comment]
is already there https://github.com/shopware/platform/blob/trunk/src/Core/Maintenance/System/Command/SystemSetupCommand.php#L59

**Comment by Zerotask** [comment]
Okay, but unfortunately not for the 6.3.x version.
