### ISSUE TITLE
Active address is allowed to be deleted - via store-api

### ISSUE THREAD

**Issue by mkucmus** [shopware/platform#2117]
### PHP Version

7.4.23

### Shopware Version

v6.4.4.1

### Expected behaviour

possible solutions
1. Active address should not be deleted -> attempt to delete should end up with http error code (400?)
2. Active address (set via patch context) should not be set as default one to avoid errors on logging in
3. after the active address is removed, the first next address from address collection should be set as active one.

### Actual behaviour

The problem comes when I set an active address on the checkout step, and some when later I delete this address on "My Account", if I do this then this will break the API context and the user will not be able to login anymore.

### How to reproduce

1. set the active shipping address - PATCH /context
2. delete address via DELETE /store-api/account/address/${addressId}
3. log out
4. try to log in
you will see error like on log-in:
```
Argument 1 passed to Shopware\Core\Checkout\Customer\CustomerEntity::setActiveBillingAddress() must be an instance of Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity, null given, called in /app/platform/src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php on line 478
```
![image](https://user-images.githubusercontent.com/5596960/136914114-3c86c3ef-456b-4260-be64-b196bc5dca47.png)

related: https://github.com/vuestorefront/shopware-pwa/issues/1348

**Comment by drjamesj** [comment]
Hi @mkucmus @shyim I would like to resolve this issue - proceeding with option 1 in the possible solutions listed above. Would you mind assigning me this if you approve of this approach?

**Comment by shyim** [comment]
Is fixed already
