### ISSUE TITLE
SalesChannelEntity and -Definition missmatch

### ISSUE THREAD

**Issue by michnhokn** [shopware/platform#2118]
### PHP Version

7.4

### Shopware Version

6.4.5

### Expected behaviour

`$salesChannel->getMaintenanceIpWhitelist()` returns a list of ip addresses.

### Actual behaviour

The type of the "maintenanceIpWhitelist" property is a string in the SalesChannelEntity.
But according to the definition it is an array, so a type mismatch exception is thrown as soon as you try to read or set the IpAddresses with the entity.

### How to reproduce

`$salesChannel->getMaintenanceIpWhitelist()`

**Comment by michnhokn** [comment]
Entity
![image](https://user-images.githubusercontent.com/38752255/136914580-c435a7f8-1a1a-4e29-ba58-8432b702c36b.png)

Definition
![image](https://user-images.githubusercontent.com/38752255/136914665-3c3df9d8-339d-44d6-9988-6a552055b8d6.png)

**Comment by shyim** [comment]
Hey,
can you make a pull request? :)

**Comment by michnhokn** [comment]
Perfect. Thank you @pogster

**Comment by shyim** [comment]
I am closing this then in favor of the PR
