### ISSUE TITLE
getCriteria in ProductStreamUpdater does not guard against empty array

### ISSUE THREAD

**Issue by Xarno** [shopware/platform#2154]
### PHP Version

8.0.8

### Shopware Version

6.4.5.1

### Expected behaviour

Function getCriteria in ProductStream should not add an empty Array as Argument for EqualsAnyFilter.

### Actual behaviour

It can add empty array. And that leads to broken searches, because then the Criteria will only lead to empty results.
Yes the shopware code itself does not look like it does that. But still … it's a bug. And my plugin which incorporates that function surfaced that bug.

### How to reproduce

Current Code: 
shopware/platform/src/Core/Content/Product/DataAbstractionLayer/ProductStreamUpdater.php Line 187
```php
private function getCriteria(array $filters, ?array $ids = null): ?Criteria
    {
        $exception = new SearchRequestException();

        $parsed = [];
        foreach ($filters as $filter) {
            $parsed[] = QueryStringParser::fromArray($this->productDefinition, $filter, $exception, '');
        }

        if (empty($filters)) {
            return null;
        }

        $criteria = new Criteria();
        $criteria->addFilter(...$parsed);

        if ($ids !== null) {
            $criteria->addFilter(new EqualsAnyFilter('id', $ids));
        }

        return $criteria;
    }
```

Suggested Fix:

```php
private function getCriteria(array $filters, ?array $ids = null): ?Criteria
    {
        $exception = new SearchRequestException();

        $parsed = [];
        foreach ($filters as $filter) {
            $parsed[] = QueryStringParser::fromArray($this->productDefinition, $filter, $exception, '');
        }

        if (empty($filters)) {
            return null;
        }

        $criteria = new Criteria();
        $criteria->addFilter(...$parsed);

        if ($ids !== null && count($ids) > 0) {
            $criteria->addFilter(new EqualsAnyFilter('id', $ids));
        }

        return $criteria;
    }
```

**Comment by namangirdhar16** [comment]
Hey @mitelg @Xarno i would like to work on this issue, do assign this to me.

**Comment by namangirdhar16** [comment]
@mitelg is this hacktoberfest-accepted? if yes, do add the label.

**Comment by namangirdhar16** [comment]
@mitelg when i try to clone the forked repo, i got some unnecessary additions and deletions in the files, while making the pull request where it should be only one file that has to be changed, in my case it shows 137 files changed.
Although the change doesnot cause any problem as seems to be but still i would like to hear you about this.

Here are some screenshots to get the context:
![image](https://user-images.githubusercontent.com/64246118/139567260-433b4761-bf88-4ed7-8dc9-938d10b9c622.png)
![image](https://user-images.githubusercontent.com/64246118/139567269-5acd207b-de31-4b32-a954-1b0e4b837744.png)
![image](https://user-images.githubusercontent.com/64246118/139567273-b07ef95c-433a-48dc-a89a-1448a2183bae.png)
![image](https://user-images.githubusercontent.com/64246118/139567283-babde8d3-a3d0-42d0-bd5a-dfcbeadb0456.png)
![image](https://user-images.githubusercontent.com/64246118/139567286-675ec0d4-0d21-4da3-b4d7-77182b3c3931.png)
![image](https://user-images.githubusercontent.com/64246118/139567292-11ce4284-150a-4723-bd23-6f4b923df8d3.png)
![image](https://user-images.githubusercontent.com/64246118/139567298-9ea53274-6743-4ada-9c1b-988720d89334.png)

**Comment by mitelg** [comment]
@pweyck @keulinho do you know how this could happen?

**Comment by Xarno** [comment]
Some of your screenshots are file permission changes. And the svg looks like line ending changes.
Use a full diff tool to see line ending changes. KDiff3 for example.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
