### ISSUE TITLE
Placing Orders containing promotions becomes EXTREMELY slow, when the number of orders increases

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/platform#2155]
### PHP Version

7.4

### Shopware Version

6.4.5

### Expected behaviour

I expect the promotion information to be stored in such a way, that update processes can be performed with adequate performance, even if the order count is high.

### Actual behaviour

The current implementation of the PromotionRedemptionUpdater is extremely slow, when the order count is high. Unfortunately the PromotionRedemptionUpdater isn't only executed by a background task, but DURING order placement. An order  that has a promotion in it can be delayed (depending on the number of orders in the system) by **tens of seconds or even minutes**. 

The reason for the weak performance is the following query:
```
SELECT JSON_UNQUOTE(JSON_EXTRACT(`order_line_item`.`payload`, '$.promotionId')) as promotion_id,
                       COUNT(DISTINCT order_line_item.id) as total,
                       LOWER(HEX(order_customer.customer_id)) as customer_id
                FROM order_line_item
                INNER JOIN order_customer
                    ON order_customer.order_id = order_line_item.order_id
                    AND order_customer.version_id = order_line_item.version_id
                WHERE order_line_item.type = :type
                AND JSON_UNQUOTE(JSON_EXTRACT(`order_line_item`.`payload`, "$.promotionId")) IN (:ids)
                AND order_line_item.version_id = :versionId
                GROUP BY JSON_UNQUOTE(JSON_EXTRACT(`order_line_item`.`payload`, "$.promotionId")), order_customer.customer_id
```
The fact that we are searching the JSON payload of all order line items during the order placement period is something that should be fixed, before version 6.5 comes out IMHO.

**Also:** 
It is concerning, that Shopware does not catch these performance issues before release. While the unit test suite and the e2e test suite of Shopware look good, it's evident that Shopware does not test it's features against systems with large datasets. 
See:
https://issues.shopware.com/issues/NEXT-15411
https://issues.shopware.com/issues/NEXT-17359
https://issues.shopware.com/issues/NEXT-12818

### How to reproduce

See actual behavior...

**Comment by 0x4** [comment]
We had the same issue on a shop with 3M orders - where the query on BF caused a lot of trouble...

Our fix:

In newer mysql vesions it's possible to add an index on JSON content

`ALTER TABLE order_line_item ADD INDEX promotion_id ( (JSON_VALUE(payload, '$.promotionId' RETURNING CHAR(32))) );
`

AND using JSON_VALUE in the SQL with the correct fieldtype:

SELECT JSON_VALUE(payload, '$.promotionId' RETURNING CHAR(32)) as promotion_id,
                       COUNT(DISTINCT order_line_item.id) as total,
                       LOWER(HEX(order_customer.customer_id)) as customer_id
                FROM order_line_item
                INNER JOIN order_customer
                    ON order_customer.order_id = order_line_item.order_id
                    AND order_customer.version_id = order_line_item.version_id
                WHERE order_line_item.type = :type
                AND JSON_VALUE(payload, '$.promotionId' RETURNING CHAR(32)) IN (:ids)
                AND order_line_item.version_id = :versionId
                GROUP BY JSON_VALUE(payload, '$.promotionId' RETURNING CHAR(32)), order_customer.customer_id

then the index can be used and everything is a lot faster.

But: if you have promotions (like us) that are used 10000 times - and the above query still returns every line - now in about 4s instead of 80+s 

so there is still a structural problem here in my opinion

**Comment by AlexBachmann** [comment]
Just to share our workaround to this issue:
We decorated the PromotionRedemptionUpdater and pushed the update process to the message queue and out of the main thread. This way, the long query do not affect the order placement process anymore.

**Comment by askat86** [comment]
Hi all, we are facing this issue two days before the new shop should launch (with old SW5 DB with > 2M entries in order_line_item.

Especially @0x4 do you have a developer who could help us? (we are using mariadb and the alter table query is probably not possible)

**Comment by 0x4** [comment]
@askat86 we're still having some trouble with the performance... the solution of @AlexBachmann is the best I think. That logic can run async.

if you don't use promotions that are limited to X times per user as a quick fix you could also deactivate this function completely - as far as I understand the logic of this function is to count the usage of the promotions global and per user.

class Shopware\Core\Checkout\Promotion\DataAbstractionLayer\PromotionRedemptionUpdater (https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php) 

and add a 

`return;`

in the first line of the update function of this class (line 40)

**Comment by AlexBachmann** [comment]
Let me share our solution. I think it's self explainatory: 

```
<?php

namespace XXXXXXXX\Core\Checkout\Promotion;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Doctrine\DBAL\Connection;
use Shopware\Core\Checkout\Promotion\DataAbstractionLayer\PromotionRedemptionUpdater;
use Shopware\Core\Framework\Context;
use Symfony\Component\Messenger\MessageBusInterface;

class DecoratedPromotionRedemptionUpdater extends PromotionRedemptionUpdater implements EventSubscriberInterface
{
    private MessageBusInterface $messageBus;

    public function __construct(
        MessageBusInterface $messageBus,
        Connection $connection
    ) {
        $this->messageBus = $messageBus;
        parent::__construct($connection);
    }

    public function update(array $ids, Context $context): void
    {
        foreach ($ids as $id) {
            $message = new PromotionRedemptionUpdateMessage();
            // Since the query can be very slow, the promotions should be processed one by one
            $message->setPromotionIds([$id]);
            $message->setContext($context);
            $this->messageBus->dispatch($message);
        }
    }

    public function doUpdate(array $ids, Context $context): void
    {
        parent::update($ids, $context);
    }
}
```

```
<?php

namespace XXXXXXXX\Core\Checkout\Promotion;

use Shopware\Core\Framework\Context;

class PromotionRedemptionUpdateMessage
{
    protected array $promotionIds;
    protected Context $context;

    /**
     * @return array
     */
    public function getPromotionIds(): array
    {
        return $this->promotionIds;
    }

    /**
     * @param array $promotionIds
     */
    public function setPromotionIds(array $promotionIds): void
    {
        $this->promotionIds = $promotionIds;
    }

    /**
     * @return Context
     */
    public function getContext(): Context
    {
        return $this->context;
    }

    /**
     * @param Context $context
     */
    public function setContext(Context $context): void
    {
        $this->context = $context;
    }
}
``` 

```
<?php

namespace XXXXXXXX\Core\Checkout\Promotion;

use Shopware\Core\Checkout\Promotion\DataAbstractionLayer\PromotionRedemptionUpdater;
use Shopware\Core\Framework\MessageQueue\Handler\AbstractMessageHandler;

class PromotionRedemptionUpdateMessageHandler extends AbstractMessageHandler
{
    private PromotionRedemptionUpdater $promotionRedemptionUpdater;

    public function __construct(
        DecoratedPromotionRedemptionUpdater $promotionRedemptionUpdater
    ) {
        $this->promotionRedemptionUpdater = $promotionRedemptionUpdater;
    }

    public static function getHandledMessages(): iterable
    {
        return [PromotionRedemptionUpdateMessage::class];
    }

    /**
     * @param PromotionRedemptionUpdateMessage $message
     */
    public function handle($message): void
    {
        $this->promotionRedemptionUpdater->doUpdate($message->getPromotionIds(), $message->getContext());
    }
}
```

**Comment by askat86** [comment]
Hey you two, thanks for sharing! I consider our options, but if you still have performance issues 0x4 we would need both solutions, because one process of add-promotion requires 33-40s and is running 3 times to redeem one voucher. 
![promotion-add](https://user-images.githubusercontent.com/12670660/144387191-e037c4f9-0286-42d2-b19c-a08449a8d4a7.png)

The problem in the async process is, that our machines are just decent VM machines with 4-8 cores and 4-8 GB of RAM. 
Just one execution is using one thread with 100% for the time and consumes up to 4 GB of RAM until it's done. 

If 3-4 customers would start this process in parallel i would except the server to crash or at least slow down heavily. 
 
@AlexBachmann Did you just overwrite the shopware files on the server or did you overload them with a plugin?
@0x4 do you know if your SQL logic would be possible on a mariaDB (v10.3.31)? if yes, i would start searching for solution, if not i would have to consider switching to mysql 8+ but then we would need to do a lot of work again or dump the database and i doubt that this would work :/

**Comment by AlexBachmann** [comment]
No, we decorated the services in a plugin. https://symfony.com/doc/current/service_container/service_decoration.html

Also, the memory issue is real. That's why we are processing the promotions one by one (each promotion dispatches an update message). The message queue triggers these messages one by one. This should be a very memory efficient solution.

**Comment by askat86** [comment]
Ok perfect, that sounds good. Cause other work i won't have the time to try your solution in the next days, but probably until wednesday. Keep you updated and thanks for your help!

**Comment by askat86** [comment]
Hey, sorry for the late update. I propably fail with the activation in the services.xml in the plugin with the decorated updater, but the behaviour of our system doesn't changed at all. 
Unfortunately i don't have much time left until christmas, so i will start with a solution next year. 
My plan is to exten the table with a column just for the promotionId and overwrite the update method in total and never look back. If the plugin is working (could be possible around jan 15th) i will update and share it with you :)

**Comment by askat86** [comment]
Hey there, because the bug report got a note for the next major release (https://issues.shopware.com/issues/NEXT-17359) i would wait with an own fix until they had their try. dependen on their last releases the next major update should come in the next 1-3 month. Thanks for all your help and time!

**Comment by RafaelKr** [comment]
The Shopware Issue Tracker issue https://issues.shopware.com/issues/NEXT-17359 is fixed now.
Is this still an issue with v6.4.11.0+?

**Comment by AlexBachmann** [comment]
No, this issue has been resolved.

Rafael Kraut ***@***.***> schrieb am Fr., 8. Juli 2022, 14:22:

**Comment by shyim** [comment]
We extracted that JSON data into a own column
