### ISSUE TITLE
API Missing mapping for product-category aggregate 

### ISSUE THREAD

**Issue by kingschnulli** [shopware/platform#2157]
### Please describe the feature you would like to see implemented.

Currently there is no Entity/Collection/Hydrator for [ProductCategoryDefinition](https://github.com/shopware/platform/blob/4cd60e944ea279cccf3c4c68cc0a2bf220047e16/src/Core/Content/Product/Aggregate/ProductCategory/ProductCategoryDefinition.php).

This makes it impossible to call admin api endpoint 

`/api/search/product-category`

as this leads to `FRAMEWORK__MAPPING_ENTITY_DEFINITION_CLASSES` error 

Is there a reason for this? e.g. `/api/search/product-media` works fine

**Comment by keulinho** [comment]
That is expected as the `ProductCategoryDefinition` is a `MappingDefinition`, meaning it is only there to establish the N:M association between the `Product`- and the `Category`-Entities. A `MappingDefinition` consists only of FKs to the two Definitions that it maps together and cannot be used standalone therefore it has no API-Endpoints.

The `ProductMediaDefinition` is a little bit of an exception, as it is no `MappingDefinition`, it is a Definition of it's own with an own `id` and an additional `position` field. Also note that there is no direct N:M association from `Product` to `Media`, rather they are designed to have a 1:N association to the `ProductMediaDefinition`. 

That's the reason why `ProductMediaDefinition` has standalone API endpoints, but the `ProductCategoryDefinition` does not.



Can you elaborate your use case a bit? As i think that what you want to accomplish can pretty sure be done by an search on the `Product` or `Category` entity itself.

**Comment by kingschnulli** [comment]
Use case is to sync (or resync) all product to category relationships with our ERP system - I know this is nothing that is used very often but comes in handy in dev or test environments. I can not come up with a good /api/search/* query that will yield all product to category relationships in a performant way.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
