### ISSUE TITLE
License file missing from individual packages like shopware/core?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2163]
### PHP Version

7.4

### Shopware Version

6.4.5.1

### Expected behaviour

In case one installs the packages manually like is done with the production template etc. the license file is not part of the packages like shopware/core. It is probably necessary to duplicate the license file accordingly, maybe symlink it (though I don't think that will work correctly) or add it manually during package creation.

As the template itself is just a template and therefore the license file might not be kept there, it should definitely be part of the dependencies. Also one doesn't need to start with the template at all.

### Actual behaviour

Missing LICENSE file in dependencies like https://github.com/shopware/core

### How to reproduce

Checkout production template and do a composer install and check the vendor/shopware/* dependency folders.

**Comment by keulinho** [comment]
Was fixed with this commit: https://github.com/shopware/platform/commit/3c45e62e5441a82292a141722dea1f85e1663a8c
