### ISSUE TITLE
package-lock.json files should use version 2 as current node.js LTS is ^16 with NPM 8.1

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2166]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

As the current node LTS version is ^16.12 and in the latest version npm is pre-installed with ^8.1, and npm ^7 uses package-lock.json in version 2, so therefore the current package-lock.json of shopware should also use version 2.

Probably something for Shopware 6.5 ?

### Actual behaviour

See description

### How to reproduce

See description

**Comment by NilsEvers** [comment]
Maybe submit it to https://github.com/shopware/proposal  so it won't be forgotten.

**Comment by shyim** [comment]
We bumped up already to node 16
