### ISSUE TITLE
system:setup command does not use default value provided by option in interactive mode.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2169]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

The current `system:setup` command uses `yes` as default value even if the option `blue-green` or the env variable `BLUE_GREEN_DEPLOYMENT` has specified to use a different default value specified.

Yes, mostly those are used in non interactive mode but for a setup documentation it is helpful to provide some default values but this one is ignored.

### Actual behaviour

Use the option value as default value

### How to reproduce

bin/console system:setup --blue-green=0

**Comment by shyim** [comment]
fixed with https://github.com/shopware/platform/commit/f4a5af2a5925cebad3fe7219b3b35af9505c3e93
