### ISSUE TITLE
Admin Api - Allow _sync upserts to reset/overwrite relations

### ISSUE THREAD

**Issue by kingschnulli** [shopware/platform#2172]
### Please describe the feature you would like to see implemented.

Currently there is no way to overwrite or reset relations when using the batch/_sync api endpoint. This will always force to first delete all relations, then write them again - this also means you will have to either store or recieve all relationship ids before resetting them.

I would suggest having some sort of special bulk action that deletes all relationships of some kind like:

```
    "delete-product-categories": {
        "entity": "product_category",
        "action": "delete-all",
        "payload": [
            {
                "productId": "000bba26e2044b98a3ee4a84b03f9551"
            },
            { 
                "productId": "5deed0c33b2a4866a6b2c88fa215561c"
            }
        ]
    }
```
 
This would need only one part of the related primary key, not all of them.

Even better would be some kind of flexible interface to define the keys to resolve a relation when running any kind of bulk operation like:

```
    "delete-products-containing-name-acme": {
        "entity": "product",
        "action": "delete",
        "filter": [
            {
                "type": "contains",
                "field": "name",
                "value": "acme"
            }
        ]
    },
    "set-some-fields-for-all-products-containing-name-acme": {
      "entity": "product",
      "action": "upsert",
      "payload": {
           "field": "value",
      },
      "filter": [
        {
            "type": "contains",
            "field": "name",
            "value": "acme"
        }
     ]
   }
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
