### ISSUE TITLE
Missing media data in image slots

### ISSUE THREAD

**Issue by jnugh** [shopware/platform#2177]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

When I add an image to a CMS page and fetch that page using the `/store-api/cms/{cmsPageId}` the image data should be available in `sections blocks[type=image-cover] slots[type=image] data media`.

`data` should look somewhat like this:
```json
"data": {
  "mediaId": "8055a086a3144a15860138a162240c4a",
  "url": "",
  "newTab": false,
  "media": {
      "mimeType": "image/png",
      "fileExtension": "png",
      "fileSize": 392559,
      "title": null,
      "metaData": {
          "width": 510,
          "height": 474,
          "type": 3
      },
      "uploadedAt": "2021-11-09T14:13:01.749+00:00",
      "alt": null,
      "url": "https://some-url.com/media/59/c7/2e/1636467181/some-picture.png",
      "fileName": "some-picture",
      "translations": null,
      "thumbnails": [
          ...
      ],
      "hasFile": true,
      "private": false,
      "_uniqueIdentifier": "8055a086a3144a15860138a162240c4a",
      "versionId": null,
      "translated": {
          "alt": null,
          "title": null,
          "customFields": {}
      },
      "createdAt": "2021-11-09T14:13:01.519+00:00",
      "updatedAt": "2021-11-09T14:13:01.754+00:00",
      "extensions": {
          "foreignKeys": {
              "apiAlias": "array_struct"
          }
      },
      "id": "8055a086a3144a15860138a162240c4a",
      "customFields": null,
      "apiAlias": "media"
  },
  "apiAlias": "cms_image"
}
```

### Actual behaviour

`sections blocks[type=image-cover] slots[type=image] data media` does not exist at all. The data objects looks like this:
```json
"data": {
    "mediaId": "8055a086a3144a15860138a162240c4a",
    "url": "",
    "newTab": false,
    "apiAlias": "cms_image"
},
```

This behavior was introduced [here](https://github.com/shopware/platform/commit/c255c823c9ea9a1cafaf38919938add0dd2019d5#diff-2893f3cc058861b6416f1cbf2af0163653d4b7b7c3cb2484c52e316f53e2b0e5R23).

Setting switching from `protected $media;` to `private $media` makes `json_encode` skip it during serialization.

### How to reproduce

Add an image to a cms page. Query that page using the store api and observe the data provided in the image slot.

**Comment by keulinho** [comment]
Hey @jnugh,

thanks for your detailed bug :bug: report and investigation.
The issue should already be solved by https://github.com/shopware/platform/commit/3e2f69c990a0921c26d97af3a5df1bc535ffef86 and will be released with the upcoming patch version.
