### ISSUE TITLE
Implement a native ES-Layer

### ISSUE THREAD

**Issue by azngeek** [shopware/platform#2179]
### Please describe the feature you would like to see implemented.

It seems like that the current ES-Implementation does not fit into a high performance environment. I am very curious about this as for example i have a merchant with more then 1 million products.

Basically we currently are in the elastic cloud with several clusters, 32GB Ram, 450GB disk and there is only a thin layer between the frontend and the backend. If i would migrate to shopware i would have a lot more overhead in the application side before even doing a single request against elasticsearch.

- On every request i have to do the full symfony + shopware bootstrapping
- For elasticsearch there is still a dependency to sql for any reason? Is it price calculation, stocks, etc?

I would suggest the following approach:

- Build an event handler for products updates, stock updates, etc. There are a lot of indexers available right now, where you could build a drop-in extension or replacement which then creates or updates an elasticsearch-document with all data (properties, keywords, price, categories, etc.)
- Build an extremely thin layer - could be php as well - to run requests again Elasticsearch. You could use the existing search criterias (https://developer.shopware.com/docs/guides/integrations-api/general-concepts/search-criteria) but the current DAL is IMHO overhead which is not required. Most developers should be familiar with the native ES-syntax. 

Are there any plans into this direction? I would be happy to provide some PRs as well.

**Comment by shyim** [comment]
Hey,

This looks like https://github.com/shopware/platform/issues/3140. Let's close this here as an duplicate
