### ISSUE TITLE
Memory issues since v6.4.6.0

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2183]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

ManyToMany - Product/Media etc. - Associations with custom entity should not run out of memory

### Actual behaviour

Since v6.4.6.0 i get many reports about 500 internal server error from my customers. After a short research I realised, that all my plugins have trouble with v.6.4.6.0 because anything in Shopware kills the memory.

### How to reproduce

For example I have associations in my blog plugin:
https://store.shopware.com/moorl35721993639/shopware-6-blog-inkl.-wordpress-import.html

1. If I load the list of the blog posts I get OOM error.
2. If I remove the product association it runs again
3. If I assign for example one product and keep the association it runs, too
4. This hotfix works also:

```php
$criteria->addAssociation('products');
$productsCriteria = $criteria->getAssociation('products');
$productsCriteria->setLimit(6);
```

But its not only that plugin, all plugins have big trouble with the new Shopware 6 update, simply all with any ManyToMany associations. I am just wondering I am the only one with this problem?!

**Comment by moorl** [comment]
https://issues.shopware.com/issues/NEXT-18709

**Comment by keulinho** [comment]
Hey @moorl, thank you for your detailed bug :bug: report, we've fixed the issue in the current trunk and will release the fix with the next version.
