### ISSUE TITLE
JavaScript Error: Uncaught TypeError: window.gbmedFormsOptions is undefined

### ISSUE THREAD

**Issue by jrson83** [shopware/platform#2184]
### PHP Version

7.4

### Shopware Version

v6.4.6.0

### Expected behaviour

No JavaScript Error in Developer Console (Firefox).

### Actual behaviour

JavaScript Error in Developer Console (Firefox):

`TypeError: window.gbmedFormsOptions is undefined` -> `all.js:3:26786`

### How to reproduce

- Create a customer account
- Login to customer account
- Place an order
- Go to Account > My Orders
- Press the button "..." and select "Change Payment method"
- On the Page "account/order/edit/" the JavaScript Error is thrown

**Comment by shyim** [comment]
That's an extension issue, not Shopware. Check the gmed extension

**Comment by jrson83** [comment]
Can you please give a link or actual name of the extension? I have not installed an extension like that.

**Comment by shyim** [comment]
The extension name is GbmedForm

**Comment by jrson83** [comment]
> The extension name is GbmedForm

Thank you, I see.
