### ISSUE TITLE
Admin API: Invalid JSON response on Internal Server Error

### ISSUE THREAD

**Issue by nrdmch** [shopware/platform#2190]
### PHP Version

8.0.8

### Shopware Version

6.4.5.1

### Expected behaviour

If I use the sync-api, I expect to get a valid json result.

Otherwise I cannot handle the response.

### Actual behaviour

There is an issue using an AdminAPI Sync-API request if a server error occures:

If the server run out of memory, an error message is added to the json response - ok.

**But obviously the errors are added in a wrong way.
It results in an invalid json response string.**

Response snippet:
`{"productId":"09b0a1ca996b433198ab54c84978420a","languageId":"2fbb5fe2e29a4d70aa5854ce7ce3e20b"},
{"productId":"fd035e1b59b0409d9c70f8ab2dacec33","languageId":"2fbb5fe2e29a4d70aa5854ce7ce3e20b"},
{"productId":"44a801d4697b4a16881f5a25dedfc5af","languageId":"2fbb5fe2e29a4d70aa5854ce7ce3e20b"}]},
"deleted":[],
"notFound":[],
"extensions":[]}{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Error: Out of memory (allocated 688119808) (tried to allocate 20480 bytes)","meta":{"trace":[],"file":"\/home\/my-project\/my-domain.com\/vendor\/symfony\/var-dumper\/Cloner\/VarCloner.php","line":270}}]}`

I think there is an error near `extensions":[]}{"errors` 
Probably this would be the solution: `extensions":[],"errors`

### How to reproduce

Try to update many products with the sync-api to exceed servers memory limit.
$client->post('_action/sync', $manyData)

In my case I tried to update about 3.600 products in one request.
The response string was about 780000 bytes.

**Comment by keulinho** [comment]
Looks like in the response there is not just one but two responses.
The first response ends with the `extensions":[]}` and that would be the response for a successful call to the sync endpoint. The second response is for the OutOfMemoryError, that seems to be thrown after symfony renders the response of the controller.

Also i see in the error description that the OutOfMemory error occurs in the symfony/var-dumper that one should not be called in production code.

As the correct response from the controller is returned, i think that the sync did work, but that there is something in your setup that produces the OutOfMemory, after symfony rendered the correct response.

**Comment by nrdmch** [comment]
Thanks for the hint - it sounds plausible.
I also could not reproduce the behaviour in production mode.
