### ISSUE TITLE
Payload in Newsletter Subscription is not recursively converted to array

### ISSUE THREAD

**Issue by ts-mothership** [shopware/platform#2191]
### PHP Version

7.4

### Shopware Version

6.4.6.0

### Expected behaviour

- No error
- \Shopware\Core\Framework\Validation\DataBag\DataBag::only() should recursively convert data to array (similar to all() method) 

### Actual behaviour

- Error Code 400
```
{
  "errors": [
    {
      "code": "ba785a8c-82cb-4283-967c-3cf342181b40",
      "status": "400",
      "detail": "This value should be of type array.",
      "template": "This value should be of type {{ type }}.",
      "meta": {
        "parameters": {
          "{{ value }}": "object",
          "{{ type }}": "array"
        }
      },
      "source": {
        "pointer": "\/0\/customFields"
      }
    }
  ]
}
```
- [www/vendor/shopware/core/Content/Newsletter/SalesChannel/NewsletterSubscribeRoute.php:213](https://github.com/shopware/platform/blob/v6.4.6.0/src/Core/Content/Newsletter/SalesChannel/NewsletterSubscribeRoute.php#L213) Validation uses all() Method
- https://github.com/shopware/platform/blob/v6.4.6.0/src/Core/Content/Newsletter/SalesChannel/NewsletterSubscribeRoute.php#L215 Data extraction uses only() Method
- customFields are not recursively converted to array

### How to reproduce

Send a valid POST Request with customFields to /store-api/newsletter/subscribe
```
POST http://aigner.test/store-api/newsletter/subscribe
Accept: application/json
sw-access-key: ...
Content-Type: application/json

{
  "email": "test@test.de",
  "option": "subscribe",
  "storefrontUrl": "http://shop.test",
  "languageId": "628e5e758d6745129f02e77ae65c959b",
  "customFields": {
    "field1": "value1",
    "field2": "value2"
  }
}
```

**Comment by ts-mothership** [comment]
Hey @shyim :) 
Is this fixed? I don't see changes in referenced files.

**Comment by shyim** [comment]
I removed that field today as it was never expected to be here. https://github.com/shopware/platform/commit/ed75c2b6bdc4665ed57d0aacbee73c1fb534344f

But if you really need that feel free to create a PR to add it using the new StoreAPICustomFieldMapper

https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php#L171-L173

So you have to explict enable that custom field in the UI that it can be written
