### ISSUE TITLE
Content-Type check implemented incorrect in admin API

### ISSUE THREAD

**Issue by samuellembke** [shopware/platform#2196]
### PHP Version

7.4

### Shopware Version

6.4.6.1

### Expected behaviour

I'm sending a Content-Type header with the value "application/json; charset=utf-8"
Hence, the Content-Type is "application/json" it should handle the request accordingly.

### Actual behaviour

```php
        $contentType = $request->headers->get('content_type');
        if ($contentType === 'application/json') {
            return $this->fileFetcher->fetchFileFromURL($request, $tempFile);
        }
```
The check fails because this string comparison is not the correct implementation of a Content-Type header check.

### How to reproduce

Try uploading a media with the admin api
POST
https://localhost/api/_action/media/{mediaId}/upload?extension={extension}

BODY:
{
    "url": "https://exampleimages.com/image1.png"
}

HEADER:
Content-Type: "application/json; charset=utf-8"

This request will fail because the Content-Type is not equals "application/json" in the string comparison.

**Comment by samuellembke** [comment]
https://github.com/shopware/platform/blob/8e125fc4c72d67be8b7bc6b8fa6be3326589505b/src/Core/Content/Media/MediaService.php#L117-L129

**Comment by samuellembke** [comment]
This Bug makes it really troublesome to send admin api request with c# dotnet core. Because the StringContent class automatically sets the charset.
This is in many cases API breaking. Please fix as fast as possible

**Comment by mynameisbogdan** [comment]
This [solution](https://github.com/dotnet/runtime/issues/1478#issuecomment-348878181 ) doesn't work for you?

**Comment by shyim** [comment]
Could you create a PR? I would say just replace the equals with str_starts_with

**Comment by samuellembke** [comment]
> This [solution](https://github.com/dotnet/runtime/issues/1478#issuecomment-348878181) doesn't work for you?

This could very well work, Thank you.
But of course this is only symptom suppression

**Comment by samuellembke** [comment]
> Could you create a PR? I would say just replace the equals with str_starts_with

This function is only available in php 8 and above.
I will open a PR with strpos

**Comment by mynameisbogdan** [comment]
> > Could you create a PR? I would say just replace the equals with str_starts_with
> 
> This function is only available in php 8 and above. I will open a PR with strpos

Shopware is using `symfony/polyfill-php80` so it's okay to use `str_starts_with`.

**Comment by samuellembke** [comment]
> > > Could you create a PR? I would say just replace the equals with str_starts_with
> > 
> > 
> > This function is only available in php 8 and above. I will open a PR with strpos
> 
> Shopware is using `symfony/polyfill-php80` so it's okay to use `str_starts_with`.

Alright, PR is out. I implemented it with str_starts_with

**Comment by shyim** [comment]
Is merged already
