### ISSUE TITLE
CLI command to set plugin configs does not work with BOOL

### ISSUE THREAD

**Issue by boxblinkracer** [shopware/platform#2207]
### PHP Version

7.4

### Shopware Version

6.4.6.1

### Expected behaviour

When i use a command like this to set a BOOL config....

`php bin/console system:config:set xxx.config.yyy false`

the config should be FALSE in the plugin config

### Actual behaviour

It will always be set to TRUE
whatever i provide 0, false,"false"

this is because the value is always used from string...
which always converts to true, as far as i can remember (once looked at the code)
...or i even think it will always store the string directly in the database...instead of the bool

### How to reproduce

use any plugin such as the mollie plugin and set the config like of the debugMode for instance

**Comment by keulinho** [comment]
The system config command does not know about any types, so it saves everything as string.

I would suggest to add an `type` option to the `\Shopware\Core\System\SystemConfig\Command\ConfigSet`-command, that allows to specify the type of the value. The type should be one of `string`, `int`, `float` and `bool` with `string` being the default.

Depending on the specified type the value would be cast to the correct type, so in your case the command would look like
```
php bin/console system:config:set xxx.config.yyy false --type bool
```

resulting in:
```php
$value = (bool) $input->getArgument('value');
```

We'll happily accept a PR for that.

**Comment by boxblinkracer** [comment]
Hi

i dont think the type option is possible
just tried it

`The "--type" option does not exist.`

only sales channel, key and value exist

**Comment by keulinho** [comment]
Oops i was not clear enough. 

You are completely right it is currently not possible to set a config value over the CLI with an other type then string. 

I just wanted to sketch out a possible solution, that we would happily accept as a contribution.

Otherwise i would say that the bug is pretty low on our list of priorities, so i can't guarantee the timeliness of fix.

**Comment by boxblinkracer** [comment]
Ah
alright

so I did indeed create a PR one day, but there where other things that would have been required from you, and i havent had time since then, so I at least wanted to make sure someone knows :D

so if the "--type" option is someone that would work for you guys, then I'll see to get some time and add it.
i have to search the old PR, i think a solution way wasn't quite clear...i cant remember :)

**Comment by boxblinkracer** [comment]
found it, it was this one,
there is indeed a decision that i never read :D inactivity, sorry for this
https://github.com/shopware/platform/pull/1722

**Comment by keulinho** [comment]
Wow purely coincidental that we both proposed a similar solution, i was not aware of the old PR and the discussion there.

So i hope the way for a solution is clearer now ;)

**Comment by mitelg** [comment]
we recently added something similar in SW5 https://github.com/shopware/shopware/pull/2447/files

where we just json_decode the incoming string if wanted :wink:

**Comment by Catalin-Ionut** [comment]
Hello @keulinho i have made a PR to fix this #2209

**Comment by boxblinkracer** [comment]
Hi @Catalin-Ionut 
ah perfect, i'm so full of meetings anway haha,
thank you so much for this

**Comment by Zwaen91** [comment]
@keulinho Decode option merged. Can be closed.

**Comment by keulinho** [comment]
Thanks for the hint @Zwaen91
