### ISSUE TITLE
Update aws/aws-sdk-php to at least 3.199.0 so guzzlehttp/psr7 v2.0 can be installed

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2220]
### PHP Version

8.1

### Shopware Version

6.4.6.1

### Expected behaviour

Most likely it is even possible to just use `^3.198` syntax so all `3.x` versions can be installed.

In general it would be good to update the require section more often.

### Actual behaviour

see title

### How to reproduce

see title

**Comment by keulinho** [comment]
:+1:  for using `^3.198` as the version constraint for aws-sdk.

Probably it will be the fastest if somebody will prepare a PR for that.

**Comment by AndreasA** [comment]
Created PR: https://github.com/shopware/platform/pull/2221

**Comment by keulinho** [comment]
Fixed with https://github.com/shopware/platform/pull/2221.
