### ISSUE TITLE
Update Symfony to 5.4 and maybe also allow 6.x

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2223]
### Please describe the feature you would like to see implemented.

Update Symfony to 5.4 and maybe also allow 6.x

**Comment by keulinho** [comment]
Hello i've created an issue tracker ticket for that: https://issues.shopware.com/issues/NEXT-19222.

We will upgrade to 5.4 before 5.3 is EOL, but an upgrade to 6.x can only be done in the next major version, as it is a breaking change.

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/ce58f2053b3ab6e0bc9adecbb7b7edb0cbc5a778
