### ISSUE TITLE
Store-api Context_token changes after 24 hours and unlinks from user account

### ISSUE THREAD

**Issue by henrikawl** [shopware/platform#2226]
### PHP Version

7.4.3

### Shopware Version

6.4.0

### Expected behaviour

When I register a user and get a context_token I expect that I will user that token for fetching carts and manipulating shop with the same token.

### Actual behaviour

Currently IDK why when I create a user and get context_token, it lasts almost a day and when I fetch a customer info with that token, it works fine bringing the customer info indicating that user is logged in, but when I fetch a cart with that token cart always refreshes with different cart-ids which had to be the same as context_token. So only the first time when I register the cart works. After 24 hours the context_token unlinks

### How to reproduce

1. Create a customer
2. Fetch a cart
3. Add items to the cart
4. Create an order
5. Wait 24 hours
6. Fetch a cart again and it doesn't bring the same token as you have put in the header. It brings cart with randomly generated token. But it had to be the same

**Comment by shyim** [comment]
That token is currently not intended to be used as like a refresh_token. When the session expires, you get a new session with the session id
