### ISSUE TITLE
Form preserver iterates through wrong elements

### ISSUE THREAD

**Issue by wannevancamp** [shopware/platform#2227]
### PHP Version

8.1

### Shopware Version

6.4.18.0

### Expected behaviour

When you add `data-form-preserver="true"` to a form the value is saved in local storage and  filled up with the stored value after a page reload. 

### Actual behaviour

When you have the other elements in the form besides input fields. The input fields (ex. `div`) are not taken into account.

### How to reproduce

Working example:
`<form id="test-form" data-form-preserver="true">
            <input name="firstname" type="text">
            <input name="lastname" type="text">
        </form>`

Not working example:
`<form id='test-form' data-form-preserver='true'>
            <input name="firstname" type='text'>
            <div class='form-row'>
                <div class='form-group'>
                    <input name="lastname" type='text'>
                </div>
            </div>
        </form>`

**Comment by tobiasberge** [comment]
Hi @wannevancamp, thank you for creating a PR to fix this issue. 👍 

You changes were merged to trunk and the PR was marked as "Accepted": https://github.com/shopware/platform/commit/9b0a663aefba7dd37ccf4ec39943a6363f491585
