### ISSUE TITLE
HappyPathValidator - Is that really the best solution? Ignores various options like e.g. groups in constraints and overrides original validator.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2233]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

Do not override original validator but use the HappyPathValidator inside DAL. Also does it really provide that much of a performance boost?

And if it is, there are definitely some scenarios in which case it is actually slower, e.g. unsupported constraints or failing constraints will call the original validator after some additional code is executed. This probably fine for DAL itself, but various other scenarios will trigger this, e.g. EntityExists validation etc.

In any case make the original Validator available like e.g. validator.default if you indeed want to decorate it but I think it would be better to not decorate it at all and use it only where it makes sense instead.

See also NEXT ticket: https://issues.shopware.com/issues/NEXT-16538

### Actual behaviour

see description and also: https://issues.shopware.com/issues/NEXT-16538

### How to reproduce

see description and also: https://issues.shopware.com/issues/NEXT-16538

**Comment by shyim** [comment]
You dont need to create a github issue when you have a jira one

**Comment by AndreasA** [comment]
I know but I just noticed it again today and that issue hasn't had any feedback (I do not mean fixes or anything but really no response or milestone or state change or anything) since quite some time, so I created this one.

Adding a milestone like e.g. 6.6 or at least a comment so people know it isn't just ignored, would be nice. 

Furthermore, the current jira issue tracker doesn't provide any notifications so I never really know if one of my tickets has been updated.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
