### ISSUE TITLE
OneToManyAssociation: EntityReader fails loading if no "id" column exists if retrieving paginated content, e.g. translations

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2235]
### PHP Version

8.1

### Shopware Version

6.4.7.0

### Expected behaviour

If one adds a one-to-many association when retrieving an entity and adds a pagination limit, then the query should not result in a SQL exception, if the primary key is not an `id` column, e.g. `translations` but the same is true for custom entities that might not have `id` as primary keys.

### Actual behaviour

SQL exception is thrown `Column not found: 1054 Unknown column 'product_translation.id' in 'field list'`

### How to reproduce

As an easy example `translations` can be used. Therefore, add the PHP code as command, and add it as service using autowiring/autoconfigure, then execute `bin/console check:query` and the exception is thrown.

```php
<?php declare(strict_types=1);

namespace Shopware\Production\Command;

use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CheckQueryCommand extends Command
{
    protected static $defaultName = 'check:query';

    protected EntityRepositoryInterface $productRepository;

    public function __construct(EntityRepositoryInterface $productRepository, string $name = null)
    {
        parent::__construct($name);

        $this->productRepository = $productRepository;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $criteria = new Criteria();
        $criteria->setLimit(1);

        $criteria->addAssociation('translations');
        $criteria->getAssociation('translations')->setLimit(1);

        $this->productRepository->search($criteria, Context::createDefaultContext())->first();

        return 0;
    }
}

```

**Comment by AndreasA** [comment]
Another way to reproduce it would be to e.g. use the product listing store API route and add translations as association, as there a `limit` is always added since `NEXT-16166`: https://github.com/shopware/platform/commit/9b9759670def4a3f8de8cf600ed8fb9d33ba36b2

**Comment by AndreasA** [comment]
OK. It is extremely easy to reproduce.

- Create product (main product not variant).
- Assign it to a sales channel.
- Do not assign images to it.

Execute a fetch to its product detail store api and join media:

```
fetch("https://<host>/store-api/product/<id>", {
  "headers": {
    "content-type": "application/json",
    "sw-access-key": "<access-key>"
  },
  "body": "{\"associations\":{\"media\": {\" \": 1}}}",
  "method": "POST",
});
```

and the error occurs.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
