### ISSUE TITLE
Criteria "getAssocation" should not add an assocation (in the next major version 6.5)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2237]
### PHP Version

8.1

### Shopware Version

6.4.7.0

### Expected behaviour

If I use 

```
$criteria->getAssocation('name1.name2');
```

then the corresponding assocation should not be added, instead it should be added only when `addAssociation` is called.

`getAsscoation` should instead return `null` in such a scenario.

Maybe add an additional `getOrAddAssociation` method that then returns the corresponding association criteria.

### Actual behaviour

getAssocation adds an asscoation and addAssociation acutally calls addAssociation that just doesn't make sense as the getter should not modify the criteria.

### How to reproduce

see expected behaviour.

**Comment by sschwei1** [comment]
Wouldn't say this is a bug, it makes sense to add the criteria on the fly, so when adding criteria for a specific association, you don't have to make sure it exists first.
Changing this behavior would end up breaking quiet a lot of things in the core, as well as many plugins.

If you want to check if an association exists you can use `$criteria->hasAssociation`, the problem with this however is, it only checks it for the current criteria and not for a nested ones.
Making `$criteria->hasAssociation` work with nested associations wouldn't end up breaking things and also makes it easier to check if an association exists.

**Comment by AndreasA** [comment]
I would invert this and say that `addAssociatoin` should return an existing one or add a new one and getAssociation only return existing ones. as `addAssociation` sounds like it changes things, but `getAssociation` sounds like it does not.

**Comment by AndreasA** [comment]
Well I just think that the method should not be called `getAssociation` then as `get` does not imply changes to an existing state.

I might expect this from `addAssociation` (return existing or new critiera). However, that method returns `$this` which actuallly makes sense as well.

Personally, I prefer to call `addAssociation` and then `getAssocation`, then just `getAssocation` as using `getAssocation` sounds like it will break in the future.

A new method that does this might be a solution or an option to `getAssociation`.

Though I admit all this is breaking. Except adding a new parameter to `getAssociation` which keeps the current behavior as default value.

Adjusting hasAssocation should happen anyway - independant of potential other changes.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
