### ISSUE TITLE
Make filter-panel.html.twig extensible

### ISSUE THREAD

**Issue by svlauer** [shopware/platform#2246]
### Please describe the feature you would like to see implemented.

The template `@Storefront/storefront/component/listing/filter-panel.html.twig` makes it quite hard to add additional filters to the panel. 

The reason is that the [innermost `block component_filter_panel_items_container`](https://github.com/shopware/platform/blob/de57b0d1b765031aba5f09e27d4b16d7f175ad99/src/Storefront/Resources/views/storefront/component/listing/filter-panel.html.twig#L15) that contains the items provided by core wraps around the `div` containing all filters.

**Proposal:** Introduce a `block component_filter_panel_items` that wraps the provided filters, but not the `div`. Then the filter list can be extended with a simple `sw_extends` that includes this block's `parent()`.

(The [current documentation recommends a workaround](https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-listing-filters#add-your-filter-to-the-storefront-ui), namely to overwrite-with-parent the "last" filter block provided by core, which currently happens to be the "shipping-free" filter. While this works at present, it strikes me as a rather fragile solution, introducing a separate block as proposed above seems better to me.)

Would a pull request for something like this be considered?

**Comment by shyim** [comment]
Can you provide a pull request?

**Comment by svlauer** [comment]
Done. This is my first pull request on this project, so please let me know if I have done something wrong.

I was not sure if such a tiny change merited a changelog file, but I added one anyways. Let me know if I should remove it.

**Comment by svlauer** [comment]
Closing since the associated PR was merged and published in 6.4.8.0
