### ISSUE TITLE
Group filters in Storefront

### ISSUE THREAD

**Issue by zaifastafa** [shopware/platform#2248]
### Please describe the feature you would like to see implemented.

An example of such a feature would be having a filter hierarchy like such: 

```
├── Colors -> // Filter type
│   ├── Blue -> // Filter group
│   │   ├── Light Blue -> // Filter values
│   │   ├── Dark Blue
│   │   ├── Royal Blue
│   ├── Yellow
│   │   ├── Golden Yellow
│   ├── Red
│   │   ├── Light Red
│   │   ├── Dark Red
│   │   ├── Bright Blue
├── Size
│   ├── Small
│   │   ├── 2
│   │   ├── 3
│   │   ├── 4
│   ├── Medium
│   │   ├── 5
│   ├── Large
│   │   ├── 6
│   │   ├── 7
│   │   ├── 8
```

So if we assign a product size 8, we can filter it using "Large" in the frontend.

**Comment by mynameisbogdan** [comment]
I would rather advise you to create 2 property groups, one hidden on category but shown on the product page and other one inversed. The first would have values for products as they are, and the second should be assign per variant via a command/event listener based on a size chart per brand, etc. This would be listed as filters on categories.

**Comment by zaifastafa** [comment]
@mynameisbogdan Yes I am already doing that, but would be nice to have this as a built-in feature since it is a very common need of an e-commerce store. But thanks for the response/suggestion.
