### ISSUE TITLE
Setup command should also be able to generate a .env.local or .env.{environment}.local file  instead of just a .env file

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2249]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

With the latest change to the production template, .env.local or .env.{environment}.local file instead of just a .env file.
However, the setup command still generates a .env file.
It should also be able to generate a .env.local file or a .env.{environment}.local file.

Its force option should also check .env and .env.local and maybe even .env.{environment}.local accordingly.

### Actual behaviour

The setup command is only capable of genereting a .env file.

### How to reproduce

call the system:setup command.

**Comment by shyim** [comment]
We will switch to Symfony Flex so it's implemented there in 6.5
