### ISSUE TITLE
Thumbnails are not working after backup restoration

### ISSUE THREAD

**Issue by 7system7** [shopware/platform#2255]
### PHP Version

`$ php --version PHP 7.4.25 (cli) (built: Oct 19 2021 15:18:10) ( NTS )`

### Shopware Version

6.4.5.1

### Expected behaviour

When I copy all data with the whole `public/` dir then the thumbnails are working on the new server.

### Actual behaviour

The copied data and the database are the same. But the pictures and media are not working on the new server.
I tried to re-generate the media files w/ `$ bin/console media:generate-thumbnails`

### output

```
 // Generating Thumbnails for 14 files. This may take some time...                                                      

 14/14 [============================] 100%

 ----------- -------------------------- 
  Action      Number of Media Entities  
 ----------- -------------------------- 
  Generated   0                         
  Skipped     14                        
  Errors      0                         
 ----------- --------------------------
```

But as you can see, nothing happened. I cleared every cache, restarted every affected servers. I tried to delete the affected table in the database and re-generate media w/ no success.

### How to reproduce

Install the whole Shopware 6.x to somewhere. After that, make a copy from the files and the database to another server with the same version of PHP and MariaDB/MySQL. The actual output will be like this:

![Screenshot from 2022-01-06 19-15-44](https://user-images.githubusercontent.com/3964568/148431263-dd93f844-b9c2-4345-a1a6-6cd0a9fa1cbd.png)

I found some documentation about the media generation (and about the import/export) but sadly it is poorly documented. **But there is no (or I did not find) any related information about the correct backup method**.

**Comment by tinect** [comment]
Hey @7system7 

Could you please test setting `SHOPWARE_CDN_STRATEGY_DEFAULT` in your `.env`-file?

`physical_filename` or `id`

**Comment by 7system7** [comment]
Hello @tinect 

I forget to mention but tried that. It did not work.

**Comment by shyim** [comment]
It has to be SHOPWARE_CDN_STRATEGY_DEFAULT
