### ISSUE TITLE
Unequal length of NodeList of source & target in the replaceElement helper.

### ISSUE THREAD

**Issue by JonathanDeBelg** [shopware/platform#2256]
### PHP Version

7.4.25

### Shopware Version

6.4.3

### Expected behaviour

Loading the product listing after filtering.

### Actual behaviour

Getting an error in the console;

This is due to a unequal length of source and target Nodelists. In the `replaceElement()` method in the `ElementReplaceHelperSingleton` it replaces each `target[i]` with the `source[i]`. While filtering on elements i get for example a nodelist of 2 sources and 3 targets. This is unequal and then i get the error. For me it was easy to fix to just set the following;

```
_replaceSelectors(src, selectors, strict) {
        Iterator.iterate(selectors, (selector) => {
            var srcElements = DomAccess.querySelectorAll(src, selector, strict);
            var targetElements = DomAccess.querySelectorAll(document, selector, strict);

            srcElements = srcElements[0]; //this fixes the error
            targetElements = targetElements[0]; //this fixes the error

            this.replaceElement(srcElements, targetElements, strict);
        });
}
```
I do not know if this affects other behaviour (i know this helper is used for other functionality.  This issue could also be fixed by checking in the `replaceElement()` function if for the source you want to replace there is an existing target.

### How to reproduce

I created a custom product listing layout, called popup. This layout opens a modal instead of linking to the product page. In this modal I show a `cms-element-image-gallery`. The images for in the image gallery are supplied via a extension in a custom `ProductListingSubscriber`.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
