### ISSUE TITLE
SEO URLs (sometimes) overwrite routes

### ISSUE THREAD

**Issue by UlrichThomasGabor** [shopware/platform#2258]
### PHP Version

8

### Shopware Version

6.4.7

### Expected behaviour

When annotating a method with a route in a controller
```php
/*
 * @Route("/whatever", name="whatever", methods={"GET"})
 */
```
I expect it to always take precedence over automatically generated SEO URLs.

### Actual behaviour

This does not seem to be the case at the moment, as every URL is tried to be resolved as SEO url:
https://github.com/shopware/platform/blob/1ee8aafaba64459f0ef0034c520975f0ee52dd71/src/Storefront/Framework/Routing/RequestTransformer.php#L140-L145
https://github.com/shopware/platform/blob/1ee8aafaba64459f0ef0034c520975f0ee52dd71/src/Storefront/Framework/Routing/RequestTransformer.php#L320-L341

This can lead to problems when e.g. a category is created (by accident) with a name of a fixed route and then redirect to whatever content-page there is. Since categories can be created by "normal" users, they can accidentally overwrite "system" routes and break a lot of stuff.

The resolving also does not seem to be deterministic at the moment (although I could not find out why it is not). I have a case here, where an URL is resolved to the `NavigationController` results in an 404 there, although the route is actually a fixed route annotated to a plugin method and should never be forwarded to the `NavigationController`. Removing potentially conflicting entries from the `seo_url` table, then cleaning the cache and reloading leads to the URL being redirected to the correct controller again. Undoing that (putting the entries back into `seo_url`, cleaning the cache and reloading again) does not return back to the old behavior (forward to `NavigationController` and returning 404), but stays at the desired behavior.

### How to reproduce

Annotate whatever method with any SEO URL and observer that the SEO URL is resolved and not the desired controller is executed.

### Potential fix

An idea to fix that is to try and match the `$request` in the `RequestTransformer` with `RequestMatcherInterface::matchRequest`, catch these two exceptions
https://github.com/symfony/symfony/blob/098ff6277a398ac91cc6731bdadf207bf82fa40c/src/Symfony/Component/Routing/Matcher/RequestMatcherInterface.php#L33-L34
and only try to resolve the URL as SEO URL when the router was not able to resolve the URL already.

**Comment by OliverSkroblin** [comment]
Hi @UlrichThomasGabor, 
Thanks for reporting the issue. 

We have been discussing the issue and have come to the conclusion that this behavior can be sold to 50% of humanity as a feature and to the other 50% as a bug. 

Since there is no right or wrong here, we would leave it at the current state.

But of course, I don't want to leave you alone with your problem and would recommend you as a solution to simply decorate the `RequestTransformer` and implement your proposed solution there yourself in your projects.

I hope that helps you
