### ISSUE TITLE
Login: redirectTo to previously cached content pages or product detail pages shows old content as sw-states are not refreshed on redirect

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2261]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

If redirectTo is used to redirect to a page in the navigation or product detail pages that has been viewed before the content should immediately display new data, e.g. new prices. Instead of showing the old data from the cache.

### Actual behaviour

The previous page content is displayed. The reason is that the redirect response itself does not update the states in the response.

However, updating the states in the response results in an issue with logout as the logout process then fails to update the content correspondingly. 

Maybe, a double redirect is necessary like e.g. redirecting to a temporary route that then redirects to the final page with the correct states.

Furthermore, the SEO redirect itself from e.g. `/detail/<id>` does not update the states either, probably as it happens before the kernel is handling the request.

### How to reproduce

Use redirectTo and redirectParameters to redirect to a page in the navigation tree, in the login form. Ensure that that page has been shown before.

**Comment by AndreasA** [comment]
A similar issue happens if you redirect due to customer not logged in, e.g. directly on the homepage (because the customer wants to limit the shop to logged in customers only), that means after login the redirect goes to the homepage which is then cached and that state is rememberd after logout.

**Comment by AndreasA** [comment]
@shyim could the cache session fix in 6.4.8.2 https://github.com/shopware/platform/commit/91d5395ae8933e80bb90a612c3311a926d0ade11

actually solve this issue too? If so I will try this again with 6.4.8.2

**Comment by shyim** [comment]
nope

**Comment by AndreasA** [comment]
@shyim OK. Thanks. I thought it won't. I might look into this in more detail and create a PR though.

**Comment by shyim** [comment]
I wrote in the comments here already a solution, but don't have currently time for that https://issues.shopware.com/issues/NEXT-17181

**Comment by AndreasA** [comment]
@shyim great. Maybe I can create a PR from it. not sure when though. Maybe tomorrow but can't guarantee. Personally, I think this is also a bit security relevant as logged in page could end up in the anonymous cache. though only if the user already manipulated the redirectTo, so a bit like their own fault

**Comment by keulinho** [comment]
Should be fixed with https://github.com/shopware/platform/commit/01f211214fe66dab45deae3075788710eca5e508.

@AndreasA can you verify that the latest does not have this problem anymore?

**Comment by AndreasA** [comment]
@keulinho I will try to verify during the weekend, probably won't have time beforehand.

Is there already a released version with that commit?

**Comment by keulinho** [comment]
Nope that commit is not yet released.

**Comment by shyim** [comment]
I will close this as the commit is released already
