### ISSUE TITLE
Allow dependency injection (services) to be used for rule validation

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2262]
### Please describe the feature you would like to see implemented.

It should really be possible to use dependency injection inside rules in case someone has to access a symfony service. As symfony services can be anything, these can even be simple utility services or similar, so it really should be possible. If someone uses something that takes a long time, it is the developers fault.

This should be be possible. Best would probably be to differentiate the rule payload and the rule check. Checking could be a service and the payload not. Or you could use non shared services.

I also know there was the following issue: https://issues.shopware.com/issues/NEXT-9347

but it was never answered why it will not happen and to be honest I think it really should happen.

**Comment by shyim** [comment]
Hey,

the Rule validation needs to be executed fast as possible. Thats the reason why its unbound from the Container, so we can make sure that only operations are made on the given context and not fetched information by own. You should manipulate the given object to the rules rather doing things in the rule itself

**Comment by AndreasA** [comment]
@shyim Services do not necessarily need to fetch stuff. The can just provide logic / implementation with existing data which is better than creating a new object, especially as it can easily be used elsewhere with Symfony.

It doesn't necessarily help regarding performance, as I can e.g. still do performance intensive stuff inside the rules like calling external APIs using curl or guzzle or ... The fault in that case lies with the developer themself.
And it also doesn't mean I validate against the correct context, it is still possible to use wrong data for validation. Also why should that be a reason for this? If the developer wants to use the wrong data to validate, then it really is their fault.

In any case: How would one best add data to the object of a rule before the rule is called? There is not really an event or something like that that is just called before the rules are validated, that part is always somewhere inside existing methods e.g. CartRuleLoader and/or private methods.

I mean the context could be adjusted during context resolve event or similar, however, that might actually be a bit late as rule validation also happens beforehand sometimes.

I guess one safe solution would be to decorate the sales channel context factory? 

In any case, it actually sounds like it is more likely to fail this way as the wrong data might be in the context (not up-to-date) etc.

But as mentioned dependency injection is not only used to load additional data, it can just provide services that calculate stuff which one could also instantiate manually or static methods.
