### ISSUE TITLE
Manual shipping cost is always calculated using default currency

### ISSUE THREAD

**Issue by Floddy** [shopware/platform#2272]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

When a manual shipping cost is set on an order that is not in the default currency, the cost should be applied in the order's currency IE if the manual shipping cost is set to 10, it should be 10 regardless of currency.

### Actual behaviour

The cost is re-calculated from the default currency to the order's currency.

### How to reproduce

We use a custom plugin to place orders, and use DeliveryProcessor::MANUAL_SHIPPING_COSTS to set the shipping cost that we get from a 3rd party service - but this behaviour is also reproducable on a vanilla order placed in Shopware admin:

Prerequisites:
* Shopware setup with SEK as default currency, EUR as another currency, with factor 0.097. (Should work with any currencies that's not with 1->1 factor)
* A shipping method with the cost of 1 EUR (or any price really)

1. Create a new order in admin
2. Add an item
3. The shipping cost is now 1 EUR
4. Click the shipping cost to edit it, but keep it at 1 EUR and click the checkmark next to it
5. The shipping cost is now 0.097 EUR
6. Click the shipping cost again, and the checkmark again...it keeps going.

The price is sent in as you type it, but DeliveryCalculator::calculateDelivery always creates the Price object with the default currency, so it gets converted.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.

**Comment by Floddy** [comment]
This is actually already fixed in NEXT-29081 :)

**Comment by mitelg** [comment]
fixed with https://github.com/shopware/shopware/commit/905bf705e2d0b4d488cd506fe6dbc1a0372c8e70
