### ISSUE TITLE
Error Shopware\Administration\Controller\AdministrationController::index()

### ISSUE THREAD

**Issue by qpi3ikk** [shopware/platform#2275]
### PHP Version

7.4

### Shopware Version

6.4.7.0

### Expected behaviour

Open Shopware admin panel on address "http://localhost:83/project-name/shopaware/admin"

### Actual behaviour

Argument 2 passed to Shopware\Administration\Controller\AdministrationController::index() must be an instance of Shopware\Core\Framework\Context, null given, called in /home/project-name/shopware/vendor/symfony/http-kernel/HttpKernel.php on line 156

### How to reproduce

1. Changed APP_URL to http://localhost:83/project-name/shopware in .env file.
2. Changed Nginx configuration file, now it listening "http://localhost:83/project-name/shopware" instead "http://localhost:83"

**Comment by tinect** [comment]
I don't know if this could be related, but `shopaware` is not `shopware`. Your listed URLs don't match.

**Comment by qpi3ikk** [comment]
Don't pay attention, I made a mistake when writing Issue

**Comment by qpi3ikk** [comment]
> Не знаю, может ли это быть связано, но `shopaware`нет `shopware`. Указанные вами URL-адреса не совпадают.

Don't pay attention, I made a mistake when writing Issue

**Comment by qpi3ikk** [comment]
> I don't know if this could be related, but `shopaware` is not `shopware`. Your listed URLs don't match.

Don't pay attention, I made a mistake when writing Issue

**Comment by shyim** [comment]
I could not reproduce it. Can you still reproduce it?
