### ISSUE TITLE
6.4.7.0 - Adding some associations to entities with inheritance - e.g. media on product - can lead to server error in combation with pagination

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2277]
### PHP Version

8.1

### Shopware Version

6.4.7.0

### Expected behaviour

Should not result in a server and load association correctly.

### Actual behaviour

According to https://github.com/shopware/platform/issues/2156
and https://issues.shopware.com/issues/NEXT-18081

Maybe also related to https://github.com/shopware/platform/issues/2235

this has supposed to be fixed with 6.4.7.0. However, I just did an updated from 6.3 on a system to 6.4.7.0 and we now encounter that issue. The issue does not occur on the staging environment though it contains similar products.

It might be related to incorrect deletions of inheritance or similar (e.g. from before the update). This is especially now an issue with the update as if I join media during store api call of a product, it automatically adds a limit to it.

It results currently in `Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityCollection::getList(): Argument #1 ($ids) must be of type array,` or on a dev env in (same data) `Warning: Undefined array key \"\"`

most likely it seems data data from the mapping array is missing. if that is actually possible, it should be safely ignored then, if it isn't posislbe please fix it.

### How to reproduce

Not exactly sure, it definitely is related to inheritance and especially easily reproducible with a product and media. 

maybe what happened was that the product variant had a custom image, then the parent product was deleted, then the media from the variant or something like that.

EDIT:
See comment https://github.com/shopware/platform/issues/2277#issuecomment-1017471897 regarding how to reproduce. I was able to do so without any issues.

**Comment by AndreasA** [comment]
In any case, long story short, there are still some scenarios where the mentioned issues were not fixed with 6.4.7.0.

It wasn't an issue prior to the update but before the update there was no pagination in use for media association.

**Comment by AndreasA** [comment]
OK. It is extremely easy to reproduce.

- Create product (main product not variant).
- Assign it to a sales channel.
- Do not assign images to it.

Execute a fetch to its product detail store api and join media:

```
fetch("https://<host>/store-api/product/<id>", {
  "headers": {
    "content-type": "application/json",
    "sw-access-key": "<access-key>"
  },
  "body": "{\"associations\":{\"media\": {\" \": 1}}}",
  "method": "POST",
});
```

and the error occurs.

**Comment by AndreasA** [comment]
The issues seems to be these lines:

https://github.com/shopware/platform/blob/v6.4.7.0/src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php#L541

No check, if there actually is a parentId set.

https://github.com/shopware/platform/blob/v6.4.7.0/src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php#L544
No check if that parent ID is in the mapping, e.g.  parent does not exist but for some reason the ID is still in the database which seems to happen sometimes with composite foreign keys depending on the mysql version. also there just might not be a mapping.

and in this line https://github.com/shopware/platform/blob/v6.4.7.0/src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php#L546 the mapping is just used but it might not exist, e.g. because parentId was null.

**Comment by shyim** [comment]
Can you provide a failing PHPUnit test?

**Comment by AndreasA** [comment]
Most likely yes but probably not soon as I don't have time this week and I am on vacation next week.

**Comment by AndreasA** [comment]
@shyim is a test case still needed as @Lucksmith369 created a PR already?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
