### ISSUE TITLE
{% parent %} not working as expected in Administration

### ISSUE THREAD

**Issue by runelaenen** [shopware/platform#2279]
### PHP Version

8.0

### Shopware Version

6.4.7.0

### Expected behaviour

```
Start custom block 1
Block two!
End custom block 1
```

### Actual behaviour

```
Start custom block 1
Start block 1
Block two!
End block 1
End custom block 1
```

### How to reproduce

In PHP twig, we have the {{ parent() }} notation which will call the block of the parent page you're extending. On the twig.js, it does not work the same. 
It works great on level 1, but not any deeper than that. {% parent %} always calls the extended block of the first level.

**a.html.twig**
```
{% block test_level_one %}
    Start block 1
    {% block test_level_two %}
        Block two!
    {% endblock %}
    End block 1
{% endblock %}
```

**b.html.twig**
```
{% extends 'a.html.twig' %}

{% block test_level_one %}
    Start custom block 1
    {% block test_level_two %}
        {% parent %}
    {% endblock %}
    End custom block 1
{% endblock %}
```

**Comment by runelaenen** [comment]
For the record, I was first creating an issue in the twig.js repo, but it seems that the {% parent %} tag is shopware-specific, and not from Twig.js itself?

`/vendor/shopware/administration/Resources/app/administration/build/nuxt-component-library/lib/file-parser/twig-components/index.js` line 30

**Comment by shyim** [comment]
Slots using Extension SDK is the future. So we would not invest time to change that 😅
