### ISSUE TITLE
CMS-Pages in Backend do not load if many products are assigned to custom product template

### ISSUE THREAD

**Issue by ttheuerkauf** [shopware/platform#2290]
### PHP Version

8.0

### Shopware Version

6.4.7.0

### Expected behaviour

-

### Actual behaviour

We have about 9.000 products spread over two sales channels. Each of these products is assigned to a custom product template, which has been copied from the default product template.

When opening the cms pages section in backend, it loads a long time and retrieves about a 100MB data in the request to load the cms pages. Sometimes this request fails completely.

If think this behaviour is similar to: #2016

### How to reproduce

-

**Comment by pinco447** [comment]
Hey @ttheuerkauf 
I'm faced this issue too and managed to fix it. Now I'm trying to fix cms page detail performance issue.
I can send you the patch file with cms page listing performance issue fix.

**Comment by ttheuerkauf** [comment]
Hi @yourborjia,

we also have a performance problem on the cms detail page, seems to be the same reason. Are you going to create a pull request here to fix both errors? 

In this case we can wait until it is released officially :-).

Thank you very much and best regards!

**Comment by pinco447** [comment]
@ttheuerkauf [here](https://github.com/shopware/platform/pull/2354) is PR. I've fucked up with fixing cms detail page, sooooooo i believe core team will take it later.

**Comment by ttheuerkauf** [comment]
OK, thank you very much! :-)

**Comment by moorl** [comment]
It would be better to define the default Listing/Product CMS pages in the Sales Channel Config, so an association would not be necessary.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
