### ISSUE TITLE
Revenue chart in backend is empty in german version

### ISSUE THREAD

**Issue by MarcelKohlmeyer** [shopware/platform#2295]
### PHP Version

7.4.27

### Shopware Version

6.4.7.0

### Expected behaviour

Revenue-Chart should show actual revenue

### Actual behaviour

Revenue-Chart is empty.
I analyzed the xhr-request, filter is set to 
```
"filter": [
        {
            "type": "equals",
            "field": "transactions.stateMachineState.name",
            "value": "paid"
        }, ...
]
```

in the german version, transactions.stateMachineState.name is "Bezahlt", not "paid". 
transaction.stateMachineState.technicalName points to "paid" in this case, so this should do the trick.
    

### How to reproduce

Install shopware in german language.

**Comment by keulinho** [comment]
Should be fixed with: https://github.com/shopware/platform/pull/2263
