### ISSUE TITLE
EnvironmentHelper utility add support to transform variables before they are used

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2296]
### Please describe the feature you would like to see implemented.

As discussed with @shyim in https://github.com/shopware/production/issues/132 I want to add a possibility for developers to easily modify environment variables used by Shopware directly, so e.g. the DATABASE_URL could be retrieved from secret stores like Symfony Secrets, HashiCorp Vault, etc.

In order to achieve this an option to transform variables is added to the EnvironmentHelper utiility by registering transformers.

**Comment by AndreasA** [comment]
NEXT issue for changelog: https://issues.shopware.com/issues/NEXT-19880

**Comment by keulinho** [comment]
Fixed with: https://github.com/shopware/platform/pull/2297

Thanks @AndreasA for your contribution!
