### ISSUE TITLE
Add events to SystemConfigService to easily allow encrypting and decrypting of stored configuration values.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2306]
### Please describe the feature you would like to see implemented.

In order to easily store and load plugin configuration values in an encrypted form, two additional events would make it easier to add a custom provider for it, be it HashiCorp Vault, Symfony Secrets etc. 

Additionally, it allows value transformation before / after loading too.

**Comment by AndreasA** [comment]
created NEXT issue for changelog: https://issues.shopware.com/issues/NEXT-19942

**Comment by shyim** [comment]
FYI: I have closed the jira issue. You don't need to create issues by own when you make a PR :)

**Comment by AndreasA** [comment]
@shyim Ah. OK. Can I just skip the isuse entry in the changelog then ? or should I reference teh github issue?

**Comment by shyim** [comment]
Yup. will be filled by us

**Comment by AndreasA** [comment]
@shyim But a github issue should be created or can I skip that as well?

**Comment by shyim** [comment]
You don't need a issue 😅 . Thy are currently not really well checked as we use jira as primary source

**Comment by AndreasA** [comment]
@shyim One more question regarding changelog, If I do not add an issue, the CI fails with wrong changelog format.
 What should I add in such a case? Just `Issue: #<PR-Number>` ?

**Comment by shyim** [comment]
Ignore the CI. we need to change this 🙈

**Comment by AndreasA** [comment]
@shyim I think as the PR https://github.com/shopware/platform/pull/2307 has been merged I can actually close the ticket?
