### ISSUE TITLE
Paging not working correctly through @shopware-pwa/shopware-6-client (or REST)

### ISSUE THREAD

**Issue by steuraa** [shopware/platform#2313]
### PHP Version

8.1.2

### Shopware Version

6.4.7

### Expected behaviour

There are currently 116 products in my store and I want to get correct info so I can set up paging.
If I do a normal post on https://.../store-api/product without a body, so not setting a manual limit, I expect to get something like:
{
    "entity": "product",
    "total": 116,
    "aggregations": [],
    "page": 1,
    "limit": 100,
    "elements": [ *100 items present* ],
    "states": [],
    "apiAlias": "dal_entity_search_result"
}

I'm not sure what exact paging info comes back as it's hard to find in the rest documentation, could be that there is a totalPages or something similar as well.

### Actual behaviour

There are currently 116 products in my store and I can't get all of them.
If I do a normal post on https://.../store-api/product without a body, so not setting a manual limit, I get:
{
    "entity": "product",
    "total": 100,
    "aggregations": [],
    "page": 1,
    "limit": 100,
    "elements": [ *100 items present* ],
    "states": [],
    "apiAlias": "dal_entity_search_result"
}
I understand that 100 is the default limit, but I don't get info about the total number of pages or correct total number of products.
If I add a body {"limit": 20} I get
{
    "entity": "product",
    "total": 20,
    "aggregations": [],
    "page": 1,
    "limit": 20,
    "elements": [ *20 items present* ],
    "states": [],
    "apiAlias": "dal_entity_search_result"
}

If I try to increase the limit above 100 ({"limit": 500} fe) I get an api error:
{
    "errors": [
        {
            "status": "400",
            "code": "FRAMEWORK__QUERY_LIMIT_EXCEEDED",
            "title": "Bad Request",
            "detail": "The limit must be lower than or equal to MAX_LIMIT(=100). Given: 500",
            "source": {
                "pointer": "/limit"
            },
            "meta": {
                "parameters": {
                    "maxLimit": 100,
                    "limit": 500
                }
            }
        }
    ]
}

Getting this problem through postman and via the JS sdk in a React project

### How to reproduce

Not sure if this is something specific about our setup of shopware (new to it, so settings are pretty much default), but if it isn't it should be pretty simple to reproduce:

- Get a store with more than 100 products
- post on https://.../store-api/product 
- see if there is any reference to more than 100 products

**Comment by steuraa** [comment]
Nothing on this? Just to clarify, the issue is not the 100 items limit, but rather that whatever limit is used (default or set), I don't see a way to implement paging currently. The total prop of the response seems to get incorrectly set currently.

**Comment by moonfr34k** [comment]
Hey, simple create a file config/packages/shopware.yaml and add this:

`shopware:
      api:
        max_limit: 200`

Some more security informations:
https://docs.shopware.com/de/de/shopware-6-de/tutorials-und-faq/flooding-praevention

**Comment by steuraa** [comment]
@LarsRaube thanks for the reply. 
Where exactly would I add this? Somewhere in the admin portal of Shopware?

Regardless, I don't think this solves the underlying issue? This increases the number of items I can get in 1 call, but what if I have 500 products that I need to show? 
There must be a way to properly implement a paging solution, which currently seems to be broken, unless I'm missing something obvious.

**Comment by shyim** [comment]
Hey,

![image](https://user-images.githubusercontent.com/6224096/153133938-2e76a288-ebd6-4a97-a1af-d5fcf8ceba81.png)


I guess you are missing the `total-count-mode` in your api request. See here what the each option is doing https://github.com/shopware/platform/blob/trunk/src/Core/Framework/DataAbstractionLayer/Search/Criteria.php#L20-L33

**Comment by steuraa** [comment]
@shyim , thanks for the help, that indeed solved my issue!
Just pointing out that that parameter is fairly well hidden for something crucial, especially as its default setting is 0.
After looking for it now, I found it in the [integration api ](https://developer.shopware.com/docs/guides/integrations-api/general-concepts/search-criteria#total-count-mode) but to the best of my knowledge it seems to be missing in the [store api docs](https://shopware.stoplight.io/docs/store-api/b3A6MTE0OTQwMzg-search-for-products) which is extra confusing as the the default response of those calls do return a page and total property, which are basically useless with the default setting.

**Comment by shyim** [comment]
Thanks for the feedback. I have created a PR internally to add this there
