### ISSUE TITLE
Move memoization of SystemConfigService into a SystemConfigLoader decorator and invalidate on SystemConfigChangedEvent

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2319]
### PHP Version

8.1

### Shopware Version

6.4.8.0

### Expected behaviour

Memoization should happen in a Decorator for the SystemConfigLoader. That way one can bypass it by setting a corresponding priority. It should be appended after the normal CachedSystemConfigLoader, so the chain would be MemoizationSystemConfigLoader (Priority: -2000) --> CachedSystemConfigLoader (Priority: -1000) --> SystemConfigLoader.

### Actual behaviour

If one intends to decorate the SystemConfigLoader to adjust certain configuration values and there is an optional requirement to data that is not available yet, and e.g. determines how to adjust the config value, then it isn't really possible to do so as once the config service is called for a sales channel ID, its values are memoized and cannot be adjusted without overriding the SystemConfigService.

To avoid this, the memoization should happen using a SystemConfigLoader decorator which also listens to the SystemConfigChanged event to invalidate that memoization.

Optionally, provide an itnerface or abstract class to the system config service.

### How to reproduce

See https://github.com/shopware/platform/blob/v6.4.8.0/src/Core/System/SystemConfig/SystemConfigService.php#L345

**Comment by AndreasA** [comment]
If that change is fine with you, I can create a corresponding PR. Though as discussed in another PR/issue it is probably best to completely rework handling of system configuration but this would already be helpful.

**Comment by keulinho** [comment]
Fixed with https://github.com/shopware/platform/pull/2342.

Thanks again for your contribution @AndreasA! :tada: :blue_heart:
