### ISSUE TITLE
Allows to change the prefix for automatically generated variant product numbers.

### ISSUE THREAD

**Issue by weselben** [shopware/platform#2322]
### Please describe the feature you would like to see implemented.

Allows to change the prefix for automatically generated variant product numbers.

Like for example instead of SW0001.1 -> SW0001-1 or something similar.

- Ben

**Comment by dneustadt** [comment]
Hi,
thank you for your suggestion. As this is a feature request we'd like to follow up on, please head to https://issues.shopware.com/ and create a ticket over there.
