### ISSUE TITLE
StoreService::getShopwareVersion removed in v6.4.8.0

### ISSUE THREAD

**Issue by Morerice** [shopware/platform#2336]
### PHP Version

7.4

### Shopware Version

6.4.8.0

### Expected behaviour

Based on the [deprecation annotation](https://github.com/shopware/platform/commit/dd88bb181af3e62160d9d6367f301388c473c5ca#diff-de90af7ba53feae9d0b3307e6e0085572abecca9ac5b41f59d93308340a7ae73L56) in the function signature, the expected behavior is that this was going to be removed in v6.5.0

### Actual behaviour

Function was removed in [v6.4.8.0](https://github.com/shopware/platform/compare/v6.4.7.0...v6.4.8.0#diff-de90af7ba53feae9d0b3307e6e0085572abecca9ac5b41f59d93308340a7ae73L58).

### How to reproduce

After installing the Adyen plugin (or any other plugin that calls this function), the following error will be thrown on the checkout page:

```
Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getShopwareVersion"
```

We are aware that we should not rely on this function anymore (based on the deprecation annotation), but it seems that this is a breaking change introduced in a feature release. 

[Related issue](https://github.com/Adyen/adyen-shopware6/issues/231)

Best regards,
Jean
Adyen

**Comment by shyim** [comment]
Hey,

the entire class is internal. (https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Store/Services/StoreService.php#L14) .
Please use alternatives like `kernel.shopware_version` from the container

**Comment by Morerice** [comment]
Hi @shyim,

Thanks for the quick response!

Best regards,
Jean
Adyen
