### ISSUE TITLE
Add event to easily add data to rule context before active rules are determined / rule matching  due to missing dependency injection or allow dependency injection

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2349]
### Please describe the feature you would like to see implemented.

As there is not dependency injection it is sometimes necessary to add additional data for rules to match. However, to get the data correctly this has to be done just before the rules are matched and there is no such event yet.

Maybe it is enough to just add an event and add data to the context before the filter matching rules is called but even better would be to allow custom payload to be added to rule objects and provide it for matching purposes.

Even better would be to restructure the rule system to separate payload and mach service, so the mach service could use dependency injection - similar to how Symfony validator separates the constraints and the validator. And it really should not be a performance issue as e.g. one can do performance slow operation with and without dependency injection, so this really should not have any impact - it is up to the developers to ensure this does not happen.

**Comment by shyim** [comment]
See https://github.com/shopware/platform/issues/3142

**Comment by AndreasA** [comment]
I would also be happy with a better solution but I don't think there is any without readjusting the complete cart / rule loading behavior.
