### ISSUE TITLE
Cannot open detail view of order if it's older than 30 days

### ISSUE THREAD

**Issue by andreaskienast** [shopware/platform#2356]
### PHP Version

7.4

### Shopware Version

6.8.4.1

### Expected behaviour

Opening the detail view of an order using its deep link code (/account/order/whateverThisDeepLinkCodeIs) will always show the order independent of the date it's created or altered.

### Actual behaviour

Opening such order that has been either created or altered more than 30 days ago will result in an empty view, this affects the detail view only. This is caused by NEXT-12359, to be precise by https://github.com/shopware/platform/commit/9d4e78cdd0f6d7101e0fb56e4cd1e914af0359a6#diff-42200ee7e6c823342422a6520b801a86405441efe005095982c209202ef553caR206-R215.

### How to reproduce

You need an order that has been created or altered more than 30 days ago (either wait 😉 or create an order and change its dates manually in the database, afterwards try to open the detail view at /account/order/$deepLinkCode, where $deepLinkCode is the order's deep link code.

**Comment by taltholtmann** [comment]
Hello @andreasfernandez, 
thank you for reporting this issue :blue_heart: . This behavior was intended as a result of a security audit. I could imagine having a shop configuration to control the time the link is accessible. Feel free to create a feature request in our issue tracker for that: https://issues.shopware.com/issues/

Regarding the empty view if the link is expired, I have created a bug ticket: https://issues.shopware.com/issues/NEXT-20331

**Comment by NeoBlack** [comment]
I am sorry, but I see nothing security-related here. Why should I not be able to see old orders? I can see any order I placed on amazon from the beginning of 2013.
Having access to old orders is nothing security-related since the order view is behind a login.

**Comment by andreaskienast** [comment]
Hello @taltholtmann,
thank you for your feedback. I'm honestly confused now as I've never heard that being able to view an old order may lead to a security incident. Any online shop I'm using allows me to view old orders.

Is it possible to get some details about that specific audit?
