### ISSUE TITLE
Skip JWT key generation during system:install command (might be provided differently)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2358]
### Please describe the feature you would like to see implemented.

I am using Symfony secrets to store private/public keys and a passphrase. This works fine in general but adjusting the corresponding service when using the production template

However, the system:install command always creates those keys. It would be nice if that could be skipped. Should be easy enough to add a corresponding option.

**Comment by AndreasA** [comment]
I think this can be closed now as https://github.com/shopware/platform/commit/e2aa43cfaf36c7ac6ef45ec8ad8b29933b0d1a1c / https://github.com/shopware/platform/pull/2360 was already merged?

**Comment by keulinho** [comment]
Good catch! Closing this as it is possible now, thanks @AndreasA for your contribution!
