### ISSUE TITLE
Can't select first shipping method in the shopping cart

### ISSUE THREAD

**Issue by ebrithiljonas** [shopware/platform#2359]
### PHP Version

7.4.28

### Shopware Version

6.4.8.1

### Expected behaviour

After selecting the first shipping method (in the shopping cart) in the drop down menu, it should switch to it.

### Actual behaviour

After selecting the first shipping method in the drop down menu, it doesn't change to the selected method.

### How to reproduce

1. Have at least two shipping methods selectable in the shopping cart.
2. Select the second shipping method, it should switch to that one.
3. Select the first shipping method again, then it doesn't switch to it.

**Comment by leptoquark1** [comment]
Hey,

please take a look on this issues using >=v6.4.9.0. Maybe my fix in #2305 is helping here

**Comment by ebrithiljonas** [comment]
I have updated to v6.4.10.0, this fixed the bug, thank you
