### ISSUE TITLE
\Shopware\Core\Framework\App\ActiveAppsLoader should be able to completely bypass database connection for CI e.g. with ComposerPluginLoader

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2368]
### PHP Version

8.1

### Shopware Version

6.4.8.1

### Expected behaviour

An option to bypass accessing the database, when retrieving active apps inside CI similar to the composer database loader, e.g. for bundle:dump command.

### Actual behaviour

It doesn't completely fail but it is first trying to access the database and only then retrieving all apps.

In case the composer plugin loader or the static plugin loader is used, I think the database connection should be bypassed completely and they should always be loaded locally.

### How to reproduce

Use ComposerPluginLoader and execute bundle:dump command, it will output `Warning: Failed to load apps. Loading apps from local.`

**Comment by keulinho** [comment]
I don't see the problem here, it works for CI environments there is a fallback, but certainly apps don't fully work if the database connection can not be established, e.g. there is no distinction between active or inactive apps and the `bundle:dump` command will include inactive apps, therefore the warning.

**Comment by AndreasA** [comment]
it might try to connect to an invalid host and provide an invalid password, in theory it could be used maliciously though unlikely as it usually only happens in the CI and there the host will not exist at all or be under the user's control.

However, it would be easy to check the plugin loader and bypass active check for composerpluginloader or even better add an option that could be changed using dot env files so in test envs it could be disabled.

**Comment by AndreasA** [comment]
But I could probably create a PR where I add a Shopware setting or ENV variable for this? for those that don't need it, it would still work fine with a corresponding default value and it would provide an option for those that need/want to use it.

**Comment by AndreasA** [comment]
@keulinho I would create a PR for this, if you are fine with it and my intention would be to inject the kernel and check if the pluginloader is not the databaseplugin loader and if it is not, I would return all apps, if you are fine with it?

otherwise, it would be more complicated to get all necessary information that far into the code.

**Comment by keulinho** [comment]
I would not inject the kernel, but in the kernel you could set a container param that indicates which pluginLoader is used and inject that param to the ActiveAppsLoader

**Comment by AndreasA** [comment]
@keulinho Just wondering if NEXT-20852 takes care of this? https://github.com/shopware/platform/commit/18ca01899b8938ce406c056af6ebff893546aae2

However, does NEXT-20852 also disable plugins or only apps?

though I guess it doesn't really fix this anyway as it disables loading apps altogether, instead of just loading all for theme compilation.

However, I think I could now check for `EnviornmentHelper::getVariable('COMPOSER_PLUGIN_LOADER', false)` to determine if all apps should be loaded or the database should be used to load only active apps?

**Comment by keulinho** [comment]
`NEXT-20852` should take care of this, and yes it prevents all apps from being loaded.

You can't load all apps for theme compilation without a DB connection, because it is not guaranteed that all the apps source files are present.

**Comment by AndreasA** [comment]
@keulinho Great. The plugins are still loaded with `NEXT-20852`, only the apps are skipped if I use `DISABLE_EXTENSIONS`?

**Comment by keulinho** [comment]
Only "composer plugins" are loaded, meaning those plugins that are required over composer.

**Comment by AndreasA** [comment]
@keulinho Great that is exactly what I need. the only thing that should be changed is that instead of using $_SERVER for them to use `EnviornmentHelper::getVariable('COMPOSER_PLUGIN_LOADER', false)`, same for `DISABLE_EXTENSIONS` inside `bin/console` and `public/index.php` to ensure e.g. $_ENV works as well. but those files the user can adjust themself too, but better to have it correctly in the templates.

**Comment by AndreasA** [comment]
@keulinho One thing I noticed, if one uses `system:install` the plugin loader should not switch to the composer plugin loader as this might fail as various database tables are still missing. this one should always use the file loader.

I can create a separate issue if necessary: https://github.com/shopware/production/blob/6.4/bin/console#L66

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
