### ISSUE TITLE
CacheController info uses getenv instead of dependency injection

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2369]
### PHP Version

8.1

### Shopware Version

6.4.8.1

### Expected behaviour

The `\Shopware\Core\Framework\Api\Controller\CacheController::info`: Use parameters / dependency injection to get infos like kernel.environment instead of getenv('APP_ENV').

Especially, as getenv and putenv are not thread safe.

this also relates to: https://github.com/shopware/platform/issues/2800

### Actual behaviour

getenv is used in `\Shopware\Core\Framework\Api\Controller\CacheController::info`

### How to reproduce

see implementation for `\Shopware\Core\Framework\Api\Controller\CacheController::info`.

**Comment by AndreasA** [comment]
It would be easy to change, just use `$this->getParameter('kernel.environment')` and `(bool)$this->getParameter('shopware.http.cache.enabled')` instead

**Comment by shyim** [comment]
You want to create a PR? :)

**Comment by AndreasA** [comment]
@shyim sure. but probably not today. However, I think I should be able to do so sometime this week, is a relatively quick fix.

**Comment by AndreasA** [comment]
@shyim If I go with the parameter option, I either need to inject the ParameterBag as another argument or adjust the container because the currently used container does not include the parameter bag.

Therefore, to avoid a potential breaking change, I would inject the ParameterBag optionally in the constructor and if it is missing fallback to existing implementation ( `getenv`, maybe event EnviornmentHelper with getenv as fallback) and add a deprecate tag that the ParameterBag will be required with 6.5?

Or just use the `EnvironmentHelper` with a default value `getenv` that way no additional arguemtns would be required but it wouldn't be as nice.

**Comment by AndreasA** [comment]
Didn't find the time yet. but will try to fix it this week.

**Comment by keulinho** [comment]
Fixed with https://github.com/shopware/platform/pull/2378.

Thanks again for your contribution @AndreasA! :tada: :blue_heart:
