### ISSUE TITLE
system:install should work without additional global privileges and only database permissions (currently needs SUPER, TRIGGER etc.)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2371]
### PHP Version

8.1

### Shopware Version

6.4.8.1

### Expected behaviour

Only require normal write / read permissions for one databse during installation. I think there are two issues, that triggers are not created with CURRENT_USER, so the user needs permission to set the trigger user and another regarding binary log in MySQL 8.0 but best to just check it manuallly and try to fix it.

### Actual behaviour

system:install requires SUPER permission (or similar depending on MySQL version). Would be nice if that is not necessary. Once the initial installation is done, it works without but it would be better to never need it.

### How to reproduce

Create a MySQL user for a database with all permissions to the database (READ/WRITE) and use that user during system:install. It will fail during trigger creation and some other tables fail with binary log warning / issues (don't remember the exact error).

**Comment by shyim** [comment]
Just disable blue green while `system:setup`

**Comment by AndreasA** [comment]
@shyim I actually did so and I still had issues but I will retry tomorrow and get back to you with the exact error message (if I can reproduce it).

**Comment by AndreasA** [comment]
@shyim I retried today and now it works without the permissions. Maybe I forgot to set the value correctly initially.

Btw. the original error was `General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)`

In any case, great that disabling blue/green deployment fixes this issue. Thanks!

**Comment by AndreasA** [comment]
@shyim One thing though it might be good to mention this in the Shopware 6 installation documentation? At least I couldn't find it.

**Comment by AndreasA** [comment]
@shyim Can I convert existing data from BLUE_GREEN_DEPLOYMENT=1 to BLUE_GREEN_DEPLOYMENT=0 and vice versa easily?

I guess from 1 to 0 I just need to remove all database triggers?

**Comment by shyim** [comment]
yep 0 -> 1: remove all triggers

0 -> 1: looking into all relevant migrations and doing it manually

**Comment by AndreasA** [comment]
@shyim Great. Thanks again!
