### ISSUE TITLE
Console system:install can't connect to database without password

### ISSUE THREAD

**Issue by ikhsan017** [shopware/platform#2373]
### PHP Version

8.1

### Shopware Version

6.4.8.1

### Expected behaviour

Database connection should be established even without password.

I found the root cause is around [DatabaseConnectionInformation::asDsn](https://github.com/shopware/core/blob/92c94214f10333b6e3c6d28f7254216292471f9f/Maintenance/System/Struct/DatabaseConnectionInformation.php#L101) which strip-out both user and password when the password is empty

### Actual behaviour

Database connection error

### How to reproduce

- Clone https://github.com/shopware/production/
- Set env value of ```DATABASE_URL="mysql://root@localhost:3306/shopware_db_name"```
- Run ```php bin/console system:install```

**Comment by shyim** [comment]
Nice catch. You want to work on it?
