### ISSUE TITLE
Adding Blocks not possible in language other than 'English'

### ISSUE THREAD

**Issue by patarok** [shopware/platform#2375]
### PHP Version

8.0.14

### Shopware Version

6.4.8.1

### Expected behaviour

It should be possible to add blocks to layouts no matter the language chosen, **
either by clicking the plus below a block already there or in the sidebar.

**(.. actually FMPOV it should/could also be possible to have different blocks in each language... but thats not the point)

### Actual behaviour

If you have chosen 'DEUTSCH' f.i. and not 'English', you can not add blocks and the plus is greyed out for no 
obvious reason.
Even if you warn about that in some paragraph, somewhere in the Docs or in some tutorial, 
which I must have missed if it exists...
It's what I would call unexpected behaviour and 
it most likely will baffle and or disgruntle a lot of people who dont exercise prudence.

BTW: Either this behaviour exists since 6.0.0 and no one ever took care about it.
or we already had this in some version around in 2019/2020
... see the following related forum entries:
https://forum.shopware.com/t/erlebniswelten-block-hinzufugen/61030 -->(very much like the actual issue)
https://forum.shopware.com/t/blocke-hinzufugen-entfernen-geht-nichtmehr/70921 -->(maybe related)
https://forum.shopware.com/t/im-layout-editor-erlebniswelten-lassen-sich-keine-blocke-einfugen/60994 -->(maybe related)

### How to reproduce

1.) Just create a "Layout" fill it with blocks and fill their content in english first.
2.) Log out. >(I dont know if its only reproducable by logging out and)
3.) Log in.   >(than back in again, but i realized the issue on the next day after I logged in again)
4.) Switch to German 
5.) Open some Layout for edting(in my case it was a landing page)
6.) et voila -> Now the plus-icon for adding blocks is greyed out.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
