### ISSUE TITLE
keep theme settings with "Theme" (and pack 'em with it)

### ISSUE THREAD

**Issue by patarok** [shopware/platform#2376]
### Please describe the feature you would like to see implemented.

now:
Theme Variables in "projRoot/var/theme-variables.scss" directory which OBVIOUSLY does not belong to 'CustomTheme'

I am pretty sure it would be a better idea to keep a "" Themes 'Theme' "" alongside with the actual 'Theme' 

...so when at the moment it is:
"projRoot/var/theme-variables.scss"
it should actually be:
"projRoot/custom/plugins/ThemeName/src/Resources/app/storefront/src/scss/theme-variables.scss"

I guess there could be a sane and totally valid explanation
 for the actual location of the file (some technical reason maybe? ... )
 ?maybe because you want to strictly separate the shop settings from the Extensions/Themes Settings and want to avoid writing settings or attributes of an extension/theme outside its own 'settings'? 
 -- but if so you maybe want avoid offering themes settings on a GUI level outside the extension/theme...
  
 But I, as much as many others, would expect a Themes color-theme to stay with the theme... 
 The reason I have a problem with keeping it external also is:
 Besides my humble self, most other people who use apps like shopware don't have so much technical background, and  assuming this, 
 
 I also have to assume that most people would expect:
     that if they make those color, font and logo settings...
     they expect those settings to stay persistant after migrating their shop, 
     but at the moment I guess 
     the color
     and 
     logo settings 
         would get lost.
 
I am not a big fan of packing everything together and I guess I understand the idea of how you structure shopware, but 4-6 logo images, as well as some color and font variables wont make a whale out of a theme-extension structure.
I have already seen a lot of other shop-systems, and things can get pretty weird when theme overrides theme in something thats also called a theme which overrides a base theme, and then...
... yaeeey ... you also have to search for variables in a directory that has  nothing to do with a theme... not even by its name and is called "var", 
which may be short for "variable" but actually it is not meant for 
more or less constant variables 
that belong to a theme (which FMPOV would only change if the corporate design identy gets altered from time to time )
and that can or should not count as what others would define as "variable data"

I know we are not bound to follow *nixoid standards but most people expect 'var' to be 'var'
and 'etc' to be 'etc' and
according to FHS 'var' should be use for a directory that contains files which are expected to  continually change during normal operation of the system, such as logs,  spool files, and temporary e-mail files.

If you dont believe this humble novelist, look it up:
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

And Shopware 6 is pretty new, 
I see there is a chance to avoid splitting things up in unexpected ways. 
Therefore my request: 
Put that file somewhere else 
or do us all a favor and let:

$'php bin/console theme:create' 
also automagically create a 'Configuration' menu entry and logic with the same UI we now find in 
  '(Sidebar)Content' > Themes > Themename(*clicked)
for the context menu that pops up, when you click the ellipsis('...') next to your theme in
the themes listed in
  '(Sidbar)Extensions' > 'My extensions' > Themes(*clicked)  
  so when you click on 'Configuration' in that Ellipsis-context-menu next to the theme
  you get to see the same prefs that  at the moment are in 
  " '(Sidebar)Content' > Themes > Themename(*clicked)"
  ... so all the colors and Logos can be set there
  and should also save and pack with(in) the theme structure BTW and not outside. 
Doing so we would end up with still complete but colorizable themes.
I am pretty sure I miss something but I guess you get what my suggestion is, 
and I hope I was able to define it unambigously. 
I know times are hard as a developer and what i wrote here actually is clearly a 'TL;DR'-novel..
On the other hand I guess a 'two sentence'-'one paragraph' feature request may die away after a few days if it does not get closed already on "Day 1".  ¯\_(ツ)_/¯ 
At least this novel will make you think about it a second time before you dump it.

To KIS: I am pretty sure it _could_ be a good idea ... to keep theme settings with the theme. 
(and pack em with it)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
