### ISSUE TITLE
Provide PHP8 attributes in addition to annotations (like Symfony does)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2377]
### Please describe the feature you would like to see implemented.

Title says it all, after updating a project to PHP8 it is way more convenient to use attributes. However, e.g. your [RouteScope](https://github.com/shopware/platform/blob/v6.4.8.1/src/Core/Framework/Routing/Annotation/RouteScope.php) annotation, does not provide the PHP8 attributes.

Symfony currently provides both in their annotation definition: https://github.com/symfony/symfony/blob/v5.4.6/src/Symfony/Component/Routing/Annotation/Route.php#L24

I think it wouldn't be that difficult to add the necessary information to all annotations and maybe even mark the annotations as deprecated (so you can remove them e.g. with 6.6 once PHP 7.4 is EOL or not supported anymore by SW6).

**Comment by AndreasA** [comment]
From what I can see with the current sensio framework extra bundle (6.2.6) it should be easily possible to adjust the existing annotations to support both. which would be really nice.

**Comment by shyim** [comment]
I guess there are no userland annotation by us anymore as we moved them into the @Route annotation https://github.com/shopware/platform/blob/trunk/adr/api/2022-02-09-controller-configuration-route-defaults.md
