### ISSUE TITLE
Warning: Undefined array key "password" during installation

### ISSUE THREAD

**Issue by gnysek** [shopware/platform#2381]
### PHP Version

8.0

### Shopware Version

6.4.3.1

### Expected behaviour

Checking system requirements during installation.

### Actual behaviour

Error Exception.

### How to reproduce

1. Download Shopware installation
2. Run it.
3. When clicking "next", instead of "System requirements step", there's error: `Warning: Undefined array key "password"` caused by: `shopware/vendor/shopware/core/HttpKernel.php (line 85)`, which is
```$message = str_replace([$connectionParams['url'], $connectionParams['password'], $connectionParams['user']], '******', $e->getMessage());```.
Seems that `$connectionParams` array might be empty/misses some keys, and thus raises E_WARNING.

**Comment by obendev** [comment]
I suspect you're using Nginx. Are you sure your configuration is set up correctly?
```nginx
  location /recovery/install {
    try_files $uri /recovery/install/index.php$is_args$args;
  }

  location /recovery/update/ {
    if (!-e $request_filename){
      rewrite . /recovery/update/index.php last;
    }
  }

  location / {
    try_files $uri /index.php$is_args$args;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
  }
```
See
https://developer.shopware.com/docs/resources/references/config-reference/server/nginx 
Wayback Machine: https://web.archive.org/web/20220514142332/https://developer.shopware.com/docs/resources/references/config-reference/server/nginx

https://www.nginx.com/resources/wiki/start/topics/recipes/shopware/

**Comment by cainydev** [comment]
I have a similar problem.
The same exception in the same file but it arose immediately when accessing the server.

I tried @obendev suggestion but it didn't work for me.

Any ideas what I could try?

My current Nginx config looks like this:
```Nginx
server {
    server_name localhost;
    root /var/www/shopware/public;

    location / {
        # try to serve file directly, fallback to index.php
        try_files $uri /index.php$is_args$args;
    }

    location /recovery/install {
        try_files $uri /recovery/install/index.php$is_args$args;
    }

    location /recovery/update/ {
        if (!-e $request_filename){
            rewrite . /recovery/update/index.php last;
        }
    }
    location ~ ^/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/shopware_error.log;
    access_log /var/log/nginx/shopware_access.log;

}
```

**Comment by obendev** [comment]
@cainytheslave I might be wrong, but for me it looks like you're enabling PHP 8.1 FPM for index.php, but you're returning 404 for every other php file.
```nginx
location ~ \.php$ {
    return 404;
}
```
See https://developer.shopware.com/docs/resources/references/config-reference/server/nginx (They use FastCGI in this example)
or my snippet above

**Comment by nguyenytran** [comment]
I am using valet to config Nginx, so I also have the same problem

**Comment by shyim** [comment]
We rewrote the entire webinstaller. It should be improved

**Comment by torbentschechne** [comment]
> I am using valet to config Nginx, so I also have the same problem

I experience the same issue, second step in the installer and it fails even when I have a SW6 Driver for Valet. How did you fix it?
