### ISSUE TITLE
Implement a Class with static variables for all Criteria Events with titel

### ISSUE THREAD

**Issue by martinweinmayr** [shopware/platform#2400]
### Please describe the feature you would like to see implemented.

Since all the "new" Criteria Events which now also have a title it would be great to have a class in which all titles are stored as CONST similar to [PlatformRequest.php.](https://github.com/shopware/platform/blob/trunk/src/Core/PlatformRequest.php)

Would be much easier to find all the events where you want to add your product data for example.
So you could always take a look into the fixed titles and also a rename would work.
Today you have to click you throu and find out where are specific Criteria created to manipulate them all.
Especially when you want to add your Extensions to the main entities, this is a huge win.

Something Like

```
final class CriteriaEvents{

public const PRODUCT_EXPORT_CRITERIA = 'product-export::products'; #see https://github.com/shopware/platform/blob/084265f936ece1ca428488b0932ef91995695e9c/src/Core/Content/ProductExport/Service/ProductExportGenerator.php#L132

....

}
```

Would love to create the pr :-)

**Comment by keulinho** [comment]
I'm not sure about this, as the titles are mostly there for easier debugging and tracing, there are many criterias with a title, where no event exists to extend the criteria.

Also currently the `title` of an criteria is not part of a public API or something, with those constant we can't change the title anymore.

Maybe a 
```php
final class CriteriaEvents
{
    public const PRODUCT_EXPORT_CRITERIA_EVENT = ProductExportProductCriteriaEvent::class;

    ....
}
```

Would be better, classes like that already exist, e.g. `\Shopware\Core\Content\Product\ProductEvents`.

but whats hard about those classes is that they tend get out of sync, because they are not updated for every added event.

**Comment by martinweinmayr** [comment]
ok then my approach may not be the right one. 
At the end it would be good if you as a developer could ensure 
1. you can get to all criterias without having to decorate a whole service
2. you have a simple way to identify them.

**Comment by shyim** [comment]
I don't really see a benefit there. You can just search the whole code in milliseconds for a such string.

**Comment by martinweinmayr** [comment]
yea but then it is "luck" as a defined Variable or something else it would be safe. 
This maybe only trouble if you code in projects and don't know all the things which sw core devs know.

**Comment by shyim** [comment]
You can just search for `->setTitle('fooo'` or even use [structured search](https://www.jetbrains.com/help/phpstorm/structural-search-and-replace.html) in phpstorm.

Tbh: It looks not worth the time doing it :)

**Comment by martinweinmayr** [comment]
It's ok that it is closed but maybe there was a missunderstanding

My intend was to let devs know which events exists where they maybe have to extends some data for example for product export feed, or others.
therefore you would need central place to look for as you would not know that it is called "foo". 

see you on friday :-)
