### ISSUE TITLE
Cannot register customer without billingAddress 

### ISSUE THREAD

**Issue by ayZagen** [shopware/platform#2408]
### PHP Version

7.4.24

### Shopware Version

6.4.9.0

### Expected behaviour

Lots of e-commerce stores let's you create a user without requiring billing or shipment address in the initial registration form. So we should be able to register customer without billingAddress.

### Actual behaviour

Instead 500 server error is received:
```json
{
  "errors": [
    {
      "code": "0",
      "detail": "Call to a member function set() on null",
      "status": "500",
      "title": "Internal Server Error"
    }
  ]
}
```

### How to reproduce

Try to register a user with following body:
```json
{
  "email": "johndoe@example.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "password123"
}
```

```sh
curl 'http://localhost/store-api/account/register' \
  -H 'sw-language-id: SET_YOUR_LANGUAGE_ID' \
  -H 'Content-Type: application/json' \
  -H 'sw-access-key: SET_YOUR_ACCESS_KEY' \
  -H 'sw-context-token: SET_YOUR_CONTEXT_TOKEN' \
  --data-raw '{"firstName":"John","lastName":"Doe","email":"johndoe@example.com","password":"password123"}' 
```

**Comment by ayZagen** [comment]
A very dirty workaround is registering customers with a dummy address than trusting to frontend validation & content.

**Comment by shyim** [comment]
billing address is required by the system.
