### ISSUE TITLE
Option to disabled or modify HTTP headers

### ISSUE THREAD

**Issue by obendev** [shopware/platform#2414]
### Please describe the feature you would like to see implemented.

Currently, Shopware 6 is setting HTTP headers like `referrer-policy`, `x-content-type-options` and `x-frame-options`.
It would be nice to have an option to disable or modify these headers, since I'd like to set these headers via my Nginx configuration instead of letting it be handled by the web application (Shopware).
Can be found in [src/Core/Framework/Routing/CoreSubscriber.php](https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Routing/CoreSubscriber.php#L41)

c4d2a49fff2f4a60230b37a157127808d99c668d

**Comment by obendev** [comment]
@pweyck I'd do this myself, however I'm more of an administrator than a coder and I don't know how to implement a function that checks for a config option before applying the headers.
Is this a lot of work or rather easy to implement?
I don't think we'd need a GUI function here, a simple config true / false would do the trick in my opinion.

**Comment by moorl** [comment]
Check: https://symfony.com/doc/current/event_dispatcher/before_after_filters.html

KernelEvents::RESPONSE

**Comment by obendev** [comment]
Any chance we'll see this implemented in a Shopware 6.5.x version?
