### ISSUE TITLE
Paypal Checkout Plugin does not work

### ISSUE THREAD

**Issue by T3chTobi** [shopware/platform#2437]
### PHP Version

8.0

### Shopware Version

6.4.10.1

### Expected behaviour

A customer can pay with Paypal (after I have installed the Paypal Checkout Plugin)

### Actual behaviour

I have set up the PayPal plugin with PayPal Checkout. This system is apparently the successor of Paypal Plus. With this I have a big problem: No payments work anymore.

The following error message is displayed with in the log files:
```
Swag\PayPal\Checkout\Payment\PayPalPaymentHandler::pay (140): Required setting "landingPage" is missing or invalid {"error":"[object] (Swag\\PayPal\\Setting\\Exception\\PayPalSettingsInvalidException(code: 0): Required setting \"landingPage\" is missing or invalid at .../custom/plugins/SwagPayPal/src/OrdersApi/Builder/AbstractOrderBuilder.php:114)"} {"url":"/account/order/update/...","http_method":"POST","server":"...","file":".../custom/plugins/SwagPayPal/src/Checkout/Payment/PayPalPaymentHandler.php","callType":"->"}
```

In this [article](https://docs.shopware.com/de/shopware-6-de/erweiterungen/paypal#verhalten) it is described that in the paypal plugin settings there is an option to set the landing page. This option does not exist for me:

<img width="1017" alt="Bildschirmfoto 2022-04-24 um 21 23 43" src="https://user-images.githubusercontent.com/7794412/164993487-7e64e60b-7ecf-4a12-bf26-d3931ebfbef2.png">

That is the Paypal Checkout Plugin:
<img width="1035" alt="Bildschirmfoto 2022-04-24 um 21 23 54" src="https://user-images.githubusercontent.com/7794412/164993495-192efa3f-8f01-4184-ac5d-a271de76988f.png">

How can I fix this problem?

### How to reproduce

Install and setup the Paypal plugin with the new **CHECKOUT** system (**not** the old Paypal Plus system). Try to purchase an item with Paypal. Then you see the error message posted above in the log files...

**Comment by mstegmeyer** [comment]
Hi @T3chTobi,
somehow you are missing the `landingPage` setting, which should automatically be set during installation of the plugin (or on Update to Version > 2.0.0).

Unfortunately, there is a bug, that the field disappears, if no setting is set. Maybe, you could set the system config
`SwagPayPal.settings.landingPage` with the value `NO_PREFERENCE` manually? Alternatively, try to reinstall the plugin.

In the meantime, for the disappearing field, I have created a ticket in our issue tracker: https://issues.shopware.com/issues/PPI-637, I will therefore close the issue here.

**Comment by T3chTobi** [comment]
Thank you for your feedback!

Where and how can I access the system config?

**Comment by T3chTobi** [comment]
To add some context: This key `SwagPayPal.settings.landingPage` is not inside the `sytem_config` table inside the sql database. Should I add this key?

**Comment by mstegmeyer** [comment]
Yes, exactly, add the settings key with the column `sales_channel_id` being `null` (therefore the default for all Sales Channels)

**Comment by T3chTobi** [comment]
Thank you, it worked!
