### ISSUE TITLE
Paging in Custom-Field-Sets broken

### ISSUE THREAD

**Issue by digitalkaoz** [shopware/platform#2445]
### PHP Version

7

### Shopware Version

6.4.10

### Expected behaviour

Paging in Custom-Field-Sets works

### Actual behaviour

paging doesnt work. Always Page 1 is requested.

### How to reproduce

create more than 25 custom-field-sets and try to page to page 2.

**Comment by keulinho** [comment]
Should be fixed here: https://issues.shopware.com/issues/NEXT-21813
