### ISSUE TITLE
Flow builder (IF condition) and/or rules (in general) not working for customer related events.

### ISSUE THREAD

**Issue by TimWuyts** [shopware/platform#2451]
### PHP Version

8.1.5

### Shopware Version

6.4.10

### Expected behaviour

We've configured the flow builder to hook into certain customer related events. Eg: customer registration 
Depending on the outcome of certain rules (with conditions also related to the customer) assigned to an IF condition/sequence we would like to trigger additional actions, besides sending the default registration confirmation email.

Within the IF condition/sequence the RuleIds array of the context is always empty. While debugging we've also noticed that the rules are matched correctly whenever a user is logged in & navigating the site. 

### Actual behaviour

Only direct actions or actions assigned to a "false" outcome are executed. The actions related to a "true" outcome are never executed, since the ruleIds array remains empty within the current context.

### How to reproduce

We've tried the following triggers within the flow builder:
- user registration
- user login
- user recovery
- user activate / deactivate (custom events)

In all the above cases the rule matching is not executed, causing the ruleIds array to remain empty within the context. Hence always producing a "false" outcome in IF conditions within the flow builder.

**Comment by wuestenmagier** [comment]
I think, this could be solved with this issue https://issues.shopware.com/issues/NEXT-20816

**Comment by erix-code** [comment]
Well the same is happening with my custom flow builder trigger created by my own.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
