### ISSUE TITLE
Bootstrap 5 - Image slider Block

### ISSUE THREAD

**Issue by sawden** [shopware/platform#2456]
### PHP Version

7.4

### Shopware Version

6.4.10 with V6_5_0_0 flag

### Expected behaviour

The background behind the arrow navigation is white.

### Actual behaviour

The next and previous image are displayed under the arrow navigation.

![image](https://user-images.githubusercontent.com/36924392/165845802-5fd92c7b-f1aa-477a-ab40-1401d847e0d6.png)

### How to reproduce

Add a Image slider Block with multiple images and set the 'Arrow navigation' to 'Outside'.

**Comment by shyim** [comment]
The linked issue is fixed already
