### ISSUE TITLE
6.4.11.0 backwards compatbility

### ISSUE THREAD

**Issue by htuscher** [shopware/platform#2463]
### PHP Version

8.0

### Shopware Version

6.4.11.0

### Expected behaviour

A minor update should not break plugins that use common extension points.

### Actual behaviour

There's been an addition to the `ImageSliderTypeDataResolver`, a constructor argument that was not required in 6.4.10.0.

As many plugins may extend this DataResolver you could have added backwards compatibilty using a CompilerPass.

```php
class ImageSliderResolverFix implements CompilerPassInterface
{

    public function process(ContainerBuilder $container)
    {
        $resolverServices = $container->findTaggedServiceIds('shopware.cms.data_resolver');
        foreach (array_keys($resolverServices) as $serviceId) {
            $definition = $container->getDefinition($serviceId);
            $class = $definition->getClass();
            if (is_subclass_of($class, ImageSliderTypeDataResolver::class) && !$definition->getArguments()) {
                $definition->setArgument(0, new Reference('Shopware\Core\Content\Media\Cms\DefaultMediaResolver'));
            }
        }
    }
}
```

Maybe this could be improved in future minor updates.
Btw. Symfony does something similar in minor versions (sometimes even in majors).

### How to reproduce

Install any plugin that extends the ImageSliderTypeDataResolver and try to update Shopware.

**Comment by Isengo1989** [comment]
Same goes for all the other ***TypeDataResolver

**Comment by OliverSkroblin** [comment]
Regardless of whether we change it or not, just to have it mentioned.

The `__construct` of a service which is in the DI container is NOT a public API for us!

https://developer.shopware.com/docs/resources/guidelines/code/backward-compatibility

![image](https://user-images.githubusercontent.com/1035358/166698052-f1ef8ed5-df1d-4ee7-8aab-ddf16820733c.png)

**Comment by shyim** [comment]
https://symfony.com/doc/current/service_container/parent_services.html
In the services.xml there is also a way to use parent services

**Comment by moorl** [comment]
Give @shyim a medal 🥇 

```
<service id="MoorlFoundation\Core\Content\Media\Cms\DownloadListCmsElementResolver"
    parent="Shopware\Core\Content\Media\Cms\Type\ImageSliderTypeDataResolver">
    <tag name="shopware.cms.data_resolver"/>
</service>
```

**Comment by OliverSkroblin** [comment]
We closed the issue due to the fact that we don't see this as a break. We will not provide a patch for it

**Comment by OliverSkroblin** [comment]
Since already described, changing a `__construct` is not a break for us, I close the ticket. The affected plugins can work around the error as described by @shyim.
