### ISSUE TITLE
Update 6.4.11.0 failt

### ISSUE THREAD

**Issue by deBugger-** [shopware/platform#2464]
### PHP Version

8.1

### Shopware Version

6.4.10.1

### Expected behaviour

RuntimeException free update 

### Actual behaviour

**Fatal error** : Uncaught RuntimeException: Unexpected data in output buffer. Maybe you have characters before an opening <?php tag? in ...keepPrivate/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php:621 Stack trace: #0 ...keepPrivate/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php(317): Slim\App->finalize(Object(Slim\Http\Response)) #1 ...keepPrivate/vendor/shopware/recovery/Update/index.php(39): Slim\App->run() #2 ...keepPrivate/public/recovery/update/index.php(6): require_once('/var/www/vhosts...') #3 {main} thrown in **...keepPrivate/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php** on line **621**

where the migration assisten is installed
where "wartungsmodus" is enabled
where the database conains no demodatas or a data migration was running

### How to reproduce

Install sw6 ( install_v6.4.10.1_554a0747a4ff0f06210816552cdf804169a185c0.zip )
switch on the "Wartungsmodus"
start the 6.4.11.0 update

**Comment by porl** [comment]
I'm experiencing the same issue. Before the error I get many deprecation warnings, an example below:

`Deprecated: Return type of Pimple\Container::offsetExists($id) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /[...]/shopware/vendor/shopware/recovery/Common/vendor/pimple/pimple/src/Pimple/Container.php on line 133`

php version 8.1.5

**Comment by shyim** [comment]
Use PHP 8.0 for the updater, we will fix it in the next update that it works also in PHP 8.1
