### ISSUE TITLE
Disabled Category displayed in Navigation 

### ISSUE THREAD

**Issue by RevolteSolutions** [shopware/platform#2466]
### PHP Version

7.4.12

### Shopware Version

6.4.11.0

### Expected behaviour

After the update from 6.4.10.x  all hidden categories which should not be shown will be displayed in main navigation.

![image](https://user-images.githubusercontent.com/12423964/166912405-74fa6f43-fe32-4b08-b3a9-c06f18139149.png)

### Actual behaviour

The category is Shown in the Frontend but it's disabled in the backend. The setting (hide in navigation) doe not solve the problem. It's shown  

![image](https://user-images.githubusercontent.com/12423964/166912902-4c119ed0-0f3e-421e-87a2-e0482ad3c53e.png)

### How to reproduce

Create a category and disable it. Now show in frontend navigation. Normaly it should not be shown but it does.

**Comment by tinect** [comment]
Duplicates #2462
