### ISSUE TITLE
Make data import friendlier - e.g. optional first name, last name, optional addresses in database and if necessary validate the data during checkout

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2473]
### Please describe the feature you would like to see implemented.

Various larger customers require data to be automatically imported. However, their datasets are not always good, so e.g. they have customers without first name - especially the case for B2B where the company is actually more important. 

So, it would be good to allow such data to be stored and validate necessary fields later on during checkout and automatically update them.

Also it should be possible to easily change the required fields during checkout as e.g. a B2B order might not necessarily need first name / last name for a customer.

Some examples:
- Optional first name / last name fields
- Billing Address / Shipping address should be optional as very often a customer needs to be created without those data and it is added later on.

**Comment by ayZagen** [comment]
I believe this should be default behavior. For instance, why the first name or the last name required in registration ?? Most e-commerce platforms only requires email or phone number with a password. Making those fields required is easier than making them optional.

Mentioned also in #2408

**Comment by AndreasA** [comment]
I also agree that less data should be required by default because that way users can complete their registration early (email / password) and complete the remaining necessary data during checkout. 
One project made it necessary to add fake address data as it was used for a pickup shop and they do not really care about customer addresses in this case most of the time. Probably are not even allowed to collect them due to data protection laws. In this scenario, however, the customers do not even needed an email/password. At least guest customers didn't. 
Another project needed the integration of an existing SSO and in that scenario even the email address was missing initially, as not all had them and the login used a customer number / username instead of an email address and as it was an SSO the password field was unnecessary as well.

It would probably be best to make all customer related fields optional - at least in the database and use e.g. validation options in combination with a cart validator during checkout to determine what is needed there.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
