### ISSUE TITLE
DISABLE_EXTENSIONS=1 still uses ActiveAppsLoader - CompilerPass not used and produces exception if used.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2480]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

If `DISABLE_EXTENSIONS=1` either ensure that the ActiveAppsLoader does not return any apps or make sure the corresponding DisableExtensionsCompilerPass is used.

It can be fixed by either
1.  just checking for `DISABLE_EXTENSIONS` in the activeappsloader or better by decorating the acitve apps loader and checking for `DISABLE_EXTENSIONS=1` there and return empty array if false and only otherwise return true.
2. Ensure the compiler pass is used correctly: in the Framework class:
    - Adding it in the framework class like: `$container->addCompilerPass(new DisableExtensionsCompilerPass());`
    - Correct the code for the compiler pass:
    ```php
    public function process(ContainerBuilder $container): void
    {
        if (!EnvironmentHelper::getVariable('DISABLE_EXTENSIONS', false)) {
            return;
        }

        $container->getDefinition(ActiveAppsLoader::class)->setClass(EmptyActiveAppsLoader::class);
    }
    ```

### Actual behaviour

1. DisableExtensionsCompilerPass is not added as compiler pass which means the ActiveAppsLoader is still used.
2. the compiler pass does not change the service definition but the service completely which most likely will fail with ` You have requested a non-existent service "Shopware\Core\Framework\App\ActiveAppsLoader".`. At least it did for me.
`

### How to reproduce

Use `DISABLE_EXTENSIONS=1 bin/console deb:cont ActiveAppsLoader`. To be safe do a `rm -rf var/cache` first.

**Comment by keulinho** [comment]
Thanks for the detailed bug report. We will fix this.
