### ISSUE TITLE
Sorting products with main variants display odd price sorting in product listings

### ISSUE THREAD

**Issue by nuvalis** [shopware/platform#2489]
### PHP Version

8.1

### Shopware Version

6.4.9.0 and Cloud

### Expected behaviour

Sorting products in frontend should display the prices in correct order with main variant products, considering which main variant display price is used.

![Screenshot 2022-05-17 at 09 35 30](https://user-images.githubusercontent.com/4467675/168833565-02c98ba2-a1bb-4a02-9950-44d3a9e74f24.png)

### Actual behaviour

The prices seems to be sorted by the most expensive variant or randomly depending on the `group by` order on the `display_group` field on the product table.

The main variant is displayed independently from the sorting.

There may be some issues with multi-currency and the fallback mechanism as well.

SQL partial from the profiler
```
# cms::product-listing::search-ids
... snip ...
GROUP BY
    `product`.`display_group`
ORDER BY
    MAX(IFNULL((ROUND((ROUND(CAST((COALESCE((JSON_UNQUOTE(JSON_EXTRACT(`product`.`price`, "$.c616da58cf7244ac2b40b4a18967209b3.gross")) + 0.0), (JSON_UNQUOTE(JSON_EXTRACT(`product`.`price`, "$.cb7d2554b0ce847cd82f3ac9bd1c0dfca.gross")) * 1.000000))) AS DECIMAL (30, 20)), 2)) * 100, 0) / 100), (ROUND((ROUND(CAST((COALESCE((JSON_UNQUOTE(JSON_EXTRACT(`product.parent`.`price`, "$.c616da58cf7244ac2b40b4a18967209b3.gross")) + 0.0), (JSON_UNQUOTE(JSON_EXTRACT(`product.parent`.`price`, "$.cb7d2554b0ce847cd82f3ac9bd1c0dfca.gross")) * 1.000000))) AS DECIMAL (30, 20)), 2)) * 100, 0) / 100)))
    ASC
```

The price `c616da58cf7244ac2b40b4a18967209b3` is NOK and `cb7d2554b0ce847cd82f3ac9bd1c0dfca` is SEK. Which is a bit odd considering that we start mixing currency values as well for sorting. The MAX/MIN seems to flip on price-asc and price-desc.

And also a GROUP BY runs before the ORDER BY which creates even more headaches, so what ever value that is grouped is now used the in the order by.

The same behaviour happens in ElasticSearch.

### How to reproduce

Create products with variants eg. XS, S, M, L.

Set default prices on all variants XS (NOK 1.25), S (NOK 2.00), M(NOK 3.00), L(NOK 4.00). Change them around a bit each product.

Set the cheapest product as the main variant and one as the most expensive.

![Screenshot 2022-05-17 at 16 28 20](https://user-images.githubusercontent.com/4467675/168835893-2c272733-e743-400e-b939-6a124ae82b67.png)

Product Test 3: Main Variant XS
![Screenshot 2022-05-17 at 16 35 45](https://user-images.githubusercontent.com/4467675/168837499-2f69b7b3-b888-4680-8a6a-8372befd52bc.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
