### ISSUE TITLE
Update 6.4.11.0  fail

### ISSUE THREAD

**Issue by deBugger-** [shopware/platform#2496]
### PHP Version

8

### Shopware Version

6.4.11.1 

### Expected behaviour

browser: Warning: Potential Security Risk Ahead

### Actual behaviour

Websites prove their identity via certificates, which are valid for a set time period. The certificate for releases.shopware.com expired on 5/21/2022.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

### How to reproduce

Try to download 
https://releases.shopware.com/sw6/update_v6.4.11.1_0a5085747dae61e01b36b8388da7e5835c0c782c.zip

**Comment by shyim** [comment]
I tried to contact internally. You can update manually until its fixed. Just replace https with http in the URL

**Comment by janbuecker** [comment]
SSL certificate has been updated. Thank you, @deBugger-
