### ISSUE TITLE
Getting logged out when opening multiple tabs of product edit pages

### ISSUE THREAD

**Issue by Alphaegen** [shopware/platform#2497]
### PHP Version

8.0.9

### Shopware Version

6.4.10

### Expected behaviour

Multiple tabs to open correctly and being able to change the product information without needing to login again.

### Actual behaviour

Getting logged out and being returned to the login screen with this error on the screen:

`Cannot read properties of undefined (reading 'response')`

And this error in the network tab on the `message?limit=5` request:

`{"errors":[{"code":"9","status":"401","title":"The resource owner or authorization server denied the request.","detail":"The JWT string must have two dots"}]}`

### How to reproduce

1. Login to an administration panel of any Shopware site
2. Go to Catalogues -> Products
3. Use middle mouse button or ctrl + click to open at least +- 10 products in new tabs

It doesn't matter whether they are different products or the same. It's just easier to open multiple different products because of the name edit functionality.

**Comment by Alphaegen** [comment]
I've been able to reproduce this with as little as opening 3 products in quick succession.

**Comment by Alphaegen** [comment]
There's a correlation with having slow internet speeds, because using `slow 3g speed` in the throttling settings makes reproducing this issue with 2 products work almost all of the time.

**Comment by Alphaegen** [comment]
We've also tried copying the `BearerAuth` token and changing the `Expiration` from `Session` to a date in the future. This seems to fix getting logged out, but still redirects all pages to the dashboard page.

**Comment by Alphaegen** [comment]
It also doesn't seem to happen with any other entities when trying the same thing. These are some of the ones I've tried:
- Dynamic product groups
- Properties
- Customer
- Orders

**Comment by TimWuyts** [comment]
We're also being affected regularly by this issue after recent updates (assuming version 6.4.18) when the browser tab remains open for a while (approximately one hour).

**Comment by keulinho** [comment]
Thanks for reporting the issue, it should be fixed now by this commit: https://github.com/shopware/platform/commit/2e46cd7f9166bc8666838c7d18256cc0f54e311c

The fix will be included in the upcoming minor and the new major release, if you still experience any problems in that regard feel free to reopen this ticket.
