### ISSUE TITLE
Migration from 5.6.9 to latest 6.*

### ISSUE THREAD

**Issue by mewcrazy** [shopware/platform#2502]
### PHP Version

7.4 / 8.0

### Shopware Version

5.6.9 / 6.4.11.1

### Expected behaviour

Migrate the old site with 0 errors.

### Actual behaviour

1)
[warning] SWAG_MIGRATION__SHOPWARE_ASSOCIATION_REQUIRED_MISSING_PRODUCT_MANUFACTURER
Associated product_manufacturer not found
The product_manufacturer with the source id "67" can not be found but is required for promotion_discount.

2)
[info] SWAG_MIGRATION__SHOPWARE_UNSUPPORTED_OBJECT_TYPE
Unsupported object type
seo_url of object type "listing" with source id "36541" could not be converted.

3)
[error] SWAG_MIGRATION__WRITE_EXCEPTION_OCCURRED
A write exception has occurred
{
    "entity": "property_group_option",
    "dataId": "ffc684f07f064647ae26104381c8f6f4",
    "error": {
        "code": "c1051bb4-d103-4f74-8988-acbcafc7fdc3",
        "status": "400",
        "detail": "This value should not be blank.",
        "template": "This value should not be blank.",
        "meta": {
            "parameters": {
                "{{ value }}": "null"
            }
        },
        "source": {
            "pointer": "\/1090\/translations\/2fbb5fe2e29a4d70aa5854ce7ce3e20b\/name"
        }
    }
}

4)
[error] SWAG_MIGRATION__WRITE_EXCEPTION_OCCURRED
A write exception has occurred
{
    "entity": "customer",
    "dataId": "e7f79e3eccd34b85b3ff2a5489c15ab5",
    "error": {
        "code": "c1051bb4-d103-4f74-8988-acbcafc7fdc3",
        "status": "400",
        "detail": "This value should not be blank.",
        "template": "This value should not be blank.",
        "meta": {
            "parameters": {
                "{{ value }}": "null"
            }
        },
        "source": {
            "pointer": "\/234\/addresses\/1\/street"
        }
    }
}

5)
[error] SWAG_MIGRATION_RUN_EXCEPTION
An exception occurred
Entity: promotion, sourceId: edd013c3853f4ee1837ec5df7a9d62f4
There are 1 error(s) while writing data.1. [/1/code] Code may not have any leading or ending whitespaces

### How to reproduce

Migrate with our local database, and the following plugins installed:

bin/console plugin:install TrustedShops
bin/console plugin:install SwagCmsExtensions
bin/console plugin:install SwagMigrationAssistant
bin/console plugin:install SwagPlatformDemoData
bin/console plugin:install SwagFlowBuilder
bin/console plugin:install NimbitsThirdPartyIconsNext
bin/console plugin:install SwagLanguagePack 
bin/console plugin:install PickwareDhl
bin/console plugin:install NetzpNotifications6
bin/console plugin:install ebizoptimiweinccTrackingServicesSW6 
bin/console plugin:install SwagB2bPlatform
bin/console plugin:install SwagSocialShopping 
bin/console plugin:install IntediaDoofinderSW6
bin/console plugin:install SixProductShortDescription
bin/console plugin:install SwagPublisher
bin/console plugin:install DreiscSeoPro
bin/console plugin:install SwagCustomizedProducts
bin/console plugin:install MillProductPropertiesTab
bin/console plugin:install SemesHotjarIntegration6 
bin/console plugin:install NimbitsExtraBadgeNext
bin/console plugin:install SwagDynamicAccess
bin/console plugin:install SwagEnterpriseSearchPlatform
bin/console plugin:install MillCustomFieldTabs

**Comment by mewcrazy** [comment]
Could you give me a couple pin pointers where to look or fix those errors?

**Comment by mewcrazy** [comment]
I managed to fix errors **4 and 5**, the other ones, especially the missing translations value one still remains. If I just knew what source table it refers to.

**Fix for 4)**

UPDATE s_order_shippingaddress SET street = '-' where street = '';
UPDATE s_order_shippingaddress SET street = '-' where street IS NULL;

**Fix for 5)**

UPDATE s_emarketing_vouchers SET vouchercode = LTRIM(RTRIM(vouchercode));
UPDATE s_emarketing_vouchers SET description = LTRIM(RTRIM(description));
UPDATE s_emarketing_vouchers SET ordercode = LTRIM(RTRIM(ordercode));

**Comment by shyim** [comment]
This is not an issue with platform itself. Please create a issue in the issue tracker for that plugin
