### ISSUE TITLE
WebP Image thumbnails not generating

### ISSUE THREAD

**Issue by ayZagen** [shopware/platform#2509]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

WebP image thumbnails should be generated. 

### Actual behaviour

After you upload a webp image and assign it to a product thumbnails are empty. It works ok with png and jpg images.

### How to reproduce

Upload a webp image and assign it to a product. Than fetch product, thumbnails are empty.

```shell
php -r "print_r(gd_info());"
Array
(
    [GD Version] => 2.2.5
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 1
    [BMP Support] => 1
    [AVIF Support] =>
    [TGA Read Support] => 1
    [JIS-mapped Japanese Font Support] =>
)
```

**Comment by mitelg** [comment]
maybe related: https://github.com/shopware/platform/pull/2505

**Comment by SimonNitzsche** [comment]
related #2239

**Comment by ayZagen** [comment]
@SimonNitzsche those changes already included in 6.4.11.1, no exception is thrown in my case.

```sh
$ php -r "print_r(function_exists('imagewebp'));"
1
```

**Comment by SimonNitzsche** [comment]
Can't replicate on 6.4.11.1 on my side. Can upload webp just fine as a product image.

**Comment by ayZagen** [comment]
Uploading is fine but no thumbnails are generated

**Comment by SimonNitzsche** [comment]
I did following:
- Take a image, that hasn't been uploaded before
- Generate a webp out of it
- Upload it as a product image
- Check the storefront product detail page
- Thumbnails are generated as usual

**Comment by SimonNitzsche** [comment]
It may depend on the content of the webp, i only tested non-transparent ones so #2505 could be the thing

**Comment by ayZagen** [comment]
> It may depend on the content of the webp, i only tested non-transparent ones so #2505 could be the thing

Probably related with transparency because all of my images are converted from transparent pngs.

**Comment by ayZagen** [comment]
#2505 solves the problem. For those who need this ASAP just create a decorator until the pull request merged.

```php

<?php declare(strict_types=1);
namespace MyPlugin\Decorator;

use Shopware\Core\Content\Media\TypeDetector\ImageTypeDetector;

class ImageTypeDetectorDecorator extends ImageTypeDetector
{
  private function isWebpAnimated(string $filename): bool
  {
    $result = false;
    $fh = fopen($filename, 'rb');
    fread($fh, 12);
    if (fread($fh, 4) === 'VP8X') {
      fseek($fh, 20);
      $animationByte = fread($fh, 1);
      $result = (\ord($animationByte) >> 1) & 1 ? true : false;
    }
    fclose($fh);
    return $result;
  }
}
```

```xml
<!-- src/Resources/config/services.xml -->
<service id="MyPlugin\Decorator\ImageTypeDetectorDecorator"
      decorates="Shopware\Core\Content\Media\TypeDetector\ImageTypeDetector">
  <tag name="shopware.media_type.detector" priority="10"/>
</service>

```

**Comment by keulinho** [comment]
Should be fixed by https://issues.shopware.com/issues/NEXT-9366
