### ISSUE TITLE
PartialEntityLoadedEvent - internal only? shouldn't the same event be useable in custom plugins as well?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2511]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

Is there a reason why the partial entity loaded event is only internal?

### Actual behaviour

see above.

### How to reproduce

see above.

**Comment by shyim** [comment]
Partial data loading is still experimental and behind feature flag

**Comment by AndreasA** [comment]
@shyim Ok. but it will be usable feature in the future, so wouldn't it make more sense to allow developers to implement corresponding subscribers already - they just wouldn't do anything for now. 

This is why I think the internal flag is weird.

**Comment by shyim** [comment]
We are not 100% sure if this feature will solve many of our issues. So we will look for another solutions before we decide for which one we go

**Comment by AndreasA** [comment]
Ok. In that case it makes sense and I am closing this issue.
