### ISSUE TITLE
Deprecated RouteScope annotation breaks almost all existing plugins in combination with V6_5_0_0 feature flag

### ISSUE THREAD

**Issue by TimWuyts** [shopware/platform#2528]
### PHP Version

7.4

### Shopware Version

6.4.12

### Expected behaviour

We've set the V6_5_0_0 feature flag in order to already use Bootstrap 5 in our new projects. We should be able to implement Bootstrap 5 without being affected by other non-related issues. Would it be possible to introduce specific feature flag for Bootstrap 5 in order to avoid any external issues?

### Actual behaviour

Since the last update the "RouteScope" annotation is set to throw deprecation warnings in combination with V6_5_0_0 feature flag. With the flag enabled nog, almost all existing Shopware plugins are throwing deprecation warnings, since this code is heavily used in the controllers.

### How to reproduce

Setting the V6_5_0_0 feature flag.

**Comment by shyim** [comment]
I will close this issue as we will release 6.5 rc in few weeks
