### ISSUE TITLE
Database index naming is not compliant with Doctrine logic in `\Doctrine\DBAL\Schema\Index`

### ISSUE THREAD

**Issue by ScottA38** [shopware/platform#2538]
### PHP Version

valet-php@7.4

### Shopware Version

6.4.10.1

### Expected behaviour

`$doctrine->getSchemaManager()->listTables()` lists all entity tables available in DAL space

### Actual behaviour

Exception thrown

> An index with name 'fk.app' was already defined on table 'app'.
(`\Doctrine\DBAL\Schema\SchemaException`)

Exception trace:

> #0 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php(524): Doctrine\DBAL\Schema\SchemaException::indexAlreadyExists('fk.app', 'app')
#1 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php(75): Doctrine\DBAL\Schema\Table->_addIndex(Object(Doctrine\DBAL\Schema\Index))
#2 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(291): Doctrine\DBAL\Schema\Table->__construct('app', Array, Array, Array)
#3 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php(328): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails('app')
#4 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(270): Doctrine\DBAL\Schema\MySqlSchemaManager->listTableDetails('app')
#5 /Users/ScottAnderson/Tech/commissions/shopware-API/development/custom/plugins/SwagAllEntities/src/Storefront/Controller/EntitiesController.php(43): Doctrine\DBAL\Schema\AbstractSchemaManager->listTables()
#6 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/symfony/http-kernel/HttpKernel.php(152): Swag\AllEntities\Storefront\Controller\EntitiesController->showEntities()
#7 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#8 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#9 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/shopware/platform/src/Core/HttpKernel.php(153): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /Users/ScottAnderson/Tech/commissions/shopware-API/development/vendor/shopware/platform/src/Core/HttpKernel.php(79): Shopware\Core\HttpKernel->doHandle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /Users/ScottAnderson/Tech/commissions/shopware-API/development/public/index.php(53): Shopware\Core\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 /Users/ScottAnderson/.composer/vendor/weprovide/valet-plus/server.php(131): require('/Users/ScottAnd...')
#13 {main}

### How to reproduce

Run the following logic from a controller:

```
$doctrine = $this->container->get('Doctrine\DBAL\Connection');
$doctrine->getSchemaManager()->listTables();
```

The responsible code is the `\Doctrine\DBAL\Schema\AbstractAsset::_setName()` function (called at `development/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Index.php:67`). It splits the index name by dot, and then takes the first and second components from that name, discarding the rest

**Comment by shyim** [comment]
Update to the latest shopware version
