### ISSUE TITLE
Vuex duplicate getter key in administration

### ISSUE THREAD

**Issue by macster84** [shopware/platform#2543]
### PHP Version

7.4

### Shopware Version

6.4.12.0

### Expected behaviour

There should be no errors when browsing products in the administration in watch-mode.

### Actual behaviour

When admin-watch mode is enabled and I browse products in the administration, I see Vuex duplicate getter key errors being logged to the browser console.

```
09:35:33.826 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/isLoading
09:35:33.827 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/defaultCurrency
09:35:33.827 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/defaultPrice
09:35:33.827 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/defaultFeatureSet
09:35:33.828 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/productTaxRate
09:35:33.828 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/isChild
09:35:33.828 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/showModeSetting
09:35:33.830 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/showProductCard
09:35:33.831 vuex.esm.js?2f62:757 [vuex] duplicate getter key: swProductDetail/advanceModeEnabled
```

### How to reproduce

```bash
docker run --name shopware --rm -p 80:80 -p 8888:8888 dockware/dev:6.4.12.0
docker exec -it shopware bash
```

Within container:
```bash
cd
PUPPETEER_SKIP_DOWNLOAD=true make watch-admin
```

Wait until watcher is ready and navigate to `localhost:8888`.
Login with user `admin` and password `shopware`.

Open browser console.
Goto products and select the first product to enter the details.
Now navigate to product listing again and select the same product to enter the details once more.

See errors being logged in browser console

To destroy container eventually
```
docker rm -f shopware
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
