### ISSUE TITLE
Storefront: Automatic shipping method / payment method changing does not work correctly if missing name translation in current language

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2544]
### PHP Version

8.1

### Shopware Version

6.4.12.0

### Expected behaviour

Notice is correctly shown and page is reloaded to ensure all data is correctly updated.

### Actual behaviour

Shipping method changed notice is not added to cart, if the shipping method name/payment method name is not translated in the current language as the language fallabck chain is not used.
Therefore, there is also no page refresh after the shipping/payment method has been changed which might also result in incorrect content.

See https://github.com/shopware/platform/blob/v6.4.12.0/src/Storefront/Checkout/Payment/BlockedPaymentMethodSwitcher.php#L91
https://github.com/shopware/platform/blob/6.4.12.0/src/Storefront/Checkout/Shipping/BlockedShippingMethodSwitcher.php#L92

### How to reproduce

- Setup two languages `en-GB` and `de-DE` with default being `en-GB`
- Create two shipping methods and only store its content in `en-GB`.
- Ensure that upon quantity changes one of the shipping methods is not available anymore with availability rules (or corresponding price matrix).
- Open the page on `de-DE` and do all following steps on that page.
- During checkout, select the shipping method that will disappear upon quantity changes.
- On checkout confirm page, change the quantity so that the selected method is not available anymore.
- There will be no changed shipping method notice and there also is no additional redirect which means that the although the shipping method was selected, it might not be shown as selected and/or some other changes due to the shipping method change might not be shown correctly.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
