### ISSUE TITLE
Storefront: Automatic shipping method / payment method changing does not work correctly if two methods have the same name

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2548]
### PHP Version

8.1

### Shopware Version

6.4.12.0

### Expected behaviour

- If there are multiple shipping/payment methods with the same name, only the one which has a wrong availability rule should be excluded from possible shipping/payment methods.
- A scenario might be where the method switches but the user should not actually know about it.

**Solution**
- Add IDs to Block errors (shipping/payment).
- Add IDs to Changed errors.
- Use IDs to to filter out blocked methods.
- It would probably also make sense to not show the user the change message, if the new shipping method name is the same as the old one.
  - This could be done by adding an option to the cart error that avoids showing / adding it to the flashbag and makes them internal only, this could return true if both names are the same. Should have a setter, so it can be adjusted manually.

**Some general improvements**
- Avoid calling the shipping method route loader twice, e.g. call it once to retrieve all available and check if it contains the default method, if so return default, otherwise first.
- Add option to allow overriding the method name with a custom field label for the error (change and blocked). 
  - Or just add an admin vs. frontend label.

### Actual behaviour

Shipping/payment method is not correctly switched to another method, if it has the same name, upon exclusion of the inital one.

### How to reproduce

- Two shipping/payment methods with the same name.
- Different availability rules, where the exclude each other, e.g. one available in Germany, the other in all other countries.
- Now switching the address will not switch the shipping/payment method correctly (at least in one direction).

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
