### ISSUE TITLE
Internet explorer is officially deprecated and as Shopware we need to advice users to switch to another browser 

### ISSUE THREAD

**Issue by Glennjans** [shopware/platform#2557]
### Please describe the feature you would like to see implemented.

Hi all

Now that Internet Explorer is finally been put to the grave, it's time that Shopware acknowledges this and advices Internet explorer users to switch to another browser.

This can be done in a similar way as the JS notification. 

![image](https://user-images.githubusercontent.com/66824278/175236179-f6b143e4-190f-44b6-b0ca-22f29990b73a.png)

**Comment by tinect** [comment]
We dropped the support on our site years ago :-)

```
We have discontinued support for Internet Explorer.
It is no longer state-of-the-art in terms of security and technology. To be able to use our online service to full extent and for your protection, we recommend switching to a more up-to-date and safer web browser.
If you have any questions, please contact your administrator.
```

**Comment by Glennjans** [comment]
Great message, should be taken as an example ;-)

**Comment by shyim** [comment]
This will be already done in next major. We won't add such message in any patch version.
