### ISSUE TITLE
Delay function for Flow Builder

### ISSUE THREAD

**Issue by andersburn** [shopware/platform#2559]
### Please describe the feature you would like to see implemented.

Delay for 10 days, 2 hours or 30 days.

So you can send review mails to customers.
Or send a Manuel to customers who buys a single product. 
Or cancel orders that are open after x time

**Comment by m00n22** [comment]
Would love this feature.

Check if an order is open after x days, and send a reminder to shop owner.

Send store/product reviews after x days after order has been fulfilled.

So many possibilities to better assist us shop owners with our business and followups.

**Comment by keulinho** [comment]
Such a feature is on our current roadmap for the Beyond plan.

Check the [public roadmap](https://www.shopware.com/de/roadmap/) and search for `Delayed flow actions`.
