### ISSUE TITLE
Enable Twig Template Includes and Template Extensions in Mail Templates (using the StringTemplateRenderer)

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/platform#2563]
### Please describe the feature you would like to see implemented.

Hey there,

using the StringTemplateRenderer currently allows us to simply create simple Mail Templates in the Administration Area of Shopware. Unfortunately the current implementation of the StringTemplateRenderer only adds the ArrayLoader to the Twig Environment, which does not support the inclusion and extension of other twig templates.

This E-Mail Template is currently impossible in Shopware:

```twig
{% sw_extends '@Plugin/mail/mail_base.html.twig ' %}

{% block mail_content_main %}
    {% sw_include '@Plugin/mail/component/salutation.html.twig' with { customer: order.orderCustomer } %}
    
   <p> we are pleased to inform you ... </p>

   {% sw_include '@Plugin/mail/component/information-block.html.twig' %}

  <p>With kind regards,<br /> Your fulfillment team</p>
{% endblock %}
```

The inclusion and extensions of of Twig Templates could be easily enabled by passing a loader to the twig environment in the `render()` method of the StringTemplateRenderer:

```php 
public function render(string $templateSource, array $data, Context $context): string
    {
        $name = \md5($templateSource);
        $this->twig->setLoader(new ChainLoader([$this->platformTwig->getLoader(), new ArrayLoader([$name => $templateSource])]));
        ....
}
``` 

This simple inclusion would be a drop in replacement for the current implementation (all current templates would still work) and would greatly enhance the power of the Shopware E-Mail Templating system. 

- Merchants would not be limited to one header or footer per sales channel, they could create many different Types of E-Mails which could be used for transaction e-mails, follow up emails (using the flow builder) and newsletter emails (via plugins or their own implementations). They could do this, by simply extending different base templates in their email template.
- Plugin developers would be able to provide highly optimized base templates and email components, which could be easily extended and included.

I hope Shopware considers this change to be worth the effort. I think it would greatly simplify and enhance the email communication efforts of merchants and developers alike.

**Comment by shyim** [comment]
You can use install https://github.com/FriendsOfShopware/FroshPlatformTemplateMail. It does excactly that you want

**Comment by AlexBachmann** [comment]
This is great. Thank you @shyim. 

We have implemented this via plugin as well. I'd love this to land in the core though, mainly because it would open up an entire new plugin segment, which is: E-Mail Templates. And since we all know, how every developer hates to deal with email templates, I think Shopware should consider this.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
