### ISSUE TITLE
confirmUrl broken in plain-text double opt-in (contains HTML entities)

### ISSUE THREAD

**Issue by laf0rge** [shopware/platform#2579]
### PHP Version

7.4.30

### Shopware Version

6.4.12.0

### Expected behaviour

When using the double opt-in process for both guest users and user registration, the confirmation links/URLs should work both in the plain-text and in the HTML mail body.

"work" for plain-text means: I can copy+paste the URL from the mail client (e.g. mutt) to a browser, and complete the account confirmation.

### Actual behaviour

When using the double opt-in process for both guest users and user registration, the confirmation links/URLs are broken in the plain text version of the e-mails.

The plain-text e-mail looks like this:
<pre>
            Hello Mr. Frenchman,

            thank you for your signing up with sysmocom Webshop.
            Please confirm the sign-up via the following link:

            https://foobar/registration/confirm?em=182d952af07cf2c9bea7165417c6b1708671f8ea&a
mp;hash=d8b11af1f7c44716aa418a8042e7a774&amp;redirectTo=frontend.account.home.page

            By this confirmation, you also agree that we may send you further emails as part of the
fulfillment of the contract.
</pre>

Comparing the two URLs from the same e-mail, plaintext (first) vs HTML:
<pre>
https://foobar/registration/confirm?em=182d952af07cf2c9bea7165417c6b1708671f8ea&a
mp;hash=d8b11af1f7c44716aa418a8042e7a774&amp;redirectTo=frontend.account.home.page
vs

https://foobar/registration/confirm?em=182d952af07cf2c9bea7165417c6b1708671f8ea&hash=d8b11af1
f7c44716aa418a8042e7a774&redirectTo=frontend.account.home.page
</pre>

So, as we can see, the plain-text version of the link also uses HTML quoting entities like `&amp;` which of course must not be used in non-HTML context.

So when this broken URL is copied+pasted into a browser, the webshop responds with a NoHashProvidedException "the given hash is empty".

### How to reproduce

- Standard / default installation of shopware. 
- Enable double opt-in for either guest or registered users.  
- Register a new user or do a guest checkout
- Wait until the registration mail is received
- compare the URLs in the text/plain MIME section with the text/html section
- observe the HTML URL is correct, while the plain text is broken.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
