### ISSUE TITLE
Redis cart persister can't remove last item from cart

### ISSUE THREAD

**Issue by lutek** [shopware/platform#2581]
### PHP Version

7.4

### Shopware Version

6.4.12.0

### Expected behaviour

Add and remove item from cart

### Actual behaviour

Add to cart one item and remove, last item always persist in cart. It's not possible to remove it.

### How to reproduce

enable in config.

```
shopware:
    cart:
        redis_url: '%env(string:REDIS_URL)%/3?persistent=1'
```

**Comment by tinect** [comment]
https://github.com/shopware/platform/pull/2536

Already fixed. Will be part of 6.4.13.0 regarding https://issues.shopware.com/issues/NEXT-21994
