### ISSUE TITLE
Remove a Required() Flag in MediaFolderDefinition

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2582]
### PHP Version

7.4

### Shopware Version

6.4.12.0

### Expected behaviour

Since Shopware apps with own upload features have to create own folders in the media manager. I need to inherit the confgurationId from any other folder (like products) to create a new folder. In some situations my customers deleted this folder, and the plugin crash on installation.

The property configurationId has a required flag. It's not necessary but I can't create new "Folders" without a configurationId. 

Just let the configuration be optional to avoid errors.

### Actual behaviour

-

### How to reproduce

-

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/FroshAppWebDav/blob/2ffd78661e7feca90c8ca142e0f4689ecd326f19/src/handler.ts#L364 it works 🤔

**Comment by moorl** [comment]
@shyim 
Thank you. In this case a new configuration is created. But I can deal with it :)
