### ISSUE TITLE
OrderDelivery requires shippingCosts even though it should not according to the documentation

### ISSUE THREAD

**Issue by SimonBKohlschein** [shopware/platform#2588]
### PHP Version

8.1.7

### Shopware Version

6.4.12.0

### Expected behaviour

An Order Delivery for the order should be created.

### Actual behaviour

The server will respond with:
`{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"An exception occurred while executing \u0027INSERT INTO `order_delivery` (`id`, `version_id`, `order_id`, `order_version_id`, `shipping_order_address_id`, `shipping_order_address_version_id`, `shipping_method_id`, `state_id`, `tracking_codes`, `shipping_date_earliest`, `shipping_date_latest`, `created_at`) VALUES (\u0027\ufffd\ufffdPb\ufffdOO]\ufffd\ufffd|\ufffd|\ufffd\ufffdb\u0027,\u0027\u000f\ufffd\u001c\ufffd\ufffdjK\u00beK\ufffd\ufffdu,4%\u0027,\u0027q\ufffd]I\ufffd\u003EB\u06de\u001c\ufffd\ufffd{\ufffdH\\\\\u0027,\u0027\u000f\ufffd\u001c\ufffd\ufffdjK\u00beK\ufffd\ufffdu,4%\u0027,\u0027\ufffd\ufffd\u0016yZ\ufffdB\ufffd\ufffd\ufffd5s.\ufffdJ\ufffd\u0027,\u0027\u000f\ufffd\u001c\ufffd\ufffdjK\u00beK\ufffd\ufffdu,4%\u0027,\u0027\ufffd\ufffd\ufffd7K\ufffd\ufffd\ufffdX\ufffd\u0026\ufffd\ufffd \u0027,\u0027I\u0018A\ufffd\ufffdXJ*\ufffd4\ufffd\ufffd\ufffd\\\u0022\ufffd\u0027,\u0027[]\u0027,\u00272022-07-07 00:00:00.000\u0027,\u00272022-07-07 00:00:00.000\u0027,\u00272022-07-05 14:01:30.987\u0027);\u0027:\n\nSQLSTATE[HY000]: General error: 1364 Field \u0027shipping_costs\u0027 doesn\u0027t have a default value","meta":{"trace":[{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":182,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":159,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":2226,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1538,"function":"handleExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/MultiInsertQueryQueue.php","line":89,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1670,"function":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\{closure}","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\MultiInsertQueryQueue","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":30,"function":"transactional","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":19,"function":"retry","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/MultiInsertQueryQueue.php","line":91,"function":"retryable","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":245,"function":"execute","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\MultiInsertQueryQueue","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":141,"function":"executeCommands","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1670,"function":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\{closure}","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":30,"function":"transactional","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":19,"function":"retry","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":142,"function":"retryable","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Write\/EntityWriter.php","line":204,"function":"execute","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Write\/EntityWriter.php","line":140,"function":"write","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/VersionManager.php","line":118,"function":"insert","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/EntityRepository.php","line":154,"function":"insert","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\VersionManager","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":916,"function":"create","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepository","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Context.php","line":207,"function":"Shopware\\Core\\Framework\\Api\\Controller\\{closure}","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":934,"function":"scope","class":"Shopware\\Core\\Framework\\Context","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":818,"function":"executeWriteOperation","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":454,"function":"write","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":152,"function":"create","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":74,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/Kernel.php","line":202,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/SubRequestHandler.php","line":86,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":479,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":269,"function":"forward","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":285,"function":"pass","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":213,"function":"invalidate","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/HttpKernel.php","line":153,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/HttpKernel.php","line":79,"function":"doHandle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/public\/index.php","line":74,"function":"handle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"}],"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","line":125,"previous":[{"code":"HY000","status":"500","title":"Internal Server Error","detail":"SQLSTATE[HY000]: General error: 1364 Field \u0027shipping_costs\u0027 doesn\u0027t have a default value","meta":{"trace":[{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php","line":60,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1534,"function":"exec","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/MultiInsertQueryQueue.php","line":89,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1670,"function":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\{closure}","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\MultiInsertQueryQueue","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":30,"function":"transactional","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":19,"function":"retry","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/MultiInsertQueryQueue.php","line":91,"function":"retryable","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":245,"function":"execute","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\MultiInsertQueryQueue","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":141,"function":"executeCommands","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1670,"function":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\{closure}","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":30,"function":"transactional","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":19,"function":"retry","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":142,"function":"retryable","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Write\/EntityWriter.php","line":204,"function":"execute","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Write\/EntityWriter.php","line":140,"function":"write","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/VersionManager.php","line":118,"function":"insert","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/EntityRepository.php","line":154,"function":"insert","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\VersionManager","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":916,"function":"create","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepository","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Context.php","line":207,"function":"Shopware\\Core\\Framework\\Api\\Controller\\{closure}","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":934,"function":"scope","class":"Shopware\\Core\\Framework\\Context","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":818,"function":"executeWriteOperation","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":454,"function":"write","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":152,"function":"create","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":74,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/Kernel.php","line":202,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/SubRequestHandler.php","line":86,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":479,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":269,"function":"forward","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":285,"function":"pass","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":213,"function":"invalidate","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/HttpKernel.php","line":153,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/HttpKernel.php","line":79,"function":"doHandle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/public\/index.php","line":74,"function":"handle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"}],"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDO\/Exception.php","line":18,"previous":[{"code":"HY000","status":"500","title":"Internal Server Error","detail":"SQLSTATE[HY000]: General error: 1364 Field \u0027shipping_costs\u0027 doesn\u0027t have a default value","meta":{"trace":[{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php","line":55,"function":"exec","class":"PDO","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1534,"function":"exec","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/MultiInsertQueryQueue.php","line":89,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1670,"function":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\{closure}","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\MultiInsertQueryQueue","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":30,"function":"transactional","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":19,"function":"retry","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/MultiInsertQueryQueue.php","line":91,"function":"retryable","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":245,"function":"execute","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\MultiInsertQueryQueue","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":141,"function":"executeCommands","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1670,"function":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\{closure}","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":30,"function":"transactional","class":"Doctrine\\DBAL\\Connection","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Doctrine\/RetryableTransaction.php","line":19,"function":"retry","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Dbal\/EntityWriteGateway.php","line":142,"function":"retryable","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Doctrine\\RetryableTransaction","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Write\/EntityWriter.php","line":204,"function":"execute","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Dbal\\EntityWriteGateway","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/Write\/EntityWriter.php","line":140,"function":"write","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/VersionManager.php","line":118,"function":"insert","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\EntityWriter","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/DataAbstractionLayer\/EntityRepository.php","line":154,"function":"insert","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\VersionManager","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":916,"function":"create","class":"Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepository","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Context.php","line":207,"function":"Shopware\\Core\\Framework\\Api\\Controller\\{closure}","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":934,"function":"scope","class":"Shopware\\Core\\Framework\\Context","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":818,"function":"executeWriteOperation","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/Framework\/Api\/Controller\/ApiController.php","line":454,"function":"write","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":152,"function":"create","class":"Shopware\\Core\\Framework\\Api\\Controller\\ApiController","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":74,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/Kernel.php","line":202,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/SubRequestHandler.php","line":86,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":479,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler","type":"::"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":269,"function":"forward","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":285,"function":"pass","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php","line":213,"function":"invalidate","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/HttpKernel.php","line":153,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/shopware\/core\/HttpKernel.php","line":79,"function":"doHandle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"},{"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/public\/index.php","line":74,"function":"handle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"}],"file":"\/usr\/www\/users\/kohlsw\/staging_shopware\/vendor\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php","line":55}}]}}]}}]}`

According to [shopwares documentation ](https://shopware.stoplight.io/docs/admin-api/c2NoOjE0MzUxMjc1-order-delivery)it should not be required to add shippingCosts to the request.

### How to reproduce

Send this REST API request: 
`{
  "trackingCode": [
    "328432328"
  ],
  "shippingMethodId": "THE_ID_OF_THE_SHIPPING_METHOD",
  "shippingOrderAddressId": "THE_ADDRESS_ID",
  "stateId": "THE_STATE_ID",
  "shippingDateEarliest": "2022-07-07T00:00:00.000+00:00",
  "shippingDateLatest": "2022-07-07T00:00:00.000+00:00"
}
`
to https://yourshopwareinstance/api/order/ORDER_ID/deliveries via POST.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
