### ISSUE TITLE
/_action/sync product Entity options will be created every time, reference by name

### ISSUE THREAD

**Issue by rubberfashion** [shopware/platform#2599]
### PHP Version

7.4.28

### Shopware Version

6.4.11.1 

### Expected behaviour

By an product upsert with options [groupId,name] i would expect that the option is created unique by name reference.
If i do a second upsert with another product i would expect that the option with the same name will not be created.
If i use the unique id, the problem does not occure.

### Actual behaviour

If i do the upsert again with same data, the API create second option with same name.

### How to reproduce

Create two different varianty with api/_action/sync with same option with [groupId,name]. e.g. color black, size S / M. You can check on the options page that the options is created twice.

**Comment by shyim** [comment]
We don't consider this as a bug. It's currently intended so.
We have a ticket to change this behavior, but it's not so much prioritized
https://issues.shopware.com/issues/NEXT-17459
