### ISSUE TITLE
API : Can't fetch order with a specific versionId

### ISSUE THREAD

**Issue by IndeedEvan** [shopware/platform#2607]
### PHP Version

8.0.1

### Shopware Version

6.4.6.1

### Expected behaviour

Hello everybody 😄 

I was trying to build an external accountancy tool for my shop, using [Vin\ShopwareSdk](https://github.com/vienthuong/shopware-php-sdk) package i'm connected to the API, everything works perfectly 💯 

To get my accountancy done, i'm fetching orders with some classic filtering that works good on the package side : 
```
$criteria->addFilter(new MultiFilter('and', 
		array(
			new EqualsAnyFilter('orderNumber', array_column($orders_id, 'id')), 
			new EqualsAnyFilter('versionId', array_column($orders_id, 'version'))
		)
	)
);
```

I'm getting a specific version of the order since after I added credits products, the total of the order is modified by Shopware (for a full refund total = 0.00 € for example)

**The problem is the following** : I can only fetch the last version of the order (I checked the "last_updated_at field in database)

**What I'm going to try next** : fetch document with associated order to see if the old version of the order is fetched

### Actual behaviour

The order is fetched only if versionId match the last versionId of the order.

### How to reproduce

- Connect to SW6 API
- Try to fetch order with specific versionId that is not the last versionId

**Comment by shyim** [comment]
You need to send a `sw-version-id` header.

**Comment by IndeedEvan** [comment]
Oh great, can I send like 100 version Ids in that header.. since i'm
getting 100 orders from the API ?

**Comment by shyim** [comment]
nope thats not possible. But why do you need that? Normally you fetch only the live version (which is the one without version id passing)

**Comment by IndeedEvan** [comment]
The original order "price" json look like that in database : 
``` 
{
    "netPrice": 38.03,
    "rawTotal": 40.72,
    "taxRules": [
        {
            "taxRate": 5.5,
            "extensions": [],
            "percentage": 100
        },
        {
            "taxRate": 20,
            "extensions": [],
            "percentage": 100
        }
    ],
    "taxStatus": "gross",
    "totalPrice": 40.72,
    "positionPrice": 35.82,
    "calculatedTaxes": [
        {
            "tax": 1.87,
            "price": 35.82,
            "taxRate": 5.5,
            "extensions": []
        },
        {
            "tax": 0.82,
            "price": 4.9,
            "taxRate": 20,
            "extensions": []
        }
    ]
}
``` 

Then I added credit produits + shipping costs in credits as my client got a refund, the new version of the order look like that : 
```
{
    "netPrice": 0,
    "rawTotal": 0,
    "taxRules": [
        {
            "taxRate": 5.5,
            "extensions": [],
            "percentage": 100
        },
        {
            "taxRate": 20,
            "extensions": [],
            "percentage": 100
        }
    ],
    "taxStatus": "gross",
    "totalPrice": 0,
    "positionPrice": -4.9,
    "calculatedTaxes": [
        {
            "tax": 0,
            "price": 0,
            "taxRate": 5.5,
            "extensions": []
        },
        {
            "tax": 0,
            "price": 0,
            "taxRate": 20,
            "extensions": []
        }
    ]
}
```

It might be specific to french tax system but we need to have a excel file that shows the two steps of the order in case of refund : the original order **and** the credits notes data if we do a partial or total refund. Since adding credit produits modify the totals of the order (maybe for statistics matter ?) I need to acces to older versions of it...

Sorry, maybe it's something really specific to french tax system 😅

**Comment by shyim** [comment]
Normally you edit the order and then do a merge version. So that modification will be live
