### ISSUE TITLE
Getting constant deprecation messages when running cli commands

### ISSUE THREAD

**Issue by Alphaegen** [shopware/platform#2613]
### PHP Version

7.4

### Shopware Version

6.4.13.0

### Expected behaviour

No deprecation warnings when running cli commands. We didn't have the deprecation warnings before updating to a newer versions so I'm not sure whether this is a problem with our Shopware project or normal in the new version.

### Actual behaviour

Any of the following commands wil output different deprecation warnings:
- bin/build-storefront.sh
- bin/build-administration.sh
- bin/build.sh
- bin/console messenger:consume -vv

Example warnings:
`Builder" is deprecated and will be removed in v6.5.0.0. Use "AbstractPropertyGroupSorter, AbstractProductMaxPurchaseCalculator, AbstractIsNewDetector" instead. ["exception" => ErrorException { …}]`

```bash
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($border-radius-default, 2) or calc($border-radius-default / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
3 │ $sw-label-border-radius: $border-radius-default / 2;
  │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    stdin 3:26  root stylesheet
```

### How to reproduce

My specific project might be needed to reproduce this, but simply running commands shows the messages above.

**Comment by scriptibus** [comment]
Same issue for me.

**Comment by shyim** [comment]
https://issues.shopware.com/issues/NEXT-22711 will be hopefully merged this week
