### ISSUE TITLE
Inactive product not removed and no error added from cart due to data timestamp being set.

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2615]
### PHP Version

8.1

### Shopware Version

6.4.11.1

### Expected behaviour

A disabled product should always be removed from the cart and/or an error should be added to let the user know and the cart cannot be ordered.

However, currently if a product is in the cart it is not removed as you only check for the data timestamps existence but not its last update and the data timestamp is stored in the database.

I tested this with 6.4.11.1 but it should also be the case for newer versions according to changelog and source code.

See:
https://github.com/shopware/platform/blob/v6.4.13.0/src/Core/Content/Product/Cart/ProductCartProcessor.php#L188
https://github.com/shopware/platform/blob/v6.4.13.0/src/Core/Checkout/Cart/CartPersister.php#L83
https://github.com/shopware/platform/blob/v6.4.13.0/src/Core/Checkout/Cart/CartPersister.php#L47

### Actual behaviour

Product has been disabled (either through removing visibility or checkbox) but it still is in the cart.

### How to reproduce

- Add product to cart.
- Call cart store API (probably also works using Storefront and going to cart page).
- Open admin and disable product or remove its visibility.
- Re-call store API.

The cart has no errors and the product is still there.

**Comment by AndreasA** [comment]
In general not loading products in the product cart processor seems like a bad idea as e.g. other cart processors / collectors might depend on that information.

If the product is not in the data collection, they manually need to load them which creates more database queries actually. So either add an event to allow reloading flag to be modified or find a better solution.
It might even be possible that they have additional data where they need something from the product that does not trigger a product update itself, so the updated at timestamp would not work. Sure, they could store the necessary data in a cart's extension but that is way more cumbersome and the extension would need to be safe to use during deserialization, so only ArrayStruct really works well.

Or a product's price changes etc. Though I guess this might result in the product being loaded due to updated timestamp changing.

**Comment by shyim** [comment]
there is an PR to fix this

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
