### ISSUE TITLE
TestDefaults used in non-dev code

### ISSUE THREAD

**Issue by apfelbox** [shopware/platform#2619]
### PHP Version

8.1.8

### Shopware Version

6.4.13.0

### Expected behaviour

The constants from `Shopware\Core\Test\TestDefaults` (https://github.com/shopware/platform/blob/trunk/src/Core/Test/TestDefaults.php) are used in core code, here:

https://github.com/shopware/platform/blob/trunk/src/Core/Defaults.php#L16

and 

https://github.com/shopware/platform/blob/trunk/src/Core/Defaults.php#L26

This will break in production as the `Shopware\Core\Test\TestDefaults` is excluded from classmap generation here:

https://github.com/shopware/platform/blob/trunk/composer.json#L416

### Actual behaviour

It breaks:

```
In BaseContextFactory.php line 127:

  [Symfony\Component\ErrorHandler\Error\ClassNotFoundError]
  Attempted to load class "TestDefaults" from namespace "Shopware\Core\Test".
  Did you forget a "use" statement for "Shopware\Core\Test\TestDefaults"?
```

### How to reproduce

This should happen in all prod-builds.

**Comment by keulinho** [comment]
Hey @apfelbox,

thanks for bringing this issue up.
You are completely right, the `Defaults.php` should not rely on any Test-class.

I've created [an issue](https://issues.shopware.com/issues/NEXT-22584) and already fixed it, the fix should be merged soon :tm:
