### ISSUE TITLE
"theme:compile" command fails with Google Storage as FS

### ISSUE THREAD

**Issue by WipeAir** [shopware/platform#2637]
### PHP Version

8.0/8.1

### Shopware Version

6.4.13.0

### Expected behaviour

I'd expect that the "theme:compile" command successfully compiles the theme and copies all files to the Google Storage bucket.

### Actual behaviour

The command fails with the following exception:
```
League\Flysystem\Filesystem::putStream expects argument #2 to be a valid resource.
```

### How to reproduce

The issue can be reproduced with a default installation. Just use Google Storage as FS and try to compile the theme.
In my case, it failed when copying the fonts to the themes folder. (Because it has multiple target files?)

After some debugging, I've resolved the issue for my case with the following:
It seems that the [`fopen` stream from CopyBatch](https://github.com/shopware/platform/blob/d6c853ca3b6b167d61d70e6329f4fcface5c5245/src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatch.php#L31) will be consumed multiple times [in some cases](https://github.com/shopware/platform/blob/d6c853ca3b6b167d61d70e6329f4fcface5c5245/src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatch.php#L34-L36). So a quick fix was to move the `fopen` into the second foreach-loop.

**Comment by shyim** [comment]
I will close this issue as we have changed the complete filesystem behaviour in next major version and it should work
