### ISSUE TITLE
If the order has an error with the blockOrder flag, the checkout confirm button remains enabled and clickable

### ISSUE THREAD

**Issue by sevarozh** [shopware/platform#2649]
### PHP Version

8.0

### Shopware Version

6.4.14

### Expected behaviour

If the order has an error with the blockOrder flag, the checkout confirm button must be disabled.

### Actual behaviour

Button remains enabled and clickable

### How to reproduce

- set phone number as mandatory field in admin
- select the billing address without phone in checkout
- flash error is displayed, but confirm button remains enabled

see https://github.com/shopware/platform/commit/bec6ac21a78ab84c7181dac2347e3e670f92033c#commitcomment-81208122

**Comment by mstegmeyer** [comment]
See here, please vote there. https://issues.shopware.com/issues/NEXT-22205

**Comment by shyim** [comment]
I will close this as its duplicate to https://github.com/shopware/platform/issues/2542
