### ISSUE TITLE
database:migrate-destructive command handles migrations in original order

### ISSUE THREAD

**Issue by lukaslangen** [shopware/platform#2652]
### PHP Version

8.0

### Shopware Version

^6.4.13 probably also earlier

### Expected behaviour

When running `bin/console database:migrate-destructive` command the migrations should be run in reverse order, to ensure, that all tables, that should be dropped, can be dropped, even when using foreign keys.

### Actual behaviour

Running `bin/console database:migrate-destructive`, while also defining foreign keys in the `update` method of a migration fails, if the foreign key references a table, that was defined in a previous migration.

The migrations are ordered in ascending order by their creation timestamp in [Shopware\Core\Framework\Migration\MigrationRuntime::getExecutableMigrationsBaseQuery()](https://github.com/shopware/platform/blob/710886f346e2a6b194cc46ef43db23600028e6dd/src/Core/Framework/Migration/MigrationRuntime.php#L129)

### How to reproduce

Create two migrations:

```php
<?php declare(strict_types=1);

namespace PluginRoot\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\MigrationStep;

final class Migration1658809705TestTable extends MigrationStep
{
    public function getCreationTimestamp(): int
    {
        return 1658809705;
    }

    public function update(Connection $connection): void
    {
        $sql = <<<SQL
        CREATE TABLE IF NOT EXISTS `test_table` (
            `id` BINARY(16) NOT NULL,
            PRIMARY KEY (`id`)
        )
        ENGINE = InnoDB
        DEFAULT CHARSET = utf8mb4
        COLLATE utf8mb4_unicode_ci;
        SQL;

        $connection->executeStatement($sql);
    }

    public function updateDestructive(Connection $connection): void
    {
        $sql = <<<SQL
        DROP TABLE IF EXISTS `test_table`;
        SQL;

        $connection->executeStatement($sql);
    }
}

```

```php
<?php declare(strict_types=1);

namespace PluginRoot\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\MigrationStep;

final class Migration1658921940TableWithForeignKey extends MigrationStep
{
    public function getCreationTimestamp(): int
    {
        return 1658921940;
    }

    public function update(Connection $connection): void
    {
        $sql = <<<SQL
        CREATE TABLE IF NOT EXISTS `table_with_foreign_key` (
            `id` BINARY(16) NOT NULL,
            `test_table_id` BINARY(16) NOT NULL,
            PRIMARY KEY (`id`),
            FOREIGN KEY (`test_table_id`) 
                REFERENCES `test_table` (`id`)
                ON DELETE CASCADE
        )
        ENGINE = InnoDB
        DEFAULT CHARSET = utf8mb4
        COLLATE utf8mb4_unicode_ci;
        SQL;

        $connection->executeStatement($sql);
    }

    public function updateDestructive(Connection $connection): void
    {
        $sql = <<<SQL
        DROP TABLE IF EXISTS `table_with_foreign_key`;
        SQL;

        $connection->executeStatement($sql);
    }
}
```

Run `bin/console database:migrate` for the plugin.

Afterwards try to run `bin/console database:migrate-destructive` for the plugin. This will fail with:

`Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails`

I will try to create a merge request for a fix as it seems trivial, after I had time to actually read the contributing guide, which will probably tomorrow. I just wanted to provide some information on this beforehand. Also I'd be interested if there was a specific reason to implement it like this, as it doesn't seem intuitive to me.

**Comment by shyim** [comment]
That's not a bug. Destructive migrations are not for rollbacking mgirations.

It's for blue green compatiblity, so you can remove old columns there
