### ISSUE TITLE
administration:watch does not work

### ISSUE THREAD

**Issue by rammi22** [shopware/platform#2663]
### PHP Version

8.0.22

### Shopware Version

6.4.14.0

### Expected behaviour

`administration:watch` has to provide the page on `http://localhost:8080`

### Actual behaviour

> Die Website ist nicht erreichbar

No access to the page (after upgrade host-System to Ubuntu 22.04)

### How to reproduce

My system: Ubuntu 22.04 LTS

- Install a fresh [shopware/platform](https://github.com/shopware/platform) lfollowing the [quick installation](https://github.com/shopware/platform#quickstart--installation)
- run `./psh.phar administration:watch`

`http://localhost:8000` works

This is the console log after execute the command:
`
./psh.phar administration:watch

###################

SHOPWARE Developer Version

       _
      | |
   ___| |__   ___  _ ____      ____ _ _ __ ___
  / __| '_ \ / _ \| '_ \ \ /\ / / _` | '__/ _ \
  \__ \ | | | (_) | |_) \ V  V / (_| | | |  __/
  |___/_| |_|\___/| .__/ \_/\_/ \__,_|_|  \___|
                  | |
                  |_|

Using .psh.yaml.dist

Starting Execution of 'administration:watch' ('/app/dev-ops/administration/actions/watch.sh')

(1/3) Starting
> bin/console bundle:dump
        
         [OK] Dumped plugin configuration.                                                                                      
        
        
(2/3) Starting
> bin/console feature:dump
        
         [OK] Successfully dumped js feature configuration                                                                      
        
        
(3/3) Starting
> PROJECT_ROOT=/app PORT=8080 HOST=localhost ESLINT_DISABLE=true ENV_FILE=/app/.env APP_URL=http://localhost:8000 npm run --prefix vendor/shopware/platform/src/Administration/Resources/app/administration/ dev
        
        > administration@1.0.0 dev
        > mode=development webpack-dev-server
        
        # Compiling with Webpack configuration
        # Development mode is activated 🛠
        BaseUrl for proxy is set to "http://localhost:8000"
        # Plugin "Storefront": Injected successfully
        
        Calling reporter service for incremental check.
          Changed files: []
          Deleted files: []
        ℹ ｢wds｣: Project is running at http://localhost:8080/
        ℹ ｢wds｣: webpack output is served from /
        ℹ ｢wds｣: Content not from webpack is served from /app/vendor/shopware/platform/src/Administration/Resources/app/administration/static, /app/vendor/shopware/platform/src/Administration/Resources/app/administration/static, /app/vendor/shopware/platform/src/Administration/Resources/app/administration/static, /app/vendor/shopware/platform/src/Storefront/Resources/app/administration/static
         DONE  Compiled successfully in 36026ms6:00:45 PM
        
        ℹ ｢wdm｣: Child
            Time: 36026ms
            Entrypoint commons = bundles/administration/static/js/runtime.js bundles/administration/static/css/vendors-node.css bundles/administration/static/js/vendors-node.js bundles/administration/static/js/commons.js
            Entrypoint app = bundles/administration/static/js/runtime.js bundles/administration/static/css/vendors-node.css bundles/administration/static/js/vendors-node.js bundles/administration/static/css/app.css bundles/administration/static/js/app.js
               6223 modules
        Child
            Time: 8683ms
            Entrypoint storefront = css/storefront.css js/storefront.js
               78 modules
        ℹ ｢wdm｣: Compiled successfully.
        No issues found.
        Time: 36410 ms
`

**Comment by flkasper** [comment]
Same problem with version 6.4.15.1 (shopware/development) on Ubuntu 22.04 too.

I have tried it with a new installation and also once without platform in the root folder and neither works.

Either it is the new node version or one of the (administration) dependencies is currently broken.

**Comment by flkasper** [comment]
I found the problem on my end and was able to solve/work around it.

As with you @rammi22, with me the webpack dev-server is started with "HOST=localhost".

According to https://dev.to/hagevvashi/don-t-forget-to-give-host-0-0-0-0-to-the-startup-option-of-webpack-dev-server-using-docker-1483 the webpack-dev-server is not accessible from outside the container.
You have to start it with HOST=0.0.0.0.

Solution:
In the file "**dev-ops/administration/actions/watch.sh**" you have to replace "**HOST=__HOST__**" with "**HOST=0.0.0.0**".

**Comment by shyim** [comment]
Good catch. But we couldn't want to touch that as it would expose the dev server maybe to the internal network
