### ISSUE TITLE
Add current SalesChannelContext to the SalesChannelContextRestoredEvent

### ISSUE THREAD

**Issue by rvveber** [shopware/platform#2679]
### Please describe the feature you would like to see implemented.

I'm in a subscriber that subscribes to the `SalesChannelContextRestoredEvent` and the only SalesChannelContext i'm getting from the event, is a future / **restored** one. 

I would also need the previous, or rather at point of emitting - the **current** context, to perform additional context merge operations with my plugin.

The current context is available at the location the event is emitted.
Can current context be added to to the SalesChannelContextRestoredEvent ?

**Comment by seggewiss** [comment]
I quickly checked this. The Component emitting this event already has the current context.
This could easily be achieved.
https://github.com/shopware/platform/blob/trunk/src/Core/System/SalesChannel/Context/CartRestorer.php#L85

**Comment by shyim** [comment]
Feel free to create a PR. The argument should be only optional and should return nullable in the getter in the object itself. Because anyone could throw that event.

So in the major we can make that required

**Comment by keulinho** [comment]
@edip123 maybe interesting
