### ISSUE TITLE
Custom import profile doesn't have a "name" in the database

### ISSUE THREAD

**Issue by vkalchenko** [shopware/platform#2695]
### PHP Version

8.1.8

### Shopware Version

6.4.15.0

### Expected behaviour

Custom Import/Export profile should be created with the name, entered on the first step

### Actual behaviour

Field name is empty in the database. 

`select * from import_export_profile where system_default = 0 order by created_at desc;`
![image](https://user-images.githubusercontent.com/6286091/191311279-d7bc63f8-6e4d-4bb7-8818-17a36315c962.png)

New profile form doesn't have a field "name", it only has a field "label".

JSON object being sent to the server during profile save:

**POST /api/import-export-profile**
`{"id":"cc5f315e5f4e420192d667f159bc01b7","label":"Test Shopware profile","type":"import-export","sourceEntity":"customer","fileType":"text/csv","delimiter":";","enclosure":"\"","mapping":[{"key":"id","mappedKey":"id","position":0,"id":"80b22e64bebb442eb699c847b611ac19"},{"key":"customerNumber","mappedKey":"customerNumber","position":1,"id":"85b322c281a6487587a358aad3e99947"},{"key":"firstName","mappedKey":"firstName","position":2,"id":"b1573092752d4e8193d4ae7d279c074e"},{"key":"lastName","mappedKey":"lastName","position":3,"id":"8a60b4af814d433c8a6637ff281baea0"},{"key":"email","mappedKey":"email","position":4,"id":"9454f37653b345e4a58436ac6ad2a9ac"},{"key":"group.id","mappedKey":"group.id","position":5,"id":"91f18aed3be841a89679d1642a999bb0"},{"key":"defaultPaymentMethod.id","mappedKey":"defaultPaymentMethod.id","position":6,"id":"6b70d5d240b744ffa927c788ef127459"},{"key":"salesChannel.id","mappedKey":"salesChannel.id","position":7,"id":"6b35ddee3dae419caed6f8ee2b20944b"},{"key":"language.id","mappedKey":"language.id","position":8,"id":"afebb321b4014a56a1de78ad2fc97939"},{"key":"defaultBillingAddress.id","mappedKey":"defaultBillingAddress.id","position":9,"id":"d03303bbddbf4484944b705bef0ef1b5"},{"key":"defaultShippingAddress.id","mappedKey":"defaultShippingAddress.id","position":10,"id":"0ed4b73d86ab42f6b6b1ec449ed0cfca"}],"config":{"createEntities":true,"updateEntities":true},"translated":{}}`

Entered value is stored in the database table `import_export_profile_translation`

`select * from import_export_profile_translation order by created_at desc;`
![image](https://user-images.githubusercontent.com/6286091/191312188-0e512537-a3bc-4329-85c7-c789d152fdea.png)

### How to reproduce

1. Go to Administration > Settings > Import/Export
2. Select Profile tab, click on "Add new profile" button
3. Enter required fields. For example 
   Profile name: Test Shopware profile
   Object type: Customer
   Usage: Import and export
4. Click "Next" 
5. On the mapping page you can either add a mapping or click "Skip CSV upload", it doesn't affect the results
6. On the last step click the "Add profile" button

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
