### ISSUE TITLE
Gallery & Buybox Image Height not working

### ISSUE THREAD

**Issue by danielDigitalArt** [shopware/platform#2705]
### PHP Version

8.1.10

### Shopware Version

6.4.15

### Expected behaviour

Minimum Height is respected

### Actual behaviour

Minimum Height is not respected.

### How to reproduce

Create a Shoppingworld, add a Gallery & Buybox, Edit the Part where the Image(s) can be selected, switch to Settings-Tab. Switch to Mode "Contain" and set a minimum height.

![image](https://user-images.githubusercontent.com/25100967/192293536-3e935074-9850-4244-948d-d04753339ce2.png)

When Debugging the CSS in the frontend, you can see that the Height gets set, but the unit is missing:
![image](https://user-images.githubusercontent.com/25100967/192293901-5d53b449-3670-4569-9c58-41fc60ec5477.png)

When adding the unit in the backend-Field, the height is correctly used.
![image](https://user-images.githubusercontent.com/25100967/192294196-c4fc21f5-15b5-49c9-88e3-63cab550a266.png)

There are two possible solutions, either the backend should set the unit into the Field by default, or the template has to add the unit (px) by itself. The File to change would then be "src/Storefront/Resources/views/storefront/element/cms-element-image-gallery.html.twig"
![image](https://user-images.githubusercontent.com/25100967/192294507-68752a50-6844-4ec1-9dd5-d55b05a8386e.png)

**Comment by tinect** [comment]
Hey,
I was confused by your Text. The setting is for MIN height, not MAX one. Would you please adjust this? :-)

**Comment by danielDigitalArt** [comment]
Hi, you are correct. I changed it.

**Comment by NinjaArmy** [comment]
I think it works like it should. If you would set the unit in the backend or in the template you force every user to use your defined unit (px). If you know want to create a slider with 100vh for example it's not possible anymore. Other units like rem, em also would not work. I think a helpText here would be enough. Let me add this real quick

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
