### ISSUE TITLE
Image-Centered does not center

### ISSUE THREAD

**Issue by danielDigitalArt** [shopware/platform#2706]
### PHP Version

8.1.10

### Shopware Version

6.4.15

### Expected behaviour

Image should be centered.

![image](https://user-images.githubusercontent.com/25100967/192301439-508554bc-d170-481a-80bd-fb3c253dd111.png)

### Actual behaviour

Image is aligned on the left, like the Text.

![image](https://user-images.githubusercontent.com/25100967/192301579-33f1f67f-438d-43e6-8d17-7bd816bb7dd2.png)

### How to reproduce

Add the Element "Image Centered" to a shopping world and select an image that is smaller than the container/wrapper of the shop. The Image will then be placed on the left side:
![image](https://user-images.githubusercontent.com/25100967/192299496-1af09c38-d1c6-49b4-8e9a-9895d9062855.png)

It could very well be inteded to be this way, sadly there is only the option for vertical centered images, not hoziontal centered.

![image](https://user-images.githubusercontent.com/25100967/192299781-2f593c1b-5477-41b9-a469-23548895a151.png)

**Temporary Fix:**
Adding this CSS to the shop centers the image:
```
.cms-page .cms-element-image .cms-image{
    margin: 0 auto;
}
```
But when the Setting for Horizontal Placement is selected, additional css is needed, as this setting will make the outer container switch to display flex, which results in the container to shrink to its contents size, thus centering can not work. Here is the additional css that is needed:
```
.cms-element-image.has-vertical-alignment .cms-element-alignment{
    width: 100%;
}
```

**Suggestion**
Add a Field to the Element which allows the selection of horizontal alignment.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
