### ISSUE TITLE
A typo in the name of block, letter "r" is missing in the word "description" 

### ISSUE THREAD

**Issue by lveith** [shopware/platform#2777]
### PHP Version

8.1

### Shopware Version

6.4.16.0

### Expected behaviour

{% block element_product_description_reviews %}

### Actual behaviour

{% block element_product_desciption_reviews %}

### How to reproduce

platform/src/Storefront/Resources/views/storefront/element/cms-element-product-description-reviews.html.twig

**Comment by lveith** [comment]
A typo in the name of block, letter "r" is missing in the word "description"

**Comment by wannevancamp** [comment]
@lveith , I created a PR for this: https://github.com/shopware/platform/pull/2842

**Comment by Zwaen91** [comment]
@keulinho This can be closed
