### ISSUE TITLE
CLI-Installer seems absent starting with v6.4.15.0

### ISSUE THREAD

**Issue by theuers** [shopware/platform#2780]
### PHP Version

8

### Shopware Version

6.4.15.0 and up

### Expected behaviour

Installing Shopware via the CLI-Installer should work as it did in 6.4.14.0.

e.g. like in https://github.com/shopware/platform/issues/2171 
php public/recovery/install/index.php \
                 --no-interaction \
                 --db-user=dbuser \
                 --db-password=dbpassword \
                 --db-name="dbname" \
                 --db-host=localhost \
                 --db-port=3306 \
                 --shop-locale=de-DE \
                 --shop-country=DEU \
                 --shop-host=example.de \
                 --shop-path="" \
                 --shop-name='Shopname' \
                 --shop-currency=EUR \
                 --shop-email="test@example.com" \
                 --admin-username=admin \
                 --admin-password=shopware \
                 --admin-email=test@example.com \
                 --admin-locale=de-DE \
                 --admin-firstname=Admin \
                 --admin-lastname=Admin

### Actual behaviour

`public/recovery/install/index.php` does not exist and cannot be restored using `bin/console assets:install` which worked in 6.4.14.0.

Am I missing something here, or is the CLI-Installer not available anymore?

### How to reproduce

Try installing Shopware >= 6.4.15.0  using `bin/console assets:install` and then `php public/recovery/install/index.php ...`

**Comment by mitelg** [comment]
the whole `recovery` directory was removed. 
@keulinho can tell you more about it

**Comment by keulinho** [comment]
@mitelg is right the whole installer was removed, you can still install it over the CLI with the documented 
```
bin/console system:setup
```
and 
```
bin/console system:install
```
commands.
