### ISSUE TITLE
Custom Fields are not getting rendered in media 

### ISSUE THREAD

**Issue by heydavee** [shopware/platform#2793]
### PHP Version

8

### Shopware Version

6.4.16.0

### Expected behaviour

If i create a custom field set to media i expect to see them in the media library

### Actual behaviour

Field not getting rendered
Searching in HTML Code shows that div `sw-custom-field-set-renderer` is empty

Settings of custom field
<img width="951" alt="Bildschirmfoto 2022-10-20 um 11 05 17" src="https://user-images.githubusercontent.com/5037624/196905988-c8ea5dcc-dd4c-4992-8345-5cc69c24006d.png">

Visible in Product
<img width="909" alt="Bildschirmfoto 2022-10-20 um 11 06 12" src="https://user-images.githubusercontent.com/5037624/196906288-bef551f2-a4d7-409c-9f7b-9704d3983fb2.png">

Not visible in Media 
<img width="363" alt="Bildschirmfoto 2022-10-20 um 11 04 17" src="https://user-images.githubusercontent.com/5037624/196905862-0a05abc0-438b-4010-8d44-83efa0cf4c5e.png">

### How to reproduce

Creating a custom field, setting it to media and looking at any media in the media library

**Comment by DaveWoody** [comment]
Console Error (not sure if relevant) 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'manifest')

<img width="804" alt="Bildschirmfoto 2022-11-03 um 12 00 26" src="https://user-images.githubusercontent.com/5037624/199704420-9f6cada7-bafb-4104-83a5-46d6437829e1.png">

**Comment by heydavee** [comment]
Just tried this on a fresh shopware 6 installation. Same Issue. 

<img width="362" alt="Bildschirmfoto 2022-11-03 um 12 15 47" src="https://user-images.githubusercontent.com/5037624/199707302-541977aa-8511-464c-b390-4a3be61e580f.png">

Looking into the source code the sw-custom-field-set-renderer is empty

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
