### ISSUE TITLE
Searching for SKU not redirecting to product detail page

### ISSUE THREAD

**Issue by heydavee** [shopware/platform#2799]
### PHP Version

8.0

### Shopware Version

6.4.16.0

### Expected behaviour

When searching via product number and it matches with a product, i should get redirected to the product detail page. 

### Actual behaviour

inconsistent results. Sometimes i get redirected to the fitting product detail page but sometimes it redirects me to the search result page, showing other products. Does this have to do with my indexer not being finished? (See issue: https://github.com/shopware/platform/issues/2795) or is this a different issue?

### How to reproduce

- See above.

**Comment by florianliebig** [comment]
For me this seems related to this: https://forum.shopware.com/t/suche-nach-artikelnummern-nicht-nach-bestandteile/68258/19

We use 4 digit SKUs and get quite confusing results, too.

The ProductSearchBuilder and ProductSearchTermInterpreter search against the product_search_keyword - in which you can' see the source of which the keyword is generated (in this case SKU). So disabling the slops in the search for all number searches might not be intended even though most number searches are based on SKU in my opinion

**Comment by heydavee** [comment]
If anyone needs a quick fix - in the above linked thread there was a plugin posted which helped me with my issue:

https://store.shopware.com/leopa84423787994f/artikeldetailseite-bei-eindeutigem-nummer-match-in-suche.html


I don't know if it would be nice to integrate this into Shopware Core itself, but that is not my decision to make.
