### ISSUE TITLE
Feature request: Add user and plugin ownership to every entity

### ISSUE THREAD

**Issue by moorl** [shopware/platform#2807]
### Please describe the feature you would like to see implemented.

To make Shopware Core more flexible in the first place, it would be a great improvement to add ownership by plugins or users.

User ownership:
- Basis for any marketplace-based system
- An entity with an ownership is only visible to the owner or superadmin
- Entities without ownership can be used

Plugin entity ownership:
- For example, if a plugin installs a new shipping method, the plugin is the owner
- We don't have to remember the ID through an uninstall routine of the plugin

This ownership can be added to any entity like the id, createdAt and updatedAt. 

For me as a plugin developer, this would be very helpful to manage and mix data from the sw core and plugins.

Maybe someone can bring advantages and disadvantages?

**Comment by shyim** [comment]
Hey,

For us, the benefit of adding it is not worth for the time implementing it. It would make the DAL also more complicated, as I would see this as a "lock" of extension to an entity that only the extension can modify that record.
