### ISSUE TITLE
Dependency symfony/inflector is abandoned

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2817]
### PHP Version

irrelevant

### Shopware Version

any 6.x

### Expected behaviour

Should not be dependent on an abandoned piece of software.

### Actual behaviour

Depends on symfony/inflector
See: https://packagist.org/packages/symfony/inflector

### How to reproduce

Just call
`composer update --dry-run`
in your project root.

And when it tells 
`Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.`
than you see that warning, that I am talking about.

**Comment by keulinho** [comment]
Thanks for pointing out the issue, sadly we can not drop the dependencies in a minor release, but we will remove those dependencies in the next major version.

I created a official issue tracker ticket for that and will close this issue for now.
https://issues.shopware.com/issues/NEXT-23972

**Comment by jonas-sfx** [comment]
I see why you do not want to drop them in a minor release.
But why did you close this issue before solving it and while [NEXT-23972]( https://issues.shopware.com/issues/NEXT-23972) is still open?

**Comment by keulinho** [comment]
See your [other issue](https://github.com/shopware/platform/issues/2818#issuecomment-1301705219) for the answer.
