### ISSUE TITLE
Api Sync invalid payload

### ISSUE THREAD

**Issue by adiXM** [shopware/platform#2830]
### PHP Version

8

### Shopware Version

6.4.14.0

### Expected behaviour

When you insert a new address to a customer you should make a check behind to make sure that customer still has the same default billing address or the payload contains the old address, because the api-sync will overwrite all the addresses with the new ones. In that case api sync should return a 400 Error Bad Request.

### Actual behaviour

Api sync let us to overwrite customer addresses by giving the old defaultBillingAddressId. (which is not valid after api sync call)
And with this issue, I can remove all the addresses because no one is for default billing or delivery. 

### How to reproduce

 Let's suppose that you have a customer with one address which is also default billing address and default delivery address.

Let's try to add a new address to a customer using api-sync, so we will have a payload something like this:

```
$payload = [
    'id' => $this->customer->getId(),
    'addresses' => [
        'title' => 'test title',
        'city' => 'Deutschland',
        'countryId' => $this->country['id'],
        'firstName' => $this->customer->getFirstName(),
        'lastName' => $this->customer->getLastName(),
        'salutationId' => $this->customer->getSalutationId(),
        'street' => 'Street test 123',
        'zipcode' => '123456',
        'company' => 'Company Test',
    ],
    'defaultShippingAddressId' => $this->customer->getDefaultShippingAddressId(),
    'defaultBillingAddressId' => $this->customer->getDefaultBillingAddressId(),
];
```

Params for api sync:

```
$apiSyncParams = [
    'action' => 'upsert',
    'entity' => 'customer',
    'payload' => $payload,
];
```

After send api-sync request, your customer will have the new data imported, but without a correct default billingAddressId or deliveryAddressId (because is overwritten by the api on insert), but as I know a customer entity has billing address required.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
