### ISSUE TITLE
RecipientsBcc

### ISSUE THREAD

**Issue by kubakulp** [shopware/platform#2832]
### PHP Version

7.4

### Shopware Version

6.4.16.0 

### Expected behaviour

I would expected to be able to add many recipients with Bcc.

### Actual behaviour

![image](https://user-images.githubusercontent.com/63971508/200306408-d20d5aef-667a-4446-8167-0737976b1c31.png)
![image](https://user-images.githubusercontent.com/63971508/200306818-eb640825-85ce-4459-a9cf-cf5b903f46a1.png)

### How to reproduce

![image](https://user-images.githubusercontent.com/63971508/200306755-9213eefa-fcd8-4e57-a445-da744748f50c.png)
![image](https://user-images.githubusercontent.com/63971508/200306801-c44e52d2-0971-4458-8a31-eb6937e99b9e.png)

**Comment by jonas-sfx** [comment]
That's [/src/Core/Content/Mail/Service/MailFactory.php](https://github.com/shopware/platform/blob/v6.4.16.0/src/Core/Content/Mail/Service/MailFactory.php) ... for those of you who like source-code in text and not in pictures, like I do.
Correct?

**Comment by kubakulp** [comment]
> That's [/src/Core/Content/Mail/Service/MailFactory.php](https://github.com/shopware/platform/blob/v6.4.16.0/src/Core/Content/Mail/Service/MailFactory.php) ... for those of you who like source-code in text and not in pictures, like I do. Correct?

Yes correct

**Comment by jonas-sfx** [comment]
Isn't this an an array with a foreach-handling so you can hand over multiple mail-addresses?

**Comment by kubakulp** [comment]
i guess it should be, but you are using array of value => value for the argument in MailFactory and that's not array of adresses with mail as a key and name as a value

**Comment by herrla** [comment]
This is known and seems ignored on the issue tracker since august 2021. I just stumbled upon this problem and found the ticket. https://issues.shopware.com/issues/NEXT-16644

**Comment by Zwaen91** [comment]
Resolved with https://github.com/shopware/platform/pull/2991

**Comment by Zwaen91** [comment]
Duplicated of https://github.com/shopware/platform/issues/2862
