### ISSUE TITLE
Google Analytics is not disabled (without cache-clear)

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2834]
### PHP Version

irrelevant

### Shopware Version

any 6.x

### Expected behaviour

Disabling Google Analytis in Backend (Sales-Channel-Settings) should disable this feature immediately.

If this requires a cache:clear-Call,
this one should be either be automatically done
or at least there should be a hint asking the backend-users to do this cache:clear to make the change work.

### Actual behaviour

Unfortunately if you wanna disable your tracking,
the snippet is still placed in template until you do the next cache:clear.

### How to reproduce

Disable a previously up and running Analytics Integration and look in the generated HTML-Code of your Shop-Pages for www.googletagmanager.com or in Network-Tab. for loading things from this domain.

**Comment by shyim** [comment]
We have a ticket which should solve that problem too https://issues.shopware.com/issues/NEXT-22839

**Comment by jonas-sfx** [comment]
[NEXT-22839](https://issues.shopware.com/issues/NEXT-22839) is about cloud instances,
where clearing the cache is even more complicated.

The issue I told about is even a problem on non-cloud instances.
Perhaps NEXT-2289 will solve #2834 perhaps it wont.

As long as shop-owners think, that their website is legally compliant and indeed it is not, this could become expensive!

**Comment by shyim** [comment]
It's the same bug, we don't clear the caches when you update a sales channel. GA is an entity bound to SC
