### ISSUE TITLE
Bug on the mime content type check of a template email attchment

### ISSUE THREAD

**Issue by dimiceli** [shopware/platform#2841]
### PHP Version

PHP 8.1

### Shopware Version

v6.4.17.1

### Expected behaviour

We should be able to upload an attachment via the administration email template editor.

I report this issue to have a trace  and i already made a pull request 
. The error is identified in the javascript media upload component v2.

https://github.com/shopware/platform/pull/2840

### Actual behaviour

There is a format validation error although the attachment is a supposedly authorized pdf.

### How to reproduce

Try to upload a pdf attachment file from the email template editor.

**Comment by keulinho** [comment]
Should be fixed with https://github.com/shopware/platform/pull/2713
