### ISSUE TITLE
Decorating ContextRoute is not possible as service is not public or add tag controller.service_arguments

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2845]
### PHP Version

8.1

### Shopware Version

6.4

### Expected behaviour

Decorating ContextRoute resolves in the decorated service. However, as the route is not marked as public or adds `controller.service_arguments` as tag (which makes it public and adds additional features, it fails to be decorated correctly as the class is directly instantiated instead of using a Symfony service.

### Actual behaviour

ContextRoute decorating fails as the controller is not marked as public or uses `controller.service_arguments` which makes it public automatically.

### How to reproduce

Add a service like:

```yaml
    FooPlugin\Core\System\SalesChannel\ContextRouteDecorator:
        decorates: 'Shopware\Core\System\SalesChannel\SalesChannel\ContextRoute'
```

it will still use the original ContextRoute which is manually instantiated instead of using the corresponding service.

**Comment by AndreasA** [comment]
Not directly related to this but in the documentation for https://developer.shopware.com/docs/guides/plugins/plugins/framework/store-api/override-existing-route 

this part `* @Route("/store-api/example", name="store-api.example.search", methods={"GET", "POST"})` should be unnecessary as it uses the route information from the original class. It might even be possible to skip `* @Route(defaults={"_routeScope"={"store-api"}})` as the issue with those annotations/attributes not being inherited was with the old custom annotations.

Also: Maybe add an example using attributes for PHP 8.x 😄

**Comment by shyim** [comment]
A service don't need to be public to be decorated 🤔

**Comment by AndreasA** [comment]
@shyim the problem is not for services. The problem is that in order for a controller to be used as service, it has to be public or use the tag `controller.service_arguments` or extend AbstractController with autoconfigure true.

Otherwise the controller is not a service but just an object that is manually isntantiated, see also: https://symfony.com/doc/current/controller/service.html#how-to-define-controllers-as-services

```
If your controllers don't extend the [AbstractController](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php) class, you must explicitly mark your controller services as public. Alternatively, you can apply the controller.service_arguments tag to your controller services. This will make the tagged services public and will allow you to inject services in method parameters:
```

if the route would use any dependency injection in its constructor, it would probably even fail to work currently as it is not a service.

**Comment by shyim** [comment]
Feel free to make a PR :)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
