### ISSUE TITLE
Category Breadcrumb not generated when inserting through Sync-API

### ISSUE THREAD

**Issue by digitalkaoz** [shopware/platform#2846]
### PHP Version

8.1

### Shopware Version

6.4.17.0

### Expected behaviour

autogeneration of Category breadcrumbs should work when inserting categories over the Sync Api Endpoint.

It works when inserting categories through `api/category` but not when upserting them over `api/sync` 

### Actual behaviour

breadcrumbs are missing, the tree is defunctional

### How to reproduce

insert categories with parent_id through the `sync` api endpoint

**Comment by shyim** [comment]
did you maybe disabled indexing in the header?

**Comment by digitalkaoz** [comment]
we do:

```go
	useTransactions := "0"
	if transaction {
		useTransactions = "1"
	}

	headers := authHeaders()
	headers["single-operation"] = useTransactions
	headers["indexing-behavior"] = "use-queue-indexing"

	return headers
```

we are investigating the indexing workers, lets see

**Comment by digitalkaoz** [comment]
the indexing worker didnt run properly, once that was fixed it working as expected and before, thanks for the hint!
