### ISSUE TITLE
New Payment Method Administration Layout not Allowing to Delete Payment Methods

### ISSUE THREAD

**Issue by arminlinzbauer** [shopware/platform#2856]
### PHP Version

*

### Shopware Version

6.4.15

### Expected behaviour

It should be possible to delete payment methods in the new layout/design

### Actual behaviour

It's only possible to delete payment methods from the old layout, which will be removed with the next major version.

### How to reproduce

Try deleting a payment method from the new layout.

**Comment by lernhart** [comment]
Hey @arminlinzbauer, thank you very much for reporting this.

We discussed this a lot while developing the new Payment Method UX. The thing is, you are not allowed to delete payment methods, which were used for orders at least once anyway - the delete button does not make a lot of sense here. The payment extensions should check, if a payment method can be safely deleted, whenever the extension is uninstalled.

I will consult with my team again, if it is useful to reimplement a delete button, as we did not think there would be a use case out there.

For now, i will close this issue - but I've created an issue internally and keep you updated on our decision making.

**Comment by arminlinzbauer** [comment]
Hi, thanks for the quick reply - I completely agree with your reasoning. The problem is that we can't force 3rd party plug-in developers to clean up after themselves. Currently we're having tons of duplicate payment methods we can't get rid of because the plug in doesn't perform its duties correctly. It would still be nice to access this as an advanced option somewhere. Shopware won't let you delete used methods anyway, so you can't really break anything.

**Comment by lernhart** [comment]
Hey @arminlinzbauer, we've just had a thorugh discussion about this topic.

We agree, that the shop owner should be able to remove stale or unused payment methods, so we decided, to reimplement a delete action. We will follow a much softer approach though, as we will check, if the payment method is used in any orders and won't allow deletion in that case. Furthermore, we will warn the shop owner, that they should know what they do, if the payment method is belonging to an installed extension - this could break apps and plugins out there. 

I'll keep you posted on the progress.

Thank you for the valuable feedback here 👍
