### ISSUE TITLE
Add composer dependency "twig/cssinliner-extra" and "twig/extra-bundle"

### ISSUE THREAD

**Issue by jd297** [shopware/platform#2858]
### Please describe the feature you would like to see implemented.

It is very frustating to write email template code for Outlook, because Outlook seems to use only the first class attribute. Because of this you have to use inline css which can fast be a mess of a code. In special if you use variables like theme_config("...").

A solution would be to provide the vendor packages: "twig/cssinliner-extra" and "twig/extra-bundle". Then you can convert your css classes from the "<style>" tag to inline css with just a an "apply inline_css"  statement in twig arround your template code.

Here you can see the offical docs: https://twig.symfony.com/doc/2.x/filters/inline_css.html

Before you ask, yes I have read your docs ["Adding Composer dependencies"](https://developer.shopware.com/docs/guides/plugins/plugins/plugin-fundamentals/using-composer-dependencies), but I dont see the point in commiting a bunch of files that make a plugin just really large for a small feature. Guess what, twig/twig it self is a dependency for the inliner and this is just a duplicate of the original vendor folder.

I think other plugin manufacturers and the shopware core can also benefit from this package.

**Comment by wexollm** [comment]
@JD297 I guess you can add those packages yourself with the Symfony Flex?

**Comment by jd297** [comment]
@wexollm The problem is, I want this package in a Plugin that is in the Shopware plugin store. It wouldn't be really convenient if the customer had to install the dependencies manually.

**Comment by shyim** [comment]
Hey,

We won't would like to add composer packages that are used by rare amount of extensions. As @wexollm said, you can bundle the package inside your extension. With 6.5 it will be also a lot of easier as you don't have to package the vendor files anymore
