### ISSUE TITLE
Typo in container parameter injection

### ISSUE THREAD

**Issue by marcogier** [shopware/platform#2860]
### PHP Version

8.0

### Shopware Version

6.4.17.2

### Expected behaviour
Affected file:
https://github.com/shopware/platform/blob/v6.4.17.2/src/Core/Framework/DependencyInjection/services.xml#L385

Wrong <argument> value:
**%kernel.cache_dir%%**

### Actual behaviour

"kernel.cache_dir" parameter is injected with tailing "%" due to typo. This creates an additional cache directory with a tailing "%"

### How to reproduce

For example: send contact form test mail from administration (this triggers the "StringTemplateRenderer", which creates the incorrect cache directory)

**Comment by keulinho** [comment]
Nice catch :+1: feel free to create a PR
