### ISSUE TITLE
Multiline Records in CSVs?!?

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2864]
### PHP Version

Does not Matter

### Shopware Version

Current Trunk and earlier

### Expected behaviour

CSV needs a LineDelimiter that is not the same than the column-delimiter.
That's at least how i understood [RFC4180](https://www.rfc-editor.org/rfc/rfc4180#page-2)
Line-Breaking after each column causes problems with the CSV-Syntax.

### Actual behaviour

If we look at the [body](https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/module/sw-sales-channel/product-export-templates/idealo/body.csv.twig) or [header](https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/module/sw-sales-channel/product-export-templates/idealo/header.csv.twig) of the csv-export-templates to export to idealo.
Or [body](https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/module/sw-sales-channel/product-export-templates/billiger-de/body.csv.twig) and [header](https://github.com/shopware/platform/blob/trunk/src/Administration/Resources/app/administration/src/module/sw-sales-channel/product-export-templates/billiger-de/header.csv.twig) of those to export to billiger.de I can see newlines after each column.
This ends in very strange CSV-Files.

### How to reproduce

Just use one of the templates mentioned above in a "Product-Comparison-Sales-Channel".
And "Enjoy" the Preview or result of such an Export.
Imho there are to much newlines.

**_Additional information:_**
I tried to quick-fix things with "{% apply spaceless %}" and "{% endapply %}" but they seem to be powerless here.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
