### ISSUE TITLE
It's not possible to create a Property Option with < or > sign

### ISSUE THREAD

**Issue by vkalchenko** [shopware/platform#2872]
### PHP Version

8.1.12

### Shopware Version

6.4.17.2

### Expected behaviour

Option should be created

### Actual behaviour

The system returns an error 
```{
    "errors": [
        {
            "code": "c1051bb4-d103-4f74-8988-acbcafc7fdc3",
            "status": "400",
            "detail": "This value should not be blank.",
            "template": "This value should not be blank.",
            "meta": {
                "parameters": {
                    "{{ value }}": "\u0022\u0022"
                }
            },
            "source": {
                "pointer": "\/0\/name"
            }
        },
        {
            "code": "c1051bb4-d103-4f74-8988-acbcafc7fdc3",
            "status": "400",
            "detail": "This value should not be blank.",
            "template": "This value should not be blank.",
            "meta": {
                "parameters": {
                    "{{ value }}": "null"
                }
            },
            "source": {
                "pointer": "\/0\/translations\/2fbb5fe2e29a4d70aa5854ce7ce3e20b\/name"
            }
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/6286091/205332367-640f67e9-5400-4e0c-be97-2d71b770cfde.png)

### How to reproduce

1. Go to Catalogues > Properties
2. Select any property, scroll down to "Property values"
3. Open "Add value" dialog
4. Enter "Name" value, containing **<** or **>** sign. For example **<1%**
5. Click "Apply" button

**Comment by kingschnulli** [comment]
Marked as won't fix already:

https://issues.shopware.com/issues/NEXT-25187

Enter the property with a space inbetween and it will work, e.g. "< 1%"

**Comment by JoshuaBehrens** [comment]
@vkalchenko https://github.com/shopware/platform/pull/3118
