### ISSUE TITLE
 Dependency sensio/framework-extra-bundle is abandoned

### ISSUE THREAD

**Issue by jonas-sfx** [shopware/platform#2876]
### PHP Version

irrelevant

### Shopware Version

any 6.x

### Expected behaviour

Should not be dependent on an abandoned piece of software.

### Actual behaviour

Depends on sensio/framework-extra-bundle
See: https://packagist.org/packages/sensio/framework-extra-bundle

### How to reproduce

Just call
`composer update --dry-run`
in your project root.

And when it tells
`Package sensio/framework-extra-bundle is abandoned, you should avoid using it. No replacement was suggested.`,
you see that warning, that I am talking about.

**Comment by keulinho** [comment]
Thanks for the heads up, we removed the abandoned dependency for 6.5.
