### ISSUE TITLE
Shopware is only PHP 8.1 compatible starting from v6.4.6.0

### ISSUE THREAD

**Issue by alessandroaussems** [shopware/platform#2881]
### PHP Version

8.1

### Shopware Version

6.4.4.1

### Expected behaviour

According to the composer.json file Shopware 6.4.4.1 should be PHP 8.1 compatible. But it's not...
Because the necessary changes (https://github.com/shopware/platform/commit/d8214c74aa75ed9d9b40834fb9389ef419f44822) are only available in v6.4.6.0

### Actual behaviour

6.4.4.1 should be PHP 8.1 compatible according to composer.json

### How to reproduce

Try to run Shopware 6.4.4.1 on PHP 8.1. You 'll seen encounter errors:
_Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityDefinition::decode(): Argument #2 ($value) must be of type ?string, int given_

This is because the necessary change:
`'driverOptions' => [
                    \PDO::ATTR_STRINGIFY_FETCHES => true,
],`

is not available in 6.4.4.1

**Comment by shyim** [comment]
We don't release patch updates for older versions. Update to a newer version

**Comment by alessandroaussems** [comment]
@shyim That's not the point. I know you won't patch older versions. But I think SW should be more careful with these kind of things. If composer.json states that a certain release is compatible with a certain php version, it should also be compatible. You can't just mess around with this stuff... How can we otherwise trust the composer.json dependencies and requirements in the future...

**Comment by keulinho** [comment]
Thanks for the input, we have now limited the upper bound for the supported php versions, starting with v6.5.0.0.

See https://github.com/shopware/platform/commit/12dcffbc42eb5348e44aace88626307246523d5b for reference.
