### ISSUE TITLE
Core composer.json PHP version mismatch (config and require)

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2884]
### PHP Version

8.1

### Shopware Version

trunk

### Expected behaviour

Currently the composer.json of Core overrides the PHP version using platform with `7.4` but require uses `^8.1`. This seems like a very weird combination.

Personally, I think the PHP version override should be removed altogether. If not, it should at least be adjusted to also use 8.1

https://github.com/shopware/platform/blob/61f2e640cd1987c29d46d8e5190df729b37994c0/src/Core/composer.json#L37
https://github.com/shopware/platform/blob/61f2e640cd1987c29d46d8e5190df729b37994c0/src/Core/composer.json#L154

This might also be the case for the composer.json files of the other sub-packages (did not check).

### Actual behaviour

see Expected behavior

### How to reproduce

See expected behavior

**Comment by keulinho** [comment]
Thanks for bringing this up, we will fix it shortly
