### ISSUE TITLE
Long snippets breaks the snippet search in Admin

### ISSUE THREAD

**Issue by BlackScorp** [shopware/platform#2886]
### PHP Version

8.1

### Shopware Version

6.4.17.2

### Expected behaviour

When i create a new snippet which is a long text (over 5000 Characters) then i should be able to search for snippets in admin interface

### Actual behaviour

When i create a new long snippet over 5000 Characters, the admin search for snippets is not working anymore.

The API Search response is then a 500 Error with following error message:

Warning: fnmatch(): Filename exceeds the maximum allowed length of 4096 characters.

The file which throws this error is

https://github.com/shopware/platform/blob/trunk/src/Core/System/Snippet/Filter/TermFilter.php#L31-L32

### How to reproduce

1) Find a long text, Lorem Ipsum Generator can generate a text over 5000 characters
2) create new snippet and paste the text 
3) in the snippet overview try to search for anything

**Comment by AltayAkkus** [comment]
Fixed in #2891

**Comment by TimWuyts** [comment]
We experience similar issues using the snippets in the administration:
- Long snippets cause the issue mentioned here by using the fnmatch() function.
- The snippetRepository search produces a timeout on larger snippet sets. It seems to be that there are no filters/limits applied on the criteria of the repository when fetching the snippets from the database.

**Comment by mitelg** [comment]
Fixed with https://github.com/shopware/shopware/pull/2891
