### ISSUE TITLE
Complications to install on Windows 10

### ISSUE THREAD

**Issue by freesoul** [shopware/platform#2890]
### PHP Version

8.0.26

### Shopware Version

6.2

### Expected behaviour

The installation is easy to do.

### Actual behaviour

First problem is that you *need* to install with --no-scripts the "composer install" (not indicated in the readme like this), because if you don't then the pre-installation script is run (bin/console ...), which tries to load the autoload.php which obviously does not exist yet.

Then It is not clear at all if you need to run a command for system:setup or system:install or to go to the installation page. You should try stuff, drop part of it, retry etc until you arrive to something.

Then the commands on the composer.json do not work because $PHP_BINARY is nothing, at least in windows.

After doing that, you will find that you just have an error 500, with no logs on apache or php. You need to turn on the debug mode to find out that actually openssl_pkey_new and openssl_pkey_export_to_file return nothing, and add some debug information to understand that you *NEED* to pass the path of the configuration of openssl (openssl.cnf) for it to work.

Then an error happens regarding the public.pem/private.pem file permissions, which are a pain to change in Windows (ok, that's not really your fault, but why do I need a public.pem/private.pem file of anything, for a basic installation?)

Finally, I figured out that I had to do the compilation of the theme,  with the particular theme:compile, theme: refresh, theme:change commands. It did not work at all, because the import routes are broken on Windows. To fix it I had to go to storefront/Theme/ThemeFileImporter.php and change $file->getFilePath() so that backslashes are now "/".

### How to reproduce

Try to install it in a WAMP stack on Windows.

**Comment by keulinho** [comment]
Running shopware under windows is not supported, refer to the [official docs](https://developer.shopware.com/docs/guides/installation/overview).

However you should be able to set shopware up using the Windows Subsystem for Linux (WSL).
