### ISSUE TITLE
GitPod broken

### ISSUE THREAD

**Issue by AltayAkkus** [shopware/platform#2893]
### PHP Version

trunk

### Shopware Version

trunk

### Expected behaviour

Being able to build a working copy of Shopware in Gitpod, via this repo.

### Actual behaviour

Index looks like this:
![grafik](https://user-images.githubusercontent.com/7849969/208669414-c1d6357a-190e-48e7-b3f6-4356f3efbb73.png)

Noteworthy: When you open the index site, look at your network tab. 
The only thing that is loaded is the index page (`/`) and the dummy product images, no CSS, JS file of any kind.

![grafik](https://user-images.githubusercontent.com/7849969/208669546-d5bb7d66-8ba8-4aa4-b8f3-629435941325.png)
/admin
Admin interface works fine, though.

When you open my PR #2891 in GitPod, the admin interface is broken too.
<a href="https://gitpod.io/#https://github.com/shopware/platform/pull/2891"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
It tries to load `app.css` and `app.js`, but GitPod returns 404, and then it throws the error "Shopware is not defined", so somehow the serving of static files has gone corrupt.

### How to reproduce

<a href="https://gitpod.io/#https://github.com/shopware/platform"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fixing this would be crucial, I use GitPod for contributing and quickly reproducing bugs without having to spin up an entire new test environment each time.

**Comment by shyim** [comment]
Can you try ./bin/console theme:change

**Comment by AltayAkkus** [comment]
> Can you try ./bin/console theme:change

Done, I tried selecting Storefront and Headless, both now return a 500.
![grafik](https://user-images.githubusercontent.com/7849969/208672342-d7f00e68-c7a2-4739-8915-3a29cb9ead4f.png)

```
Symfony\Component\ErrorHandler\Error\ClassNotFoundError:
Attempted to load interface "ValueResolverInterface" from namespace "Symfony\Component\HttpKernel\Controller".
Did you forget a "use" statement for another namespace?

  at /workspace/platform/src/Core/Checkout/Customer/CustomerValueResolver.php:14
  at include()
     (/workspace/platform/vendor/composer/ClassLoader.php:571)
  at Composer\Autoload\includeFile()
     (/workspace/platform/vendor/composer/ClassLoader.php:428)
  at Composer\Autoload\ClassLoader->loadClass()
     (/workspace/platform/vendor/symfony/error-handler/DebugClassLoader.php:294)
  at Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() 
...
```

**Comment by shyim** [comment]
`composer update`

**Comment by AltayAkkus** [comment]
> `composer update`

Yea im battling everything since like 40 minutes now.

Now it's giving me the error:
`Unable to compile the theme "Storefront". Unable to load file "src/Storefront/Resources/app/storefront/dist/js/vendor-node.js". Did you forget to build the theme? Try running ./psh.phar storefront:build     `

`psh.phar` is no longer included in this repo, so I downloaded it, pirated the config from the deprecated [shopware/development](https://github.com/shopware/development/blob/trunk/dev-ops/storefront/actions/build.sh) repo, the path in npm run production is wrong so i fixed it:
```
bin/console bundle:dump
bin/console feature:dump
npm install
PROJECT_ROOT=__PROJECT_ROOT__/  npm --prefix /workspace/platform/src/Storefront/Resources/app/storefront run production
bin/console assets:install
bin/console theme:compile
```
`npm install` because it fails with `webpack: not found` if you don't, and now it just fails with 
```
⚠️  The feature dump file "config_js_features.json" cannot be found. All features will be deactivated. Please execute bin/console feature:dump.  ⚠️

/workspace/platform/src/Storefront/Resources/app/storefront/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Definition file does not exists
```

**Comment by shyim** [comment]
Are you in Community Slack? Drop me a DM with an Shared Running Instance

**Comment by shyim** [comment]
We fixed it using DM
