### ISSUE TITLE
Support for Dev Containers

### ISSUE THREAD

**Issue by AltayAkkus** [shopware/platform#2901]
### Please describe the feature you would like to see implemented.

I am really loosing my mind over contributing to this repo, I just can't get it working locally so I use GitPod all the time, my free tier is now used up and I don't really want to pay for it. Nix devenv also won't work for me, out of the box atleast, and in GitPod I regularly just throw away my instances and reload everything.
[There is a new, open specification for development containers](https://containers.dev/), like Gitpod but it works everywhere
Currently VS Code supports it, Github Codespaces supports it, [PhpStorm is working on it](https://youtrack.jetbrains.com/issue/IDEA-292050), so it may make a lot of sense.

I'm starting to work on this to get ourselves a working `.devcontainer`

**Comment by shyim** [comment]
Since https://github.com/shopware/platform/commit/05eff4b52f3b74adf49583c7f402598e065abe08 Gitpod should work normal again. 

I am currently adding Devenv which is already added to this repo to Gitpod https://github.com/gitpod-io/workspace-images/pull/999 without needing to install it.

**Comment by shyim** [comment]
For Opensource Gitpod also offers a special plan somewhere is a Google Form to get it.
![image](https://user-images.githubusercontent.com/6224096/209471247-6a632dea-de60-428a-a39e-d4d28fbf7b07.png)
