### ISSUE TITLE
Method findBestVariant with wrong availability sorting

### ISSUE THREAD

**Issue by areanet-schmid** [shopware/platform#2924]
### PHP Version

8.*

### Shopware Version

6.4.18.0

### Expected behaviour

On the storefront product detail page, the cheapest AVAILABLE variant should be preselected, if there is no variant in the admin storefront presentation is defined.

### Actual behaviour

On the storefront product detail page, the cheapest NOT AVAILABLE variant is preselected, if there is no variant in the admin storefront presentation is defined.

### How to reproduce

- One product with variants and one not available variant (with cheapest price).
- Select "main product" in the storefront presentation and clear "main variant" selection
- open the product detail page in the storefront: The not available variant with the cheapest price is preselected

**Comment by niklaswolf** [comment]
This issue can be closed, as it was resolved in https://github.com/shopware/shopware/pull/3352
