### ISSUE TITLE
EntityRepositoryInterface deprecated but some decorators like e.g. PaymentMethodDecorator do not extend the EntityRepository which results in typehint issues

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#2945]
### PHP Version

8.1

### Shopware Version

6.4.18.1

### Expected behaviour

All current EntityRepository decorators need to also extend the EntityRepository as otherwise switching the typehints to EntityRepository will fail if such repositories are used as the only implement the interface but not the EntityRepository.

### Actual behaviour

Some current entity repository decorators only implement the interface but do not extend the entity repository class.

Therefore, the issue is that if such a repository is used, e.g. `EntityRepostory $paymentMethodRepository` the typehint `EntityRepository` will fail as it is resolved to the PaymentMethodRepositoryDecorator which only implements the EntityRepositoryInterface.

see also https://github.com/shopware/platform/blob/v6.4.18.1/src/Core/Checkout/Payment/DataAbstractionLayer/PaymentMethodRepositoryDecorator.php

A similar issue is with the swag language package which decorates its own repository. However, it could use that repository class without decoration as well by just using that service internally e.g.

### How to reproduce

see above.

**Comment by mitelg** [comment]
already fixed on 6.4 branch and will be part of 6.4.19.0

https://github.com/shopware/platform/commit/5103333c284152f11b6243b15c3e1e8a19f04fed

**Comment by AndreasA** [comment]
Hi @mitelg , I am actually talking about a bit of a different issue than the one fixed in the referenced commit. Though related. the referenced commit fixes the issue if one decorates a repository currently.

However, it does not fix if one wants to switch to EntityRepository typehinting in their own plugins to retrieve entity repositories like e.g. paymentMethodRepository as those might be decorated and only implement the interface.

So e.g. using "EntityRepository $paymentMethodRepository" in the code of a plugin now to avoid deprecation, results in a typehint error due to: https://github.com/shopware/platform/blob/6.4/src/Core/Checkout/Payment/DataAbstractionLayer/PaymentMethodRepositoryDecorator.php#L21 only implementing the interface.

However, just fixing it for that repository will not work in all scenarios as third party plugins could do a similar decoration.

So:

```php

class Foo {
    public __construct(private readonly EntityRepository $paymentMethodRepository)
    {
    }
}
```

will result in a typehint error due to https://github.com/shopware/platform/blob/6.4/src/Core/Checkout/Payment/DataAbstractionLayer/PaymentMethodRepositoryDecorator.php#L21 not extending the EntityRepository. However, that is the only way to get rid of using the deprecated interface in once code before upgrading to 6.5, and as the interface is marked deprecated it just makes sense to avoid using it already.

The only solution that would work here and ensures that it doesn't matter if another plugin decorates the repository would be to create a repository decorator for all repositories with an extremely low decoration priority (e.g. `-999999`) with something like this:

```php
class EntityRepositoryDeprecationWrapper extends EntityRepository implements EntityRepositoryInterface
{
    public function search(.... {
      return $this->repoInner->....
   }
....
}
```

This could be done immediately in the compiler pass that defines the repositories.

That way no matter if another plugin decorates a repository, the user can use EntityRepository and EntityRepositoryInterface to reference the repository as the outer most service is always the EntityRepositoryDeprecationWrapper. It will also fix the issue regarding the PaymentMethodRepositoryDecorator and it would also fix the issue of the commit https://github.com/shopware/platform/commit/5103333c284152f11b6243b15c3e1e8a19f04fed without the need to switch to EntityRepositoryInterface typehinting there - however as that is part of the core it is fine if it stays with the interface for now.

Hopefully, this better explains the issue.

**Comment by mitelg** [comment]
@shopware/ct-core could you take over here? 

my guess would be, to avoid repository decorator at all 🤔

**Comment by keulinho** [comment]
Hey @AndreasA, thanks for your suggestions! 

Indeed currently it is not really possible to handle the `EntityRepositoryInterface` deprecation in your plugins without risking to break behaviour. 

Additionally it is not possible out of the box to make the break forwards compatible, meaning you can adapt your plugin to be compatible with both 6.4 and 6.5.

With your suggestion that would be possible and would make upgrading to 6.5 a lot easier for the whole community.

Honestly the solution feels quite hacky, but in this case i think the benefits outweigh the cons. We will work on something and will continue the discussion internally.

**Comment by keulinho** [comment]
It should be fixed now by the linked commit, thanks again for your suggestion :v:

**Comment by AndreasA** [comment]
Hi @keulinho I agree that it is a bit of a hacky solution. However, as you mentioned it is perfect for you current scenario to already get rid of deprecated interfaces but still support plugins that use deprecated EntityRepositoryInterface decorators, so it definitely outweighs the hackyness 😄 Furthermore, it is only in there temporary until the 6.5 release.

One point to it would have probably been enough to use `extends EntityRepository` as the EntityRepository itself already implements the interface. However, having the interface there as well doesn't hurt so I would keep it as it is.

Btw. is there a timeline regarding the planned 6.5 release?

**Comment by keulinho** [comment]
There is already a release branch created: https://github.com/shopware/platform/tree/6.5.0.0

So we are getting close, expect the first RC release in the next month ;) From then on we plan for a 2-3 month RC phase depending on the feedback we got on the first RC.
