### ISSUE TITLE
Set promo-price for period (from/to date)

### ISSUE THREAD

**Issue by Tim-VL** [shopware/platform#2950]
### Please describe the feature you would like to see implemented.

Option to set an date period for promo prices on the product detail page.

In WC it looks like this.
![afbeelding](https://user-images.githubusercontent.com/75847795/214348643-a6cc6ec0-5255-4363-96f2-dfb38fce2f5b.png)

**Comment by Zwaen91** [comment]
Hi @Tim-VL, with the rule builder you have the possibility to create a rule which filters a date range. This rule can be selected in the advanced pricing tab.

**Comment by keulinho** [comment]
Additionally you can use the `promotion` for time based discounts
