### ISSUE TITLE
500 Error while trying to register a customer

### ISSUE THREAD

**Issue by salihgun** [shopware/platform#2979]
### PHP Version

-

### Shopware Version

v6.5.9

### Expected behaviour

I want to create a customer.

### Actual behaviour

When i was trying to register a customer i always get this error
![Screenshot 2023-02-14 at 14 09 43](https://user-images.githubusercontent.com/47421572/218720035-0837a874-ce97-40a1-88e3-267b8c2d7d51.png)

I follow these docs https://shopware.stoplight.io/docs/store-api/b08a8858e0c5d-register-a-customer and https://shopware.stoplight.io/docs/store-api/aa7ea5e14dea6-registering-a-customer but i got still error

### How to reproduce

request for register a customer

**Comment by Zwaen91** [comment]
@salihgun Could you please provide a request payload. I tried with the payload below and had no problems.
```
{
	"email": "gdfg@eer.de",
	"password": "string",
	"salutationId": "9ce170c9b3704595bcb6d2fa6d406a46",
	"firstName": "string",
	"lastName": "string",
	"billingAddress": {
		"countryId": "0d87657d262e45ee92ef3a4ebc2e119b",
		"zipcode": "",
		"city": "string",
		"street": "string"
	},
	"accountType": "",
	"password": "Test1234!",
	"createCustomerAccount": "false",
	"storefrontUrl": "default.headless0"
}
```

**Comment by salihgun** [comment]
The problem was access key i changed it and it worked. Thanks
