### ISSUE TITLE
Update `LegacyPassword` with less than `core.loginRegistration.passwordMinLength` not possible

### ISSUE THREAD

**Issue by PheysX** [shopware/platform#2987]
### PHP Version

8.1

### Shopware Version

6.4.19.0

### Expected behaviour

Imported customers with `LegacyPassword` can easily update their passwords and `core.loginRegistration.passwordMinLength` schould be ignored or the customer should get an prompt to update the password.

### Actual behaviour

It's not possible to login as customer with `LegacyPassword` less than `core.loginRegistration.passwordMinLength`. 

### How to reproduce

Add customer with `LegacyPassword` less than `core.loginRegistration.passwordMinLength` and try to login via storefront.

**Comment by keulinho** [comment]
Can you open a PR?

**Comment by PheysX** [comment]
Should be done with the #2990
