### ISSUE TITLE
Admin CMS broken due to visibility feature

### ISSUE THREAD

**Issue by htuscher** [shopware/platform#2989]
### PHP Version

8.1

### Shopware Version

6.4.19.0

### Expected behaviour

The CMS should work

### Actual behaviour

No matter which element you're trying to use, you will always get this error in the admin JS:
```
An error was captured in current module: TypeError: Cannot read properties of undefined (reading 'desktop')
    at s.isVisible (app.js?16766494408371995:1:1515297)
```

I've found multiple issues:

1. Missing default value
The `isVisible` computed property of the `sw-cms-block` is called before the `createdComponent` method is called where the missing default value would be set.
Unfortunately there's no other place where the default value would be set (most likely because you would have had to modify every CMS elements `defaultConfig`.
Therefore also the rendering of `<sw-cms-visibility-config` is impossible because there's no prop `visibility` set.

2. Inverse logic of `isVisible` from the `sw-cms-block`

The `<sw-cms-visibility-toggle` is shown if the component `isVisible` but the toggle displays an indicator, that the component is not visible in the current viewport. That doesn't make sense.

Temporary Workaround:
`sw-cms-block/index.js`:
```
        isVisible() {
            const view = State.get('cmsPageState').currentCmsDeviceView;
            return false;  <==== because of the inverse logic
```

`sw-cms-visibility-config/index.ts`:
``` 
    props: {
        visibility: {
            type: Object,
            required: true,
            default() {
                return {
                    visibility: {  // Added default value
                        mobile: true,
                        tablet: true,
                        desktop: true,
                    }
                };
            }
        },
    },
```

`sw-cms-sidebar.html.twig`:
```
<!-- ADDED v-if -->
<sw-cms-visibility-config v-if="selectedBlock.visibility" :visibility="selectedBlock.visibility" />
```

### How to reproduce

Just use any element or try to open an existing cms page.

**Comment by htuscher** [comment]
I finally found the solution.

A base plugin was overriding sw-cms-section (MoorlFoundation which is present in all projects of us).

```
--- /dev/null
+++ ../src/Resources/app/administration/src/extension/sw-cms/component/sw-cms-section/index.js
@@ -48,11 +48,12 @@
         }
     },
 
-    created() {
-        this.initSectionGrid();
-    },
+    methods: {
 
-    methods: {
+	createdComponent() {
+            this.initSectionGrid();
+            this.$super('createdComponent');
+        },
         initSectionGrid() {
             if (!this.isSectionGrid) {
                 return;

```
Solves the issue @moorl 


I would assume that the `sw-cms-section` didn't have a `created()` lifecycle method. So when Shopware introduced that (most likely it wasn't listed as a breaking change), it got overseen.

**Comment by moorl** [comment]
@hhoechtl 
Both ways are executed and I didn't get any error. I will change it to your suggestion. Thanks
