### ISSUE TITLE
Missing css/js assets when installing v6.5rc1

### ISSUE THREAD

**Issue by harli91** [shopware/platform#3002]
### PHP Version

8.1

### Shopware Version

v6.5rc1

### Expected behaviour

When installing via the browser install wizard all css and js should be loaded

### Actual behaviour

Css and js are not loaded from public/bundle/*

### How to reproduce

clone the repository, swich to the v6.5rc1 tag, attempt to install with browser

**Comment by shyim** [comment]
Hey,

how did you set it up. :)

**Comment by harli91** [comment]
@shyim  what do you mean "set it up"? git clone this repository, swiched to v6.5 tag, added a htaccess in the public folder, open the site in the browser, attempted to install it

**Comment by shyim** [comment]
Which repository cloned :)

**Comment by harli91** [comment]
https://github.com/shopware/platform

**Comment by shyim** [comment]
Ahh okay.

The shopware/platform repository does not contain any build assets in the tags as its purpose is to develop and not host. For hosting you should use the sub packages `shopware/core`, `shopware/storefront` etc.

You can create with `composer create-project shopware/production:6.5.0.0-dev` a Shopware 6.5.0.0 project for development.

If you still want to stick to this development repository, you can run `composer init:js && composer build:js`
