### ISSUE TITLE
Plugin uninstall will not work with executeComposerCommands() returning true

### ISSUE THREAD

**Issue by jd297** [shopware/platform#3032]
### PHP Version

8.2

### Shopware Version

6.5.0.0.RC.3

### Expected behaviour

Plugin uninstall should work with the method _executeComposerCommands_ return true, when using a own plugin class in uninstall method.

### Actual behaviour

The plugin classes will be loaded from a directory that not longer exists and therefore you get an error as mentioned in the _How to reproduce_ section.

### How to reproduce

I'm currently update a plugin for the new 6.5 version. I added a new composer requirement because the dom will not be installed by default.
```json
{
    "require": {
        "shopware/core": "^6.5",
        "symfony/dom-crawler": "~6.2.0"
    }
}
```

I saw the new feature that composer commands will be installed by shopware, so I added the executeComposerCommands method returning true.
```php
class AcmePlugin extends Plugin
{
    public function executeComposerCommands(): bool
    {
        return true;
    }
}
```

In the same plugin class is an uninstall method that just removes plugin tables from database.
```php
public function uninstall(UninstallContext $uninstallContext): void
{
    if ($uninstallContext->keepUserData()) {
        parent::uninstall($uninstallContext);

        return;
    }

    /** @var Connection $connection */
    $connection = $this->container->get(Connection::class);

    $entities = [
        AcmeEntityTranslationDefinition::ENTITY_NAME,
        AcmeEntityDefinition::ENTITY_NAME,
    ];

    foreach ($entities as $entityName) {
        $connection->executeStatement(\sprintf('DROP TABLE IF EXISTS `%s`', $entityName));
    }
}
```

Now put your plugin into _custom/plugins_, install and activate the plugin. After that just uninstall the plugin with _Remove all app data permanently_. You will get an error like this:

Warning: include(/full/path/shopware/vendor/composer/../acme/my-plugin/src/Entity/AcmeEntity/Aggregate/AcmeEntityTranslationDefinition.php): Failed to open stream: No such file or directory.

The plugin is now deactivated but still installed. If you repeat the uninstall process it will work without errors and all plugin data is removed as expected.

**Comment by keulinho** [comment]
Hi @JD297, 

thanks for your detailed bug report :+1: 

I'm currently trying to reproduce your issue but having some troubles. At least when you install activate and uninstall the plugin over the CLI everything works fine locally for me.

Do you use the administration to install or uninstall the plugin?

**Comment by keulinho** [comment]
Ok i was able to reproduce your issue and created a ticket for that: https://issues.shopware.com/issues/NEXT-26059

Will take a look and we'll fix this for the 6.5.0.0 final release.

Thanks again for bringing up the issue.

**Comment by keulinho** [comment]
The issue should be fixed with https://github.com/shopware/platform/commit/4a92c0e60e756170e9fb120b437eb487c08fb08c on the trunk branch, the fix will be included in the next 6.5 release.

**Comment by timo-haas-gh** [comment]
@keulinho hey sorry for disturbing but i am currently facing the same issue as described above in 6.6.
The file has changed: https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Plugin/PluginLifecycleService.php

Do i miss something in the documentation?

**Comment by nucle** [comment]
We have the same issue with version 6.6.10. 
Should we create a new ticket?
