### ISSUE TITLE
404 /static/js/swag-pay-pal.js in Admin-Backend

### ISSUE THREAD

**Issue by VonZubinski** [shopware/platform#3036]
### PHP Version

8.1.16

### Shopware Version

6.4.20

### Expected behaviour

No 404 errors from Extensions/Plugins in the administrative backend.

### Actual behaviour

Missing file in the the PayPal Extension in `public/bundles/swagpaypal/administration/static/js/swag-pay-pal.js`

<img width="981" alt="Screenshot 2023-03-31 at 13 40 06" src="https://user-images.githubusercontent.com/63931403/230257519-0fcc94e5-77b2-49e3-8f24-9f27baae2341.png">

### How to reproduce

- Install PayPal Extension Version: 6.0.2 and activate.
- Check folder `public/bundles/swagpaypal/administration/static/js/` for the missing file, only `swag-pay-pal.js.LICENSE.txt` can be found.

**Comment by mstegmeyer** [comment]
This is a known issue: https://issues.shopware.com/issues/PPI-671
