### ISSUE TITLE
System update to 6.4.20.1 breaks everything

### ISSUE THREAD

**Issue by nicgentile** [shopware/platform#3041]
### PHP Version

8.1.13

### Shopware Version

6.4.20.0

### Expected behaviour

I expected that after an update cycle, the process would occur smoothly and would resume service when completed.

### Actual behaviour

When I run the update, it downloads the update, extracts it and then moves to a screen that says 

> Unsere Website befindet sich gerade in der Wartung.
> Wir stehen Ihnen bald wieder zur Verfügung. Entschuldigen Sie etwaige Unannehmlichkeiten.
> 
> Our website is currently undergoing maintenance.
> We'll be back very soon. Sorry for any inconvenience.

The Url is /recovery/update/index.php/checks

Nothing happens beyond here and the site has to be redone.

### How to reproduce

This has been tested on both my dev and live, so the backup thing is good.

1. Install vanilla Shopware.
2. Get it up and running with credentials and everything.
3. Disable all enabled extensions.
4. Go to the update part and pull an update.
5. Follow the instructions.
6. Watch the thing crash and burn.

For reference's sake, this is running on FreeBSD 13.1, MySQL 8.0.31, Nginx 1.23.3

Everything else runs ok, addons are installed without an issue.

Screenshot to show you how this is happening.

![Screenshot from 2023-04-18 00-10-34](https://user-images.githubusercontent.com/15862599/232670843-fe3a38ed-ae50-41a0-ae5d-8272ab710799.png)

**Comment by shyim** [comment]
Is your nginx properly configured? location for /recovery/update?

**Comment by nicgentile** [comment]
Hi, yes. The nginx server is running fine. The production server has been running for over a year. 

On the public side it is 

`domain.tld/recovery/update`

Internally, it is within the public folder.

It is exactly how I unzipped it structurally.

**Comment by shyim** [comment]
It looks like so your rewrite is not working properly and is still using /public/index.php instead of /public/recovery/update/index.php 🤔  

When you remove the /checks from the URL does it render properly a update page?

BTW you can finish it also locally by doing php public/recovery/update/index.php

**Comment by nicgentile** [comment]
> It looks like so your rewrite is not working properly and is still using /public/index.php instead of /public/recovery/update/index.php

Found the issue. My "perfectly" configured server had a config leftover from the previous install which was Wordpress. One line was throwing the whole thing off.

> When you remove the /checks from the URL does it render properly a update page?

Sorted.

> BTW you can finish it also locally by doing php public/recovery/update/index.php

Wish I had known this earlier. Could have saved me from borking a site. Thanks though. Saved under "snippets that get you out of trouble."

**Comment by gaxweb** [comment]
I'm having the same issue on a completely fresh server. I'm using an Ionos Cloud pre-configured app image that comes with 6.4.13 which works fine OOTB. If I try to upgrade SW on that one way or another (browser or CLI  - doesn't matter which), I always end up with the same maintenance mode message that I can't get rid of.

When the update is supposedly done and I open the `recovery/update/index.php` in the browser I get this error message:

```
Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Message: trim(): Argument #1 ($string) must be of type string, bool given
File: /redacted/vendor/shopware/recovery/Update/src/DependencyInjection/Container.php
Line: 43
Trace
#0 /redacted/vendor/shopware/recovery/Update/src/DependencyInjection/Container.php(43): trim()
#1 /redacted/vendor/shopware/recovery/Common/vendor/pimple/pimple/src/Pimple/Container.php(118): Shopware\Recovery\Update\DependencyInjection\Container->Shopware\Recovery\Update\DependencyInjection\{closure}()
#2 /redacted/vendor/shopware/recovery/Common/src/DependencyInjection/Container.php(49): Pimple\Container->offsetGet()
#3 /redacted/vendor/shopware/recovery/Update/src/app.php(61): Shopware\Recovery\Common\DependencyInjection\Container->get()
#4 [internal function]: Closure->{closure}()
#5 /redacted/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#6 [internal function]: Slim\DeferredCallable->__invoke()
#7 /redacted/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#8 /redacted/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#9 /redacted/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#10 /redacted/vendor/shopware/recovery/Common/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#11 /redacted/vendor/shopware/recovery/Update/index.php(39): Slim\App->run()
#12 /redacted/public/recovery/update/index.php(6): require_once('...')
#13 {main}
```

If I run it via console, I get `No update files found.`

PHP version was updated to  8.1.18 before starting the SW update. Server uses Alma Linux 8.

Edit: Ok, config issue here as well. The update process removed the `.htaccess` file which had the rewrite to the `public` folder in it. I've changed the Apache VHost config instead and now it works again.
