### ISSUE TITLE
Platform Security Plugin Update - 1.0.23 breaks installation

### ISSUE THREAD

**Issue by pajonas** [shopware/platform#3042]
### PHP Version

8.0.28

### Shopware Version

6.4.18.0

### Expected behaviour

- Installing the platform security plugin update to fix NEXT-26140
- working after plugin update

### Actual behaviour

- Installing the platform security plugin update to fix NEXT-26140 breaks the installation. It returns an error code 500. The problem is a missing dependency in the platform package which the security update relies on:

> Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "Shopware\Core\Framework\Adapter\Twig\SecurityExtension". in /var/www/vhosts/xyz/httpdocs/vendor/symfony/dependency-injection/ContainerBuilder.php:996
> 
> Stack trace:
> #0 /var/www/vhosts/xyz/httpdocs/custom/plugins/SwagPlatformSecurity/src/Fixes/NEXT26140/SecurityFix.php(30): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
> 
> #1 /var/www/vhosts/xyz/httpdocs/custom/plugins/SwagPlatformSecurity/src/SwagPlatformSecurity.php(86): Swag\Security\Fixes\NEXT26140\SecurityFix::buildContainer()
> 
> #2 /var/www/vhosts/xyz/httpdocs/custom/plugins/SwagPlatformSecurity/src/SwagPlatformSecurity.php(28): Swag\Security\SwagPlatformSecurity->fetchPluginConfig()
> 
> #3 /var/www/vhosts/xyz/httpdocs/vendor/symfony/http-kernel/Kernel.php(676): Swag\Security\SwagPlatformSecurity->build()
> 
> #4 /var/www/vhosts/xyz/httpdocs/vendor/symfony/http-kernel/Kernel.php(647): Symfony\Component\HttpKernel\Kernel->prepareContainer()
> 
> #5 /var/www/vhosts/xyz/httpdocs/vendor/symfony/http-kernel/Kernel.php(545): Symfony\Component\HttpKernel\Kernel->buildContainer()
> 
> #6 /var/www/vhosts/xyz/httpdocs/vendor/shopware/core/Kernel.php(191): Symfony\Component\HttpKernel\Kernel->initializeContainer()
> 
> #7 /var/www/vhosts/xyz/httpdocs/bin/console(74): Shopware\Core\Kernel->boot()
> 
> #8 {main}
>   thrown in /var/www/vhosts/xyz/httpdocs/vendor/symfony/dependency-injection/ContainerBuilder.php on line 996

### How to reproduce

This leads to a broken installation:
- Install shopware with Version 6.4.18
- Install platform security plugin with latest version

p.s.: sorry I could not find the SwagPlatformSecurity Plugin Repo, I guess it's private.

**Comment by shyim** [comment]
Hey,

Can you test if this zip works for you?

[SwagPlatformSecurity.zip](https://github.com/shopware/platform/files/11262015/SwagPlatformSecurity.zip)

**Comment by pajonas** [comment]
Hey @shyim, thank you for the patch. The patch is working for me. I needed to extract the files manually because the Admin was not accessible (previous update).

- extracted files to target
- dropped cache
- installed update via CLI `bin/console plugin:update SwagPlatformSecurity`

**Comment by shyim** [comment]
1.0.24 is now released in store
