### ISSUE TITLE
doubled products in checkout (this bug is only in Google Chrome Browser sometimes)

### ISSUE THREAD

**Issue by Bayish** [shopware/platform#3053]
### PHP Version

8.1

### Shopware Version

6.4.20.1

### Expected behaviour

If one click to buy box button we have to see in checkout only one product. (this bug is only in google chrome)

### Actual behaviour

We see doubled products in checkout. 

### How to reproduce

if we click to buy boy button in listing or product detail page. https://staging6.emmi-dent.bm.media/Ultraschallzahnbuersten/

**Comment by shyim** [comment]
Hey,

this bug must be introduced due to theme / plugins. You see also in network tab that the request is made two times (store-api and normal storefront). 

So check your extensions to find the bug.

**Comment by Bayish** [comment]
But I tried to deactivate all themes and plugins, it did not help

**Comment by shyim** [comment]
We need a reproducer without plugins and default theme.
