### ISSUE TITLE
shopware/core 6.4.* requires nyholm/psr7 exact version 1.4.0 which has a security issue

### ISSUE THREAD

**Issue by mmenozzi** [shopware/platform#3054]
### PHP Version

Any

### Shopware Version

6.4.*

### Expected behaviour

[Symfony Security Check](https://symfony.com/doc/6.3/setup.html#checking-security-vulnerabilities) should not detect any security issue.

### Actual behaviour

[Symfony Security Check](https://symfony.com/doc/6.3/setup.html#checking-security-vulnerabilities) reports an issue on `nyholm/psr7`:

```
➜ symfony security:check
Symfony Security Check Report
=============================

1 package has known vulnerabilities.

nyholm/psr7 (1.4.0)
-------------------

 * [CVE-NONE-0001][]: Improper Input Validation in headers

[CVE-NONE-0001]: https://github.com/advisories/GHSA-wjfc-pgfp-pv9c
```

### How to reproduce

1. Install Shopware
2. Run [Symfony Security Check](https://symfony.com/doc/6.3/setup.html#checking-security-vulnerabilities)

**Comment by shyim** [comment]
We will tag today 6.4.20.2 to address this.

**Comment by keulinho** [comment]
Fixed with https://github.com/shopware/platform/releases/tag/v6.4.20.2

**Comment by mmenozzi** [comment]
Thanks guys!
