### ISSUE TITLE
[Opensearch] Search by property value doesn't work with opensearch engine

### ISSUE THREAD

**Issue by guvra** [shopware/platform#3055]
### PHP Version

8.1

### Shopware Version

6.4.20.1

### Expected behaviour

Search should return products that match the searched property value.

### Actual behaviour

Search returns no results with opensearch, but returns the expected results when the mysql search engine is used.

### How to reproduce

1. Make sure that opensearch is defined as active the search engine.
2. Go to Settings > Search in the admin area.
3. In "searchable content", set "Property value" as searchable and save.
4. Rebuild the search index.
5. Try to search for a property value (e.g. "blue" if you have installed the demo data). This should find products with blue color, but it finds nothing instead.

**Comment by shyim** [comment]
Add `FEATURE_NEXT_22900=1` to your `.env` file do an complete reindex.

This feature will be active by default with 6.5
