### ISSUE TITLE
Cannot create webhooks (webhook resource) via the admin api

### ISSUE THREAD

**Issue by larskoole** [shopware/platform#3076]
### PHP Version

8.2

### Shopware Version

6.4.20.2

### Expected behaviour

Following [the official Docs](https://shopware.stoplight.io/docs/admin-api/ec7e44eb8a393-create-a-new-webhook-resources):

1. Send a POST request to `/api/webhook` with a `name`, `eventName`, and `url`.
2. After that it should return a 200 response with the created webhook.

### Actual behaviour

After sending the request you will get a write error referring to `errorCountererrorCount`.

This is caused because `errorCount` is `WriteProtected` but it has a default of `0` so even though you're not sending it with the body it does try to "write" it.

![image](https://github.com/shopware/platform/assets/8629456/454db1fd-ffb3-49f1-aa22-86e01a82ef1e)

### How to reproduce

1. A fresh Shopware 6 install (You could use https://hub.docker.com/r/shyim/shopware with their base docker-compose template)
2. Create an integration in Shopware
3. Use the access keys of the integration to authenticate yourself with the admin api
4. Do the post request as described in "Expected behaviour"

Tip:
You can use Postman for the OAuth 2.0 process.
I'm using the following config under the "Authorization" tab.
<img width="538" alt="image" src="https://github.com/shopware/platform/assets/8629456/5df81798-e279-4659-9d40-257c34dd4f8f">

**Comment by shyim** [comment]
Is fixed ih 6.5.0.0

**Comment by larskoole** [comment]
Thanks! Any eta on the updated docker image? @shyim

**Comment by larskoole** [comment]
Can confirm it doesn't work in 6.5.0.0.

<img width="880" alt="image" src="https://github.com/shopware/platform/assets/8629456/276f0016-88f9-4090-8a56-ab71fae0c5c9">

**Comment by shyim** [comment]
ahh it's not released yet https://github.com/shopware/platform/commit/27ca6715d1766329c78043d53a32a94fe87a3694

**Comment by shyim** [comment]
@larskoole which docker image

**Comment by larskoole** [comment]
Thanks for clearing that up!

I assumed you managed this: https://hub.docker.com/r/shyim/shopware so I was referring to an image with Shopware 6.5 😅

**Comment by shyim** [comment]
@larskoole see :) https://github.com/shyim/shopware/issues/94
