### ISSUE TITLE
Closing the modal with .close() doesn't work

### ISSUE THREAD

**Issue by shortee-mm** [shopware/platform#3112]
### PHP Version

8.1

### Shopware Version

6.5.1.1

### Expected behaviour

this.modal.close() should close the modal

### Actual behaviour

nothing happens because the close() function in the pseudo-modal.util.js is missing the .hide() on this._modalInstance in line 44

### How to reproduce

try to use this.modal.close()

**Comment by tobiasberge** [comment]
Hi, thanks for the hint. This was indeed not working and overlooked during the Bootstrap v5 update.

A fix was merged to `trunk`: https://github.com/shopware/platform/commit/a956170192ae4e4384a2e03c15de5d43b74edaf2

Therefore, we will close this issue.
