### ISSUE TITLE
Error downloading Shopware 6.5.2.1 via shopware-installer.phar.php

### ISSUE THREAD

**Issue by prbt2016** [shopware/platform#3113]
### PHP Version

8.1.20

### Shopware Version

6.5.2.1

### Expected behaviour

Hello ,

I was in the process of installing Shopware 6.5.2.1 on Centos 7 with PHP 8.1.20, MYSQL 8.0.33.
However I encountered with the following error i.e after running the phar installer i.e : 

http://domain.com/shopware-installer.phar.php

Following error is thrown : 

```
Script assets:install returned with error code 255
!!  Warning: Failed to load plugins. Message: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
!!  
Script @auto-scripts was called via post-update-cmd
```

Following is the screenshot of the same : 

![image](https://github.com/shopware/platform/assets/17871448/85bb31ba-616b-4c3a-ab13-d2e343cb9c71)

An error log is thrown in root folder i.e : 
`
PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 45056 bytes) in /{{PATH}}/vendor/composer/ClassLoader.php on line 582`

I tried increasing memory limits in php.ini , but that doesn't seem to work . 

Is there any resolution for the issue ?. Checked on another server with similar configuration . There also I get the same issue.

### Actual behaviour

Shopware should download without any hassles.

### How to reproduce

1) Download phar installer.
2) Execute phar installer via web. 
3) Above error is thrown.

**Comment by shyim** [comment]
Can you check the memory configured in the PHP CLI? (`php -i | grep memory_limit`)

**Comment by prbt2016** [comment]
Hello @shyim ,

Thanks I checked that memory limit was 64M in PHP CLI . Increased it to 1024M . Works fine now.

You can close this.

Regards.
