### ISSUE TITLE
 #3086  lead potential error "duplicate entry in database"

### ISSUE THREAD

**Issue by rattananen** [shopware/platform#3204]
### PHP Version

8.1

### Shopware Version

6.5.3.0

### Expected behaviour

no duplicate entry in database

### Actual behaviour

might cause duplicate entry in database (from duplicate id)

### How to reproduce

UUID v4 that  Shopware use for unique id for database is generate from both PHP and Javascript 
but  #3086 update only in PHP that mean Shopware use both v4 and v7 now.
it might duplicate if we use v4 and v7 together.

to change v4 to v7 with safety we need to do more than #3086 does.

- update function for generate UUID both PHP and JavaScript.
- migrate exist v4 id in database to v7.
- update all constant that use v4 to v7.

**Comment by Christian-Rades** [comment]
Duplicates between UUIDs of two different versions are impossible 

> the 4-bit version found in Bits 48 through 51 within a given UUID.

Please see also https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.3

Please feel free to reopen should any problems arise
