### ISSUE TITLE
Missing the getter for 'isNew' in SalesChannelProductEntity

### ISSUE THREAD

**Issue by eypsilon** [shopware/platform#3219]
### PHP Version

8.1.21

### Shopware Version

6.4.20.0

### Expected behaviour

Expected that the  `(SalesChannelProductEntity) $item->getIsNew()` method returns a bool value, but it's missing in the Class. There is only a `isNew()` method, but not the getter-variant.

### Actual behaviour

An `UndefinedMethodError` Exception gets thrown.

`Attempted to call an undefined method named "getIsNew" of class "Shopware\Core\Content\Product\SalesChannel\SalesChannelProductEntity".`

The affected class: [SalesChannelProductEntity::isNew](https://github.com/shopware/platform/blob/73506aa328198b089c76256275fab5b23a735fd4/src/Core/Content/Product/SalesChannel/SalesChannelProductEntity.php#L96)

### How to reproduce

In short:

```xml
<service id="Swag\Example\RepoService" public="true">
    <argument type="service" id="sales_channel.product.repository"/>
</service>
```

```php
//  class Swag\Example\RepoService

private SalesChannelContext $salesChannelContext;
private SalesChannelRepository $products;

$products = $this->products->search(new Criteria, $this->salesChannelContext);

foreach($products->getElements() as $product)
{
    $r[] = $product->getIsNew();
}
```

But i guess it's pretty obvious, that the getter for `isNew` is missing.

[SalesChannelProductEntity::isNew](https://github.com/shopware/platform/blob/73506aa328198b089c76256275fab5b23a735fd4/src/Core/Content/Product/SalesChannel/SalesChannelProductEntity.php#L96)

**Comment by mitelg** [comment]
but the method `isNew` just returns the value, so it is basically a getter method 🤔 or do I miss something here?

**Comment by keulinho** [comment]
What @mitelg said! The `isNew()` method is the getter for the `isNew` property, it is pretty wide spread to use `isser` or `hasser` for boolean values, instead of `getters` as they are read more naturally.

So your code should look like this:
```php
//  class Swag\Example\RepoService

private SalesChannelContext $salesChannelContext;
private SalesChannelRepository $products;

$products = $this->products->search(new Criteria, $this->salesChannelContext);

foreach($products->getElements() as $product)
{
    $r[] = $product->isNew();
}
```

**Comment by eypsilon** [comment]
> The `isNew()` method is the getter for the `isNew` property,

No, it's not. Look at all the other Getters within the Framework, they all starts with "get", that's the point of getters. I can write logic, that uses "get" as a Prefix for the properties, which will fail for `getIsNew`.

I mean, technically you're right, it's the getter, but for the sake of consistency, it should have the prefix like all other properties have. 

Currently, i've to check, before i can use it, which shouldn't be necessary in the first place. And like i said, it's not for my comfort, but for consistency.

**Comment by eypsilon** [comment]
What I meant to say was that we just should stick to the standards. Developers should be able to rely on certain things like getters, especially in a Symfony environment.

[symfony/code/conventions](https://symfony.com/doc/current/contributing/code/conventions.html)
