### ISSUE TITLE
Headless sales channels: SEO URLs are created for provided domains which is unnecessary

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#3250]
### PHP Version

8.2

### Shopware Version

6.5.3.3

### Expected behaviour

No SEO URLs should be created for headless sales channels, even if they have domains because those URLs cannot be called anyway.

### Actual behaviour

For products of headless sales channels the SEO URLs are still created as soon as those sales channels have domains which makes product saving slower and creates a lot of unnecessary data.

### How to reproduce

First test no createion:

- Create headless sales channel without domain.
- Add product to headless sales channel.
- To be safe change the product's title after creation.
- No SEO URL created, which is the expected behavior.

Second test invalid behavior:

- Create another headless sales channel.
- Add a domain to that headless sales channel.
- Add a product to that headless sales channel.
- To be safe change the product's title after creation.
- A SEO URL for that product has been created.

**Comment by bschulzebaek** [comment]
Fixed with https://github.com/shopware/platform/pull/3311
