### ISSUE TITLE
Products not shown in Storefront

### ISSUE THREAD

**Issue by flowl** [shopware/platform#3268]
### PHP Version

8.2

### Shopware Version

6.5.4.0

### Expected behaviour

Products with an assigned active/visible category and required attributes set should appear in the appropriate Storefront channel and category.

### Actual behaviour

They don't.

### How to reproduce

Setup a product, assign category, refresh caches => product not visible!

![image](https://i.stack.imgur.com/x4Wa7.png)

![image](https://i.stack.imgur.com/axMeU.png)

This question is off-topic on Stackoverflow, that's why I'm asking here.

Shopware must have a tool/analyzer that reports WHY a selecting product does not appear in the front. Where is this tool?

**Comment by tinect** [comment]
- Is the product active?
- has the product visibility set for the saleschannel?
- if it is set closeout: has the product positive available stock?

**Comment by flowl** [comment]
Ok I didn't set an active sales channel, because I thought the checkmark with the text "Active for all selected Sales Channels" is the option to set it active on all channels.
