### ISSUE TITLE
asset-manifest.json generated during build and breaking the administration

### ISSUE THREAD

**Issue by wexotht** [shopware/platform#3271]
### PHP Version

8.2.6

### Shopware Version

6.5.4.0

### Expected behaviour

The administration working after deployment.

The asset-manifest.json should either not be generated during bin/build-js.sh or should not break the administration.

### Actual behaviour

After deployment the deployment the administration is broken with a blank page due to 404 responses for all CSS and JS assets.
The asset-manifest.json file have been created in the <project-root>/files/ folder.

The asset-manifest.json is creted with the writeManifest() function in the AssetService.php:
https://github.com/shopware/platform/blob/v6.5.4.0/src/Core/Framework/Plugin/Util/AssetService.php#L288

This have not been an issue before SW 6.5.4.0

### How to reproduce

1. Delete the asset-manifest.json file from <project-root>/files/ and/or <project-root>/public/
2. Deploy your shop following the guidelines here: https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/deployment-with-deployer
3. Confirm that the administration page is broken with a blank page and 404 errors for the assets
4. Delete the asset-manifest.json file from <project-root>/files/ and/or <project-root>/public/ 
5. Run assets install: `php bin/console assets:install`
6. Confirm the administration page is now working again

**Comment by shyim** [comment]
Do you use any external storage like s3?

**Comment by wexotht** [comment]
@shyim no, we do not.
We have a CDN_URL for a BunnyCDN pullzone configured, that's it, but it's only affects the images

**Comment by shyim** [comment]
then it's fixed with https://github.com/shopware/platform/commit/98a98064627213bae419da538a9e2830627e9c57 already

**Comment by wexotht** [comment]
@shyim okay nice, but wouldn't this normally merit a patch release? Seems a bit critical and I guess the default is having assets locally, so this should affect a lot of customers
