### ISSUE TITLE
Migrations for Shopware 6.4 fails with MariaDB 10.6.15

### ISSUE THREAD

**Issue by wexotht** [shopware/platform#3273]
### PHP Version

8.2.6

### Shopware Version

6.5.4.0

### Expected behaviour

Core migrations to run successfully on supported MariaDB versions.

### Actual behaviour

The following migration crash on MariaDB 10.6.15. (works on 10.6.10)

https://github.com/shopware/platform/blob/v6.5.4.0/src/Core/Migration/V6_4/Migration1656397126AddMainVariantConfiguration.php#L30

Error message:

Migration error: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1901 Function or expression 'variant_listing_config' cannot be used in the CHECK clause of `variant_listing_config`
Trace: 
#0 /builds/sw6/projects/elefantprint/vendor/doctrine/dbal/src/Connection.php(1935): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#1 /builds/sw6/projects/elefantprint/vendor/doctrine/dbal/src/Connection.php(1878): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#2 /builds/sw6/projects/elefantprint/vendor/doctrine/dbal/src/Connection.php(1206): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'ALTER TABLE `pr...', Array, Array)
#3 /builds/sw6/projects/elefantprint/vendor/shopware/core/Migration/V6_4/Migration1656397126AddMainVariantConfiguration.php(30): Doctrine\DBAL\Connection->executeStatement('ALTER TABLE `pr...')
#4 /builds/sw6/projects/elefantprint/vendor/shopware/core/Framework/Migration/MigrationRuntime.php(40): Shopware\Core\Migration\V6_4\Migration1656397126AddMainVariantConfiguration->update(Object(Doctrine\DBAL\Connection))
#5 /builds/sw6/projects/elefantprint/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(58): Shopware\Core\Framework\Migration\MigrationRuntime->migrate(Object(Shopware\Core\Framework\Migration\MigrationSource), NULL, 0)
#6 /builds/sw6/projects/elefantprint/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(160): Shopware\Core\Framework\Migration\Command\MigrationCommand->getMigrationGenerator(Object(Shopware\Core\Framework\Migration\MigrationCollection), NULL, 0)
#7 /builds/sw6/projects/elefantprint/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(102): Shopware\Core\Framework\Migration\Command\MigrationCommand->runMigrationForIdentifier(Object(Symfony\Component\Console\Input\ArrayInput), 'core', 0, NULL)
#8 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/Command.php(326): Shopware\Core\Framework\Migration\Command\MigrationCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#9 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/LazyCommand.php(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#10 /builds/sw6/projects/elefantprint/vendor/shopware/core/Maintenance/System/Command/SystemInstallCommand.php(197): Symfony\Component\Console\Command\LazyCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#11 /builds/sw6/projects/elefantprint/vendor/shopware/core/Maintenance/System/Command/SystemInstallCommand.php(163): Shopware\Core\Maintenance\System\Command\SystemInstallCommand->runCommands(Array, Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#12 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/Command.php(326): Shopware\Core\Maintenance\System\Command\SystemInstallCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#13 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/LazyCommand.php(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /builds/sw6/projects/elefantprint/vendor/shopware/core/TestBootstrapper.php(345): Symfony\Component\Console\Command\LazyCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /builds/sw6/projects/elefantprint/vendor/shopware/core/TestBootstrapper.php(78): Shopware\Core\TestBootstrapper->install()
#16 /builds/sw6/projects/elefantprint/custom/static-plugins/IlluxCore/tests/FullTestBootstrap.php(23): Shopware\Core\TestBootstrapper->bootstrap()
#17 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/builds/sw6/pro...')
#18 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/builds/sw6/pro...')
#19 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(565): PHPUnit\Util\FileLoader::checkAndLoad('custom/static-p...')
#20 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(345): PHPUnit\TextUI\Command->handleBootstrap('custom/static-p...')
#21 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments(Array)
#22 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#23 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#24 /builds/sw6/projects/elefantprint/vendor/bin/phpunit(123): include('/builds/sw6/pro...')
#25 {main}
#0 /builds/sw6/projects/elefantprint/vendor/shopware/core/Framework/Migration/Command/MigrationCommand.php(102): Shopware\Core\Framework\Migration\Command\MigrationCommand->runMigrationForIdentifier(Object(Symfony\Component\Console\Input\ArrayInput), 'core', 0, NULL)
#1 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/Command.php(326): Shopware\Core\Framework\Migration\Command\MigrationCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#2 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/LazyCommand.php(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#3 /builds/sw6/projects/elefantprint/vendor/shopware/core/Maintenance/System/Command/SystemInstallCommand.php(197): Symfony\Component\Console\Command\LazyCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#4 /builds/sw6/projects/elefantprint/vendor/shopware/core/Maintenance/System/Command/SystemInstallCommand.php(163): Shopware\Core\Maintenance\System\Command\SystemInstallCommand->runCommands(Array, Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#5 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/Command.php(326): Shopware\Core\Maintenance\System\Command\SystemInstallCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Shopware\Core\Framework\Adapter\Console\ShopwareStyle))
#6 /builds/sw6/projects/elefantprint/vendor/symfony/console/Command/LazyCommand.php(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /builds/sw6/projects/elefantprint/vendor/shopware/core/TestBootstrapper.php(345): Symfony\Component\Console\Command\LazyCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /builds/sw6/projects/elefantprint/vendor/shopware/core/TestBootstrapper.php(78): Shopware\Core\TestBootstrapper->install()
#9 /builds/sw6/projects/elefantprint/custom/static-plugins/IlluxCore/tests/FullTestBootstrap.php(23): Shopware\Core\TestBootstrapper->bootstrap()
#10 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/builds/sw6/pro...')
#11 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/builds/sw6/pro...')
#12 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(565): PHPUnit\Util\FileLoader::checkAndLoad('custom/static-p...')
#13 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(345): PHPUnit\TextUI\Command->handleBootstrap('custom/static-p...')
#14 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments(Array)
#15 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#16 /builds/sw6/projects/elefantprint/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#17 /builds/sw6/projects/elefantprint/vendor/bin/phpunit(123): include('/builds/sw6/pro...')
#18 {main}
Previous error: Doctrine\DBAL\Exception\DriverException:
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1901 Function or expression 'variant_listing_config' cannot be used in the CHECK clause of `variant_listing_config`

### How to reproduce

Use MariaDB version 10.6.15 on a clean Shopware and run core migrations. This will fail.

Change to MariaDB version 10.6.10 and it works again.

**Comment by shyim** [comment]
Is a known bug, we created already a bug report at MariaDB https://jira.mariadb.org/browse/MDEV-31931. Our requirement page does not recommend them also anymore

**Comment by grooverdan** [comment]
Hi, sorry you found this post release.

If you are interested and able, MariaDB CI for major branches pushes a container image after a change has been reviewed and considered complete to https://quay.io/repository/mariadb-foundation/mariadb-devel?tab=tags. Images function are same as Docker Official images - `quay.io/mariadb-foundation/mariadb-devel:X`. Container logs will contain 'source revision 5895a3622b2cc67cfdf91057ad532b4b41d0c56c' that can be used to identify the exact mapping to the source .This way MariaDB can know about failing regressions before release, and even if they are intentional like the thankfully reported MDEV-31931, maybe we can defer these until the workarounds are complete.

unrelated note while I notice it:  https://docs.shopware.com/en/shopware-6-en/first-steps/system-requirements typo 'preveligies' -> 'privileges'

**Comment by shyim** [comment]
Has been fixed with https://github.com/shopware/platform/commit/2ac98252d631b50ea173d8b9e42d002be1e496aa

We will release soon a 6.5.4.1
