### ISSUE TITLE
CachedSalesChannelContextFactory should have an event similar to ShippingMethodRoute to change cache keys / cachable flag

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#3294]
### PHP Version

8.,3

### Shopware Version

6.5.4.1

### Expected behaviour

see \Shopware\Core\Checkout\Shipping\SalesChannel\CachedShippingMethodRoute::generateKey it hsould be avilable in the cached context factory and other things as well.

**Comment by AndreasA** [comment]
same fo rCachedBaseContextFactory and potential other similar caches.

**Comment by OliverSkroblin** [comment]
Hi, thanks for the info. 

We are currently working on the HTTP cache rework, which will result in store API routes no longer having a cache wrapper, and we want to get rid of the object cache as much as possible.

https://github.com/shopware/platform/discussions/3299

Therefore, I wouldn't want to introduce another event here for 1-2 minor versions.
