### ISSUE TITLE
Duplicate composer.json requirements. By design or merge error?

### ISSUE THREAD

**Issue by wexotht** [shopware/platform#3298]
### PHP Version

8.2

### Shopware Version

6.5.5.1

### Expected behaviour

That each composer dependency is only included once.

### Actual behaviour

The dev packages jdorn/sql-formatter & johnkary/phpunit-speedtrap are included twice with different version contraints. It this a merge error or by design?

See this:
https://github.com/shopware/platform/blob/v6.5.5.1/composer.json#L157

        "jdorn/sql-formatter": "^1.2.17",
        "johnkary/phpunit-speedtrap": "^4.0.0",
        "jdorn/sql-formatter": "~1.2.17",
        "johnkary/phpunit-speedtrap": "~4.0.0",

### How to reproduce

Look at this file:

https://github.com/shopware/platform/blob/v6.5.5.1/composer.json#L157

**Comment by wexotht** [comment]
Got response at same time this was created :) closing

https://shopwarecommunity.slack.com/archives/C011EH5TUDV/p1693988856177049?thread_ts=1693900228.002019&cid=C011EH5TUDV

**Comment by keulinho** [comment]
It's also now fixed: https://github.com/shopware/platform/commit/c8f9b4a421a51926619b5b03a4bb7b26c4bd5ad6

But thanks for pointing it out!
