### ISSUE TITLE
Fix missing ;

### ISSUE THREAD

**Issue by akkushopJK** [shopware/platform#3314]
### PHP Version

8.2

### Shopware Version

6.5.5.1

### Expected behaviour

fix missing ;

### Actual behaviour

missing ;

### How to reproduce

look at console and see error

**Comment by akkushopJK** [comment]
https://github.com/shopware/platform/blob/511c0c2f7c58938b08d5e417b58775b107f08225/src/Storefront/Resources/views/storefront/component/analytics.html.twig#L9

**Comment by tinect** [comment]
Good catch. I created a pull request for you to fix it.

**Comment by bschulzebaek** [comment]
Fixed with https://github.com/shopware/platform/pull/3317, thanks for raising the issue 👍🏻
