### ISSUE TITLE
run ./bin/build-administration.sh

### ISSUE THREAD

**Issue by lxregistry** [shopware/platform#3329]
### PHP Version

8.2.10

### Shopware Version

6.5.5.2

### Expected behaviour

./bin/build-administration.sh

### Actual behaviour

<img width="673" alt="Screenshot 2023-09-27 170848" src="https://github.com/shopware/platform/assets/32699348/3af47b09-d43a-49e3-bd83-5426be0600a5">

in a fresh installed shopware when I run ./bin/build-administration.sh
I receive this error
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @vue/server-renderer@3.3.4
npm WARN Found: vue@3.3.4
npm WARN node_modules/vue3/node_modules/vue
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer overridden vue@"2.7.14" (was "3.3.4") from @vue/server-renderer@3.3.4
npm WARN node_modules/vue3/node_modules/@vue/server-renderer
npm WARN   @vue/server-renderer@"3.3.4" from vue3@3.3.4
npm WARN   node_modules/vue3
npm WARN   1 more (vue)
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: administration@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: administration@1.0.0
npm ERR! notsup Required: {"node":"^18.0.0","npm":"^8.0.0 || ^9.0.0"}
npm ERR! notsup Actual:   {"npm":"9.8.1","node":"v16.18.1"}

### How to reproduce

run ./bin/build-administration.sh

**Comment by mitelg** [comment]
I guess you should update your nodeJs installation? :thinking:

**Comment by lxregistry** [comment]
<img width="657" alt="Screenshot 2023-09-28 081546" src="https://github.com/shopware/platform/assets/32699348/4194ec49-fa02-4552-80f8-0833268a45a1">

is 20.7
tested with npm 9.8.1 and 10.1.0, the same result

**Comment by mitelg** [comment]
it says, it needs node 18 and npm 8 or 9 

so I guess you need to install exactly that

**Comment by lxregistry** [comment]
Yes, you are right
