### ISSUE TITLE
Property cheapestPrice do not exist in class Shopware\Core\Content\Product\ProductEntity

### ISSUE THREAD

**Issue by Ifnir** [shopware/platform#3344]
### PHP Version

8.1

### Shopware Version

6.5.5.2

### Expected behaviour

Get cheapest price of a product.

### Actual behaviour

Property cheapestPrice do not exist in class Shopware\Core\Content\Product\ProductEntity

in [vendor/shopware/core/Framework/DataAbstractionLayer/Entity.php ](file:///var/www/html/vendor/shopware/core/Framework/DataAbstractionLayer/Entity.php#L114)(line 114)

in [vendor/shopware/core/Content/Product/SalesChannel/Price/ProductPriceCalculator.php ](file:///var/www/html/vendor/shopware/core/Content/Product/SalesChannel/Price/ProductPriceCalculator.php#L116)-> get (line 116)

### How to reproduce

```
use Shopware\Core\Content\Product\SalesChannel\Price\AbstractProductPriceCalculator;
public function __construct(
  private AbstractProductPriceCalculator $priceCalculator
) {}
```
```
public function getProduct(String $id, SalesChannelContext $context)  
{      
          $result = $this->productRepository->search(new Criteria([$id]), $context->getContext());
          if (!$result->count()) {
              return false;
          }
          $product = $result->first();
          $this->priceCalculator->calculate([$product], $context); // Errors happens here.
          return $product;
}
```

**Comment by lukvai** [comment]
`Having the exact same problem, maybe someone found out a workaround?`

Edit: 
used `<argument type="service" id="sales_channel.product.repository"/>` as product repository

```
 public function __construct(
        private readonly AppScriptProductPriceCalculator $priceCalculator,
        private readonly SalesChannelRepository $productRepository,
    ) {
    }
```

**Comment by OliverSkroblin** [comment]
Hi, the behavior is intentional. Unserializing and calculating the cheapest price is very CPU and memory intensive. Therefore, we only determine this when loading Sales Channel Products.
