### ISSUE TITLE
Product Export messages are failing with Google Cloud Storage filesystem adapter because exceeded rate limit for object mutation operations (create, update, and delete)

### ISSUE THREAD

**Issue by 5imun** [shopware/platform#3357]
### PHP Version

8.1

### Shopware Version

6.5.6.0

### Expected behaviour

Product export messages in job queue that are being consumed and processed by multiple consumer pods should not fail when using google storage filesystem adapter because of rate limit of google cloud bucket object modification actions.

### Actual behaviour

In my case we are using Google Storage adapter and in the logs of consumer pods I can see exceptions:

```
Error thrown while handling message Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportPartialGeneration. Sending for retry #1 using 1000 ms delay. Error: "Handling "Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportPartialGeneration" failed: {
  "error": {
    "code": 429,
    "message": "The object shopware-staging/export/ exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.",
    "errors": [
      {
        "message": "The object shopware-staging/export/ exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.",
        "domain": "usageLimits",
        "reason": "rateLimitExceeded"
      }
    ]
  }
}
```

Relevant trace info:
```
shopware/core/Content/ProductExport/Service/ProductExportFileHandler.php:104
vendor/shopware/core/Content/ProductExport/Service/ProductExportFileHandler.php:25
```

Export directory in bucket (in my case `shopware-staging/export/`) is being modified too fast and I think this is due to bad check for directory existence that is using `fileExists` instead of `directoryExists` method so that is why every time export messages are executed it will try to create directory even if it already exists and this happens many times in short time interval and then bucket rate limit gets exceeded.

### How to reproduce

1. Use shopware version: v6.5.6.0
2. Use multiple consumer pods that are solving messages for product export
3. Use google storage adapter filesystem that is storing product export files in bucket
4. Start product export from administration

**Comment by KaiOnGitHub** [comment]
+1
PHP 8.1.22
Shopware 6.5.7.4

**Comment by KaiOnGitHub** [comment]
@5imun 
I was having a look at this and it looks to me as if the problem is caused by excessive logging. The fileExists method is only called twice per `ProductExportPartialGeneration` message but there were also 30k lines of deprecation logs per message. 
We have the fingers_crossed handler active, which means these messages only get logged if there is an error in the application. 

My suspicion: In our case directory permissions were set incorrecty after the cache was cleared which caused the actual error and likely also triggered logging of the deprecation warnings and that probably caused the rate limit error from GCP. This was the actual error in the context of the rate limit errors:
```
messenger.CRITICAL: Error thrown while handling message 
Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportPartialGeneration. Removing from transport after 3 retries. Error: "Handling "Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportPartialGeneration" failed: Unable to create the cache directory (/sw6/var/cache/prod_h9258d60f2814c4607b74fb896fd831cf/twig/string-template-renderer/23)
```

These are the deprecation warnings:
```
User Deprecated: Since shopware/core : Method "Shopware\Core\Framework\Log\LoggerFactory::Shopware\Core\Framework\Log\LoggerFactory::createRotating()" is deprecated and will be removed in createRotating.

User Deprecated: Since shopware/core : Method "Shopware\Core\Content\Media\Pathname\UrlGenerator::Shopware\Core\Content\Media\Pathname\UrlGenerator::getRelativeMediaUrl()" is deprecated and will be removed in v6.6.0.0. Use "Use AbstractUrlGenerator instead" instead.

User Deprecated: Since shopware/core : Method "Shopware\Core\Content\Media\Pathname\PathnameStrategy\AbstractPathNameStrategy::Shopware\Core\Content\Media\Pathname\PathnameStrategy\AbstractPathNameStrategy::generateMd5Path()" is deprecated and will be removed in v6.6.0.0.

User Deprecated: Since shopware/core : Method "Shopware\Core\Content\Media\Pathname\PathnameStrategy\AbstractPathNameStrategy::Shopware\Core\Content\Media\Pathname\PathnameStrategy\AbstractPathNameStrategy::generatePathCacheBuster()" is deprecated and will be removed in v6.6.0.0.

User Deprecated: Since shopware/core : Method "Shopware\Core\Content\Media\Pathname\PathnameStrategy\AbstractPathNameStrategy::Shopware\Core\Content\Media\Pathname\PathnameStrategy\AbstractPathNameStrategy::generatePhysicalFilename()" is deprecated and will be removed in v6.6.0.0.
```

**Comment by 5imun** [comment]
@KaiOnGitHub This specific issue was solved in this [PR](https://github.com/shopware/shopware/pull/3358), PR was closed but relevant [commit](https://github.com/shopware/shopware/commit/2c9f7249e40707c3656d225054825a391b296452) was cherrypicked to `shopware:trunk` so you should not have this problem anymore if you are using newer version.

This issue should be closed
