### ISSUE TITLE
Twig block spelling error in the standard contact form

### ISSUE THREAD

**Issue by AEYCEN** [shopware/platform#3403]
### PHP Version

8.1

### Shopware Version

6.5.6.1

### Expected behaviour

File: `src/storefront/resources/views/storefront/element/cms-element-form/form-types/contact-form.html.twig` Line 58:48

Expected: `{% block cms_form_contact_input_phone %}`

### Actual behaviour

Actual: `{% block cms_form_contact_input_phome %}`
Incorrect naming of the block. The `m` should be a `n`.

### How to reproduce

Looking in the code...

It's a small thing, but I wanted to point it out :)

**Comment by AEYCEN** [comment]
Just saw that the exact error got closed [earlier](https://issues.shopware.com/issues/NEXT-21321). So sorry for inconveniences

**Comment by mitelg** [comment]
hey @AEYCEN 
the issue was closed, because it was old and as stated in the comment, we didn't have the chance to put some priority on it. That does not mean, we do not want that to be fixed!
So if you feel like providing a fix for that, we would highly appreciate this :+1:

**Comment by AEYCEN** [comment]
hi @mitelg 
yes, I would like to help. What would be the next steps if I wanted to tackle this?

**Comment by mitelg** [comment]
great, you can find more information here: https://github.com/shopware/shopware/blob/trunk/CONTRIBUTING.md

be aware, that the old name needs to be deprecated first, so it is not just a simple renaming :wink: but there are other examples in the templates, where this already happend

**Comment by AEYCEN** [comment]
okay, the block doesn't seem to be called anywhere else. do i need a ticket in the issuetracker first to refer to it with my branch name? everyone else has.

**Comment by mitelg** [comment]
no, that is not necessary. you can refer to the old ticket in the description, if you like. 

if you create the PR, we will take care of a ticket and so on
