### ISSUE TITLE
Question: How long do you support the minor/major/patch level versions like e.e. 6.4 (regarding security updates etc.)?

### ISSUE THREAD

**Issue by AndreasA** [shopware/platform#3539]
See question, Symfony etc. has a timeline how long each minor version is support as e.g. Symfony 6.3 is not supported anymore after January. 

However I was not able to find a timeline regarding Shopware. Do you support all major 6 versions in the latest minor versions or is it the latest patch level version?

Or do you support all patch level versions? And if so, is the latest security plugin required or not? And for which versions is the latest security plugin required to be supported and for which not? 

Is there an overview? If not, can you add an overview somewhere in the docs?

**Comment by mitelg** [comment]
Hey @AndreasA 
we are currently working on something like that. please stay tuned 😉

**Comment by lernhart** [comment]
Hey @AndreasA, have a look here:
https://developer.shopware.com/release-notes/

Hope this helps.
