### ISSUE TITLE
DB Installation does not start on 6.6.0.0 RC1

### ISSUE THREAD

**Issue by choeft** [shopware/platform#3542]
### PHP Version

8.2.0

### Shopware Version

6.6.0.0 RC1

### Expected behaviour

After filling in DB credentials on installation process, I expected a list of available databases to be loaded into the select field. After clicking on the "Start installation" button, the DB installation should start.

### Actual behaviour

Website is telling me to fill out all the fields, databases are not loaded into select field. This does not happen when trying to install a version <6.6.x

![Bildschirmfoto 2024-01-25 um 17 44 44](https://github.com/shopware/shopware/assets/8790432/75bbadcd-2a49-40e4-81b6-ca49c556481e)

### How to reproduce

1. Download shopware installer phar file from shopware.com
2. start installer and go to database installation
3. fill in credentials
4. click "start installation" button

**Comment by gitekDev** [comment]
@choeft try with 127.0.0.1 (worked for me)

**Comment by choeft** [comment]
@gitekDev Not for me :( I'm working on MAMP Pro 6.7 on a Mac

Error:  An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused

**Comment by AydinHassan** [comment]
@choeft I just tried the installer and connect fine. Can you please debug a little deeper and provide some more information? Can you connect on the CLI for example, can you connect to the database using PDO directly? Can you debug and see what the connection string is, if all parameters are correct? Thanks!

**Comment by choeft** [comment]
Hey @AydinHassan, thanks for your reply.

So I tried again with the current RC3 package.

1) I download the installer here: https://www.shopware.com/en/changelog/#release-6-6-0-0-rc3
2) Package gets downloaded, second installer starts
3) AJAX Call is made to http://localhost:8888/sw6600dev/public/installer/database-information, credentials are correct, response is just empty {} - no errors in log
4) Problem as described above stays the same - no databases are loaded
5) I also update my MAMP and tried PHP8.2.13

When I use the SAME installer and download the 6.5.8.3 package, everything works fine as expected.

Connecting to DB is possible, other local SW installations all working fine.

**Comment by AydinHassan** [comment]
hi @choeft thanks for the extra info I could reproduce using latest MAMP. The real problem is that MAMP is using MySQL ` 5.7.39` - Shopware 6.6 Support minimum `8.0.17`. The next problem is that the error reporting is not great. It should have been immediately obvious. I will close this issue for now and work on a fix for the error reporting. For now, you can use devenv, docker or install MySQL with brew and point Shopware to that MYSQL server instead. You can still use MAMP for nginx/apache and the other tools.
