### ISSUE TITLE
OpenSSLVerifier::isValid fails on OpenSSL 3.0.7 - Shopware-Store is not available

### ISSUE THREAD

**Issue by boecko** [shopware/platform#3543]
### PHP Version

8.2.7

### Shopware Version

6.4.x,6.5.x

### Expected behaviour

Shopware-Store is available in the backend.

### Actual behaviour

Backend shows an internet connectivity error. 
But in fact it's a problem with openssl_verify in OpenSSL 3.0.7.
So the only thing you can do here is to document that there is problem with the ssl-library :/

Here is the official issue https://github.com/openssl/openssl/issues/19589

### How to reproduce

Here is a test-script on a failing server http://h3013826.stratoserver.net/test.php.
It's basically extracted from https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Store/Services/OpenSSLVerifier.php and a valid signature and your public.key included.

This is on a current AlmaLinux distribution. CentOs should have the same problem.

This bug report is just here, that everyone who has the same issue, can find it.

**Comment by shyim** [comment]
So with openssl 3.2.0, it's fixed right? 🤔

**Comment by keulinho** [comment]
I created a small hint for the docs: https://github.com/shopware/docs/pull/1275
