### ISSUE TITLE
Can not clone structs with enums

### ISSUE THREAD

**Issue by nussjustin-hmmh** [shopware/platform#3551]
### PHP Version

PHP 8.1

### Shopware Version

6.5.7.3

### Expected behaviour

I can use enums in structs

### Actual behaviour

Cloning a struct with a field that contains an enum value fails because Shopware tries to clone the enum which is not allowed.

### How to reproduce

Clone a struct with an enum.

```php
<?php

declare(strict_types=1);

enum MyEnum {
    case Case;
}

class MyStruct extends \Shopware\Core\Framework\Struct\Struct
{
    public MyEnum $enum;
}

$struct = new MyStruct();
$struct->enum = MyEnum::Case;

dd(clone $struct);
```

Result:

```
Error: Trying to clone an uncloneable object of class MyEnum
```

**Comment by mitelg** [comment]
I guess we need to fix the [CloneTrait](https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Struct/CloneTrait.php) for that

**Comment by nussjustin-hmmh** [comment]
Yes. Changing

```php
if (\is_object($value)) {
```

to


```php
if (\is_object($value) && !$value instanceof \UnitEnum) {
```

in both methods should work.

**Comment by shyim** [comment]
Do you mind creating a PR for that? I think we need to check also for BackedEnums? 🤔

**Comment by nussjustin-hmmh** [comment]
BackedEnum extends UnitEnum so we just need to check for UnitEnum.

Will create a PR once I have some time.
