### ISSUE TITLE
TestMessageHandler missing from dist

### ISSUE THREAD

**Issue by letstalk-nl** [shopware/platform#3557]
### PHP Version

8.3

### Shopware Version

6.6.0-rc2

### Expected behaviour

When I run my PHPUnit tests using the described test bootstrapper, I'm expecting them to be able to run without issue

### Actual behaviour

Including the `services_test.xml` config as extra DI in the kernel results in an error message:
```
1) Exception in third-party event subscriber: Invalid service "Shopware\Tests\Integration\Core\Framework\MessageQueue\fixtures\TestMessageHandler": class "Shopware\Tests\Integration\Core\Framework\MessageQueue\fixtures\TestMessageHandler" does not exist.
```

since it is not present in the dist version of the repo (it's in the tests namespace)

### How to reproduce

Run a basic unit test suite of a plugin or similar with the test bootstrapper provided.

**Comment by shyim** [comment]
is fixed with https://github.com/shopware/shopware/commit/c36f2231856789aab5bacb8d07b14931a19da021
