### ISSUE TITLE
Migration1706272837UpdateProductExportForeignKey fails because of incorrect SQL-Syntax

### ISSUE THREAD

**Issue by philipschikora** [shopware/platform#3561]
### PHP Version

8.2

### Shopware Version

6.5.8.3

### Expected behaviour

`php bin/console database:migrate --all`
to complete without any errors.

### Actual behaviour

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version   
  for the right syntax to use near 'CONSTRAINT `fk.product_export.sales_channel_domain_id`' at line 1 
```

### How to reproduce

`php bin/console database:migrate --all`
the issue can be fixed by changing the update method to this:

```
$connection->executeStatement('ALTER TABLE `product_export` DROP FOREIGN KEY `fk.product_export.sales_channel_domain_id`;');

$connection->executeStatement(
    <<<'SQL'
    ALTER TABLE `product_export`
        ADD CONSTRAINT `fk.product_export.sales_channel_domain_id`
            FOREIGN KEY (`sales_channel_domain_id`) REFERENCES `sales_channel_domain` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
SQL
);
```

**Comment by shyim** [comment]
Do you maybe use MySQL 5.7?

**Comment by philipschikora** [comment]
Hi Shyim. I am using MySQL 8.0.33 in this case.

**Comment by jozsefdamokos** [comment]
@philipschikora `DROP CONSTRAINT` syntax should be supprted since MySQL 8.0.19. 
But because we support MySQL 8.0 and up we will change it to `DROP FOREIGN KEY`. Thanks for raising this.

**Comment by philipschikora** [comment]
Thank you very much!

**Comment by jozsefdamokos** [comment]
Fixed 
https://github.com/shopware/shopware/commit/5356a5aefda744b6ae2c73f094d4f6e91fb2d455 https://github.com/shopware/shopware/commit/e0f3c379057f9395889c7496b3ec1b55ceb16f95
