### ISSUE TITLE
Cannot load resource "/var/www/html/custom/plugins/xxx/src/Storefront/Controller/AbstractPaymentController.php". Make sure there is a loader supporting the "annotation" type.    

### ISSUE THREAD

**Issue by harli91** [shopware/platform#3566]
### PHP Version

8.3.2

### Shopware Version

v6.6.0-rc2

### Expected behaviour

controller to be loaded

### Actual behaviour

controller are not loaded, error in the page after runing /bin/console cache:clear : `Cannot load resource "/var/www/html/custom/plugins/xxx/src/Storefront/Controller/AbstractPaymentController.php". Make sure there is a loader supporting the "annotation" type. `

### How to reproduce

follow https://developer.shopware.com/docs/v6.6rc/guides/plugins/plugins/storefront/add-custom-controller.html

**Comment by lxregistry** [comment]
update your plugin to use Attributes not annotation

`<import resource="../../Controller" type="attribute" />`

**Comment by shyim** [comment]
like @lxregistry said
