### ISSUE TITLE
attribute instead of annotation

### ISSUE THREAD

**Issue by lxregistry** [shopware/platform#3582]
### PHP Version

8.3.3

### Shopware Version

6.6.0.0.RC.3

### Expected behaviour

    <import resource="../../Storefront/Controller/**/*Controller.php" type="attribute" />
    <import resource="../../Core/**/*Route.php" type="attribute" />

### Actual behaviour

    <import resource="../../Storefront/Controller/**/*Controller.php" type="annotation" />
    <import resource="../../Core/**/*Route.php" type="annotation" />

### How to reproduce

when run bin/console plugin:create SwagCustomplugin
it create a plugin with routes.xml
```
    <import resource="../../Storefront/Controller/**/*Controller.php" type="annotation" />
    <import resource="../../Core/**/*Route.php" type="annotation" />
```

but I think it should be attribute instead of annotation in symfony 7
```
    <import resource="../../Storefront/Controller/**/*Controller.php" type="attribute" />
    <import resource="../../Core/**/*Route.php" type="attribute" />
```

also edit your docs
https://developer.shopware.com/docs/v6.6rc/guides/plugins/plugins/storefront/add-custom-controller.html

https://symfony.com/doc/current/routing/custom_route_loader.html#loading-routes

**Comment by keulinho** [comment]
@jozsefdamokos you already have a MR to update the create plugin command, can you take care to update the docs pages that are mentioned as well?

**Comment by wannevancamp** [comment]
Fixed in https://github.com/shopware/shopware/commit/bd18ea823872f0a2460ed827eb345e628ac61259
