### ISSUE TITLE
deprecated code

### ISSUE THREAD

**Issue by lxregistry** [shopware/platform#3590]
### PHP Version

8.3.3

### Shopware Version

6.6.0.0.RC.3

### Expected behaviour

use Symfony\Component\Routing\Attribute\Route;

### Actual behaviour

use Symfony\Component\Routing\Annotation\Route;

### How to reproduce

in src/Core/Framework/Api/Controller/FeatureFlagController.php

should be:
use Symfony\Component\Routing\Attribute\Route;

instead of: 
use Symfony\Component\Routing\Annotation\Route;

**Comment by AydinHassan** [comment]
@lxregistry this controller does not exist in the RC, only in trunk
