### ISSUE TITLE
Ensure compatibility with newer libxml2 versions on linux/wsl2 distributions

### ISSUE THREAD

**Issue by sneakyvv** [shopware/platform#3637]
### PHP Version

8.1.27

### Shopware Version

6.5.1.1

### Expected behaviour

Plugin installation succeeds without errors

### Actual behaviour

During bootstrap while running my integration tests, plugins get installed and this error occurs

```
Shopware Plugin Lifecycle Service
=================================

 Install 1 plugin(s):
 * ...

Unable to parse file "/home/.../vendor/.../src/Resources/config/config.xml". Message: [ERROR 3070] complex type 'input-field': The content model is not determinist. (in in_memory_buffer - line 31, column 0)
```

### How to reproduce

```
new SwTestBootstrapper()
    ->setPlatformEmbedded(false) // might be irrelevant
    ->setEnableCommercial() // might be irrelevant
    ->addActivePlugins('a plugin with a config.xml')
    ->bootstrap();
```

Choose a plugin to install with the code above that has a config.xml that refers to this schema https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd

**Comment by sneakyvv** [comment]
Related issue: https://github.com/shopware5/shopware/pull/2625

**Comment by shyim** [comment]
It's fixed since 6.5.8.2 https://github.com/shopware/shopware/blob/v6.5.8.2/src/Core/System/SystemConfig/Schema/config.xsd

**Comment by sneakyvv** [comment]
@shyim this ticket should be reopened because the link I provided is the same version as the commit you mentioned. It's that one that still gives the error on the input-field schema.

**Comment by sneakyvv** [comment]
Or is there another part of the code that makes this no longer occur? 
To that seems not probable since the schema validation is independent of any other code, right?

**Comment by shyim** [comment]
in the issue you mentioned 6.5.1.1, the fix is only in 6.5.8.2 in newer. maybe thats the thing here?

**Comment by sneakyvv** [comment]
That's indeed the SW version I'm using, but the plugins refer to the latest (master) schema on github: https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd

So, that means the SW version I'm using is not important, right?

**Comment by shyim** [comment]
the reference in the `config.xml` itself is just for the IDE. It uses always the local copy of the config.xsd.

**Comment by sneakyvv** [comment]
Wow, major TIL! ❤️ 

Thanks for your help @shyim you're an absolute hero!

**Comment by sneakyvv** [comment]
For anyone stumbling upon this issue: @shyim even has a repo to backport this => https://github.com/shyim/shopware-libxml2-fix
