### ISSUE TITLE
Shopware6 not installing in Cpanel server.

### ISSUE THREAD

**Issue by shree0** [shopware/platform#3675]
### PHP Version

8.2

### Shopware Version

6.6.1.0

### Expected behaviour

Shopware 6.6.1.0 no installing in Cpanel server.

### Actual behaviour

Shopware6 not installing in Cpanel server. Showing Shopware 6 requires at least MySQL 8.0.17 or MariaDB 10.11.

Where this error checks in the `composer create ` downloaded file.

I want to bypass this error.
please help
Thanks.

### How to reproduce

Using Command `composer create-project shopware/production shopware`.

**Comment by shyim** [comment]
Hey,

your system does not fulfill the system requirements. From cpanel docs you can somehow install MariaDB 10.11. 
https://docs.cpanel.net/knowledge-base/general-systems-administration/supported-mysql-mariadb-versions/
