### ISSUE TITLE
You must call "setEnvironment()" before calling "Twig\\Extension\\EscaperExtension::setEscaper()".

### ISSUE THREAD

**Issue by smodev** [shopware/platform#3706]
### PHP Version

8.3.6

### Shopware Version

6.6.2.0

### Expected behaviour

Plugins listed in Backend, changes for templates saveable.

### Actual behaviour

Plugins not showing up in Backend, not able to save changes in template settings. Axios calls responding with "500 Internal Server Error".

### How to reproduce

Try to activate plugin with cli or try to change the collor in the template settings

**Comment by shyim** [comment]
```
composer require shopware/conflicts:>=0.1.9
```

should fix it

**Comment by shyim** [comment]
```
composer require shopware/conflicts:>=0.1.21
```
