### ISSUE TITLE
On install: "Failed to add the foreign key constraint. Missing unique key for constraint 'fk.product.main_variant_id' in the referenced table 'product'."

### ISSUE THREAD

**Issue by sergey-belous** [shopware/platform#3724]
### PHP Version

8.3.6 

### Shopware Version

v6.6.2.0

### Expected behaviour

I am installing a new copy from scratch. I've typed `composer create-project shopware/production shopwareTest` and `symfony console system:install --basic-setup`,
and i was expected to get app installed.

### Actual behaviour

After `symfony console system:install --basic-setup` i've got that error:

```
Get collection for identifier: "core"
migrate Migrations
 217/655 [=========░░░░░░░░░░░░░░░░░░░]  33%01:55:30 ERROR     [app] Migration: "Shopware\Core\Migration\V6_3\Migration1586260286AddProductMainVariant" failed: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 6125 Failed to add the foreign key constraint. Missing unique key for constraint 'fk.product.main_variant_id' in the referenced table 'product'"
```

### How to reproduce

installed packages from composer.json:
```
"require":
{
    "composer-runtime-api": "^2.0",
    "shopware/administration": "*",
    "shopware/core": "v6.6.2.0",
    "shopware/elasticsearch": "*",
    "shopware/storefront": "*",
    "symfony/flex": "~2"
  },
```

**Comment by shyim** [comment]
Hey,

downgrade to MySQL 8.0 until https://github.com/shopware/shopware/commit/3cbc76925f58e3093750bb5f5e58dc2c1a8815ef is released

**Comment by sergey-belous** [comment]
Thanx.

**Comment by aahmadts** [comment]
I still have this issue with 6.5.8.11 but not with 6.6.4.1.

downgrading to MYSQL 8.0 works with 6.5.

Thanks

**Comment by jonaaix** [comment]
Still having the issue with SW 6.6.10.4 when importing a mysql dump from `image: mysql:lts` (which is 8.4) into a new mysql 8.4 database.

Could workaround it by importing into a new 8.3 database. Since my production DB is running with LTS, I hope it would not fail in future 🥴
