### ISSUE TITLE
Component Text Field  doesn't work anymore

### ISSUE THREAD

**Issue by luhmannAlexander** [shopware/platform#3726]
### PHP Version

8.3

### Shopware Version

6.6

### Expected behaviour

The value should not disappear.

### Actual behaviour

The value disappears.

### How to reproduce

https://component-library.shopware.com/components/sw-text-field

Type in input field then tab or click out.

This worked in Shopware 6.5

`<sw-field
                            :label="$t('netzhirsch-promocode-group.detail.nameLabel')"
                            v-model="promocodeGroup.name"
                            maxLength="255"
                            required
                        ></sw-field>`

**Comment by stefanpoensgen** [comment]
Take a look at the upgrade guide
https://github.com/shopware/shopware/blob/trunk/UPGRADE-6.6.md#vue-3-upgrade
https://developer.shopware.com/docs/resources/references/upgrades/administration/vue3.html#vue-3-upgrade

**Comment by luhmannAlexander** [comment]
Thank you for the fast reply.

I have already recompiled the JavaScript for 6.6 and I did not use the @change or @input event.
I don't understand why the value in the input field simply disappears. This even happens in the documentary.
https://component-library.shopware.com/components/sw-text-field

**Comment by kingschnulli** [comment]
You need to use it like this:
`
<sw-field :label="$t('netzhirsch-promocode-group.detail.nameLabel')" v-model:value="promocodeGroup.name" maxLength="255" required ></sw-field>`

**Comment by luhmannAlexander** [comment]
Thank you @kingschnulli 
This work for me.

**Comment by DanieliMi** [comment]
For anyone else stumbling on it and not noticing the difference in https://github.com/shopware/shopware/issues/3726#issuecomment-2135253733 right away...

`v-model:value=""` must be used instead of `v-model=""`.
