### ISSUE TITLE
Development setup with devenv failed: 

### ISSUE THREAD

**Issue by Lanzelot711** [shopware/platform#3741]
### PHP Version

8.2

### Shopware Version

6.6.2

### Expected behaviour

```shell
git clone git@github.com:shopware/shopware.git
cd shopware
devenv up
```
Then I created a .env file with the database url
```shell
DATABASE_URL="mysql://shopware:shopware@127.0.0.1:3306/shopware?sslmode=disable&charset=utf8mb4"
```
in new terminal: 
```shell
devenv shell
bin/console system:install --basic-setup --create-database --force
```
Shopware should be installed and accessible under localhost:8000

### Actual behaviour

Outputs:

```shell
Warning: require_once(/Users/lanzelotmoll/workspace/shopware-dev/shopware/bin/../vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /Users/lanzelotmoll/workspace/shopware-dev/shopware/bin/shopware on line 16

Fatal error: Uncaught Error: Failed opening required '/Users/lanzelotmoll/workspace/shopware-dev/shopware/bin/../vendor/autoload_runtime.php' (include_path='.:/nix/store/sxld48dayip79w4mf684rc6hz5201jv9-php-8.2.18/lib/php') in /Users/lanzelotmoll/workspace/shopware-dev/shopware/bin/shopware:16
Stack trace:
#0 {main}
  thrown in /Users/lanzelotmoll/workspace/shopware-dev/shopware/bin/shopware on line 16
  ```
  
Tried to fix by running
```shell
composer install
```

then the installation works but shopware is rendering dom only and admin does not appear

![image](https://github.com/shopware/shopware/assets/154733307/3dbdc1b8-8001-4f22-8d55-fe0fbafcbf74)

With the production template everything works fine

did I misunderstand something in the docs?

### How to reproduce

see above

**Comment by shyim** [comment]
shopware/shopware has an little different setup than other setups. For `shopware/shopware` you need to run once `composer run setup` and then everything should be fine.

When you want to use Shopware, please create a flex project. Using `shopware/shopware` is only intended for contribution to Shopware

**Comment by Lanzelot711** [comment]
Thank you so much, that resolved the issue. Now it is working. Is there a reason why this is not  mentioned in the docs?

So just a quick last question. In the production setup with symphony flex I can't see the storefront/src folder, which makes it harder to look for references when overwriting twig for a theme or plugin. What is the best practice here?

**Comment by shyim** [comment]
Building extensions it's fine to use shopware/shopware, but for projects you want shopware as an dependency so you see on diffs only your changes and not whole shopware

In the `shopware/core` and so the assets are prebuild, and not with `shopware/shopware` so you need to rebuilt the storefront and admin to have css/js :)

**Comment by Lanzelot711** [comment]
Thank you so much! I will dive a bit deeper into that.
