### ISSUE TITLE
Write permissions required

### ISSUE THREAD

**Issue by tvlooy** [shopware/platform#3771]
### PHP Version

any

### Shopware Version

latest

### Expected behaviour

For security hardening reasons, I would like to remove write permissions on all files and only allow write permissions on certain directories, this makes it more difficult to tamper with code / prevent injection or upload in locations where this is not intended.

The installer checks if the . directory is writable, I don't think this is needed https://github.com/shopware/shopware/blame/03cea7134bd756751a9b17d89d4f41d80fc348c7/src/Core/Installer/Requirements/FilesystemRequirementsValidator.php#L17 and I would like to remove this check.

Another check is https://github.com/shopware/shopware/blame/03cea7134bd756751a9b17d89d4f41d80fc348c7/src/Core/Installer/Requirements/ConfigurationRequirementsValidator.php#L62 which should be a warning, we run shopware with 128M and so this doesn't seem to be a requirement, rather a suggestion (warning).

### Actual behaviour

Don't check for . to be writable. It must only exist and be readable.

### How to reproduce

chmod a-w on .
run the installer

**Comment by shyim** [comment]
Yes, I am with you. But typically the people using the Browser installer, are also updating using the browser than are the permissions required.

When you do the complete installation through cli, it doesn't check for that

**Comment by tvlooy** [comment]
hm okay, that makes sense
