### ISSUE TITLE
Webpack sockjs http 1 issue

### ISSUE THREAD

**Issue by raffaelecarelle** [shopware/platform#3799]
### PHP Version

8.3

### Shopware Version

6.6.4.0

### Expected behaviour

Shopware create a LiveReload server with sockjs transport that serve and watch changes on files.

### Actual behaviour

The sockjs client send a http post request (like this http://127.0.0.1:9998/__webpack_ws/562/bywoum4e/xhr_streaming?t=1720593957181) on every plugin installed (every plugin that has a dist file) and the request remain in pending. But in this case if the request reach maximum limit of concurrent request of http 1, the remain requests will blocked by browser and the page can't reload correctly and stuck on loading.

### How to reproduce

Install the fresh shopware 6.6.4.0 version and it is enough install Shopware Commercial plugin and run the watcher on the storefront.

**Comment by shyim** [comment]
We are reverting the watcher changes. It will be released next week monday
