### ISSUE TITLE
`Allow payment change after checkout` feature is not working correctly

### ISSUE THREAD

**Issue by newzio-pixel** [shopware/platform#3817]
### PHP Version

8.2.21

### Shopware Version

6.6.4.0

### Expected behaviour

If `Allow payment change after checkout` is enabled, the payment should show in the order edit page. If it is disabled, it should not.

### Actual behaviour

Now even if Allow payment change after checkout is disabled, the payment method is showing in the checkout.

### How to reproduce

Use the Shopware deafult payment method:
Cash on delivery

Disable 'Allow payment change after checkout' for Cash on delivery

Then change the code to throw an error manually,

`vendor/shopware/core/Checkout/Payment/Cart/PaymentHandler/DefaultPayment.php`

adding these modifications just to check the function,

```
public function pay(SyncPaymentTransactionStruct $transaction, RequestDataBag $dataBag, SalesChannelContext $salesChannelContext): void
    {
        // needed for payment methods like Cash on delivery and Paid in advance
        try {
            throw new Exception("Sample Error");
        } catch (\Exception $e) {
            throw PaymentException::syncProcessInterrupted(
                $e->getMessage()
            );
        }
    }
```

Now if this feature is disabled, Cash on delivery should not show in order edit page

but the payment method will show even if it is disabled.

**Comment by mstegmeyer** [comment]
Fixed with https://issues.shopware.com/issues/NEXT-37405 🎉
